### ISSUE TITLE
Hello world app

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#1127]
For open source launch we need a "hello world" demo, where you

- build a custom moby
- deploy it locally and on a cloud platform (and test)
- see that your application is running

Or similar. It could be a Moby that just runs eg `nginx` in Docker say. Extensions would include bringing up a cluster not a single instance.

See also https://docker.atlassian.net/wiki/display/Product/F-2%3A+We+are+prepared+for+a+successful+Moby+launch

**Comment by rn** [comment]
outdated
