### ISSUE TITLE
intermittent timeout failure contacting notary with DOCKER_CONTENT_TRUST=1 docker  pull

### ISSUE THREAD

**Issue by RobbKistler** [linuxkit/linuxkit#1195]
When running the Moby test suite (initrd-test.img) on an actual GCE instance, the following failure occurs in ~ 20% of the test runs:

```
DOCKER_CONTENT_TRUST=1 docker --debug pull alpine:3.5
time="2017-02-16T22:25:45Z" level=debug msg="reading certificate directory: /tmp/.docker/tls/notary.docker.io" 
time="2017-02-16T22:25:50Z" level=debug msg="Error pinging notary server \"https://notary.docker.io/v2/\": Get https://notary.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" 
time="2017-02-16T22:26:07Z" level=debug msg="received HTTP status 401 when requesting root." 
you are not authorized to perform this operation: server returned 401.
```

The easiest way to reproduces this is [this branch in my Moby repo fork](https://github.com/RobbKistler/moby/tree/gce-many-instance).  (I apologize, its not quite ready for merge because of a hack handle race conditions in GCE logging)

If needed, install gcloud sdk tools (i.e., `brew install gcloud`).

You need permission to use the moby-ci GCP project (ask me) -or- override the environment variables as specified in the scripts/ngce.sh script.  i.e., 

```
export CLOUDSDK_CORE_PROJECT="moby-ci"
export CLOUDSDK_COMPUTE_ZONE="us-central1-c"
export BUCKET="com-docker-moby-ci"
```

Then run the test-gce-many target.  This will simultaneously run 8 instances and store logs in logs/.

```
make clean # Pick up hack in alpine/packages/test/etc/init.d/test
make test-gce-many
```

**Comment by rn** [comment]
haven't seen this in CI for a long time. Closing

**Comment by guillaumerose** [comment]
We moved Docker Desktop CI to autoscaled Linux agent and we have several times per week this failure early in the morning, when the slave is fresh:
```
time="2019-06-05T06:59:56Z" level=fatal msg="Error writing outputs: Error writing kernel+iso output: docker pull linuxkit/mkimage-iso:3d81e29b28ddf739becf10758eb6077b198d26d8 failed: exit status 1 output:\n"
```

Before this error, we successfully pulled many Docker images without issue.

I suspect content trust to be the reason.

**Comment by justincormack** [comment]
@guillaumerose an error on pull is not something LinuxKit can fix easily. You can look at the logs on Hub/Notary potentially and get some error messages.
