### ISSUE TITLE
Experimental L2 bridge support with vpnkit/hyperkit

### ISSUE THREAD

**Issue by MagnusS** [linuxkit/linuxkit#1212]
https://github.com/docker/vpnkit/pull/188 adds an optional L2 bridge between processes connected to VPNkit. This allows multiple Moby VMs to exist on the same network on Mac, e.g. to run swarm mode. It also allows other processes to connect to the network from the host if they speak the vpnkit protocol.

The bridge is currently experimental and there may be issues with it - please report them here and I'll try to fix them. I've tested a local swarm with Docker for Mac and 10 Moby workers and that seems to work fine.

### Initial setup

The easiest way to test this without building `vpnkit` manually is to download and install a master build of D4M. Build 15512 and later includes bridge support.

To enable the bridge, a key has to be set in the database:
```
$ cd ~/Library/Containers/com.docker.docker/Data/database
$ git reset --hard
$ cd com.docker.driver.amd64-linux
$ echo -n "1" > slirp/bridge-connections
$ git add slirp/bridge-connections
$ git commit slirp/bridge-connections -m "enable bridge"
```

The first time the key is set `Docker.app` may need to be manually restarted to pick up the change.

With the bridge mode enabled the Mac address in the D4M Moby VM should change to `02:50:00:00:00:01` (from `C0:FF:EE:C0:FF:EE`).

### Creating a swarm

To start 10 moby VMs on the same network as the D4M VM, you can for example do something like this (from a new directory, as it creates 10 copies of console-ring, tty etc):

```bash
for i in {1..10}; do
    rm -f hypervisor${i}.pid
    /Applications/Docker.app/Contents/MacOS/com.docker.hyperkit -A -m 2048M -c 2 -u -s 0:0,hostbridge \
        -s 31,lpc -s '2:0,virtio-vpnkit,uuid=35e617a8-5db9-4420-9dfb-84da72dec7ac,path=/Users/magnus/Library/Containers/com.docker.docker/Data/s50,macfile=mac.'${i} -s '4,virtio-9p,path=/Users/magnus/Library/Containers/com.docker.docker/Data/s40,tag=db' \
        -s 5,virtio-rnd \
        -s '6,virtio-9p,path=/Users/magnus/Library/Containers/com.docker.docker/Data/s51,tag=port' \
        -l 'com1,autopty=tty.'${i}',log=console-ring.'${i} \
        -f 'kexec,/Applications/Docker.app/Contents/Resources/moby/vmlinuz64,/Applications/Docker.app/Contents/Resources/moby/initrd.img,earlyprintk=serial console=ttyS0 com.docker.driver="com.docker.driver.amd64-linux", com.docker.database="com.docker.driver.amd64-linux" ntp=gateway mobyplatform=mac vsyscall=emulate page_poison=1 panic=1' \
        -F hypervisor${i}.pid &
    sleep 1
done

echo "Ten instances running, press enter to kill"

read

for i in {1..10}; do
    kill $(cat hypervisor${i}.pid)
    sleep 1
done 
```

You should now be able to enable swarm mode on D4D (`docker swarm init` on the macOS host) and then run the join command in each of the moby tty's created by the above command (with `screen`) to add workers.

```
host$ docker swarm init
Swarm initialized: current node (knfzlnqzg2mmqnswycd6y06o5) is now a manager.
[...]
host$ screen tty.1
/ # docker swarm join --token xxx 192.168.65.2:2377
[...]
host$ screen tty.2 .. etc
[...]
host$ docker node list
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
4i42918cak60w97morgdd6h4b    moby      Ready   Active
937g7dsx5l6dzb2hwfh80wmx6    moby      Ready   Active
a2udpia0pvb4ir6ogea3to8wk    moby      Ready   Active
a90g606pqiux9d8ott882azq4    moby      Ready   Active
dchiqvllawevk64td22hf5vhc    moby      Ready   Active
gfnkvsznwm020fq846xgf66h6    moby      Ready   Active
lxx7120aa7ssuwiur2fg5rkvz    moby      Ready   Active
m79ucwv779wckgr76zanepyza    moby      Ready   Active
qdznia6l22quzcp8dtsyx5djx *  moby      Ready   Active        Leader
rso77u2xqzalwq7803glwawg1    moby      Ready   Active
wymghdcsrd4lpgozcy4ejp2fn    moby      Ready   Active
```

The docker socket in macOS is only connected to the original Moby VM, so you need to connect to the tty's to run commands in the other VMs. It may be possible to set up a docker socket to each VM, which would make management from the host a bit easier.

**Comment by enzofrnt** [comment]
Any possibility on Mac M1 ?
Made able to bind MACVLAN IPVLAN to Mac interface ?

**Comment by deitch** [comment]
What do you mean? What are you looking to do?

**Comment by enzofrnt** [comment]
Hi @deitch thanks for your answer.

On Docker i would like to give Ip from my LAN network to my container.
Usually I use IPVLAN or MACVLAN to achieve.

But there i'm not able to do it.
Because the interface of LinuxKit are not bridged to any of the MacOS interface..

And that really bad, a lot of potential of docker networking on Mac M1 is locked by that.
(Host mode also)
