### ISSUE TITLE
SSH?

### ISSUE THREAD

**Issue by nathanleclaire** [linuxkit/linuxkit#123]
Consider having an `sshd` service and if so we need to follow the instructions at http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/building-shared-amis.html#public-amis-install-credentials to populate it on Amazon.

**Comment by bryanhuntesl** [comment]
> How about SSH agent? Guess we don't want to include support for that at all?

Would have been great cool if docker had. It's 2018 now and I still can't check out private repos.

**Comment by justincormack** [comment]
@bryanhuntesl I think you are commenting on the wrong issue in the wrong repo. If you want docker build ssh secrets to check out private repos, this is now available see https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066
