### ISSUE TITLE
xfs / modularized file system support

### ISSUE THREAD

**Issue by dsheets** [linuxkit/linuxkit#1241]
A user requests `xfs` support at <https://forums.docker.com/t/mounting-xfs-volumes-in-docker-for-mac/29193>. Along with `btrfs` (#597), this is the second major file system that we don't really want to support but we should probably make available. What is the loadable kernel module story? Does moby's yaml config allow users to select modules or kernel config? Should we expose this to users in a nice way in Docker for Desktop?

**Comment by justincormack** [comment]
xfs and btrfs have been added
