### ISSUE TITLE
Add build support for Azure to `moby build`

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#1421]

**Comment by fntlnz** [comment]
FTR: There should be also the relative `linuxkit` push like is now for gce

related link: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/classic/create-upload-vhd

**Comment by radu-matei** [comment]
This is work in progress

https://github.com/linuxkit/linuxkit/pull/1864

**Comment by radu-matei** [comment]
This is work in progress

https://github.com/radu-matei/linuxkit/pull/2

**Comment by radu-matei** [comment]
Another thing that would greatly help - running the Azure Linux Agent from a container, then adding it as a service - https://github.com/Azure/WALinuxAgent/issues/723

**Comment by justincormack** [comment]
We do run the agent on Docker4Azure in a container. It is huge and makes a lot of assumptions that are not really valid, so its a bit of a mess and I hope we can do better than that version...

**Comment by radu-matei** [comment]
Ok, is it open source? Could you point me in that direction?
Thanks!

**Comment by justincormack** [comment]
Not yet; they will start porting d4azure over to the open source linuxkit soon. It needs a bit of a rework though in my opinion (havent looked at it for a wile).

**Comment by radu-matei** [comment]
Is this work to be done by Docker or the Azure people?

**Comment by justincormack** [comment]
Hopefully everyone together...

**Comment by radu-matei** [comment]
Merged https://github.com/linuxkit/linuxkit/pull/1933

Immediate next steps: 

- integrate with Azure Network Security Groups to open ports on the VM
- investigate the Docker4Azure Agent and integrate it when building images targeting Azure

**Comment by rn** [comment]
Closing this issue as the initial Azure support is there. It's best to have separate issues for the outstanding work items

**Comment by radu-matei** [comment]
@justincormack - is there any news regarding Azure Linux Agent in a container?
Thanks!

**Comment by justincormack** [comment]
@radu-matei I dont think anyone has worked on it since we last discussed... Would be good to add to the checklist on your other issue.
