### ISSUE TITLE
Improve kernel build process

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1430]
The current build process for the kernel has a number of issues
- We should check before building the kernel (via the sha1) if it has already been build. Don't build if it has
- The above implies to also push an image with a sha1 tag (on top of the specific kernel version and the more generic version), ie each kernel should be on hub as, e.g.: `:4.9.21-0`, `:4.9.x`, `:<sha1>`.
- Building for different kernels requires a `make clean` because otherwise the build will just pickup potentially old and wrong vmlinux and inittrds. The build artefacts should go into different subdirs prefixed by `KERNEL` or `KERNEL_VERSION`

**Comment by rneugeba** [comment]
moving to post docker con

**Comment by AkihiroSuda** [comment]
It would be great if we can use `distcc` with Swarm-mode cluster, by using `docker build --network`
