### ISSUE TITLE
./tools/perf does not compile with newer kernels

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#1613]
It currently use 4.9.3 but when updating to 4.9.21I noticed a compile error

**Comment by nwt** [comment]
This is the same issue described at https://lkml.org/lkml/2016/10/24/546. With that patch, perf from 4.9.21 compiles without error.

**Comment by rneugeba** [comment]
@nwt thanks for the pointer. I will give that a try after I reworked the general kernel build
