### ISSUE TITLE
how should `moby build` work for cloud platforms?

### ISSUE THREAD

**Issue by dave-tucker** [linuxkit/linuxkit#1618]
## Summary of current behaviour

The `linuxkit.yml` contains a number of fields like `Bucket` and `Project` that are used to allow the `gcp-img` artifact to be uploaded to Google Storage and for an Google Compute Engine image to be created from this file.

## Problems with the current approach

- `linuxkit.yml` files need to be edited by each user to contain the correct variables and for an image upload to proceed. As a user, this means that I don't bother using the `format: gcp` and prefer to use `format: gcp-img` and let `moby run` handle the upload and image creation. It also means that the `examples/gcp.yml` can't be used without being edited

- The `format` section of `linuxkit.yml` will grow exponentially as more cloud providers are added, each needed a dozen or so additional fields or format types

## Proposed solutions

These were discussed in #1607

### Configuration using CLI flags and environment variables

This was the approach taken by #1607
It simplifies the `format` section and allows the `examples/gcp.yml` to be used without editing.
The drawback of this approach is that we end up with dozens of flags available to `moby build`.

### Introduce an intermediate command `moby upload` or `moby cloud`

In this scenario, `moby build` would only output local files. Akin to the `gcp-img` format that is available today. The result of `moby build` could then be passed to `moby upload` or `moby cloud` to create an image on the targeted cloud platform. This command could be structured such that there is a subcommand for each cloud provider and would re-use code (and possibly flags) from `moby run`.

This would simplify the `format` section a lot, as it only needs to know about local formats.
It would also mean that the examples would be portable too.

The drawback is that the promise of `moby build` providing you something that you can run is broken if you were hoping to run on a cloud platform.

For example:

```
moby build examples/gcp.yml
moby cloud gcp -bucket foo -project bar -replace true gcp
moby run gcp gcp
```

### Add a supplemental configuration file to `moby build`

This could be, in a default location for example, `~/.moby/provider.yml` or provided using a command line flag e.g `moby build --config /secrets/provider.yml` and would contain:
```
gcp:
  bucket: foo
  project: bar
  keys: /path/to/keyfile.json
aws:
  ...
packet:
  ...
```

`moby build` would then test for the presence of this file before performing a build that required access to a cloud provider.

This is possibly the most elegant solution but it comes at the cost of additional onboarding for a user. For example, a `moby build examples/gcp` may fail with `[ERROR]: Google Cloud Credentials not present. Please ensure that you have configured ~/.moby/providers.yml`

**Comment by justincormack** [comment]
We decided to switch to split `build` (local only), `push` which pushes VM images to some sort of per platform image store, and `run` (which uses in image store if the platform has one, still uses local images eg for hyperkit). Working on the switch now, so I can remove all the cloud dependencies out of the `moby` tool as this will not have `push` and `run`.

**Comment by rneugeba** [comment]
are you planning to move `run` and `push` into a new `linuxkit` tool?

**Comment by justincormack** [comment]
Yes, at least for now. Maybe they can go away later eg if `run` is infrakit based. I am not sure if we should vendor `moby build` into `linuxkit build` though...

**Comment by rneugeba** [comment]
I agree re vendoring. We want to make `moby` the tool to assemble. doing the same thing by a different name is more confusing than getting the tools from somewhere else

**Comment by justincormack** [comment]
another option would be to give both the `push` and `run` tools separate names, eg `vm-push` and ?. If infrakit takes over `run` thats easier too.
