### ISSUE TITLE
moby run vmware does not seem to work

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1658]
Use the vmare.yml and build run with `moby run vmware vmware` and the VM get's started but doesn't seem to find a bootable image.

This was reported by a user at DockerCon, and i could repro on my Mac with VMware fusion

**Comment by rneugeba** [comment]
@thebsdbox could you take a look

**Comment by thebsdbox** [comment]
I noticed this as well, I realised that the VMware plugin was before we decided on using the <prefix> to detect the image. `-disk <PATH_TO_DISK.vmdk>` will start VMware. Fix coming.

**Comment by solidnerd** [comment]
Hey, this works for me and @DieterReuter #1662.

**Comment by rneugeba** [comment]
closed via #1662
