### ISSUE TITLE
Logs sometimes don't work when using containerd

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1660]
https://github.com/linuxkit/linuxkit/pull/1636 introduced the ability to use `containerd`, instead of `runc`, to run containers. For service containers, sometimes the log files are empty.

**Comment by justincormack** [comment]
@MagnusS was looking at this - we should file an upstream bug...

**Comment by MagnusS** [comment]
I can reproduce this locally with containerd master. Upstream issue in https://github.com/containerd/containerd/issues/770
