### ISSUE TITLE
With containerd, sometimes service containers don't get started

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1661]
#1636 introduced the ability to use containerd, instead of runc, to run containers. This seems to work fine with HyperKit, but when booted on some other platform, like Hyper-V and packet.net, I've seen that sometimes the service containers don't get started. This looks like a race condition to me. 

I'll try to get a more reliable repo, but thought I add an issue to track

**Comment by justincormack** [comment]
This may be fixed, unclear.

**Comment by rneugeba** [comment]
I haven't seen this issue with since we updated containerd, so closing this for now
