### ISSUE TITLE
moby run failed in CentOS 7

### ISSUE THREAD

**Issue by xianwei2016** [linuxkit/linuxkit#1664]
As there have no qemu package in CentOS 7, so it's impossible to run qemu-system-x86_64.

$sudo moby run linuxkit
FATA[0000] Unable to find qemu-system-x86_64 within the $PATH

**Comment by tippexs** [comment]
Hi @xianwei2016 , I gave it a try last night and it worked for me.

Make sure the epel repo is enabled. You can check this by running `yum repolist`. The output should have something like this.

`!epel/x86_64                                                 Extra Packages for Enterprise Linux 7 - x86_64     `

After this try  `yum list qemu\*`. Now you should see something like this:

`qemu.x86_64                                                                          2:2.0.0-1.el7.6                                                              epel
qemu-common.x86_64                                                                   2:2.0.0-1.el7.6                                                              epel
qemu-guest-agent.x86_64                                                              10:2.5.0-3.el7                                                               base
qemu-img.x86_64                                                                      10:1.5.3-126.el7_3.5                                                         updates
qemu-kvm.x86_64                                                                      10:1.5.3-126.el7_3.5                                                         updates
qemu-kvm-common.x86_64                                                               10:1.5.3-126.el7_3.5                                                         updates
qemu-kvm-tools.x86_64                                                                10:1.5.3-126.el7_3.5                                                         updates
qemu-system-alpha.x86_64                                                             2:2.0.0-1.el7.6                                                              epel
qemu-system-arm.x86_64                                                               2:2.0.0-1.el7.6                                                              epel
qemu-system-cris.x86_64                                                              2:2.0.0-1.el7.6                                                              epel
qemu-system-lm32.x86_64                                                              2:2.0.0-1.el7.6                                                              epel
qemu-system-m68k.x86_64                                                              2:2.0.0-1.el7.6                                                              epel
qemu-system-microblaze.x86_64                                                        2:2.0.0-1.el7.6                                                              epel
qemu-system-mips.x86_64                                                              2:2.0.0-1.el7.6                                                              epel
qemu-system-moxie.x86_64                                                             2:2.0.0-1.el7.6                                                              epel
qemu-system-or32.x86_64                                                              2:2.0.0-1.el7.6                                                              epel
qemu-system-s390x.x86_64                                                             2:2.0.0-1.el7.6                                                              epel
qemu-system-sh4.x86_64                                                               2:2.0.0-1.el7.6                                                              epel
qemu-system-unicore32.x86_64                                                         2:2.0.0-1.el7.6                                                              epel
qemu-system-x86.x86_64                                                               2:2.0.0-1.el7.6                                                              epel
qemu-system-xtensa.x86_64                                                            2:2.0.0-1.el7.6                                                              epel
qemu-user.x86_64                                                                     2:2.0.0-1.el7.6    `

Now, just run `qemu-system-x86.x86_64`.

**Comment by thebsdbox** [comment]
The `./moby run` can make use of a number of backends in order to test a built image and will default to a preferred hypervisor dependant on the operating system.

Calling `./moby run` without any arguments will list the supported backends along with the platform they default to.

**Comment by dave-tucker** [comment]
@thebsdbox didn't we have used to have a fallback of using qemu in containers?

**Comment by rneugeba** [comment]
the qemu script used to run qemu in a container, but I din't think the qemu run backend has implemented this yet

**Comment by thebsdbox** [comment]
Its on my list, I'll try and submit another PR for that as soon as I can.

**Comment by rneugeba** [comment]
@thebsdbox thanks! I think we can close this as @tippexs  kindly provided instructions on how to get qemu on centos..
