### ISSUE TITLE
One for the FAQ: What's the difference compared to Alpine?

### ISSUE THREAD

**Issue by Forage** [linuxkit/linuxkit#1666]
As the title states: What's the difference between linuxkit and Alpine? Why linuxkit now? How are they related? In what way is linuxkit better?

**Comment by tippexs** [comment]
I think most of this questions are covered by this blog post.

https://blog.docker.com/2017/04/introducing-the-moby-project/

The Linuxkit was introduced together with the Moby project at dockercon, yesterday.

**Comment by justincormack** [comment]
We use Alpine to build all of our containers and code, but it is a very different project from Alpine, just designed to run containers, with containers not a general purpose distro.

**Comment by EvanCarroll** [comment]
I have no idea what they're talking about and also find this *very* confusing. I've spent 30 minutes trying to figure it out. If you're also confused still, you're not alone.

**Comment by tristanls** [comment]
@EvanCarroll , the value I get out of linuxkit is that I can create machine (bare metal or virtual) images which can be minimalist and immutable. I then [import these images as custom AMIs into AWS](https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html). 

From my perspective, just like docker made cgroups, namespaces, etc accessible/customizable/usable for me, linuxkit makes machine images accessible/customizable/usable for me.
