### ISSUE TITLE
Where can i find kubernetes sample presented at DockerCon?

### ISSUE THREAD

**Issue by debianmaster** [linuxkit/linuxkit#1670]
**Description**

Where can i find kubernetes sample presented at Dockercon?

**Steps to reproduce the issue:**

cd examples , no example listed

**Comment by RobbKistler** [comment]
[linuxkit/projects/kubernetes/README.md](https://github.com/linuxkit/linuxkit/blob/master/projects/kubernetes/README.md)

**Comment by debianmaster** [comment]
Thanks  @RobbKistler
