### ISSUE TITLE
Q: How do you connect to the SSHD example?

### ISSUE THREAD

**Issue by alexellis** [linuxkit/linuxkit#1674]
I built the "moby" CLI and then ran `build/run` on the SSHD example on my Mac. I can see the system booted, but it's not clear how to connect to it. Is that even possible?

https://github.com/linuxkit/linuxkit/blob/master/examples/sshd.yml

**Comment by MagnusS** [comment]
The new linuxkit instance will be on the same network as the Docker for Mac VM, so you should be able to connect to it from containers. You could also forward the port (e.g. with `socat`) so you can connect directly from the host.

For example:
```
$ docker run -p 127.0.0.1:8080:8080 -it --rm alpine sh
/ # apk -U add socat
[...]
/ # socat TCP-LISTEN:8080,fork TCP:[linuxkit_vm_ip]:22
```
(`[linuxkit_vm_ip]` is the IP of `eth0` in the linuxkit vm)

And then connect to localhost on the host:
```
$ ssh -o StrictHostKeyChecking=no localhost -p 8080 -l root
[...]
Welcome to LinuxKit
moby-025000000030:~#
```

**Comment by alexellis** [comment]
Great - thanks for this. Also detailed with SSH in http://blog.alexellis.io/boot-linuxkit-in-10-mins/ (for Googlers)
