### ISSUE TITLE
Should the moby CLI be moved?

### ISSUE THREAD

**Issue by everett-toews** [linuxkit/linuxkit#1680]
There is considerable (and understandable) confusion around moby [A new upstream project to break up Docker into independent components](https://github.com/moby/moby/pull/32691). Over time I think people will calm down and come to a common understanding.

However, one of the biggest challenges going forward for http://mobyproject.org/ will be how to communicate that https://github.com/linuxkit/linuxkit is the upstream source of the `moby` CLI while https://github.com/moby/moby is the upstream source of the `docker` CLI. This is pretty confusing to those "in the know" and will be extremely confusing to new comers.

Please give serious consideration to renaming the `moby` CLI. This will greatly reduce the amount of confusion in the future.

**Comment by rheinwein** [comment]
@everett-toews I have a bit of a different perspective on this -- one that we talked about yesterday at the maintainers meeting at the #mobysummit.

The `moby` CLI is a tool to interact with components of the Moby Project. It's basically an `assembler` tool, and directly relates to Moby-compatible components, so the `moby` name makes sense. To me, the weird name (right now) is the repo `moby/moby`, which includes code that will be consumed by Docker Community Edition.

Right now, it is true that the Docker CLI is in `moby/moby`; this isn't the desired state, and `moby/moby` is not intended to be the home for any Docker-specific code -- that's the whole idea behind the Moby Project. The CLI will eventually be a standalone component; see https://github.com/moby/moby/pull/32694. It will take a while to split everything out, though. 

I do agree the naming is confusing; if anything, maybe `moby/moby` could be called `moby/core` or `moby/origin`. To make the divisions between `moby` and `docker` a bit clearer, there is an action item to create a repo called something like `docker-ce` which will better illustrate that Docker is just a consumer of `moby/moby` and that `moby` !=` docker`.

If you haven't yet had a chance to read it yet, check out the explanation and goals of the Moby Project, and how Moby relates to Docker: https://mobyproject.org/#moby-and-docker

**Comment by alexellis** [comment]
I know there are solid reasons for the way things are as of today. I think @everett-toews is echoing the response we've seen in the wider community. It's surprising that linuxkit has a binary called `moby` - if it had a CLI called `linuxkit` it may be more obvious where things go from the outside.

**Comment by everett-toews** [comment]
Yep. And I'm also trying to look at it from the perspective of a newcomer to the Docker/Moby ecosystem. There seems to be an implicit expectation that newcomers understand the history of Docker to figure out why things are the way they are. That doesn't scale particularly well.

https://mobyproject.org/#moby-and-docker reads,

>The Moby project provides a command-line tool called moby which assembles components. Currently it assembles bootable OS images, but soon it will also be used by Docker for assembling Docker out of components, many of which will be independent projects.

That isn't so. The LinuxKit project provides a CLI called `moby`. Obviously https://mobyproject.org/#moby-and-docker needs to be changed but I think that illustrates just how confusing this is.

If any repo under https://github.com/linuxkit produces a binary for any repo under https://github.com/moby I really think it's going to confuse newcomers.

**Comment by rheinwein** [comment]
The Moby Project and the Moby organization on GitHub are two different things -- I think that's adding to the confusion here. Not all Moby Project components are going to live at github.com/moby.

@justincormack any additional insight? I remember a couple points from yesterday but I'll defer to you :)

**Comment by rneugeba** [comment]
The `moby` tool will be moved to the moby project soon. We are currently discussing where to. `github.com/moby/cmd` and `github.com/moby/tool` where considered, AFAIK.

The `moby` tool will also be extended to support building assemblies other then bootable Linux systems, such as debian packages and the like.

Does that help?

**Comment by everett-toews** [comment]
@rneugeba That really does help. I'd say that's the solution to this particular issue. And as we know a rename is really just a `mv`. 😄 

Let's close this issue when the move actually happens. 

If you remember, can you please reference this issue in the PR? 

If not, I try to remember to check back in.

**Comment by Vanuan** [comment]
There's already a pull request to move moby tool to moby:
https://github.com/moby/moby/pull/32693

The newest comment suggests there's a change of plans.

**Comment by rneugeba** [comment]
@everett-toews glad that this clears up things a little. I leave this issue open for now as the utility has not been moved yet

**Comment by justincormack** [comment]
From discussion at the summit, we will remove parts of the `moby` tool that are LinuxKit specific (ie around VM images, `run`) and probably keep them here for now, then move the tool (shortly).

**Comment by justincormack** [comment]
linuxkit specific parts were split out in https://github.com/linuxkit/linuxkit/pull/1695
