### ISSUE TITLE
support devicemapper for encrypted swap or other block or general usage

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#1689]
devicemapper support, of course, requires the `dm` kernel module. If you want to do anything like, e.g. encrypted swap (or any other encrypted or loopback), you need devicemapper, which needs `dm`. How to get it done? Is there a sane way? I don't relish the idea of building my own kernel to replace `linuxkit/kernel` (actually, that would be rather silly of me to do). 

Is there a way to get the module in? Or is there an alternate path? @justincormack has suggested libguestfs to use for mounting when making build images, but in this case I need mounted encrypted devices not as a on-off but ongoing to run the system.

**Comment by deitch** [comment]
The kernel need not be different, but the `dm` module needs to be compiled at kernel build time.

It is difficult (painful) to build the module independently, and it has to match the kernel version, so putting the module in an `onboot` is a bad idea.

The module should be built at kernel build time. There are two options for loading it:

1. Loads at boot time automatically. This is preferable, but only if it does not negatively impact boot time
2. Does not load automatically, but is available for an `onboot` container to do `insmod`.

**Comment by deitch** [comment]
Great. I am happy to try it. Need I do anything special? And is the latest kernel image updated? Which one do I use in my `moby.yml`?

**Comment by justincormack** [comment]
The image is not updated yet, will be later today.

**Comment by deitch** [comment]
> The image is not updated yet, will be later today

That is part of the challenge with using hashes as versions. I have no way of knowing what features are included in `123ffbc` vs `668fac8`, or even which comes first.

Any chance of moving to sequential or semver? I had the same issue with a client project, we combined the two, so every image is `repo/image:3.2.1-1234fabc`. We get hashing for immutability, along with "normal" versioning so it is clear what is in which release.

**Comment by rneugeba** [comment]
we'd would have to automate this somehow as it is too error prone to do manually. Any good suggestion? We also will move to use git tree hashes (as in the recently changed kernel builds) and there may be a way to link the tree hash back to a commit. Need to investigate

**Comment by deitch** [comment]
> Any good suggestion? 

I have been struggling with this for some time now. See http://stackoverflow.com/questions/40886315/how-do-i-combine-versioning-with-merge-only-to-master-git-workflow (and a few others I cannot find right now).

It gets more difficult for app services (as opposed to LinuxKit) because everything has its own concept of where to store version: `application.properties` for Java files, `package.json` for node, `gemspec` for Ruby, etc. 

For now, we are using git tags. Our automated CI flow looks something like this.

1. `GIT_TAG=$(git describe --exact-match 2>/dev/null)`
2. `GIT_HASH=$(git rev-parse HEAD)`
3. `FULL_TAG="${GIT_TAG}-${GIT_HASH}"`
4. Check if a commit for this image exists that has any of the following: `${GIT_TAG}`, `${GIT_HASH}`, `${FULL_TAG}`. If so, fail CI
4. If everything passes (tests, etc.), push out all three tags

We really only needed `${FULL_TAG}`, but found it easier to work with all of them. E.g. if a user wants to test a particular image, it is easier to just do `3.2.1` than `3.2.1-1ab45678ad`. Plus having `3.2.1` ensures that a version never is reused (step 4 above).

So... the build is good at automatically determining version by git tag - and thus we avoid our build system needing to figure out every possible versioning mechanism - but we still need a human to add the git tag. Push the problem further down the stack.

Also, in LinuxKit it is all one git repo, so all one git hash. It might be easier (and make sense) to break out the various packages (everything that makes an image or executable) into its own repo (which you already started doing with linuxkit and moby tools).

Summary: easy to automate _getting_ the tag via git tag, but still looking for some way to automate creating the tag.

Mind you, sequential is not so hard, just find the most recent tag in the registry and increment (minus simultaneous builds, locking issues, etc.). semver is quite a bit harder.

Any thoughts?

**Comment by rneugeba** [comment]
we definitely want to include git tags in the future, once we do releases. For now, I was thinking to add common labels and include the git repo and hash in there, so that you can link it more easily. The labelling needs to work across repos as `moby` will pull in packages from several repositories

**Comment by deitch** [comment]
> For now, I was thinking to add common labels and include the git repo and hash in there, so that you can link it more easily

Not sure I understood. Can you give an example?

**Comment by rneugeba** [comment]
in the docker file:
```
ARG COMMIT
LABEL "linuxkit.commit"=${COMMIT}
```
in the makefile:
```
IMAGE:=foo
GIT_COMMIT:=$(shell git rev-parse HEAD)
GIT_TREEHASH:=$(shell git ls-tree HEAD -- ../$(notdir $(CURDIR)) | awk '{print $$3}')
docker build --build-arg COMMIT=$(shell git rev-parse HEAD) -t $(IMAGE):$(GIT_TREEHASH)
```

or some such.

That way the tag doesn't change when the content of the subdir does not change (and we wouldn't rebuild/push) but with `docker inspect` you can find out the git commit hash the image was based on. We can extend this with `GIT_TAG=$(git describe --exact-match 2>/dev/null)` if not empty etc.

We'd also want to add a bunch of other stuff to labels, like most the boilerplate from the YAML file, like which CAPs are needed etc and allow folks to override them in the YAML

I plan to write up a proposal soon

**Comment by deitch** [comment]
So it adds the git commit to the image, but tags it with the hash of contents (like now)?
