### ISSUE TITLE
Example needed for converting compose to services

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#1690]
Let us say I have a compose file with 8 or 10 services in it. If I want to run it on Moby/LinuxKit, I have two options:

1. LinuxKit image with docker service, and another service that waits for docker to be ready, has the compose baked in, and then starts it up.
2. Convert all of the compose services to LinuxKit services

We need examples of both. 

The first appears more straightforward, but can get complex in terms of waiting for docker service to be ready. The bigger issue is that it will load all of the images from a registry in runtime. That isn't terrible, but won't work if we want a fully-baked static image, and especially if I cannot rely on the network at runtime.

The second is harder, but more ideal. The same way that LinuxKit provides a snapshot of what everything would look like when ready to run, I want to set up an image that is "as if" I ran compose, got my volumes and networks and DNS naming (most importantly) services, snapshotted it, and then made it part of Moby.

**Comment by rneugeba** [comment]
This is not a uses case we want to support. compose files are for applications composed of micro-services running on top of docker. The YAML file in LinuxKit is really for assembling a system/platform from low level system components and services. It's an entirely different use case and shouldn't support either of the two scenarios, so I'm closing this issue.

**Comment by justincormack** [comment]
1.  should be simple, just bind mount the docker socket directory and wait for docker to respond, then run compose.

2. should in theory be doable with an external tool; there are quite a few differences though and some work would have to be done, eg around volumes and networks.

**Comment by deitch** [comment]
That is a *very* purist viewpoint. I'm thinking practically. Sure, in theory compose is about weaving microservices together. In practice, it is a convenient way to run several container together. When I teach docker, the basic way I explain compose is, "a better way to do lots of docker commands than a script." 

By that argument, no services should exist, and the nginx and kubernetes examples shouldn't be included.  

In any case, if you have five or ten containers that you want to distribute as a unit, you do it via compose. Linuxkit could be a great way to distribute it as an OS unit, but requires the mindset transition and explanation as to how to translate from compose to linuxkit services. 

I'd like this one reopened please.

**Comment by deitch** [comment]
@juatincormack, thanks

1. Yeah makes sense. I'll try that out as a start. Any way to preload the images? 
2. I don't care quite so much for full automation now, be sufficient to be able to make the translation manually. Any direction or samples on mapping compose concepts to moby.yml concepts? Most of individual containers are easy, but volumes, networks and service names are harder.

**Comment by rneugeba** [comment]
I don't think my view is a purist view. linuxkit and the `moby` tool are really about assembling components to build a system/platform. Compose is about composing and running applications. `moby` is really about assembly, the `run` part is likely going away. linuxkit/moby doesn't support stuff like `link`, name resolution etc. They are really quite different and shouldn't be confused or sued for the same thing

**Comment by justincormack** [comment]
Also Rancher OS uses Compose for much this role, so seems relevant...

**Comment by deitch** [comment]
> I don't think my view is a purist view.

My original comment might have come across more as snarky than robust debate; unintended, @rneugeba.

> Compose is about composing and running applications. moby is really about assembly.

Agreed. But _what_ we are assembling might actually be applications. Many of the examples do exactly that (linuxkit.yml with nginx, kubernetes, etc.) in a simplified fashion. One of the beauties of linuxkit is that you can assemble _any_ image into it as `onboot` or `services`, so I can make a pre-baked image with my entire app on it, not just exposing a docker. I love it, I think it is a great way to have a truly immutable secure system, with complex apps on it... yet all packaged as container images.

But I would need to know how to do it.

I am happy to start with the 1st simpler case, though, as @justincormack raised: single image as service with compose in it that talks to a docker service, if I can pre-bake the images in the compose into the linuxkit image somehow.

I think I see four distinct cases:

1. Vanilla distro with compose ready and listening. All docker containers started by docker cli (or REST API) externally. This is very similar to RancherOS.
2. Distro with app definition (compose file) defined as another of the `services`. When it starts, it causes docker to run the apps. Identical to 1 above, except that the app definition is baked into the OS image.
3. Distro with app definition (compose file) *and app images* baked in. Identical to 2 above, except it does not need to talk to registry to get images. Has better immutability, security and startup times.
4. Distro with app baked in *as linuxkit services*. This is essentially the same as the linuxkit.yml nginx example, but with greater app complexity. 

We know how to do 1 (see https://github.com/linuxkit/linuxkit/blob/master/examples/docker.yml), 2 is fairly straightforward (happy to put together a sample case and PR if it will get merged in). It is 3 and 4 I struggle with.

**Comment by techninja1008** [comment]
I too am quite interested in this issue as it could potentially be very useful to the IoT area once linuxkit supports arm.

@deitch you could make #3 work by having your compose image (or maybe a compose-based image, thinking FROM here) do some `docker save`ing in the Dockerfile after a pull and then `docker load` at runtime.

**Comment by deitch** [comment]
@techninja1008 

> you could make #3 work by having your compose image (or maybe a compose-based image, thinking FROM here) do some docker saveing in the Dockerfile after a pull and then docker load at runtime.

`docker save` *in* the Dockerfile?

**Comment by techninja1008** [comment]
Yeah, in the one for the compose service. It'd need to be DinD though.

**Comment by deitch** [comment]
See https://github.com/linuxkit/linuxkit/pull/1961

**Comment by deitch** [comment]
Closing in favour of #1961
