### ISSUE TITLE
Proposal: example for swap created and configured by onboot

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#1694]
I have had a need for an instance with swapfile, configured at build time. The sample at https://github.com/deitch/linuxkit-swap includes that, as well as adding conditions (e.g. "only make swapfile if `/var/external` is its own filesystem and >20GB"). Encrypted swap is in partially, but largely depends on devicemapper.

**Comment by justincormack** [comment]
We do want a generic swap service in the repo. We currently use swap on the desktop (but not cloud) Docker Editions so will use for those anyway. I think it selects if there is enough disk space and not lots of memory, so would be great to do a PR for this.

**Comment by justincormack** [comment]
(it used to be in the format code in d4m/d4w but I removed it to make things more modular so we dont have anything right now)

**Comment by deitch** [comment]
Sure, I will PR it. Wait for resolving encrypted swap first? Or as is?

**Comment by justincormack** [comment]
I think we can add encryption later.

**Comment by deitch** [comment]
Closing in favour of #1715
