### ISSUE TITLE
Network Options for the qemu runner

### ISSUE THREAD

**Issue by fntlnz** [linuxkit/linuxkit#1698]
Right now the qemu runner has a very limited set of options available, but the thing I most need is the ability to specify network options to the VM.

The  hyperkit runner for example uses a  VPNKit key generated from the IP address to allow you to bridge a network interface from the host to the VM.

In qemu things would be easier because it already has all the needed options to do bridging/port forwarding, for example, I achieved a simple 8080:80 port forwarding in my fork like this:

```go
qemuArgs = append(qemuArgs, "-net", "user,hostfwd=tcp::8080-:80")
qemuArgs = append(qemuArgs, "-net", "nic")
```

Also, I think that there should be some shortcut like hyperkit's `-ip` to allow some sort of consistency between different runners when the runner is not specified and the default is used.

Wdyt?

**Comment by fntlnz** [comment]
BTW, I would be glad to submit a pr to achieve this and discuss on the code if there's interest

**Comment by justincormack** [comment]
cc @thebsdbox @dave-tucker

**Comment by thebsdbox** [comment]
Sure sounds like a good idea, I was a little concerned about wrapping too many of the options for `qemu` and i'm not sure if it would be easier just having the capability to pass through a string containing any additional/advanced params/arguments. Would simplify the use of multiple host forwarded ports. 

Happy to discuss the code.

**Comment by alexellis** [comment]
For developer experience a unified CLI would be helpful - so that `-ip` works the same for either back-end where applicable. Docker-machine had a "plugin" model - does this make sense for `moby`?

**Comment by rneugeba** [comment]
Networking is quite specific to the VMM used and the host platform so I doubt we'll get consistent options across different runner.

The PR to expose ports with qemu has been merged.

Can this be closed, or is there something in the discussion I missed?

**Comment by fntlnz** [comment]
@rneugeba completely agree :+1: but keeping an eye on having the most consistent possible set of options

Closing this
