### ISSUE TITLE
Status of the start-stop-daemon and type safety

### ISSUE THREAD

**Issue by fntlnz** [linuxkit/linuxkit#1731]
I see that for the init package `linuxkit/init` there's a modified version `start-stop-daemon` here https://github.com/linuxkit/linuxkit/blob/master/pkg/init - I have only a few minor concerns about it:

- How is the lifecycle of that piece of software going to be managed?
- Will we backport fixes (security fixes primarly) from it's source or is a complete separate thing?
- If I need to do a fix where should I do it?
- Could we rewrite it in Go or in a type safer language?

**Comment by fntlnz** [comment]
PTAL @justincormack and @riyazdf

**Comment by justincormack** [comment]
That should go away; this is a leftover of before we were using `containerd` to manage system services. We are currently waiting for https://github.com/containerd/containerd/issues/770 to be fixed and also ongoing work on switching over to the `containerd` image store in order to remove that.
