### ISSUE TITLE
Handle kernel module loading better

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#1742]
With vendor kernels being mostly modules based I noticed that we are not loading modules for device drivers on boot.

We currently can't run `modprobe` as we don't have `modules.dep`. The vendor kernels (at least centos and ubuntu) don't have them in the package. We can't run `depmod` as we have a read-only root filesystem.

Ideally we run `depmod` pre-boot, but I'm not sure we can do that...

**Comment by justincormack** [comment]
Hmm, we do have `modules.dep` in our builds (and I was thinking of setting up a service to run it, as we now have modular `btrfs`). They must have them in another package? We could bind mount and make `modules.dep` but its a bit slow and clunky. You can run it at the end of the kernel build/packaging I think, from memory.

**Comment by rneugeba** [comment]
Ideally we run it at end of kernel build so we don't have to mess around with it during boot

**Comment by rneugeba** [comment]
we also need to consider if we want something like `udev` to load modules for devices on boot

**Comment by justincormack** [comment]
We are currently using busybox `mdev` which should do that in theory, but not entirely sure how well it works.

**Comment by rneugeba** [comment]
I tried it with foreign kernels and it didn't seem to work...need to poke around a bit more.

**Comment by justincormack** [comment]
Yeah, it didnt autoload `btrfs` on our kernel when I tried either (which is our only major module), I thought `mkfs` would try to autoload but not sure if it will or not.

**Comment by pwFoo** [comment]
I just have done some short testing with mdev yet, but it should work for hotplugged devices during the system is up and running.

**hotplug**
* echo /sbin/mdev > /proc/sys/kernel/hotplug
* echo '$MODALIAS=.*    0:0 660 @modprobe "$MODALIAS"' > /etc/mdev.conf
* /sbin/mdev -s


But you should need a function to load modules during boot.
At the moment I still use a simple (and slow) script during boot.

```
MODALIAS=`find /sys/devices -iname modalias -exec cat {} \;`
TMODALIAS="" 

while [ `echo "$MODALIAS"|wc -l` -gt `echo "$TMODALIAS"|wc -l` ]; do
    for i in $MODALIAS; do
        /sbin/modprobe $i 2>/dev/null
    done

    [ "$VERBOSE" ] && echo Loaded `echo "$MODALIAS"|wc -l` modaliases
    [ "$DRV_WAIT" -gt 0 ] && sleep $DRV_WAIT
    TMODALIAS="$MODALIAS" 
    MODALIAS=`find /sys/devices -iname modalias -exec cat {} \;`
done
```

Maybe that [**link**](http://comments.gmane.org/gmane.linux.busybox/40136) helps?
Examples about hotplug and also code to load modules during boot.
**coldplug (from alpine)**

```
find /sys -name modalias | xargs sort -u \
  | xargs modprobe -a 2> /dev/null
```

or

```
grep -h MODALIAS /sys/bus/*/devices/*/uevent | \
    cut -d= -f2 | xargs modprobe -abq 2>/dev/null
```

**Comment by rneugeba** [comment]
@pwFoo thanks for the pointers. I will look into this once I get around to it. At the moment, at least with the LinuxKit kernels we compile all drivers into the kernel. But this is already an issue with "foreign" kernels, which are mostly module based

**Comment by pwFoo** [comment]
I don't know if it's really  needed, but it seems a mdev.conf is recommended.
```echo '$MODALIAS=.* 0:0 660 @modprobe "$MODALIAS"' > /etc/mdev.conf```

You should NOT use the loop mentioned above because it's extremely slow... :)
Automatically load modules during boot works fine and fast with this line:
```
grep -h MODALIAS /sys/bus/*/devices/*/uevent | cut -d= -f2 | xargs modprobe -abq 2>/dev/null
```

Tested it with a custom init container (added to rcS script and built a local init image. HDD and sound card was detected and modules loaded.

**Comment by rn** [comment]
based on a comment here: https://github.com/linuxkit/linuxkit/pull/1906#issuecomment-308034610 I tried the following:

- Added `btrfs-progs` to `getty` package for testing
- Create a YAML with `format`/`mount` packages to mount a disk at `/var/lib/test`
- Build, boot with a 4G disk
- The within the `getty` container:
  - `mkdir /mnt/btrfs`
  - `dd if=/dev/zero of=/var/lib/test/foo  bs=1048576 count=2048`
  - Make a filesystem
```
btrfs-progs v4.10.2
See http://btrfs.wiki.kernel.org for more information.

Label:              (null)
UUID:               10fddba0-9fe3-4681-a474-e1a40848904f
Node size:          16384
Sector size:        4096
Filesystem size:    2.00GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP             102.38MiB
  System:           DUP               8.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1     2.00GiB  /var/lib/test/foo
```
- Mount it:
```
/ # losetup /dev/loop0 /var/lib/test/foo
/ # mount /dev/loop0 /mnt/btrfs
[  135.600335] raid6: sse2x1   gen()  9265 MB/s
[  135.769210] raid6: sse2x1   xor()  7063 MB/s
[  135.940189] raid6: sse2x2   gen() 11340 MB/s
[  136.109212] raid6: sse2x2   xor()  7986 MB/s
[  136.280903] raid6: sse2x4   gen() 13692 MB/s
[  136.450183] raid6: sse2x4   xor()  9160 MB/s
[  136.619806] raid6: avx2x1   gen() 17548 MB/s
[  136.791125] raid6: avx2x2   gen() 21680 MB/s
[  136.960174] raid6: avx2x4   gen() 24462 MB/s
[  136.960740] raid6: using algorithm avx2x4 gen() 24462 MB/s
[  136.961395] raid6: using avx2x2 recovery algorithm
[  136.962344] xor: automatically using best checksumming function   avx
[  136.972949] Btrfs loaded, crc32c=crc32c-intel
[  136.973558] BTRFS: device fsid 10fddba0-9fe3-4681-a474-e1a40848904f devid 1 transid 5 /dev/loop0
[  136.991209] BTRFS info (device loop0): disk space caching is enabled
[  136.991822] BTRFS info (device loop0): has skinny extents
[  136.992883] BTRFS info (device loop0): flagging fs with big metadata feature
[  136.996728] BTRFS info (device loop0): creating UUID tree
```

So, this auto-loaded the `btrfs` filesystem kernel module as expected.

**Comment by justincormack** [comment]
You sure it autoloaded it, vs eg `mkfs.btrfs` doing a `modprobe`?

**Comment by rn** [comment]
yes, I'm pretty sure it autoloaded. the `mkfs.btrfs` does not need it and the module got loaded on the `mount`. The output after the mount is from the kernel module loading

**Comment by rn** [comment]
just verified (and fixed the above comment). The `mkfs.btrfs` does not load the kernel module. The `btrfs` kernel module is loaded during `mount`

**Comment by pwFoo** [comment]
@rn @justincormack 
The current cold plug code doesn't work well. Some modules missing after boot. My HDD needs sd_mod which isn't loaded by the used snippet. I'll do some more tests to verify in the next days.

**Comment by ijc** [comment]
I guess `sd_mod` is not, strictly speaking, a "driver" for a piece of hardware, it is further up the stack (e.g. `ahci` is the hardware driver, `sd_mod` is another link in the chain). So I guess it is not covered by the cold plug of hardware drivers.

Not sure how this is handled in general by other distros, but I notice that `initramfs-tools` on Debian includes:
```
        if [ -e /sys/bus/scsi/devices/ ]; then
                modules="$modules sd_mod"
        fi
```
among its list of special cases (this is building the initramfs, rather than cold plug, but it is in effect preprocessing a list of things to cold plug).

**Comment by justincormack** [comment]
But modprobing ahci will pull in `sd_mod` anyway? Or is it needed for probing? We could build in `sd_mod` and similar infrastructure modules if it makes it simpler, it is mainly all the device drivers it makes sense to have as modules.

**Comment by ijc** [comment]
I don't think modprobing `ahci` will pull in `sd_mod`, there is no code/symbol dependency between them, they are interacting indirectly through the SCSI bus subsystem.

**Comment by justincormack** [comment]
Oh, hmm, but @pwFoo must need sd_mod for something, sorry was saying `ahci` for no reason.

**Comment by ijc** [comment]
`sd_mod` is what creates the `/dev/sd*` devices (you can think of it as `sd_mod` links the SCSI subsystem to the block subsystem and `ahci` links the SCSI subsystem to the hardware).

The SCSI subsystem, having identified some devices on the bus as being in the "disk" class should, I think, be generating an event to load the driver for those, based on:
```
$ grep TYPE_DISK drivers/scsi/sd.c
MODULE_ALIAS_SCSI_DEVICE(TYPE_DISK);
```
I think it does, so we are not picking up that event for some reason. Perhaps this is an `mdev` issue, or relates to the static hotplug handler thing which was added recently?

**Comment by pwFoo** [comment]
sd_mod is needed to have hdd (/dev/sda) available, yes. 

The used code 
```
# Load modules for cold-plugged devices (ie devices present on boot)
grep -h MODALIAS /sys/bus/*/devices/*/uevent | cut -d= -f2 | xargs modprobe -abq 2> /dev/null
```
should also read scsi devices. There is a `MODALIAS=scsi:t-0x00` which is an alias for sd_mod, right?

modinfo snippet (another host with sd_mod):
```
alias:          scsi:t-0x0e*
alias:          scsi:t-0x07*
alias:          scsi:t-0x00*
```

So the current cold plug could miss some devices or just scsi devices.

**Comment by ijc** [comment]
Maybe the relevant match under `/sys/bus/*/devices/*/uevent` wasn't there the first time yet, either because `ahci` wasn't loaded at that point or because there was an initialisation race?

**Comment by pwFoo** [comment]
Earlier I used the loop posted above without sd_mod problems:
```
MODALIAS=`find /sys/devices -iname modalias -exec cat {} \;`
TMODALIAS="" 

while [ `echo "$MODALIAS"|wc -l` -gt `echo "$TMODALIAS"|wc -l` ]; do
    for i in $MODALIAS; do
        /sbin/modprobe $i 2>/dev/null
    done

    [ "$VERBOSE" ] && echo Loaded `echo "$MODALIAS"|wc -l` modaliases
    [ "$DRV_WAIT" -gt 0 ] && sleep $DRV_WAIT
    TMODALIAS="$MODALIAS" 
    MODALIAS=`find /sys/devices -iname modalias -exec cat {} \;`
done
```
But here is /sys/devices scanned instead of /sys/bus/*/devices/*/uevent and there is a re-scanning started in the end I think?
```
while [ `echo "$MODALIAS"|wc -l` -gt `echo "$TMODALIAS"|wc -l` ]; do
[...]
    MODALIAS=`find /sys/devices -iname modalias -exec cat {} \;`
done
```
