### ISSUE TITLE
YML enhancement - Support capabilities: none

### ISSUE THREAD

**Issue by alexellis** [linuxkit/linuxkit#1747]
**Description**

For a less surprising developer experience `capabilities: none` could be supported to mirror the `capabilities: all` setting.

**Steps to reproduce the issue:**

Add `capabilities: none` to a LinuxKit YML file.

**Describe the results you received:**

Invalid for target.

**Describe the results you expected:**

Acts in the same way as if nothing was supplied. If none is one of the options then this should be mutually exclusive with any other option.

cc @justincormack

**Comment by justincormack** [comment]
That should be in https://github.com/moby/tool
