### ISSUE TITLE
[Question]  What can we use linuxkit build images with docker ?

### ISSUE THREAD

**Issue by HackToday** [linuxkit/linuxkit#1759]
**Description**

Hi  @justincormack ,  I have read the docs and tried linuxkit manually.

Right now, I am confused with the linuxkit built images, and docker images.

Could you help answer that ?

1> For  all docker images, we can use docker tool to run and exec.  
If with linuxkit, it would produce some images, like ISO format, kernel+initrd image.  

Could docker run with those images?  I think no.  

If yes, how can docker( or rkt) use those images ?

2> What's the use cases for linuxkit image  ?

Per my understanding, it would be like customized images (For example, minimal-os image, minimal-redis image)

Those images would be for hypervisor  platform and cloud platform.

For docker itself, it have docker registry. 

So linuxkit images and docker images are managed by different tool.  Is it ?

**Comment by justincormack** [comment]
Yes that is right. LinuxKit is at a much lower level than Docker, for building systems, not so much for user applications. It builds VM images, one common use case for these is to run the Docker engine itself; this is how we use LinuxKit internally in the Docker Editions.

**Comment by HackToday** [comment]
Hi  @justincormack  

Could you elaborate a little more how to run Docker engine in such VM images ?

I tried  https://github.com/linuxkit/linuxkit/blob/master/examples/docker.yml
It seems in such VM, you could not execute any docker command.  

Or do you have such example which I can try ?

Thanks

**Comment by justincormack** [comment]
It is not very easy to use right now, we are currently in the process of rebuilding the Docker Editions so we should have better examples soon.

If you do 
```
docker exec -t docker sh
```
from the console you will be able to run containers after that.

We should have a full easy to use version in a while.

**Comment by HackToday** [comment]
Hi @justincormack  

Maybe we not use same example,

I use https://github.com/linuxkit/linuxkit/blob/master/examples/docker.yml
and after moby build, it had following

```
-rw-r--r-- 1 root root     2372 May  2 08:25 docker.yml
-rw-r--r-- 1 root root 75668558 May  3 08:02 docker-initrd.img
-rw-r--r-- 1 root root  7541328 May  3 08:02 docker-kernel
-rw-r--r-- 1 root root       40 May  3 08:02 docker-cmdline

```

And run `linuxkit run docker`

enter the VM, and run 

```
/ # docker exec -t docker sh
docker exec -t docker sh
/bin/sh: docker: not found[   66.364855] random: fast init done
```

BTW, my docker on host version is 1.12.0


**Or do that example need to work with docker CE  v 17.0x  ?**

**Comment by justincormack** [comment]
sorry, typo, use `runc exec -t docker sh`

**Comment by arm64b** [comment]
Hi @justincormack 
I have the same issue with @HackToday , I moby build `docker.yml` and `bin/linuxkit run qemu -uefi -fw /usr/share/ovmf/OVMF.fd -networking tap,tap0 docker`
When enter into the system, I can:
```
(ns: getty) linuxkit-8ea4a5096881:/# ctr c
CONTAINER    IMAGE    RUNTIME                           LABELS    
dhcpcd       -        io.containerd.runtime.v1.linux    -         
docker       -        io.containerd.runtime.v1.linux    -         
getty        -        io.containerd.runtime.v1.linux    -         
ntpd         -        io.containerd.runtime.v1.linux    -         
rngd         -        io.containerd.runtime.v1.linux    - 
```
but when I tried to execute the command `runc exec -t docker sh`:
```
(ns: getty) linuxkit-8ea4a5096881:/# runc exec -t docker sh
exec failed: container "docker" does not exist
```
So what's usage scenario of the 'docker.yml'?

**Comment by paulshannon** [comment]
@justincormack I have the same question as @arm64b above; I feel like I am missing something fundamental here...

**Comment by ijc** [comment]
`containerd` doesn't use the default `runc` root these days, so `runc exec` will not work.

Try `ctr exec --exec-id foo -t docker ash -l` to get a shell in the docker container.

**Comment by kevinbrink** [comment]
Version `v1.0.0-beta.0` of `ctr` (which is what's installed with the [current docker example yml from linuxkit](https://github.com/linuxkit/linuxkit/blob/master/examples/docker.yml)) doesn't seem to have an `exec` option:

```
(ns: getty) linuxkit-025000000004:~# ctr c --help
NAME:
   ctr containers - manage containers (metadata)

USAGE:
   ctr containers command [command options] [filter, ...]

COMMANDS:
     delete, del, rm  deletes one or more existing containers
     label            Set and clear labels for a container.
     info             get info about a container

OPTIONS:
   --quiet, -q  print only the container id
   --help, -h   show help
```

However, using `runc` **will** work if you point it at the correct "root directory for storage of container state" for the **service** containers. I happened to stumble on the correct directory to use while digging around. 

The default is `/run/runc`, but for whatever reason, with recent changes, any containers that are started as a "service" have their state stored in the `/run/containerd/runc/default` directory. 

So all you need to do to get your `docker exec` running is add in the `--root /run/containerd/runc/default` flag, like so:

```
(ns: getty) linuxkit-025000000004:~# runc --root /run/containerd/runc/default list
ID          PID         STATUS      BUNDLE                                                          CREATED                          OWNER
dhcpcd      510         running     /run/containerd/io.containerd.runtime.v1.linux/default/dhcpcd   2017-09-14T16:00:00.4800029Z     root
docker      585         running     /run/containerd/io.containerd.runtime.v1.linux/default/docker   2017-09-14T16:00:00.5740894Z     root
getty       635         running     /run/containerd/io.containerd.runtime.v1.linux/default/getty    2017-09-14T16:00:00.6993412Z     root
ntpd        712         running     /run/containerd/io.containerd.runtime.v1.linux/default/ntpd     2017-09-14T16:00:00.8204147Z     root
rngd        797         running     /run/containerd/io.containerd.runtime.v1.linux/default/rngd     2017-09-14T16:00:00.941831134Z   root
(ns: getty) linuxkit-025000000004:~# runc --root /run/containerd/runc/default exec docker docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

It's a little gnarly, but it works.

**Comment by ijc** [comment]
> ... doesn't seem to have an exec option:

Oh, sorry, it's `ctr task exec ...` these days.
