### ISSUE TITLE
no host networking on Linux/qemu

### ISSUE THREAD

**Issue by mbruzek** [linuxkit/linuxkit#1767]
**Description**

The `ssh_into_kubernetes.sh` script does not work on Ubuntu Linux.

**Steps to reproduce the issue:**
I was following the linuxkit Kubernetes README.md file: https://github.com/linuxkit/linuxkit/blob/master/projects/kubernetes/README.md
Step 4 failed when I attempted to ssh to the running instance.

**Describe the results you received:**
Step 3:
```
# ip addr show dev eth0
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fec0::45e:2c0c:9f1c:ebca/64 scope site dynamic 
       valid_lft 86354sec preferred_lft 14354sec
    inet6 fe80::40b8:f19d:2eed:ed8e/64 scope link 
       valid_lft forever preferred_lft forever
```
The docker runtime downloaded an image, but it appears to hang, here is the output:
```
$ ./ssh_into_kubelet.sh 10.0.2.15
+ ./ssh.sh -t 10.0.2.15 nsenter --mount --target 1 runc exec --tty kubelet ash -l
+ docker run -ti -v /home/mbruzek/.ssh/:/root/.ssh jdeathe/centos-ssh ssh -o Compression=yes -o LogLevel=FATAL -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -t 10.0.2.15 nsenter --mount --target 1 runc exec --tty kubelet ash -l
```

**Describe the results you expected:**
I expected to ssh to the running VM on my system.

**Additional information you deem important (e.g. issue happens only occasionally):**
I saw this work on a Mac earlier today, and I don't understand why this isn't working on my Linux machine (yet).

The vm is running in qemu (from the `linuxkit run` command):
```
$ ps -ef | grep qemu
mbruzek  17961 17956 70 16:04 pts/18   00:06:55 /usr/bin/qemu-system-x86_64 -device virtio-rng-pci -smp 2 -m 4096 -enable-kvm -machine q35,accel=kvm:tcg -kernel kube-master-kernel -initrd kube-master-initrd.img -append console=ttyS0 console=tty0 page_poison=1 -nographic
```

```
$ uname -a
Linux pandora 4.8.0-49-generic #52-Ubuntu SMP Thu Apr 20 09:38:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   78d1802
 Built:        Tue Jan 31 23:47:34 2017
 OS/Arch:      linux/amd64
```

**Comment by justincormack** [comment]
Can you get onto the console? There are logs in `/var/log` for `sshd`. Did you allocate enough memory for the nodes (currently it needs a lot, will be fixed, and various things may fail if it doesnt have enough).

cc @errordeveloper @ijc25

**Comment by ijc25** [comment]
I noticed this yesterday too. I think in the default (SLIRP) networking configuration the simply host cannot access the qemu guest network.

I'm unsure how to resolve this without a) requiring root and b) requiring host level networking setup (i.e. switching to `tap` or some other privileged mode). Perhaps using slirp's `hostfwd` option to bind a host port to guest 22 would suffice as a workaround.

For guest-to-guest comms (i.e. to produce a cluster) something like the `-net socket` option with a common option might work, but I think that is better left to infrakit.

Personally I just logged into the guest console instead and ran `runc exec --tty kubelet` from there to get a shell.

**Comment by justincormack** [comment]
@ijc25 ah yes of course, that makes sense. Maybe we should add an option for host networking with a note it requires root?

**Comment by ijc25** [comment]
Perhaps just expose a way to pass in the raw value for qemu's `-nic` option, with the caveats that this might require you to have root?

**Comment by rneugeba** [comment]
It would be nice to add a doc for qemu similar to the one I created for hyperkit/macos. There is also the patch to expose ports with qemu (https://github.com/linuxkit/linuxkit/pull/1713)

**Comment by mbruzek** [comment]
@justincormack thanks for the response. As for allocating enough memory I was running the `boot-master.sh` script that has `-mem 4096`. I believe there is enough memory on the host.
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G          9G        1.7G        863M        3.5G        4.0G
Swap:          3.8G        766M        3.1G
```

For completeness here are the contents of sshd log:  
```
/var/log # more sshd.log 
[WARN  tini (686)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
```

Which process should I run with root? boot-master.sh  or the wrapped `linuxkit run` command? Is there something that I can test on my end?

**Comment by justincormack** [comment]
@mbruzek see above from @ijc for the issue - qemu slirp mode does not give access from the host

**Comment by mbruzek** [comment]
I can confirm that running the kubelet container from the guest shell worked using:  
```
# runc exec --tty kubelet ash -l
```
From there I was able to issue `kubeadm init` command. Perhaps we should change the instructions to suggest this approach. I suspect we do want the ssh method to work as well, but that requires a code fix, I don't know much about slirp but willing to learn.

I was able to progress further on the Kubernetes readme, but got wedged on different issues. @errordeveloper were you working off an unpublished branch for the demo yesterday?  I can create issues for the next few problems, if you wish.

**Comment by lachie83** [comment]
This appears to work in when using docker edge as referenced in #1800

**Comment by mbruzek** [comment]
@lachie83 thanks for the link. That seemed to be related to Mac and Docker edge. I installed the dockerCE edge on my Ubuntu system today: 
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:27:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:27:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
And was **still** unable to ssh to the master, the script timed out:
```
$ ./ssh_into_kubelet.sh 10.0.2.15
+ ./ssh.sh -t 10.0.2.15 nsenter --mount --target 1 runc exec --tty kubelet ash -l
+ docker run -ti -v /home/mbruzek/.ssh/:/root/.ssh jdeathe/centos-ssh ssh -o Compression=yes -o LogLevel=FATAL -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -t 10.0.2.15 nsenter --mount --target 1 runc exec --tty kubelet ash -l
```
I turned on verbose on the ssh image, not much more information:
```
$ ./ssh_into_kubelet.sh 10.0.2.15
+ ./ssh.sh -t 10.0.2.15 nsenter --mount --target 1 runc exec --tty kubelet ash -l
+ docker run -ti -v /home/mbruzek/.ssh/:/root/.ssh jdeathe/centos-ssh ssh -vvv -o Compression=yes -o LogLevel=FATAL -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -t 10.0.2.15 nsenter --mount --target 1 runc exec --tty kubelet ash -l
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.0.2.15 [10.0.2.15] port 22.
```

This still seems broken from a users perspective. Is there something else I can try or more information I can provide?

**Comment by justincormack** [comment]
@mbruzek see https://github.com/linuxkit/linuxkit/issues/1767#issuecomment-299140267 for the answer on Linux...

**Comment by ijc25** [comment]
@mbruzek yes @lachie83 had a different issue on Mac. So far as I know nothing has changed/improved wrt `ssh_into_kubernetes` when running on Linux.

**Comment by justincormack** [comment]
Its not a bug, its just a non feature right now, its just how the non privileged qemu networking works. There are several possible ways to fix this.

**Comment by mbruzek** [comment]
Closing this based on the last comment. I would suggest that the Kubernetes doc be updated to reflect this "non feature" as the work around is not in the doc.
