### ISSUE TITLE
make running a getty optional

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#1771]
currently `init` does https://github.com/linuxkit/linuxkit/blob/master/pkg/init/init#L27 and sets up a `getty` on every `tty`.

Make all `getty` setup part of a standalone `init` process.

Note this could also be replaced with a `getty` container.

cc @deitch

**Comment by rneugeba** [comment]
couldn't we make this conditional on `console=` entries on the kernel commandline. No entries, no getty?

**Comment by justincormack** [comment]
You want the output on the console though; if you dont put those you might not be able to see the boot log at all.

**Comment by deitch** [comment]
I am not saying we *must* follow what all prior distros have done, but there is a reason why every distro outputs stdout/stderr to console, but allows only authenticated login via console.

I think there are two separate issues here:

* Enable/disable login-less (insecure?) console access, configurable via yml or cmdline options
* Enable/disable console logging , configurable via yml or cmdline options

I think default should be secure console access only, log all to console. But that is just my opinion.

**Comment by justincormack** [comment]
For this we don't really have defaults, only examples, as currently the `init` containers have no way to add config options. In production I would generally not run a login at all, but for test it is useful.

**Comment by deitch** [comment]
> For this we don't really have defaults, only examples, as currently the init containers have no way to add config options

Meaning that whatever is in the `.yml` will get passed through irrelevant of cmdline? Or that you cannot config the `init` containers?

**Comment by rn** [comment]
this looks fixed via https://github.com/linuxkit/linuxkit/pull/1978 and some subsequent cleanups. Closing
