### ISSUE TITLE
Needs a mechanism to respond to ACPI (or other) power events

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#1773]
**Description**

Neither the `Reboot` nor `Shutdown` options in `virt-manager` cause anything to happen.

I _think_ those are generating ACPI power events and that something in the userspace needs to react to these as appropriate. I tried `apk -U add acpi` (which includes `acpid`) and ran the daemon by hand but this didn't appear to help so there must be something more required.

I didn't try a three finger salute since it was greyed out (I suspect because I hadn't configured a graphical console on the VM, just serial).

Although I am using KVM/libvirt/virt-manager I think this likely affects most virtualisation and cloud solutions as well as bare metal (where the physical power button typically generates an ACPI event on moderns systems I think).

I am using `projects/swarmd/swarmd.yml` but I don't see anything in any of the other images which would implement this.

Running `poweroff` or `reboot` manually from the console works mostly as expected, except there is no status message (I'm not sure if it is actually transitioning runlevels or not) and you can continue to interact with the console shell for several seconds afterwards until it suddenly goes dead or reboots.

**Steps to reproduce the issue:**

Start a LinuxKit image, attempt to send it a power event.

**Describe the results you received:**

Nothing happened.

**Describe the results you expected:**

I expected the system to either reboot or poweroff.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
It does transition runlevels on halt - thats what the 5s delay is, and it is configured in `inittab`.

I really don't know what is involved in this - it has mainly been designed as crash-only so far, but if it is not intrusive it would be nice to support shutdown I guess...

**Comment by rneugeba** [comment]
IIRC, on Hyper-V there is a special VMBus message which get's handled in the kernel, which then get's passed to user-space via `orderly_poweroff()`. I don't know the normal ACPI flow, but none of the kernel ACPI code calls `orderly_poweroff()`

**Comment by ijc** [comment]
Resolved by #2154!
