### ISSUE TITLE
makes uses the wrong moby version numbers and git commit

### ISSUE THREAD

**Issue by dave-tucker** [linuxkit/linuxkit#1778]
For example:

```
make bin/moby
docker run --rm --log-driver=none -e GOOS=darwin -e GOARCH=amd64 linuxkit/go-compile:5bf17af781df44f07906099402680b9a661f999b --clone-path github.com/moby/tool --clone https://github.com/moby/tool.git --commit d504afe4795528920ef06af611efd27b74098d5e --package github.com/moby/tool/cmd/moby --ldflags "-X main.GitCommit=edb909567c0296b22ba326627964b8614b3f30dc -X main.Version="0.0" " -o bin/moby > tmp_moby_bin.tar
```

Note that **d504afe4795528920ef06af611efd27b74098d5e** is the moby commit whereas **edb909567c0296b22ba326627964b8614b3f30dc** is passed in to the LDFLAGS.

The same is true of the version number too!

**Comment by justincormack** [comment]
Ah good point...

**Comment by dave-tucker** [comment]
Oh, and if you install via `go get` you will get `version: unknown` due to lack of `LDFLAGS` 😖 

The best solution I can think of is to fetch the binary from a GitHub release or defer to something like homebrew/linuxbrew/chocolately and make sure we have packages available for both moby and rtf.

**Comment by justincormack** [comment]
We definitely want packages. When we switch to using `containerd` for the `moby` tool it will want `containerd`, `dist`, and (optionally) `registry` available, so having this all compiled in a container will be a pain.

**Comment by rn** [comment]
this seems fixed:
```
[master]iMac:c/linuxkit/linuxkit: moby version
moby version 0.0
commit: d8cc1b3f08df02ad563d3f548ac2527931a925a6
[master]iMac:c/linuxkit/linuxkit: grep ^MOBY_COMMIT Makefile
MOBY_COMMIT=d8cc1b3f08df02ad563d3f548ac2527931a925a6
```
The brew formula also reports the correct version.

closing

**Comment by justincormack** [comment]
Oh yes, I fixed it the other day...
