### ISSUE TITLE
VMware `run` command has disk options which are inconsistent with other backends

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1780]
The `qemu` and `hyperkit` `run` backends take a `disk-size` argument and create disks if they don't exist. Ideally, the `vmware` backend should do the same

**Comment by rneugeba** [comment]
@thebsdbox do you think this can be done? Note sure how easy it is to create a VMware disk image

**Comment by thebsdbox** [comment]
It can be done, it isn't as simple as creating a flat file and attributing it to a Virtual Machine however as the disk has to have the correct format to work as a VMDK. There are tools inside of VMware Fusion.app and Workstation that should allow us to do this, i'll investigate.

**Comment by rneugeba** [comment]
Thanks. It would be nice to have a consistent UX where possible

**Comment by fntlnz** [comment]
Reported the same thing a few days ago https://github.com/linuxkit/linuxkit/issues/1732 sadly it's already happening. IMHO we need a better way to ensure that "common" options honors some rules, if we even know how to define them.

**Comment by rneugeba** [comment]
closed via #1813
