### ISSUE TITLE
nginx stopped working

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#1792]
Turns out I broke symlink handling... fix incoming.

@dave-tucker we really need a test for Nginx. Wondering if we should test whether it is working locally or remotely?

**Comment by dave-tucker** [comment]
@justincormack now we have port forwarding in qemu this should be pretty easy to add.
I assume that building and running `linuxkit.yml` and checking we get the nginx welcome page would be sufficient?

**Comment by justincormack** [comment]
@dave-tucker yes thats fine.
