### ISSUE TITLE
(project/kubernetes): master an nodes are all allocated the same IP/MAC addresses

### ISSUE THREAD

**Issue by lachie83** [linuxkit/linuxkit#1800]
**Description**

Master and nodes VMs get allocated to the same IP/MAC address and thus cannot communicate

**Steps to reproduce the issue:**

Following steps as described here -- https://github.com/linuxkit/linuxkit/blob/master/projects/kubernetes/README.md

**Describe the results you received:**
master (./boot-master.sh)
```shell
/ # ifconfig eth0
eth0      Link encap:Ethernet  HWaddr C0:FF:EE:C0:FF:EE
          inet addr:192.168.65.2  Bcast:192.168.65.7  Mask:255.255.255.248
          inet6 addr: fe80::53ae:a73c:c302:5564/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:15 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2190 (2.1 KiB)  TX bytes:2731 (2.6 KiB)
```

node (./boot-node.sh 1 --token <token> <master_ip:port>)
```shell
ifconfig eth0
eth0      Link encap:Ethernet  HWaddr C0:FF:EE:C0:FF:EE
          inet addr:192.168.65.2  Bcast:192.168.65.7  Mask:255.255.255.248
          inet6 addr: fe80::99a7:3221:6ff7:942e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:24 errors:0 dropped:0 overruns:0 frame:0
          TX packets:34 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3000 (2.9 KiB)  TX bytes:3611 (3.5 KiB)

```

**Describe the results you expected:**

The master and node(s) to have different IPs on the same connected network

**Comment by lachie83** [comment]
Possibly related to #1767 due to default SLIPR network configuration

**Comment by justincormack** [comment]
You need to use Docker for Mac `edge` to get this to work - the stable version does not have the hyperkit bridge code (until 17.06).

**Comment by lachie83** [comment]
Perfect. Worked a treat. Thanks
