### ISSUE TITLE
linuxkit/init: does not exist

### ISSUE THREAD

**Issue by vwarner1411** [linuxkit/linuxkit#1801]
**Description**
If I run the command  `moby build linuxkit.yml`, I receive a not found error.

**Steps to reproduce the issue:**
`moby build linuxkit.yml` 

**Describe the results you received:**
> Extract kernel image: linuxkit/kernel:4.9.x
> Add init containers:
> Process init image: linuxkit/init:deea956a9ab07bf262083e93a86930bdc610cc2f
> Pull image: linuxkit/init:deea956a9ab07bf262083e93a86930bdc610cc2f
> FATA[0004] Failed to build init tarball from linuxkit/init:deea956a9ab07bf262083e93a86930bdc610cc2f: Could not pull image linuxkit/init:deea956a9ab07bf262083e93a86930bdc610cc2f: exit status 1: Error response from daemon: manifest for linuxkit/init:deea956a9ab07bf262083e93a86930bdc610cc2f not found

**Describe the results you expected:**
I expect the image to be pulled from the repo. 

**Additional information you deem important (e.g. issue happens only occasionally):**
I checked the [linuxkit repo](https://hub.docker.com/r/linuxkit/init/tags/), and the tag deea956a9ab07bf262083e93a86930bdc610cc2f doesnt exist. If I modify the yml to use the correct latest tag (ad3c4df89242a1b9b0306b4f85389990b2cf4e86 as far as i can tell it's the latest anyway), it pulls correctly and builds the iso.

**Comment by justincormack** [comment]
Sorry, I forgot to push the new image, can you try again?

**Comment by vwarner1411** [comment]
Thanks, that's resolved it!
