### ISSUE TITLE
Build  my own kernel

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1835]
**Description**
When I rebuild the kernel under /kernel with the modified kernel_config-4.11.x and moby rebuild linuxkit.yml. After it  I run 'linuxkit run linuxkit". But the kernel is not modified. So Is it a wrong situation?

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rneugeba** [comment]
did you recompile the kernel by typing `make tag` in `./kernel`?

**Comment by yankunsam** [comment]
Yes. I just modify 2 part in Makefile.
1)
#HASH?=$(shell git ls-tree HEAD -- ../$(notdir $(CURDIR)) | awk '{print $$3}')
2)
$(eval $(call kernel,4.11,4.11.x))
#$(eval $(call kernel,4.11,4.11.x,_dbg))
#$(eval $(call kernel,4.10.15,4.10.x))
#$(eval $(call kernel,4.10.15,4.10.x,_dbg))
#$(eval $(call kernel,4.9.27,4.9.x))
#$(eval $(call kernel,4.9.27,4.9.x,_dbg))
#$(eval $(call kernel,4.4.67,4.4.x))

Is there something wrong for me?  

Thanks!

**Comment by rneugeba** [comment]
You don't need to comment out the other kernels, and can use `make build_4.11.x` to just build the 4.11 kernel (sorry, I gave the wrong command above).

What I typically do when I compile custom kernels for testing, I change the docker hub from `linuxkit` to my own (I often compile on a different machine to where I test, so having the image on hub helps).  Alternatively, you can set the `HASH` to force a rebuild, something like:
```
make build_4.11.x HASH=foo
```
will create a local docker image called `linuxkit/kernel:4.11-foo` which you can use in the YAML file

**Comment by yankunsam** [comment]
I will try as your advice. BTW, after I build the kernel. I need change linuxkit.yml like below:
kernel:
         image: "linuxkit/kernel:4.11-foo"

right? Will this use the local image?

Thanks!

**Comment by rneugeba** [comment]
yes, the YAML file should have the new docker image name

**Comment by pwFoo** [comment]
Thanks for examples with make and HASH! Should be added to the documentation 👍

**Comment by yankunsam** [comment]
When I run like this,

make build_4.9.x HASH=ima
moby build linuxkit.yml(kernel:4.9-ima)

it will report "Could not pull image linuxkit/kernel:4.9-ima: "

But when I change 4.9-ima with 4.9.27-ima. It works. I am not sure if it is important for you? 
Thanks!

**Comment by rneugeba** [comment]
sorry, my mistake (again) above. #1838 should have the correct instructions

**Comment by yankunsam** [comment]
Thanks. It works. I will close this issues.
