### ISSUE TITLE
`ctr exec -t` hangs

### ISSUE THREAD

**Issue by rneugeba** [linuxkit/linuxkit#1837]
This is likely an issue with the version of `containerd` we are using, but on the latest version (`9fd743a28fd363b9ec0bdbd8800932e3026f1eba`) and the `linuxkit.yml` example, doing a:
```
ctr exec -t --id nginx /bin/sh
```
hangs indefinitely

**Comment by justincormack** [comment]
Does it always or just sometimes? I opened an issue yesterday about the tty
on run having a race.

**Comment by rneugeba** [comment]
@avsm and @FrenchBen reported the same on slack. I've only twice and it hung both times.

**Comment by avsm** [comment]
I also noticed `ctr list` hung for me but only sporadically

**Comment by justincormack** [comment]
Can someone test this on `containerd` master not in LinuxKit and open an issue on containerd as we are not doing anything unusual.

**Comment by rneugeba** [comment]
tested with `runc:c1287819af73a4408e089a358d28d18f6adb7dfc` and `containerd:fae11b6673870e49d85ac67fb52255391ad59895` (their respective latest) in LinuxKit and the issue's still there.

Will try native next

**Comment by rneugeba** [comment]
I can repro native as well and created https://github.com/containerd/containerd/issues/869

**Comment by rneugeba** [comment]
the upstream issue (https://github.com/containerd/containerd/issues/869) was reported fixed via https://github.com/containerd/containerd/pull/940. The `containerd` currently used in the `linuxkit` package is a few commits behind that

**Comment by justincormack** [comment]
ok I will update `containerd` again

**Comment by rneugeba** [comment]
This was fixed (just verified) with one of the recent `containerd` updates
