### ISSUE TITLE
After halt, it will been blocked  and have no response

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1839]
**Description**
/ # ls
Makefile    dev         init        proc        sbin        tmp
bin         etc         lib         root        srv         usr
containers  home        media       run         sys         var
/ # halt
Terminated
/ # [  106.830184] reboot: System halted

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thebsdbox** [comment]
I'd recommend `poweroff` as some of the hypervisor backends will keep the VM in a powered on state even though the CPU has been halted.

**Comment by rneugeba** [comment]
I don't think this is not something we can fix with LinuxKit. It depends how your Hypervisor reacts to the various VM exit reason. For example in `hyperkit` we do the following: https://github.com/moby/hyperkit/blob/master/src/hyperkit.c#L531

Which backend are you using? Qemu/KVM? hyperkit? which version?

**Comment by avsm** [comment]
This is probably happening because you are using the `qemu` backend. It exists successfully with `hyperkit`

**Comment by yankunsam** [comment]
I use kvm.

**Comment by yankunsam** [comment]
Thanks. "poweroff " is good.
