### ISSUE TITLE
Windows moby build failed

### ISSUE THREAD

**Issue by tippexs** [linuxkit/linuxkit#1841]
**Description**
After installing moby on Windows 10, I tried to run moby build docker.yml to build a iso-file creating my HyperV VM).

**Steps to reproduce the issue:**
Install moby from scratch and run moby build docker.yml. 

**Describe the results you received:**
I got the following error:

$ moby build sshd.yml
Extract kernel image: linuxkit/kernel:4.9.x
time="2017-05-16T11:19:40+02:00" level=fatal msg="Failed to extract kernel image and tarball: exit status 1: Unable to find image 'linuxkit/kernel:4.9.x' locally
4.9.x: Pulling from linuxkit/kernel
64a8d3bcbb6f: Pulling fs layer
3d7df400cde5: Pulling fs layer
2eacbd228db1: Pulling fs layer
64a8d3bcbb6f: Verifying Checksum
64a8d3bcbb6f: Download complete
64a8d3bcbb6f: Pull complete
3d7df400cde5: Verifying Checksum
3d7df400cde5: Download complete
3d7df400cde5: Pull complete
2eacbd228db1: Verifying Checksum
2eacbd228db1: Download complete
2eacbd228db1: Pull complete
Digest: sha256:dd706d391fddc3d2efc254a6c03223d6cb82b86a3dc059a9264063be2fd8911f
Status: Downloaded newer image for linuxkit/kernel:4.9.x
**tar: bzImage: No such file or directory**
"

**Describe the results you expected:**
an iso file to create a HyperV VM with the linuxkit-ps1 script.

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker-Version Information:
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by rneugeba** [comment]
this looks like an old `moby` build. We change the structure of the kernel images a few weeks back

**Comment by tippexs** [comment]
Hi @rneugeba - I downloaded the go sources again and performed a make. With the new binaries it is working. The output of moby build docker.yml is now a docker-initrd.img. 

But i can't bind the img or convert it to a iso to use it with your LinuxKit.ps1 script to create the HyperV-VM out of it. 

Is there anything I missed?

**Comment by rneugeba** [comment]
you need to specify `- format: iso-efi` in the `output` section. That will create a EFI bootable ISO

**Comment by tippexs** [comment]
I just found it a second ago! Sorry :) You are right! I think that will do the trick!

**Comment by rneugeba** [comment]
glad it's working. Closing.
