### ISSUE TITLE
Selection of architecture in config by `moby` tool

### ISSUE THREAD

**Issue by mor1** [linuxkit/linuxkit#1847]
Need some way to select the target architecture needed in the config file. 
A list of target architectures perhaps?

Given multiarch support is to be used for the containers that feed into building an image, how is architecture selected if "cross-building" (that is, running the `moby` tool on architecture A to create an image to boot architecture B)? Or is "cross-building" explicitly out of scope?

**Comment by justincormack** [comment]
I think having a command line option and an option to specify an architecture in the yaml might both be useful, plus default to the host architecture if you are building on Linux, or amd64 if not. But this issue should be opened on https://github.com/moby/tool not here.

**Comment by mor1** [comment]
Ack, raised moby/tool#38. Closing this one.
