### ISSUE TITLE
Can I use a local image for image of service .

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1866]
**Description**
For example: image: "redis":3.0.7-alpine 

Can I replace it with my local image.If so, How to do this?

Thanks

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Yes it will currently use local images if you don't specify --pull on the
command line. This may change in future when we switch to containerd for
build.

**Comment by rneugeba** [comment]
closing this. Question seems to be answered. Please re-open if this is not clear

**Comment by jflatow** [comment]
Is it still possible to use local images?

**Comment by rn** [comment]
yes. I do it all the time. Do you have an issue with it?

**Comment by jflatow** [comment]
I found it works if I remove the trust section. In that case my question is: is there a way to combine trusted images with local ones?

**Comment by justincormack** [comment]
the trust section can either list specific images or orgs. if you push an image as `justincormack/blah` and the org `justincormack` is not in the trust org list it should be ok. But if you have a local image thats is `linuxkit/blah` or just `blah` it will be picked up from the default `org` of `linuxkit` and `library`.
