### ISSUE TITLE
Makefile does not rebuild bin/moby when it should

### ISSUE THREAD

**Issue by ijc25** [linuxkit/linuxkit#1880]
I just tripped over this because the reduced `sysctl` stanza in my swarmd.yml wasn't working after 702ad5d9d9646826a158774c9bd2cde259723856 when I thought it should be, it's not the first time this sort of thing has tripped me (and others) up but I couldn't find an issue for it

Looking at the `Makefile` I expect `bin/rtf` has the same issue.

I'm not sure what the right answer is. It's a `docker run` and not a `docker build` so I guess caching can never help us. We could write the commit to a stamp file and update only if it changed and have `bin/moby` depend on that, something like:
```

.PHONY: .bin.moby.stamp
.bin.moby.stamp:
        echo $(MOBY_COMMIT) > .bin.moby.stamp.new
        if cmp -s .bin.moby.stamp .bin.moby.stamp.new ; then mv .bin.moby.stamp.new .bin.moby.stamp else rm .bin.moby.stamp.new ; fi

bin/moby: .bin.moby.stamp | bin
         <build bin/moby, etc>
```
(NB sense of `cmp` may be wrong, also behaviour if one input isn't present needs confirming, also I'm sure I need either more or less `;`s in that oneliner)

That arranges (or should arrange) that if the commit doesn't change we don't change the stamp file and hence don't change its timestamp which avoids the rebuild. Possibly the stamp should container other stuff, like the git URL.

Or perhaps we could always build to `bin/moby-$(MOBY_COMMIT)` and create symlink at `bin/moby` from the same rule, so it would always point to the latest.

**Comment by justincormack** [comment]
Why not always rebuild? That's the only reason to type make anyway and it's
pretty quick.

**Comment by ijc25** [comment]
My scrollback generally contains:
```
make bin/moby bin/linuxkit && ./bin/moby build projects/swarmd/swarmd.yml
```
which saves me (or _should_ save me) from needing to worry about whether I need to rebuild `bin/moby` or `bin/linuxkit` today on the current commit or not. I would expect that if the advice was to only run `make` when you know an update is required that I (and other users) are just as likely to end up with confusion due to stale binaries.

As for "quick":
```
rm bin/moby && time make bin/moby
[...]
real	0m12.846s
user	0m0.020s
sys	0m0.020s
```
which I think is not nearly quick enough to always rebuild.

**Comment by tych0** [comment]
+1, this just bit me. I like @ijc25's first proposed solution. I can put it into a PR if it's agreeable.

**Comment by justincormack** [comment]
No that solution is horrendous. Just make the `Makefile` a dependency for `moby` and `rtf` as it has the commits in it.
