### ISSUE TITLE
External disk not work as expected

### ISSUE THREAD

**Issue by HackToday** [linuxkit/linuxkit#1886]
**Description**

**Steps to reproduce the issue:**
1. use moby build  docker example (https://github.com/linuxkit/linuxkit/tree/master/examples)
 docker kernel + initrd  images
2. then follow doc from 
https://github.com/linuxkit/linuxkit/blob/master/docs/external-disk.md

It not specify any requirements. so I ran following command

`linuxkit run qemu -disk foo.img -disk-size 1024 docker`

And if you in the VM, and check as below:

```
/ # runc list
ID          PID         STATUS      BUNDLE                         CREATED                          OWNER
dhcpcd      599         running     /run/containerd/linux/dhcpcd   2017-05-24T05:30:51.153828733Z   root
docker      635         running     /run/containerd/linux/docker   2017-05-24T05:30:53.598604676Z   root
ntpd        663         running     /run/containerd/linux/ntpd     2017-05-24T05:30:55.980477397Z   root

/ # ls -l /dev/sd*
ls: /dev/sd*: No such file or directory
/ # ls -l /dev/vd*
ls: /dev/vd*: No such file or directory
/ # 

```

**Describe the results you received:**

not any dev/sd*  dev/vd*  available

**Describe the results you expected:**

should work as the doc https://github.com/linuxkit/linuxkit/blob/master/docs/external-disk.md
dev/vd*  or  dev/sd* any available

**Comment by deitch** [comment]
What platform are you running it on?

**Comment by deitch** [comment]
And what version of `linuxkit`?

**Comment by HackToday** [comment]
Hi  @deitch  

For your questions, info as below:

```
Linuxkit: linuxkit version 0.0
commit: 72ad8ac3a3f3a79904c9eaf585dd3d4cff8b678c

Platform:  It is one VM,  OS is: CentOS Linux release 7.2.1511 (Core) 
```

**Comment by deitch** [comment]
I don't have immediate access to a CentOS platform to try. Someone from linuxkit team have that?

**Comment by HackToday** [comment]
Hi @deitch , Per my understanding, linuxkit is platform independent. It said support Linux platform.(It seems not  care about OS distribution)

**Comment by deitch** [comment]
True. The kernel you built is independent. But you are running it in `qemu`, which can vary between platforms, and via the `linuxkit` binary, which might as well. I had no problems on Mac, you did on CentOS. Might be irrelevant, might not be.

Can you look and see if the disk was created locally? `rm -f foo.img` and then rerun? Also, might want to create a gist with the output of `linuxkit run qemu ...`

**Comment by HackToday** [comment]
Hi @deitch

The gist is here     https://gist.github.com/HackToday/91ecb74e0897b76375d24647e021b714

and BTW, my qemu is here 

[root@mytest ~]# qemu-system-x86_64 --version
QEMU emulator version 2.0.0, Copyright (c) 2003-2008 Fabrice Bellard

And ps qemu output is here:

```
[root@mytest ~]# ps -ef | grep qemu
root     25893 23126  0 14:31 pts/3    00:00:00 linuxkit run qemu -disk foo.img -disk-size 1024 docker
root     25900 25893 25 14:31 pts/3    00:01:09 /usr/bin/qemu-system-x86_64 -device virtio-rng-pci -smp 1 -m 1024 -machine q35 -drive file=foo.img,format=qcow2,index=0,media=disk -kernel docker-kernel -initrd docker-initrd.img -append console=ttyS0 console=tty0 page_poison=1 -nographic
root     26286 25953  0 14:35 pts/0    00:00:00 grep --color=auto qemu

```

**Comment by deitch** [comment]
Sure looks normal. Want to add the `ls -ls /dev` to the output? Also, what was your `moby build` line?

**Comment by thebsdbox** [comment]
This will create a disk of approximately 1024 bytes`linuxkit run qemu -disk foo.img -disk-size 1024 docker`, it needs prefixing with `M` for MB or `G` for GB. 

Does the output of `fdisk -l` reveal anything?

**Comment by rneugeba** [comment]
I noticed that too. The qemu runner `disk-size` is inconsistent with the hyperkit `disk-size` parameter. the latter takes megabytes, the former bytes. They should be the same (and it should be mentioned in the usage as it does for the hyperkit runner)

**Comment by deitch** [comment]
> The qemu runner disk-size is inconsistent with the hyperkit disk-size parameter. 

Oh nice catch. We could fix the docs, but probably should just fix the problem.

**Comment by rneugeba** [comment]
IIRC there is a another inconsistency. The hyperkit runner does not need the `-disk` parameter and will create a default disk if `-disk-size` is specified.

I was going to fix this, but had to prepare some slide for later today

**Comment by HackToday** [comment]
Hi @thebsdbox and @deitch 

Use `linuxkit run qemu -disk foo.img -disk-size 1024M  docker`  got same issue: still no lucky

Please check https://gist.github.com/HackToday/97a8f82ccf5f5c0a81e4aa792eaaa3fb 
for `ls -ls /dev  ` and `fdisk`  output

**Comment by deitch** [comment]
You got me here. It appears to be creating the disk, and certainly is passing it to qemu. Maybe qemu version? What do you have? I am working pretty recent:

```
$ qemu-system-x86_64 --version
QEMU emulator version 2.9.0
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

**Comment by HackToday** [comment]
Hi  @deitch  

Yes, the qemu version was the issue, I used 2003-2008 version.

When I tried to compile to the latest version  like yours,   2003-2017 , It worked now.

as can be seen from following:

``
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   495.6M    127.4M    368.2M  26% /
tmpfs                    99.1M     36.0K     99.1M   0% /run
tmpfs                    99.1M      4.0K     99.1M   0% /tmp
dev                      10.0M         0     10.0M   0% /dev
shm                     495.6M         0    495.6M   0% /dev/shm
cgroup_root              10.0M         0     10.0M   0% /sys/fs/cgroup
tmpfs                   495.6M    127.4M    368.2M  26% /var
tmpfs                   495.6M    127.4M    368.2M  26% /containers/onboot/000-sysctl/rootfs
tmpfs                   495.6M    127.4M    368.2M  26% /containers/onboot/001-format/rootfs
tmpfs                   495.6M    127.4M    368.2M  26% /containers/onboot/002-mount/rootfs
/dev/sda1               990.9M      3.5M    920.2M   0% /var/external
tmpfs                   495.6M    127.4M    368.2M  26% /containers/services/dhcpcd/rootfs
tmpfs                   495.6M    127.4M    368.2M  26% /containers/services/rngd/rootfs
tmpfs                   495.6M    127.4M    368.2M  26% /containers/services/sshd/rootfs
`
``
