### ISSUE TITLE
how to run other container after "linuxkit run linukit"

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1895]
**Description**

Except the service in linuxkit.yml, is it possible to run a other containers with linuxkit ?
**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rneugeba** [comment]
The `onboot` and `service` containers are compiled into the image. If you want to start new containers after the system booted it's best to add a container to you image which has `docker` (or `ctr/dist`) installed.

There is a example under `./examples/docker.yml`. You can `runc exec` into the docker container and do `docker run` from there

**Comment by yankunsam** [comment]
Thanks. But how to get the container-id for "runc exec" in the os.

**Comment by rneugeba** [comment]
`runc list`

**Comment by yankunsam** [comment]
Thanks. Can you help me with this issue: https://github.com/linuxkit/linuxkit/pull/1838

**Comment by rneugeba** [comment]
closing this issue, as I get the impression that it is solved. please re-open if it isn't

**Comment by yankunsam** [comment]
Thanks!

**Comment by yankunsam** [comment]
By a docker container to pull a new container will meet some question, such  as "no space left on device". So as a os, why it is read-only ? And always to built the new iso to support the new container will be un-easy to use, right?
