### ISSUE TITLE
hyperkit: allow having no networking

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#1912]
I have use cases where I don't want to run vpnkit with the hyperkit driver at all, so I have no networking.

Can we have an option for not doing any vpnkit at all, and not configuring a network?

cc @MagnusS

**Comment by MagnusS** [comment]
This should be possible via the HyperKit API by specifying an empty vpnkit socket path, but there's a bug that resets it to ".". I've opened https://github.com/moby/hyperkit/pull/134

**Comment by justincormack** [comment]
Thanks
