### ISSUE TITLE
How to install the linuxkit.iso to a disk or virtual disk

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1916]
**Description**
Is there some doc for installing the linuxkit.iso?

Thanks.

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rneugeba** [comment]
@yankunsam you really need to provide more details in your issues. You filed several over the past week and they are pretty much one liners leaving us guessing what you mean. Again, I have no idea what you try to do...

If you have an issue, you should quote the output of commands, the version of tools involved, error messages. sample YAML files etc. If you have a question, like it would seem it is the case in this issue, you have to provide more context. If these things are not provided it is time consuming for us to follow up and, in the future, we likely will simply close or ignore issue like this.

**Comment by yankunsam** [comment]
About this issue:

When I have built the linuxkit.iso and now I want to use qemu/kvm to install  as a virtual machine, like ubuntu. So what should I do after booting with the linuxkit.iso.  I do not know if I have given you a detail description?

**Comment by rneugeba** [comment]
You don't install. You just run the image that's a major point of LinuxKit to create bootable images which can't be changed.

**Comment by yankunsam** [comment]
You mean when I run "poweroff" , the container create by "linuxkit run linuxkit.yml"  will disappear and the data also?

**Comment by rneugeba** [comment]
`linuxkit run linuxkit.yml` does not create containers in the VM.

There are examples and documentation on how to run LinuxKit with persistent storage, `examples/docker.yml` and `docs/external-disk.md`

**Comment by yankunsam** [comment]
If linuxkit did not create containers by the image defined within linuxkit.yml, who did it?  if not, who is responsible for saving the state of service.  I have read the documents, 
but ...   
Sorry for that.
