### ISSUE TITLE
After upgrade docker.

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1917]
**Description**

sammachinedeMBP:linuxkit sam$ linuxkit run linuxkit
Failed to set up pidfile
pidfile error -1
FATA[0000] Cannot run hyperkit: exit status 1
sammachinedeMBP:linuxkit sam$
**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Mac:
sammachinedeMBP:linuxkit sam$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: true
sammachinedeMBP:linuxkit sam$

And docker run xxx is well.

Thanks!

**Comment by rneugeba** [comment]
the hyperkit runner stores some state in a directory, by default `<prefix-state>` and refuses to run if some of the state, in this case the file with the PID, exists. There are two common reasons this file is there:
- you either already have an instance with the same prefix running
- a previous run did not exit cleanly (e.g. was killed with -9).

In the first case, you can run multiple instances by each giving them a different state directory using the `-state` command line argument

In the latter case, juts remove the state directory

**Comment by yankunsam** [comment]
.../linuxkit/linuxkit-state/hyperkit.pid  

Thanks
