### ISSUE TITLE
AWS support

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#1918]
We need support for AWS. Includes:

- `push` to AMI
- `run` an AMI

Plus CI.

**Comment by allingeek** [comment]
And Metadata support.

**Comment by kencochrane** [comment]
@justincormack how can I help with this?

**Comment by justincormack** [comment]
@kencochrane I am just cleaning up the code that can generate raw disk images (currently we have `img-gz` which is a compressed raw image). These should work fine on AWS. @dave-tucker was looking at the VM import code to see if we could use that, but it seems buggy, so we probably need to do the disk snapshotting method we were using before, which should be fine with the current images. We basically want a `linuxkit push` and `linuxkit run` for AWS so we have easy ability to test in CI, see eg the `gcp` code in https://github.com/linuxkit/linuxkit/tree/master/src/cmd/linuxkit for example.

**Comment by dave-tucker** [comment]
I don't think the VM import method will work without some support from AWS.

See [here](http://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html) for their docs and prerequisites. I have no idea why AWS can only support import of some OSs.

Following the example in their docs with a raw LinuxKit image gives you `ClientError: Unknown OS / Missing OS files.`

**Comment by kencochrane** [comment]
@dave-tucker that stinks. Looking at this page http://docs.aws.amazon.com/vm-import/latest/userguide/vmie_prereqs.html it looks like they have only a small list of Linux flavors that they support. We would either need to have them support a LinuxKit version, or we need a different way to do it.

#### Linux/Unix (64-bit)

- Ubuntu 12.04, 12.10, 13.04, 13.10, 14.04, 14.10, 15.04, 16.04, 16.10
- Red Hat Enterprise Linux (RHEL) 5.1-5.11, 6.1-6.6, 7.0-7.1 (6.0 lacks required drivers)
- SUSE Linux Enterprise Server 11 with Service Pack 1 and kernel 2.6.32.12-0.7
- SUSE Linux Enterprise Server 11 with Service Pack 2 and kernel 3.0.13-0.27
- SUSE Linux Enterprise Server 11 with Service Pack 3 and kernel 3.0.76-0.11, 3.0.101-0.8, or 3.0.101-0.15
- SUSE Linux Enterprise Server 11 with Service Pack 4 and kernel 3.0.101-63
- SUSE Linux Enterprise Server 12 with kernel 3.12.28-4
- SUSE Linux Enterprise Server 12 with Service Pack 1 and kernel 3.12.49-11
- CentOS 5.1-5.11, 6.1-6.6, 7.0-7.2 (6.0 lacks required drivers)
- Debian 6.0.0-6.0.8, 7.0.0-7.8.0, 8.0.0
- Oracle Linux 6.1-6.6, 7.0-7.1
- Fedora Server 19-21

**Comment by justincormack** [comment]
Reading that guide suggests it does weird things like install drivers, so I think its not going to work. We should probably stick with the disk snapshot method that we use for docker 4 aws now

**Comment by kencochrane** [comment]
@justincormack agreed

**Comment by dave-tucker** [comment]
Re-posting the link I pasted in Slack yesterday:
https://blog.zhaw.ch/icclab/walk-through-importing-virtual-machine-images-into-ec2/

Quoting the author, emphasis mine:
> The derived recommendation for VM images is therefore to build them with the Grub boot loader and its configuration, using a partitioned disk with at least one partition, and an appropriate 64-bit Xen-enabled kernel booting with initrd. **Yet, when building a minimal image from scratch using this combination of configuration choices, it still results in the ominous Unknown OS / Missing OS files error message, which is not very helpful without further details**

I agree that the aforementioned docker 4 aws method would be easier

**Comment by kencochrane** [comment]
@allingeek for metadata support do you mean adding a provider here, like we have for GCP? https://github.com/linuxkit/linuxkit/tree/master/pkg/metadata

**Comment by kencochrane** [comment]
@justincormack @dave-tucker if no one is working on adding the aws provider to the metadata package I can work on that if you would like?

**Comment by justincormack** [comment]
Sure, I don't think anyone is.

**Comment by kencochrane** [comment]
Cool, I'll get started. thanks

**Comment by kencochrane** [comment]
Submitted my PR to add an AWS provider to the metadata package. Let me know if you need help with anything else. https://github.com/linuxkit/linuxkit/issues/1954

**Comment by dave-tucker** [comment]
Success with uploading an LinuxKit raw image as an AMI

```
$ aws s3 cp disk.raw s3://<your-bucket-name>
$ cat container.json
{
    "Description": "LinuxKit",
    "Format": "raw",
    "UserBucket": {
        "S3Bucket": "<your-bucket-name>",
        "S3Key": "disk.raw"
    }
}
$ aws ec2 import-snapshot --description "LinuxKit Test" --disk-container file://containers.json
$ aws ec2 describe-import-snapshot-tasks --import-task-ids <task-id-from-above-command>
$ # You should have the snapshot ID when this finishes
$ aws ec2 register-image --name dt-LinuxKit --architecture x86_64 --root-device-name /dev/sda1 --virtualization-type hvm --block-device-mappings DeviceName="/dev/sda1",Ebs={SnapshotId=snap-0cae423393883e067}
```

I started the AMI from the console and it worked - booted, outputted stuff to serial console and then shut down!

I'll get a PR ready for this today!

**Comment by kencochrane** [comment]
@dave-tucker awesome!

**Comment by DieterReuter** [comment]
I just created a PR #1958 with an AWS example, which is basically a clone of the updated GCP example. 

So with this example it's easy to create a first AWS LinuxKit VM with ssh support, where the ssh keys will be provided through the newly added AWS support (see #1954).

**Comment by dave-tucker** [comment]
Progress is in a branch [here](https://github.com/dave-tucker/linuxkit/tree/aws)
I'm behind where I wanted to be due to issues with vendoring 🦀 

I'm currently testing this now but it *should* manage to get you an AMI but YMMV.

Then I just need to plumb in the `DescribeImages` and `RunInstances` API calls...
Displaying output from `run` will be more complicated as the `GetConsoleOutput` is bufffered and just *appears* after a given period afaict.

Testing with raw images as follows:
```
$ moby -v build -output img -size 200M linuxkit.yml
$  ./bin/linuxkit -v push aws -bucket dave-tucker-linuxkit linuxkit.img
```

This expects you to have `AWS_REGION` exported in your environment.

Docs will be included with the final PR.
