### ISSUE TITLE
qemu on macOS has no entropy source (according to rngd)

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#1924]
While we start qemu with `-device virtio-rng-pci` the VM can't find a entropy source. `rngd` fails to start with (from `linuxkit.yml`):
```
/ # ctr run --rootfs /containers/services/rngd/rootfs --runtime-config /containers/services/rngd/config.json --id rngd
[  117.359835] IPVS: Creating netns size=2104 id=3
[  117.361477] IPVS: ftp: loaded support on port[0] = 21
Unable to open file: /dev/tpm0
can't open any entropy source
Maybe RNG device modules are not loaded
```

However, according to sysfs there is a rng available:
```
/ # cat /sys/devices/virtual/misc/hw_random/rng_available
virtio_rng.0
/ # lspci
00:1f.3 Class 0c05: 8086:2930
00:00.0 Class 0600: 8086:29c0
00:03.0 Class 00ff: 1af4:1005
00:02.0 Class 0200: 8086:100e
00:1f.2 Class 0106: 8086:2922
00:1f.0 Class 0601: 8086:2918
00:01.0 Class 0300: 1234:1111
```

This is with qemu 2.9.0

the same image booted on hyperkit:
```
/ # cat /sys/devices/virtual/misc/hw_random/rng_available
virtio_rng.0
/ # lspci
00:00.0 Class 0600: 1275:1275
00:03.0 Class 1000: 1af4:1002
00:02.0 Class 0200: 1af4:103f
00:1f.0 Class 0601: 8086:7000
00:01.0 Class 0200: 1af4:1000
```

**Comment by justincormack** [comment]
Qemu has no rdrand emulation, so rngd can't do anything. I tried changing
the virtual CPU but doesn't help.

I don't think it has a virtio rng driver which is what we use for hyperkit.

**Comment by justincormack** [comment]
ok it does have a virtio rng, adding `-device virtio-rng-pci` should be sufficient. `rngd` will still just exist though.

**Comment by justincormack** [comment]
virtio rng seems to be enabled, so closing this as its a platform issue. Makes writing a test for rngd a bit annoying.
