### ISSUE TITLE
how to save the service's state when reboot the linuxkit.iso

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#1941]
**Description**

As fs as I can understand, linuxkit will generate container from image directly. But when reboot, all the useful information will disappear, right?  BTW, is linuxkit have irc or mail-list ?

Thanks!
**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
You need to create a persistent disk and mount it to store the data, for example we do this in the `docker` example https://github.com/linuxkit/linuxkit/blob/master/examples/docker.yml the `format` container will format an empty disk, `mount` will mount it, and then `docker` will use that for its persisitent data.

We dont have a mailing list yet, we have a Slack channel #linuxkit on the Docker Community Slack https://community.docker.com/registrations/groups/4316

**Comment by yankunsam** [comment]
OK thanks. I will try it.

**Comment by yankunsam** [comment]
$ cp ./examples/docker.yml linuxkit
$ moby build linuxkit.yml
$ linuxkit run linuxkit
I try "touch " a file in "/var/lib/docker/" but when reboot. The file also disappear. So what should I do to use the external disk?

Thanks!

**Comment by rneugeba** [comment]
please read `./docs/external-disks.md` on how to tell `linuxkit run` how to
specify disk

**Comment by yankunsam** [comment]
Now I do as the document:
$linuxkit run -disk ./disk.ima -disk-size 100M -iso linuxkit
Using existing disk [./disk.ima]

And it hangs up  and have no response.

What should I do?

**Comment by yankunsam** [comment]
BTW, it works well on mac, but failed on fedora.
