### ISSUE TITLE
linuxkit run hyperkit -ip <address> fails if the address was used once before

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#1970]
**Description**

The docs say `linuxkit run hyperkit -ip <address> <name>` should give it the `<address>`

It does not

**Steps to reproduce the issue:**

```
linux kit run hyperkit -ip 192.168.65.22/24 linuxkit
```

When I log in:

```
/ # ip a show eth0
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 02:50:00:00:00:58 brd ff:ff:ff:ff:ff:ff
    inet 192.168.65.27/24 brd 192.168.65.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::dcca:36f6:26df:b45e/64 scope link
       valid_lft forever preferred_lft forever
```

I have the latest linuxkit command via `go get -u github.com/linuxkit/linuxkit/src/cmd/linuxkit`

**Comment by justincormack** [comment]
Cc @magnusS

**Comment by MagnusS** [comment]
@deitch It works for me with 192.168.65.22 (without /24), but /24 is also accepted and gives me the wrong IP. Looks like the IP parsing code should have return an error: https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/run_hyperkit.go#L86. I'll take a look.

**Comment by deitch** [comment]
I tried with /24 with /32 and with no mask. None worked, but with no mask, it refused to start, just spewed error messages.

**Comment by MagnusS** [comment]
@deitch hm - which version of docker for mac do you have? This feature should be supported in newer edge releases and 17.06, but not in 17.03 stable. If the IP has already been used (if you started 22 VMs first) it would also fail - not sure how good the error message is for that. If that's the problem it may help to restart DfM

**Comment by deitch** [comment]
> newer edge releases and 17.06

I didn't think you could get 17.06 without being on edge? 
In any case, I bumped up to edge yesterday, so full restart.

> If the IP has already been used

Isn't that the idea? Should I not be able to start a vm with `192.168.65.100`, exit it, and start a new one with the same IP?

**Comment by deitch** [comment]
Hmm, so if I give it an IP I know I have not used, it works. If I try one that was used before (by `linuxkit run ...` but without `-ip ____`, it fails:

```
$ linuxkit run -ip 192.168.65.2 swap
virtio-net-vpnkit: initialising, opts="path=/Users/adeitcher/Library/Containers/com.docker.docker/Data/s50,uuid=00000000-0000-0000-0000-0000c0a84102"
Interface will have uuid 00000000-0000-0000-0000-0000c0a84102
virtio-net-vpnkit: magic=VMN3T version=1 commit=0123456789012345678901234567890123456789
virtio-net-vpnkit: read EOF
virtio-net-vpnkit: failed to read vif info
virtio-net-vpnkit: magic=VMN3T version=1 commit=0123456789012345678901234567890123456789
virtio-net-vpnkit: read EOF
virtio-net-vpnkit: failed to read vif info
```

**Comment by deitch** [comment]
That error is what got me thinking it is an invalid address and need to use full cidr. Clearly, the full cidr is ignored, and this was a different problem.

OK, renaming the issue.

**Comment by MagnusS** [comment]
@deitch I've made a PR to VPNKit to add support for reporting error messages back to the hyperkit driver. This should at least give a better error message when this happens. It will still fail if the IP address has already been used with a different VPNKit UUID though, as the IPs are assigned per UUID to allow clients to reconnect with the same network config.

We could perhaps also improve this by storing the UUID used to connect to VPNKit in the state directory and reuse it, so we don't run out of dynamically assigned IPs as quickly.

**Comment by MagnusS** [comment]
With Docker for Mac 17.09-rc1 or newer and https://github.com/linuxkit/linuxkit/pull/2490, you will get an error message if this happens and we also check that the IP can be parsed. As IPs are now reused by default (as long as the state directory is preserved) it should also take longer to use the full IP range in VPNKit. I'm not sure we can improve this further unless we allow clients to take over an IP address already assigned to a different VPNKit UUID / client.

**Comment by rn** [comment]
Thanks @MagnusS closing this issue. Please re-open if it is not fixed
