### ISSUE TITLE
sshd pkg should have additional mounts

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#1972]
In working on getty, I realized that when users log in, they expect the following:

```
     - /var:/var
     - /containers:/containers
     - /usr/bin/ctr:/usr/bin/ctr
     - /usr/bin/runc:/usr/bin/runc
     - /run:/run
     - /dev:/dev
```

in addition to the following already mounted via the Dockerfile LABEL:

```
     - /root/.ssh:/root/.ssh
     - /etc/resolv.conf:/etc/resolv.conf
```

Subject for discussion?

**Comment by deitch** [comment]
Add to that:

```yml
        - /tmp/ctr:/tmp/ctr
```

If that isn't mounted, then some `ctr` commands fail, because `ctr` places stuff in `/tmp/ctr`, which containerd (in a different context) does not see.

**Comment by rneugeba** [comment]
There are plans to have a `dev` container of sorts which would have these (plus a bunch of useful other tools). We also want to make the CI self hosting which would be another example, similar to the above.

**Comment by deitch** [comment]
> There are plans to have a dev container of sorts which would have these (plus a bunch of useful other tools)

Do you mean a container that when you put it in `services` (or `onboot`), it provides access and a bunch of necessary tools? Would we not need to be careful to mix too many together? E.g. someone might want console but not ssh, etc.

From a naming perspective, this is not exactly `dev`. I love the idea of "never log into prod", but in reality there are millions (billions?) of systems in prod that require login access, and always will. Calling it "dev" will drive people off.

FYI, I came across this while figuring out how to get `getty` out of `init` and into its own container. Been working with @justincormack on it. He also mentioned the "dev" container, and the possibility of eventually merging getty and sshd somehow.

> We also want to make the CI self hosting

What does that mean? I didn't understand it.

**Comment by rneugeba** [comment]
`dev` might not be a good name, but we wanted a sample container which people can use to log into a system to poke around, debug etc. I view this more like a more complete template people can adjust to their needs.

As for hosting CI, our CI currently spins up a debian based VM on GCP to compile the tools and then run the tests. This should be a LinuxKit VM and it needs SSH as well as docker access.

**Comment by deitch** [comment]
> a sample container which people can use to log into a system to poke around, debug etc

Is that its genesis? I see what it got the name `dev`. In the larger sense, though, it is likely to have a bigger life than for `dev`. 

> As for hosting CI, our CI currently spins up a debian based VM on GCP to compile the tools and then run the tests. This should be a LinuxKit VM and it needs SSH as well as docker access.

Got it, thanks.

**Comment by deitch** [comment]
In any case, in the meantime, might as well add the necessary paths to `linuxkit/sshd`. First, why wait for the `access` (or `dev` or whatever) container to come to life if we can fix something now? Second, I figure `sshd` will be a key basis for it, so...

**Comment by justincormack** [comment]
Yes I don't see any difference between sshd and dev, as it's designed to
let you log in and do stuff. Maybe there is a better name.

**Comment by deitch** [comment]
> Yes I don't see any difference between sshd and dev

`sshdev` ! :-)

**Comment by justincormack** [comment]
Do you want to do a PR to align `sshd` with `getty` now?

**Comment by deitch** [comment]
I have been wrapping my head around it. What do we mean when we say "align"? With the container philosophy, shouldn't getty and sshd each be an independent container?

**Comment by justincormack** [comment]
I just meant have identical binds and contents.

**Comment by deitch** [comment]
@justincormack so a single image, but run in different modes?

**Comment by justincormack** [comment]
No not at all, just make the differences between the two smaller so you dont notice really if you used ssh or getty you get the same experience...

**Comment by dweomer** [comment]
Something that I noticed with the `examples/aws.yml` image is that the `sshd` has no `runc`, nor `ctr`, nor `containerd` executables which I believe is a direct result of the `binds` entry in the YAML overriding what has been placed in the `org.mobyproject.config` label, i.e.:
```
  - name: sshd
    image: linuxkit/sshd:89b2e91d7d1bf2f40220be0e3ed586e74746cceb
    binds:
     - /var/config/ssh/authorized_keys:/root/.ssh/authorized_keys
```

Maybe this can be addressed at the same time?

**Comment by deitch** [comment]
To the best of my knowledge, the labels are synced up, so I am going to close this issue.

@dweomer yes, there is an issue that `binds:` in the `.yml` will _replace_ the list of binds in the label, instead of _supplementing_ them. That creates the issue here. There is a discussion around having a `data:` section in `.yml` that will create named volumes (similar to docker volumes) that can be mounted into a container and be distinct from (and thus not override) the binds from the labels. See https://github.com/linuxkit/linuxkit/issues/2151
