### ISSUE TITLE
Request: Add onshutdown section to yaml config

### ISSUE THREAD

**Issue by kencochrane** [linuxkit/linuxkit#1988]
Right now in the yaml config we have an `init`, `onboot`, and `services` section. It would be nice if there was an `onshutdown` section that would act just like `onboot`, but in reverse. It would be run before shutdown and allow you to add a list of images to help perform clean up tasks before the instance is shut down.

**Comment by ijc25** [comment]
Could be useful but in general you can't always expect an orderly shutdown, so the `onboot` and `services` really ought to be written to cope with recovering as necessary. cf https://en.wikipedia.org/wiki/Crash-only_software which I think is particularly pertinent to microservice type workloads.

**Comment by justincormack** [comment]
@ijc25 yes had that exact discussion already, Ken said "yeah, I'm fine if it doesn't always run, but if it does go down like normal, it would be nice to cover that use case. For D4AWS, we would like to have a chance to do some cleanup (leave swarm, etc), before the instances go away."

We already have a small script that kills processes and unmounts filesystems, this would just hook some containers in front. I wouldn't encourage anyone to use it in normal circumstances, and they should test hard brexit too ...

**Comment by justincormack** [comment]
PR here https://github.com/moby/tool/pull/124
