### ISSUE TITLE
pkg/init fails to build

### ISSUE THREAD

**Issue by tych0** [linuxkit/linuxkit#1991]
```
~/packages/linuxkit/pkg/init master make
docker build --no-cache --network=none -t linuxkit/init:83f70b224a300e63f8df62d0917486d5e8b8bb11 .
Sending build context to Docker daemon  17.92kB
Step 1/12 : FROM linuxkit/containerd:5749f2e9e65395cc6635229e8da0e0d484320ddf AS mirror
 ---> 27a76c5adbb3
Step 2/12 : RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
 ---> Running in a0ce82bb2b2e
container_linux.go:262: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
oci runtime error: container_linux.go:262: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

Makefile:11: recipe for target 'tag' failed
make: *** [tag] Error 1
```

Seems like we're using containerd's image as our source image, which itself is built from a scratch image. I can switch it back to linuxkit/alpine, but I assume that's not what we want here. I'm happy to do the PR if someone knows the right fix.

**Comment by justincormack** [comment]
unfortunately @ijc25 PR this morning switched some `alpine`s to `containerd` oops https://github.com/linuxkit/linuxkit/commit/0eb21735ae1b73d6012beff2898aaae49bf46f34

**Comment by justincormack** [comment]
Can someone do a PR to revert the broken parts?

**Comment by justincormack** [comment]
cc @riyazdf

**Comment by tych0** [comment]
Sure, I'll send one shortly.

**Comment by ijc25** [comment]
Sorry about this, was due to going back and forth with the even newer version of `containerd` (broken as described in #1979). I spotted one instance of my having done this and fixed it up but clearly missed all the many other cases :-(.

Thanks @tych0 for the fix.
