### ISSUE TITLE
mount securityfs on boot failed

### ISSUE THREAD

**Issue by yankunsam** [linuxkit/linuxkit#2019]
**Description**

when run "mount | grep "securityfs", " it is null. So there maybe is some issues for the rc.local, or else.
**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
This worked very recently, I did a build with --pull and it failed so
suspect recent kernel change.

We need to add tests for the filesystems supported as part of kernel tests.

**Comment by justincormack** [comment]
ok, fixing this now (it was mounted, but not in getty container; also adding tests)
