### ISSUE TITLE
Things to talk about at the Summit on Monday June 19

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#2033]
Please add anything you would like to discuss at the Moby Summit here.

**Comment by riyazdf** [comment]
We discussed this topic briefly on slack but would be nice to flesh out how we plan to do releases.

In particular, how often we plan to release, how long releases are supported for, etc.

**Comment by thebsdbox** [comment]
Some ideas... 

## Further supported platforms:
**Virtual**
- Digital Ocean
- RackSpace
- VirtualBox
- OpenStack
- IBMs cloud platform

**Physical**
- Cisco UCS
- RedFish (some work on going)
- Hyper Converged platforms (some are based on VMware anyway)
    - SimpliVity etc. 
    - Nutanix (has its own hypervisor (KVM fork) and APIs)

**Comment by justincormack** [comment]
@thebsdbox IBM (@davefreitag) are working on BlueMix support. We have some contact with DO, but running a custom kernel is still difficult sadly.

**Comment by riyazdf** [comment]
I'd like to discuss exposing system onboot/service container ports explicit (yml change), and if we should use stricter default iptables rules (can be controlled by a pkg)

**Comment by rn** [comment]
@riyazdf I thought it might actually be a fun project to do this with eBPF :)

**Comment by ryan-blunden** [comment]
What about who can benefit the most from LinuxKit?

As in, what type of companies should be investing in building and managing their own Linux distributions? What expertise is required? 

I'm onboard with all of the what it can deliver, but help me understand what I don't know I don't know.

Producing something from LinuxKit is one thing, but diagnosing issues, maintenance etc and essentially, what it means to maintain a distribution is more work for a company to take on. I would like to see what Docker thinks is the tipping point for when a company should invest in doing this.

**Comment by justincormack** [comment]
@ryan-blunden we didn't quite end up discussing that, but have been having a few similar conversations with companies recently, will try to prepare some answers soon.
