### ISSUE TITLE
Update Packet provider info and documentation

### ISSUE THREAD

**Issue by vielmetti** [linuxkit/linuxkit#2046]
**Description**

Information about running LinuxKit at Packet is skeletal, and could be improved.

**Steps to reproduce the issue:**

Review the [existing Packet docs](https://github.com/linuxkit/linuxkit/blob/master/docs/platform-packet.md) and notice the deficiencies.

**Describe the results you expected:**

Expected to see at least a rudimentary set of operations guidelines, with references to

* https://help.packet.net/technical/infrastructure/custom-ipxe
* https://help.packet.net/technical/networking/sos-rescue-mode

**Additional information you deem important (e.g. issue happens only occasionally):**

I have started notes here

* https://github.com/vielmetti/linuxkit/blob/patch-2/docs/platform-packet.md

but they are currently rough work in progress. I was able to successfully boot a server, but since it did not have any persistent storage, it did not survive a reboot.

**Comment by justincormack** [comment]
Indeed, the stub docs are rather useless! Improvements much appreciated.

cc @avsm who did the original work on packet support

Looking at the code there is no mention of disks, so looks like the disk support needs adding still.

The bonded interfaces are not yet supported, we would like to add support. Also the arm64 machine support is still WIP.

**Comment by rn** [comment]
I added the stubs to encourage them being filled in :)

The stubs are there to give a common outline for all platforms.
