### ISSUE TITLE
sleep issue kernel patch

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#2053]
We should consider adding

https://patchwork.kernel.org/patch/9724743/

this is in 4.12 but not backported yet.

See https://github.com/moby/moby/issues/31007

**Comment by justincormack** [comment]
cc @thaJeztah

**Comment by rn** [comment]
looks simple enough to backport

**Comment by thaJeztah** [comment]
Thanks!

**Comment by rn** [comment]
this was added to 4.9.30 as commit 6dc6a2700b6a0dd755027654b85bd614d8d3d52b and subsequently picked up by linuxkit. closing
