### ISSUE TITLE
undefined: x509.SystemCertPool

### ISSUE THREAD

**Issue by Madko** [linuxkit/linuxkit#2055]
Trying to install moby/linuxkit on CentOS 7 following the linuxkit documentation (README.md)

**Steps to reproduce the issue:**
Install CentOS 7
```
yum update
yum install golang
export GOPATH=$HOME/go
export PATH=${GOPATH//://bin:}/bin:$PATH
```
Then try to install moby:
```
$ go get -u github.com/moby/tool/cmd/moby
# github.com/moby/tool/cmd/moby
go/src/github.com/moby/tool/cmd/moby/trust.go:193: undefined: x509.SystemCertPool
```

**Describe the results you received:**
Results are not good. Maybe some prereqs are missing but can't see anything in the documentation.

**Describe the results you expected:**
I expected better results.

**Additional information you deem important (e.g. issue happens only occasionally):**
- this is static, happens every time
- I'm new to Go lang
- Likely just a bug in the doc (missing prereqs, minimal Go version, packages, or instructions)

**Comment by riyazdf** [comment]
@Madko: thanks for reporting, which version of golang are you using?  You can check with `go version`

`x509.SystemCertPool` was added to the standard golang library in version 1.7.  We can add docs for this.

In the meantime, you can try running `make bin/moby`, which will compile the moby tool in a container with the appropriate golang version and place the binary in the `bin` subdir in the repo tree.

**Comment by Madko** [comment]
CentOS 7 is providing `go version go1.6.3 linux/amd64`
So this is it.

Thanks for your help @riyazdf
