### ISSUE TITLE
run_packet: persisting iPXE

### ISSUE THREAD

**Issue by vielmetti** [linuxkit/linuxkit#2065]
**Description**

Right now, if you are running on Packet, a Linuxkit install does not survive a reboot; that means development of a custom image has to start again from scratch.

From the Packet [documentation on iPXE]:

> When provisioning the Custom iPXE operating system kicks off, we set the next boot option to PXE on first boot.  By default, this PXE process only happens once on the first boot, and subsequent reboots will default back to local disk.

> If you want to persist with PXE on subsequent boots, you can use the always_pxe=(true|false) parameter for the custom_ipxe operating system.  

[documentation on iPXE]:https://help.packet.net/technical/infrastructure/custom-ipxe

**Steps to reproduce the issue:**

Boot linuxkit on packet; reboot the server; try to log in. 

**Describe the results you received:**

Unable to log in to server.

**Describe the results you expected:**

If a flag `--always-pxe true` is set, subsequent reboots will restart from PXE instead of trying to boot from disk. This will allow testers to simply reboot the system in order to load a new image, rather than deleting and starting over from scratch.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'll do a PR to implement this, at least to support the testing process. 

The syntax is aimed to exactly match the Packet API, and like the Packet API, the default will be `--always-pxe false`.

It's unclear to me at this point whether this will be the right thing for production environments, though I don't see any reason why it couldn't be if the image is smart enough to e.g. initialize disk only once and test a condition before starting over from scratch. At the moment there's no disk support yet.

**Comment by justincormack** [comment]
I think for LinuxKit it would make sense to always set it to true. We don't
really expect to be installed. We do need to set up disk support of course.

**Comment by vielmetti** [comment]
If there are never any circumstances when you'd want anything other than `always_pxe` then this simplifies things greatly as no option flag would be needed.
