### ISSUE TITLE
No files are created from the "files" section

### ISSUE THREAD

**Issue by furious-luke** [linuxkit/linuxkit#2067]
Hi there,

For the past week or so none of the example `yml` files provided with linuxkit that involve the `files` section have been working for me. It seems that none of the entries in the files list are actually created in the produced image.

I'm able to reproduce this issue consistently by simply building moby/linuxkit, running `moby build examples/sshd.yml`, then `linuxkit run -publish 8022:22 sshd`, then from within the linuxkit console I can see there is no file for `/root/.ssh/authorized_keys`, as there should be in order to be able to login. Attempting to login from another console with `ssh locahost -h 8022` results in `Host key verification failed`.

I've tried numerous tests with dummy files in the `files` configuration and nothing seems to be able to produce any files in the resulting image.

Cheers,
Luke

**Comment by justincormack** [comment]
Have you got a file ` ~/.ssh/id_rsa.pub`? Maybe you only have a DSA key? If so you will need to modify the yaml file to match the key have have. The file is marked as `optional` in the config, mainly so that our CI passes, as it does not have an ssh key, which is perhaps confusing. 

If you do
```
moby -v build -output tar -o - examples/sshd.yml | tar tf -
```
there may be a message in the ouput at the end.

**Comment by furious-luke** [comment]
Hi there, I do indeed have a public key file. In addition, I've such configurations as

```
files:
   - path: dummy.txt
     contents: 'hello world'
```

and no file at `/dummy.txt` exists once inside the console.

Cheers,
Luke

**Comment by justincormack** [comment]
You wont find the file inside the console, which is somewhat confusing, as the console now runs in a container. You will find it at `/proc/1/root/dummy.txt`, which is the root namespace. This is a bit confusing, you can use an `init` `getty` instead see https://github.com/linuxkit/linuxkit/tree/master/pkg/getty#linuxkit-debug

**Comment by furious-luke** [comment]
Aaah, that explains it! Awesome thanks, I can see the files from the `files` section now, including the contents of my `id_rsa.pub` in `authorized_keys`. However I'm still unable to login via ssh, `Permission denied (public key)`. Is there a way I can confirm the `sshd` container is mapping the `authorized_keys` file correctly?

**Comment by justincormack** [comment]
Is there anything in `/var/log/sshd.log`? It should have an error message from `sshd` as to the reason login failed.

**Comment by justincormack** [comment]
Actually that is a client side error, you probably need to delete `localhost:8022` from your `~/.ssh/known_hosts` file
