### ISSUE TITLE
Non-host filesystem for getty and sshd containers is confusing everyone

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2078]
Multiple people (nearly everyone AFAICT) have been confused by the getty/sshd containers not being in the host mount namespace in the last week (usually manifests as "where has this file I'm sure should be in the fs gone?").

There are good reasons for this isolation but perhaps we can mitigate somehow. Some things which spring immediately to mind are an `/etc/motd` displayed on login with a reminder (and perhaps some cut-and-pastable runes to get into the root namespace) or an indication in `$PS1` (or maybe both).

Maybe someone has a better idea.

**Comment by rn** [comment]
I think both `motd` and `$PS1` sound like good ideas

**Comment by justincormack** [comment]
Runes to enter the namespace will fail once we remove `sh` from the root namespace but you can mention that it is at `/proc/1/root`. But some sort of `motd` seems reasonable.

**Comment by riyazdf** [comment]
`$PS1` and/or `motd` with a reminder SGTM 👍

**Comment by rn** [comment]
I had a look at this. In the getty container:
- `/etc/motd` or `/etc/issue` are not displayed
- `.profile` is not sourced because we don't seem to run this as a login shell
I've tried a little to hack around to no avail so far

**Comment by ijc** [comment]
FWIW on my Debian box it looks like motd comes from a pam plugin:
```
$ grep motd pam.d/*
pam.d/login:# This includes a dynamically generated part from /run/motd.dynamic
pam.d/login:# and a static (admin-editable) part from /etc/motd.
pam.d/login:session    optional   pam_motd.so motd=/run/motd.dynamic
pam.d/login:session    optional   pam_motd.so noupdate
pam.d/sshd:# This includes a dynamically generated part from /run/motd.dynamic
pam.d/sshd:# and a static (admin-editable) part from /etc/motd.
pam.d/sshd:session    optional     pam_motd.so  motd=/run/motd.dynamic
pam.d/sshd:session    optional     pam_motd.so noupdate
```
I've no idea what sort of authentication setup we are using when passwords are enabled, but when running without I suppose we are bypassing a bunch of it.

Maybe adding `cat /etc/motd > $tty` in an appropriate part of `/usr/bin/rungetty.sh` would suffice?

In "insecure" mode we appear to be passing `-n -l /bin/sh` as extra options to the `getty`. I think it needs to be `-n -l "/bin/sh -l"` to make it a login shell. I suspect in "secure" mode it will work ok, because it will invoke `/bin/login` instead which should DTRT by default.

**Comment by rn** [comment]
Looks like `getty` doesn't like commands with arguments passed in on `-l`...tried all sorts of variations but no dice

**Comment by ijc** [comment]
Debian's manpage (so might not be accurate) has:
```
       -o, --login-options "login_options"
              Options  that  are passed to the login program.  \u is replaced by the login name.  The default
              /bin/login command line is "/bin/login -- <username>".

              Please read the SECURITY NOTICE below if you want to use this.
```

**Comment by ijc** [comment]
"not be accurate" -- by which I mean relevant to the version of getty we are using, not casting aspersions on its accuracy...

**Comment by rn** [comment]
busybox getty is different: https://www.busybox.net/downloads/BusyBox.html

and if I read the [source code](https://github.com/mirror/busybox/blob/master/loginutils/getty.c#L736) right, then you can't pass in arguments...sigh

**Comment by justincormack** [comment]
We can install a different `getty` now its in a container and optional it makes more sense...

**Comment by deitch** [comment]
> it is at /proc/1/root

The following mounts already exist for convenience:

* `/run:/run`
* `/tmp:/tmp`
* `/etc:/hostroot/etc`
* `/usr/bin/ctr:/usr/bin/ctr`
* `/usr/bin/runc:/usr/bin/runc`
* `/usr/bin/dist:/usr/bin/dist`
* `/var:/var`
* `/containers:/containers`
* `/dev:/dev`
* `/sys:/sys`

Two questions:

1. Why do we need access to much other than that?
2. If we do, should we just replace `/etc:/hostroot/etc` with `/:/hostroot` and make it convenient for everything?
