### ISSUE TITLE
`runc list` doesn't list containers, while `ctr ls` does

### ISSUE THREAD

**Issue by ndeloof** [linuxkit/linuxkit#2085]
**Description**

`ctrl ls` do list the containers as one could expect
but `runc list` doesn't list anything

**Steps to reproduce the issue:**

Running linuxkit "minimal" sample
`runc list`

**Describe the results you received:**

empty list

**Describe the results you expected:**

same output as ctrl ls

**Additional information you deem important (e.g. issue happens only occasionally):**

runc default root `/run/runc` exists on VM but is empty. Actual root in use is `/run/containerd/runc/default`. Maybe the former should just be a symlink, or a mount is missing.

**Comment by justincormack** [comment]
cc @ijc while you are fixing related things

**Comment by ijc** [comment]
Discussed with @justincormack IRL but no satisfactory solution. `runc` doesn't have the ability to use an envvar for the root which we could add to the `getty` and `sshd` containers and adding a symlink in `/run` will be exposed to other containers which share `/run` which is undesirable.

We think the only real alternative is to document the need to use `runc --root /run/containerd/runc/default «command»` (where `default` is a `containerd` namespace of interest). Not sure where best to put it, nowhere under `docs` really leaps. Best bet is perhaps `docs/faq.md`, although I'm not aware of it having been asked twice let alone frequently ;-) (but maybe I'm not paying close enough attention).

In general with the switch to `containerd` the need to have `runc` do useful things by default when invoked manually is much reduced.

**Comment by justincormack** [comment]
I think we should move most/all of https://github.com/linuxkit/linuxkit/tree/master/pkg/getty into `docs/` and make it about logging in in general. Its hard to find under the `getty` package.
