### ISSUE TITLE
Unable to compile sysdig kernel module

### ISSUE THREAD

**Issue by luca3m** [linuxkit/linuxkit#2096]
**Description**

I'm unable to compile sysdig kernel module for LinuxKit

It looks that some files are missing, for example the `fixdep` binary and everything under `scripts` directory. I changed some lines to fix this, essentially by removing many of the files that are filtered out [here](https://github.com/linuxkit/linuxkit/blob/master/kernel/Dockerfile#L100). Also to get the `fixdep` binary a step of `make modules_prepare` is necessary. Are you interested on a patch to do that?

**Steps to reproduce the issue:**

1. Grab and unpack `kernel-dev.tar`
2. setup local sysdig development: https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-from-the-Source-Code
3. go on `<builddir>/driver`
4. run `KERNELDIR=<kernel-dev-unpack-dir>/usr/src/linux-headers-4.11.6-linuxkit make`

**Describe the results you received:**

```
 driver > KERNELDIR=/h/usr/src/linux-headers-4.11.6-linuxkit make
Built target configure_driver
/bin/sh: 1: scripts/basic/fixdep: not found
scripts/Makefile.build:294: recipe for target '/mnt/hgfs/draios/sysdig/driver/main.o' failed
make[5]: *** [/mnt/hgfs/draios/sysdig/driver/main.o] Error 127
Makefile:1492: recipe for target '_module_/mnt/hgfs/draios/sysdig/driver' failed
make[4]: *** [_module_/mnt/hgfs/draios/sysdig/driver] Error 2
Makefile:9: recipe for target 'all' failed
make[3]: *** [all] Error 2
driver/CMakeFiles/driver.dir/build.make:57: recipe for target 'driver/CMakeFiles/driver' failed
make[2]: *** [driver/CMakeFiles/driver] Error 2
CMakeFiles/Makefile2:384: recipe for target 'driver/CMakeFiles/driver.dir/all' failed
make[1]: *** [driver/CMakeFiles/driver.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
 driver >
```

**Describe the results you expected:**

I expect the module to build successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Sure, patches welcome. The necessary scripting to set this up seems to be rather poorly documented, sadly.

**Comment by rn** [comment]
@luca3m any reason you closed this? Did you get it to work?

**Comment by luca3m** [comment]
yeah, I was trying to compile the kernel module using a glibc based toolchain. By using the linuxkit own toolchain based on alpine it works.

**Comment by rn** [comment]
Cool. Thanks for the info
