### ISSUE TITLE
Network is never disabled for pkg/* builds.

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2134]
From https://github.com/linuxkit/linuxkit/pull/2126#discussion_r124993489:
> `pkg/package.mk` has:
> ```
> ifndef $(NETWORK)
> NET_OPT=
> else
> NET_OPT=--network=none
> endif
> ```
> So setting NETWORK=1 would appear to disable the network. Which is a bit confusing because e.g. pkg/runc sets NETWORK=1 and does a clone, and appears to work fine.
>
> Ah, I see the error to work as the author (@dave-tucker I think?) expected it would need to be ifndef NETWORK, as it is it is expanding to either ifndef (i.e. no argument at all) or ifndef 1 (if NETWORK=1) both of which apparently evaluate to true (if it were possible ot assign to a variable named 1 things might be different).
>
> Rather than fix the syntax here thought I'd suggest we fix the semantics and use ifneq ($(NETWORK),1) (or y) which I think will match what people expect.

However simply switching to `ifneq ($(NETWORK),1)` also requires moving the `NETWORK=1` in various `Makefile`s to above the `include`, since `if*` are evaluated at the time they are processed and not deferred in the way expansions in rules and targets etc are. I don't think it is possible to defer such things.

Having requirements on where variables are in `Makefile`, although it seems `ORG` already has this requirement (I noticed this experimentally in #2126, although I can't see where in `package.mk` that becomes necessary right at the moment)

One possible solution is something along the lines:
```
NETWORK ?= 0
NET_OPT_0 := --network=none

tag: $(BASE_DEPS) $(DEPS)
	DOCKER_CONTENT_TRUST=1 docker pull $(TAG) || \
	docker build $(NET_OPT_$(NETWORK)) -t $(TAG) .
```
If `NETWORK` is set to anything other that `0` then the expansion will be blank, otherwise it will expand to `$(NET_OPT_0)` and in turn to `--network=none`. This might be a step of Make-craycray to far for some people though

Or we could go with:
```
NETWORK ?= none

tag: $(BASE_DEPS) $(DEPS)
	DOCKER_CONTENT_TRUST=1 docker pull $(TAG) || \
	docker build --network=$(NETWORK) -t $(TAG) .
```
And require the packages to set `NETWORK=default`.

Last idea for now, do it in the shell:
```
tag: $(BASE_DEPS) $(DEPS)
	if [ "$(NETWORK)" != 1 ] ; then NET_OPT=--network=none ; fi \
	DOCKER_CONTENT_TRUST=1 docker pull $(TAG) || \
	docker build $${NET_OPT} -t $(TAG) .
```

If we can agree an approach and I haven't figured out the issues with #2117 by then I'll add it there.

**Comment by ijc** [comment]
> Having requirements on where variables are in Makefile, although it seems ORG already has this requirement (I noticed this experimentally in #2126, although I can't see where in package.mk that becomes necessary right at the moment)

I'm just dumb and had written `ORG?=linuxkitprojects` instead of `ORG=linuxkitprojects`...

**Comment by ijc** [comment]
> I'm just dumb and had written ORG?=linuxkitprojects instead of ORG=linuxkitprojects...

Oh, I remember why -- otherwise you can't do `make -C «something» ORG=ijc25 HASH=dev` and being able to do so is quite desirable...

**Comment by justincormack** [comment]
I don't mind ordering requirements in the `Makefile`.

**Comment by dave-tucker** [comment]
Thanks for catching this @ijc!
I also don't mind ordering requirements in the Makefile.

The plan was that if `NETWORK` was defined then to use the network.
The value of network is irrelevant. It could be `1`, `true` or `foo` and still have the same effect.

If we switch the conditional to `ifdef` and move the `include ../package.mk` to the bottom of the package Makefiles would that fix the issue?

**Comment by ijc** [comment]
I think moving the include to the end makes sense, yes.

The issue isn't `ifdef` vs `ifndef` though, its the `$(` and `)` around `NETWORK`.

@dave-tucker Are you going make a PR?

Moving to the end would let it use `:=` in a bunch of places too, which would save us some multiple shell outs I think.

**Comment by dave-tucker** [comment]
@ijc yep I'll open a PR in a jiffy!

**Comment by ijc** [comment]
@dave-tucker it'll conflict with #2117, but TBH that's going completely nuts and I don't see it getting merged soon, so I'll rebase on your when the time comes.
