### ISSUE TITLE
Add CONFIG_I40E to default

### ISSUE THREAD

**Issue by dsklopp** [linuxkit/linuxkit#2139]
We are leveraging XL710 10G Intel NICs on our physical hardware, which requires CONFIG_I40E to be set.  I believe this is a sane default to include in the default kernel config and images.  This can be set in:

Device Drivers => Network device support -> Ethernet driver support -> Intel devices -> Intel(R) Ethernet Controller XL710 Family support

**Comment by rn** [comment]
closing in favour of #2146
