### ISSUE TITLE
AWS raw image not booting in bare metal

### ISSUE THREAD

**Issue by rajasec** [linuxkit/linuxkit#2143]
**Description**

**Steps to reproduce the issue:**

**Describe the results you received:**
I created the AWS raw image for booting in AWS instance, I could successfully launch the instance in AWS EC2, post that I was trying to bring on bare metal, so I tried to copy the raw image to USB using dd command.
Booted the machine having USB.  
Following messages appeared:

Loading /kernel ....OK
Loading /initrd .. ok

..

Physical KASLR using RDTSC
Virtual KASLR using RDTSC

Decompressiong Linux parsing ELF Peforming relocations done
Booting the kernel.

After the above message, I could not see anything further.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
the AWS image is configure to use the serial console as the console. Where do you see the output you quote above?

**Comment by rajasec** [comment]
On bare metal, I tried to boot the USB with with raw image

**Comment by rn** [comment]
sure, but which console are you using?

**Comment by rajasec** [comment]
I'm using HP Z800

**Comment by rn** [comment]
But *where* do you see the output you mention in the original post? Do you look at serial console or a monitor attached to the graphics card? If you use the aws example it has the kernel console configured to just go to the serial console:
```
cmdline: "console=ttyS0 page_poison=1"
```
if you use a monitor, you probably have to add `console=tty0` to that and rebuild

**Comment by rajasec** [comment]
Sorry @rn  for not clear here.
I have attached to monitor, let me rebuild with and let you know the updates.

**Comment by rajasec** [comment]
I could run the image in bare metal and login to shell. As part of the image, there are 3 containers which I expected out of runc list, nginx, randdomgen(rngd), sshd. Though all this process were running, I dont see in the output  of runc list command. 
runc list comes as empty.

**Comment by rn** [comment]
see https://github.com/linuxkit/linuxkit/issues/2085 for an explanation. `ctr list` should give you a list of the container.

Closing this issue since you now seem to be able to boot the image.

**Comment by rajasec** [comment]
list is not an option. I'm using ctr version f3b85a9 ( based on the image pulled from aws.yml)

Here is the error
(ns: getty) linuxkit-525400123456:~# ctr list
No help topic for 'list'

ctr 
USAGE:
   ctr [global options] command [command options] [arguments...]

VERSION:
   f3b85a9

COMMANDS:
     attach         attach to the IO of a running container
     checkpoint     checkpoint a container
     run            run a container
     delete         delete an existing container
     namespaces     manage namespaces
     events         display containerd events
     containers, c  manage containers (metadata)
     tasks, t       manage tasks
     info           get info about a container
     kill           signal a container (default: SIGTERM)
     pprof          provides golang pprof outputs for containerd
     exec           execute additional processes in an existing container
     pause          pause an existing container
     resume         resume a paused container
     snapshot       snapshot management
     version        print the version
     ps             list processes for container
     shim           interact with a shim directly
     help, h        Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug                      enable debug output in logs
   --address value, -a value    address for containerd's GRPC server (default: "/run/containerd/containerd.sock")
   --timeout value              total timeout for ctr commands (default: 0s)
   --namespace value, -n value  namespace to use with commands (default: "default") [$CONTAINERD_NAMESPACE]
   --help, -h                   show help
   --version, -v                print the version

**Comment by rn** [comment]
works for me with the latest version from master:
```
linuxkit-025000000006 login: root (automatic login)

Welcome to LinuxKit!

NOTE: This system is namespaced.
The namespace you are currently in may not be the root.
(ns: getty) linuxkit-025000000006:~# [    2.767020] IPVS: Creating netns size=2104 id=2
[    2.767365] IPVS: ftp: loaded support on port[0] = 21
[    3.432247] clocksource: Switched to clocksource tsc
ctr list
ID        IMAGE     PID       STATUS
getty     -         503       running
nginx     -         555       running
rngd      -         601       running
(ns: getty) linuxkit-025000000006:~# ctr version
Client:
  Version: c215531
  Revision: c215531a8f63a98a69134e804fea4ee6d354bb90

Server:
  Version: c215531
  Revision: c215531a8f63a98a69134e804fea4ee6d354bb90
(ns: getty) linuxkit-025000000006:~#
```

**Comment by rajasec** [comment]
As per linuxkit/containerd:c977f27c234d55b85172813b8451f67ea86be4a3, thought that it will have the same containerd image ( similar to linuxkit.yml), not sure how it is having different ctr version.

**Comment by rajasec** [comment]
I've clone the containerd from master.
Looks like list command is replaced via "ctr containers and ctr tasks as per the latest commits

USAGE:
   ctr [global options] command [command options] [arguments...]

VERSION:
   8e1a04f

COMMANDS:
     attach         attach to the IO of a running container
     checkpoint     checkpoint a container
     run            run a container
     delete         delete an existing container
     namespaces     manage namespaces
     events         display containerd events
     containers, c  manage containers (metadata)
     tasks, t       manage tasks
     info           get info about a container
     kill           signal a container (default: SIGTERM)
     pprof          provides golang pprof outputs for containerd
     exec           execute additional processes in an existing container
     pause          pause an existing container
     resume         resume a paused container
     snapshot       snapshot management
     version        print the version
     ps             list processes for container
     shim           interact with a shim directly
     help, h        Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --debug                      enable debug output in logs
   --address value, -a value    address for containerd's GRPC server (default: "/run/containerd/containerd.sock")
   --timeout value              total timeout for ctr commands (default: 0s)
   --namespace value, -n value  namespace to use with commands (default: "default") [$CONTAINERD_NAMESPACE]
   --help, -h                   show help
   --version, -v                print the version
