### ISSUE TITLE
LinuxKit networking: can't ping but can wget

### ISSUE THREAD

**Issue by arm64b** [linuxkit/linuxkit#2195]
I get an IP address with the help of dhcpcd for the eth0, the information of this device is:
(ns: getty) linuxkit-525400123456:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 52:54:00:12:34:56  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::e2fb:7bc6:5436:7560/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1180 (1.1 KiB)  TX bytes:1046 (1.0 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

I can't ping a website(seems the DNS works), but I can get the webpage content with wget:
(ns: getty) linuxkit-525400123456:~# wget www.google.com
Connecting to www.google.com (172.217.26.68:80)
index.html           100% |*******************************| 10350   0:00:00 ETA

(ns: getty) linuxkit-525400123456:~# ping www.google.com
PING www.google.com (74.125.68.105): 56 data bytes

Does some mechanism that block the ping package or something I am missing here?

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
which backend are you using to run? which arch?

**Comment by arm64b** [comment]
Sorry forget those basic information. I use qemu as the backend on ARM64 platform.

**Comment by justincormack** [comment]
qemu by default uses host alirp networking which doesnt support ping. see http://wiki.qemu.org/Documentation/Networking#Enabling_ping_in_the_guest.2C_on_Linux_hosts you can enable it if you need to

**Comment by justincormack** [comment]
There are other network options but they need root access so not the default...

**Comment by justincormack** [comment]
Closing as this is the expected default for qemu
