### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by uberhacker** [linuxkit/linuxkit#2199]
It would be nice if there were tagged releases with a bonus of precompiled binaries available for various architectures.

**Comment by justincormack** [comment]
We are planning to do a release fairly soon there are some things on the milestone see https://github.com/linuxkit/linuxkit/milestone/9

**Comment by uberhacker** [comment]
@justincormack: Awesome.  Thanks for the heads up.  I wasn't aware of the milestone plan.

**Comment by rn** [comment]
Just released https://github.com/linuxkit/linuxkit/releases/tag/v0.2

closing
