### ISSUE TITLE
building arm64 kernels seems broken?

### ISSUE THREAD

**Issue by tych0** [linuxkit/linuxkit#2212]
Hi,

I'm trying to reproduce the arm64 kernel builds, but having a bit of trouble. The first issue is that there are seemingly no binaries for arm64 that have multi stage builds yet, but I assume that will be solved with some time.

The second more pressing issue is: https://github.com/linuxkit/linuxkit/blob/master/kernel/Dockerfile#L1 references an image by hash that's an x86 image. That means when I try to use it on arm, I get an expected exec error:

```
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
```

I can hack around this using aarch64/alpine:edge for now, but I guess we need a better solution than changing this line based on what build you're doing. Thoughts?

**Comment by justincormack** [comment]
You need to use arm64b branch, arm64 support is not merged yet

**Comment by tych0** [comment]
Another option I had considered (which would be awesome, actually), is to just always cross compile from x86. It doesn't look like alpine has tooling for an aarch64 build chain, but we could switch to ubuntu for kernel builds and use theirs, or grab one from lenaro or something (although it looks like theirs depends on glibc).

**Comment by tych0** [comment]
I see, thanks. I guess we can close this for now. I just saw some of the bits in the dockerfile and thought it should work :)

**Comment by justincormack** [comment]
It's being merged piece by piece
