### ISSUE TITLE
containerd: Not able to use /etc/security/limits.conf to set ulimits

### ISSUE THREAD

**Issue by dave-tucker** [linuxkit/linuxkit#2214]
When I was shellcheck-ing all the things this week one thing that was complained about was the non-POSIX-ness of the `ulimit` flags that we are using. The suggested fix was to set the limits in `/etc/security/limits.conf` and there was already a `#TODO` in the script for this. Simple!

Alas it was not so. It appears that [`limits.conf`](https://linux.die.net/man/5/limits.conf) requires `pam`. AFACIT `busybox`'s login doesn't use `pam` 😢 

Fixing it would require adding the `shadow` package to the `getty` and `sshd` Dockerfiles which would then enable PAM and *should* then pay attention to our `/etc/security/limits.conf` file.

**BUT**

The limits would only be set when someone logs in via a `login` shell.
That's not always going to be the case and `containerd` probably wants these limits set by `init`.

In which case, as un-POSIX-y as the flags may be, this seems like the right approach.

The purpose of this issue is to discuss the above and either:
a) Bless the current approach and remove the `TODO` + have `shellcheck` ignore errors
b) Decide upon a new, better approach and implement that.

**Comment by justincormack** [comment]
Under no circumstances will we enable PAM.

**Comment by justincormack** [comment]
I don't really understand the Posixy complaint from shellcheck, I would ignore it.

**Comment by dave-tucker** [comment]
The POSIX-y complaint is because of [this](http://pubs.opengroup.org/onlinepubs/009696699/utilities/ulimit.html). TL;DR no flag other than `-f` is specified by POSIX. There are also some subtle differences between `busybox` and `bash`. E.g `ulimit -p` is processes in alpine but pipe buffer size in `bash`.

**Comment by justincormack** [comment]
Well just ignore it; we will probably rewrite this in Go shortly anyway

**Comment by rn** [comment]
Is this stale and can be closed?

**Comment by ijc** [comment]
I think the code in question was rewritten in Go a while back as @justincormack suggested above, or at least the only uses of `ulimit -p` are in (stale) projects. New code is calls to `unix.Setrlimit` in `pkg/init/cmd/rc.init/main.go`.

Closing.
