### ISSUE TITLE
Makefile - Docker file base image mismatch

### ISSUE THREAD

**Issue by liqdfire** [linuxkit/linuxkit#2215]
There is a mismatch between the base image in the Dockerfile, and the base defined in the Makefile for tools/guestfs

The Makefile is pulling debian:jessie
https://github.com/linuxkit/linuxkit/blob/master/tools/guestfs/Makefile#L3

The Dockerfile is using debian:stretch
https://github.com/linuxkit/linuxkit/blob/master/tools/guestfs/Dockerfile#L1

Right now this is just resulting in an extra image being pulled for this particular tool, as the BASE in the Makefile is not used anywhere else, which is not significant; however, the overriding thought is it feels a bit redundant, and a potential point for errors in the build stack to be introduced.

**Comment by justincormack** [comment]
Ah, I guess it was missed in the update. Feel free to open a PR to move both to `stretch`

**Comment by liqdfire** [comment]
@justincormack  will do
