### ISSUE TITLE
Determine best packaging for WireGuard

### ISSUE THREAD

**Issue by riyazdf** [linuxkit/linuxkit#2273]
Let's continue the discussion from community slack and #2266 in a centralized place. Namely:
- should we use WireGuard tools in `getty`/`sshd`
- should we use `pkg/wireguard`
- other?  Both?

cc @ijc @justincormack @rn @deitch  @zx2c4

**Comment by zx2c4** [comment]
I'm hoping for both. `getty / sshd` for people who want to be able to set it up in the course of normal administration, just as they use `ip` in the course of normal administration.

And then I'll of course be making a `pkg/wireguard` for automatic at-boot configuration.

**Comment by deitch** [comment]
> making a pkg/wireguard

I like that. Then you just add an `onboot` or `services` 

> I'm hoping for both getty / sshd for people who want to be able to set it up 

We have had some discussions around getting config data into standard containers. E.g. you want to change `/etc/securetty`. Right now your options are to put the file in the host rootfs and mount (creates a lot of problems) or extend the `getty` image (messy, difficult to maintain... all for one file). We have some ideas around them, see https://github.com/linuxkit/linuxkit/issues/2151

We have had some discussions around similar ideas for basic packages, but the usual way seems to be to extend base images. What qualifies as "everyone wants it so worth extending base" vs "narrower use case so it stays out" is unclear.

No easy answer.

**Comment by zx2c4** [comment]
I'm planning on giving `pkg/wireguard` a stab during the first week of August. Let's see how that turns out, and then looking at it before us then, we can make a decision.

**Comment by justincormack** [comment]
I am looking at config for moving interfaces into containers and creating longer lasting network namespaces which can be used for wireguard.

**Comment by justincormack** [comment]
I am happy with the setup we now have, although improvements are ongoing, so closing this issue for now. There are other issues that come up, such as how to do key management for cluster style use cases, etc.

**Comment by zx2c4** [comment]
Increasing integration with https://github.com/linuxkit/linuxkit/pull/2483 , which should help settle this ticket as well.
