### ISSUE TITLE
Initialise persistent disk post formatting

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2307]
It's not that uncommon to want to initialise some data (typically directories) on the persistent disk after formatting, for example in `projects/kubernetes` there is a [fairly crude hack](https://github.com/linuxkit/linuxkit/blob/master/projects/kubernetes/kube-master.yml#L26...L30) to ensure `/var/lib/kubeadm` exists after putting the persistent disk on `/var/lib` (solving this properly is a bullet in #2236)  and the `docker-for-mac` blueprint has [something similar](https://github.com/linuxkit/linuxkit/blob/master/blueprints/docker-for-mac/base.yml#L26..L31).

A while back I wrote a [quick patch](https://gist.github.com/ijc/c985ab61ea8d113385156fb64bdd1a03), which I subsequently discarded, which simply added a list of directories to be created to the arguments of the mount container.

That approach seemed a bit inflexible and I'm not really sure mount (rather than format) is the right place to do this, since mount happens on every boot while format is a one shot operation (for a given disk/filesystem) which better suites initialisation. The problem with format is that writing to the filesystem requires the fs to be mounted, so doing it on mount is certainly more convenient, but format could also do a temporary mount. Or maybe there should be a third onboot image to do this stuff.

I also wonder if it might be more useful to be able to do something more sophisticated, like unpacking a tarball (or image?) into the newly created filesystem.

/cc @djs55 @MagnusS for the d4m case. /cc @dave-tucker who has been involved with format+mount recently.

**Comment by justincormack** [comment]
I am thinking about adding a "runtime config" section to the config, which would allow `mkdir -p` (on writeable paths) before a service runs. This config is needed for stuff I am planning on pinning network namespaces and moving interfaces into containers, which has to be done at runtime, which is another reason why I am rewriting the startup in Go right now...

It would look something like
```
name: kubernetes
image: blah:
runtime:
  - mkdir
      - /var/log/kubernetes
      - /var/lib/kubeadm
  - interface: eth0
```

**Comment by ijc** [comment]
Assuming that happens after the bind mounts are configured then that would work.

**Comment by justincormack** [comment]
Hmm, well I was thinking of the use case where the bind mounts will fail if directories are not created too, so I was thinking of before, and that these would be absolute root namespace paths. Would that not work?

**Comment by ijc** [comment]
Ah, yes, because `/var/lib/kubeadm` is also a root path, I'd gotten myself confused there.

**Comment by justincormack** [comment]
Generally all paths are root paths somewhere, so it should generally be workable; we could support in namespace paths too that are done after if it is easier I guess.

**Comment by justincormack** [comment]
You can create directories with the runtime config now, closing.
