### ISSUE TITLE
Issues with `linuxkit.packages.extend.{ext4,btrfs,xfs}`

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2311]
These are failing in CI on master (see [here](https://linuxkit.datakit.ci/log/live/linuxkit-build-of-2c58fbc01ab3a52f8e875f4e6fa4ebb2be34279a-default-ci) and [here](https://linuxkit.datakit.ci/log/saved/linuxkit-build-of-16674a1557ca85876dcd8d536341fe2602a7a7f6-default-ci/baa4b01f1abab399c5394d5e29977dd655a8d4bc) for the two most recent at time of writing).

Strangely in the PR which merged them (#2152) and on PRs since they seem to pass. They pass for me locally

The tests look to have multiple issues (which may or may not be related to the failures, and some of which make other moot):
* Misnamed (in `cases/040_packages/` the number is the index of the first char of the test name).
* They rely on docker.
* All use the same image name tag (`test-extend`).
* For some reason they bind mount in the script instead of `ADD` in the `Dockerfile`.
* They all leak `test-create*` into the filesystem.

@justincormack suggests that the use of docker and much of the related complexity could be replaced by simply using `format=raw` when creating the disk and then using `dd` to append some (sparse) empty space.

That would just leave the leak of `test-create*` which should be a simple case of adjusting the cleanup runes.

**Comment by justincormack** [comment]
weirdly one of the tests just failed on https://github.com/linuxkit/linuxkit/pull/2309 so probably racy

**Comment by dave-tucker** [comment]
> Misnamed (in cases/040_packages/ the number is the index of the first char of the test name).

That seems quite an odd convention and should probably be documented somewhere.
IMHO (unless there are strong objections to the contrary) I'd recommend just picking the next available number. If we have no constraints for order, I *think* that `rtf` is smart enough to order alphabetically which would be much simpler IMO.

> All use the same image name tag (test-extend).

Laziness on my part 😴. Sorry.

> -They rely on docker.
> - For some reason they bind mount in the script instead of ADD in the Dockerfile.

This is mainly a hangover from many failed attempts as, IMO, these tests were a pain in the a**e to write. `raw` formatted disks and `dd` would make a lot more sense. I did try this route but ran out of patience as I hit silly issues with the disks not being recognized and complaints that the disks were too small for journaling filesystems etc...

> They all leak test-create* into the filesystem.

These should be called `create-*` as it's using `moby build -name create test-create.yml`.
They may leak as they are cleaned up midway through the script.

Overall, yes, these tests could do with some TLC.
I'd be happy to do so when back from vacation (Aug 7) unless some kind soul decides to fix them before I get back.
