### ISSUE TITLE
Boot process stops with a laptop

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2321]
I was away from my laptop (Dell Vostro 131) the last days and updated linuxkit and built new kernel / initrd for testing. It should be the first time after linuxkit init package rewrite.

start files with grub
```
linux /boot/docker-kernel console=tty0
initrd /boot/docker-initrd.img
boot
```

Boot stops with:
```
[     13.691200] input: SynPS/2 Synaptics TouchPad as /devices/platform/i8042/serio1/input/input11
[   306.870068] random: crng init done

```
Tested with custom yml and unchanged docker.yml example. No shell, but `strg + alt + del` works to reboot the laptop.
`linuxkit run docker` to run with qemu works fine. 

Tests with minimal.yml (unchanged) ends up with 
```
[     6.107223] usb 2-1.6: new high-speed USB device number 5 using ehci-pci
[   112.377171] random: fast init done
[   125.144451] random: crng init done
```
No chance to get a console or execute shell commands. Also `strg + alt + del` doesn't work

Any hint? Is it related to the new init package or getty related? Would be great to be able to use my test laptop for linuxkit again.

**Comment by justincormack** [comment]
A while back we reversed the order of the default consoles, so ttyS0 was
first. This might be the issue - can you try removing the ttyS0 and see if
that helps?

**Comment by pwFoo** [comment]
Hi @justincormack 
how to remove the ttyS0? 

I set console=**tty0** to kernel line (see above). Also tested with both (tty0 and ttyS0) and without a console definition. All stops at the same position during boot process.

**Comment by rn** [comment]
also, did you have updated the `moby` tool? There were quite few changes in LinuxKit which require an up-to-date `moby` tool

**Comment by pwFoo** [comment]
Yes, deleted directory, git clone and make to build moby / linuxkit. Clean, fresh install.

**Comment by justincormack** [comment]
Hmm, thats a bit odd. Can you put the `getty` into `init` instead of as a service ie just add ` - linuxkit/getty:58620cff1b0bf8b5d144d087602115e996f18a02` in the `init` section and remove the getty service. But it really looks like you are not getting a VGA console at all after the boot messages which is odd.

I should get out my old laptop and check.

If you could bisect when it broke that would help. There have been quite a few changes, but it seems most likely to be getty related. Kernel config has not changed.

**Comment by pwFoo** [comment]
Added getty to init, but same problem. :(

**Comment by pwFoo** [comment]
@rn @justincormack 
Did it work for You with a laptop?

**Comment by justincormack** [comment]
Sorry, haven't had a chance to test yet...

**Comment by pwFoo** [comment]
Tested with ms surface pro 4. Boot process looks better, but also ends without a shell. And SP4 type cover / external keyboard not working.

Haven't another laptop to test it. It should be hardware / bare metal dependent, because linuxkit run works fine with working shell.

**Comment by pwFoo** [comment]
It looks like a init problem, because last output is hardware initialization. Added sshd with pubkeys (verified authorized_keys file with linuxkit run + ctr exec ... sshd sh the file is fine.

No shell with getty and sshd isn't working (looks like host gets no ip address).
Also moved getty behind sshd for testing or getty to init section.

Last time it worked was with "old" init pkg before rewritten to go. Maybe there is a problem?

**Comment by pwFoo** [comment]
Don't know why, but pulled latest linuxkit (changes since Friday) again and it boot up to a shell again...

So I think we should close the issue.

**Comment by justincormack** [comment]
Oh that's good. A bit weird but there have been a few fixes.

**Comment by rn** [comment]
weird indeed, but will be hard to get to the bottom of it now that it's working. I close this for now
