### ISSUE TITLE
4.12 kernel support

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2322]
This issue is to track progress on tracking progress on supporting 4.12 now that 4.11 has been EOLed.

First step is get the patches applied. There is a new https://github.com/dcui/linux/commits/decui/msft-4.12.y branch for hyper-v sockets but it does not seem complete, so here is the status of the 4.11 patch queue applied to 4.12:

- 0001-tools-build-Add-test-for-sched_getcpu.patch
  Did not apply cleanly, maybe not needed. Fixed perf compilation

- 0002-vmbus-vmbus_open-reset-onchannel_callback-on-error.patch
  mew version: b20ffd850ad97 at git@github.com:dcui/linux.git

- 0003-vmbus-add-the-matching-tasklet_enable-in-vmbus_close.patch
  Already in as 5116f5e2e05cf("vmbus: re-enable channel tasklet")

- 0004-vmbus-remove-goto-error_clean_msglist-in-vmbus_open
  new version: 981ae0c39f4a0 at git@github.com:dcui/linux.git

- 0005-vmbus-dynamically-enqueue-dequeue-a-channel-on-vmbus.patch
  not in 4.12 and not in
  https://github.com/dcui/linux/commits/decui/msft-4.12.y
  Applies cleanly.

- 0006-hv_sock-implements-Hyper-V-transport-for-Virtual-Soc.patch
  new version: ca99361977429 at git@github.com:dcui/linux.git

- 0007-VMCI-only-try-to-load-on-VMware-hypervisor
  new version: 52d06e92fca7e at git@github.com:dcui/linux.git

- 0008-hv_sock-add-the-support-of-auto-loading.patch
  new version: 6c9b2ebd7fc79 at git@github.com:dcui/linux.git

- 0009-tools-hv_sock-2-simple-test-cases.patch
  drop. This is just test code

- 0010-vmbus-introduce-in-place-packet-iterator.patch
  Already in as f3dd3f4797652("vmbus: introduce in-place packet iterator")

- 0011-hvsock-fix-a-race-in-hvs_stream_dequeue.patch
  new version: f06df7f9be11c9 at git@github.com:dcui/linux.git

- 0012-hvsock-fix-vsock_dequeue-enqueue_accept-race.patch
  new version: 719999b4908874 at git@github.com:dcui/linux.git

- 0013-Drivers-hv-vmbus-Fix-rescind-handling.patch
  not in 4.12 and not in
  https://github.com/dcui/linux/commits/decui/msft-4.12.y
  Applies cleanly

- 0014-vmbus-fix-hv_percpu_channel_deq-enq-race.patch
  not in 4.12 and not in
  https://github.com/dcui/linux/commits/decui/msft-4.12.y
  Applies cleanly

- 0015-vmbus-add-vmbus-onoffer-onoffer_rescind-sync.patch
  not in 4.12 and not in
  https://github.com/dcui/linux/commits/decui/msft-4.12.y
  Applies cleanly

- 0016-hv-sock-a-temporary-workaround-for-the-pending_send_.patch
  not in 4.12 and not in
  https://github.com/dcui/linux/commits/decui/msft-4.12.y
  Does not apply cleanly with 'git am' nor with 'git am -3'

- 0017-vmbus-fix-the-missed-signaling-in-hv_signal_on_read.patch
  not in 4.12 and not in
  https://github.com/dcui/linux/commits/decui/msft-4.12.y
  Does not apply cleanly with 'git am' but 'git am -3' works

- 0018-hv-sock-avoid-double-FINs-if-shutdown-is-called.patch
  new version: 82235a6f52a493 at git@github.com:dcui/linux.git

- 0019-Added-vsock-transport-support-to-9pfs.patch
  Applies cleanly

- 0020-NVDIMM-reducded-ND_MIN_NAMESPACE_SIZE-from-4MB-to-4K.patch
  Applies cleanly

The patches need to be sorted first, then we need to look at the kernel config

**Comment by arm64b** [comment]
@rn I will keep an eye on the kernel part for AArch64

**Comment by rn** [comment]
closing as 4.12 is EOLed
