### ISSUE TITLE
pkg/binfmt issue

### ISSUE THREAD

**Issue by arm64b** [linuxkit/linuxkit#2332]
**Description**
Today I clone a new LinuxKit git repository on my ARM64 server, so all the below operations are based on the latest code, include the bin/moby and bin/linuxkit.
When I launch below command:
```
root@entos-huawei-d05:/home/arm64/mainline# bin/linuxkit run qemu -arch "aarch64" linuxkit
```
The issue #2305 is still there, but I try to narrow down the issue, I found that if I comment out below 2 lines in pkg/binfmt/Dockerfile:
```
...
#RUN mkdir /binfmt_misc 
...
#COPY --from=mirror /binfmt_misc /binfmt_misc/
...
```
then rebuild the binfmt image and `bin/moby build linuxkit.yml` , the system can boot into the shell:
```
(ns: getty) linuxkit-7a79e8ff09d8:~# ls -l /proc/1/root/etc/init.d/* /proc/1/root/usr/bin/onboot /proc/1/root/usr/bin/service /proc/1/root/bin/rc.*
-rwxr-xr-x    1 root     root          4505 Aug  1 02:28 /proc/1/root/bin/rc.init`
-rwxr-xr-x    1 root     root           400 Jul 28 10:17 /proc/1/root/bin/rc.shutdown
-rwxr-xr-x    1 root     root           200 Jul 25 02:04 /proc/1/root/etc/init.d/000-issue
lrwxrwxrwx    1 root     root            15 Aug  1 03:16 /proc/1/root/etc/init.d/010-onboot -> /usr/bin/onboot
lrwxrwxrwx    1 root     root            16 Aug  1 03:22 /proc/1/root/etc/init.d/020-containerd -> /usr/bin/service
-rwxr-xr-x    1 root     root       1785944 Aug  1 03:16 /proc/1/root/usr/bin/onboot
-rwxr-xr-x    1 root     root      12261592 Aug  1 03:22 /proc/1/root/usr/b
(ns: getty) linuxkit-7a79e8ff09d8:~# mount
overlay on / type overlay (rw,relatime,lowerdir=/containers/services/getty/lower,upperdir=/containers/services/getty/tmp/upper,workdir=/containers/services/getty/tmp/work)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=102104k,mode=755)
rootfs on /containers type tmpfs (ro,relatime)
rootfs on /containers/onboot/002-binfmt/rootfs type tmpfs (ro,relatime)
tmpfs on /containers/services/getty/tmp type tmpfs (rw,relatime,size=102104k)
```
The only issue is, before enter into shell, it will display below error message:
```
container_linux.go:265: starting container process caused "process_linux.go:348: container init caused \"rootfs_linux.go:57: mounting \\\"/proc/sys/fs/binfmt_misc\\\" to rootfs \\\"/containers/onboot/002-binfmt/rootfs\\\" at \\\"/containers/onboot/002-binfmt/rootfs/binfmt_misc\\\" caused \\\"mkdir /containers/onboot/002-binfmt/rootfs/binfmt_misc: read-only file system\\\"\""
```

Any thoughts about this? is the binfmt mandatory for the LinuxKit system?

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
That is odd, will take a look.

**Comment by justincormack** [comment]
I can't replicate this on amd64. You will get that error if you comment out those lines from the Dockerfile as then it will not be able to make that directory, as the container is read only now, so that would be expected.

**Comment by arm64b** [comment]
@justincormack 
I tried chase down the root cause of this issue, I found that the last line of the binfmt's Dockerfile seems doesn't work on x86 platform:
```
LABEL org.mobyproject.config='{"binds": ["/proc/sys/fs/binfmt_misc:/binfmt_misc"], "readonly": true, "net": "new", "ipc": "new"}'
```
Because no matter I pull a linuxkit/binfmt:xxx from the hub or build a local binfmt image, with those image included into the linuxkit.yml, then
```
$bin/moby build linuxkit.yml
$bin/linuxkit run qemu -containerized linuxkit
```
After the system boot into the shell, I found nothing under "/proc/sys/fs/binfmt_misc" folder:
```
(ns: getty) linuxkit-ee5ac58f38ae:~# ls -l /proc/sys/fs/binfmt_misc/
total 0
```
On ARM64 platform, if I comment out the same last line in binfmt's Dockerfile, I will get the same scenario as x86 does.

I take a look at the binfmt/main.go code, clearly it will create a '/binfmt_misc/register' file inside the docker, then mount '/binfmt_misc' to the '/proc/sys/fs/binfmt_misc' with the help of last 'LABEL', is that correct?

I checked the same folder on my host linux system, on x86:
```
root@dennis-ws:/# ls -l /proc/sys/fs/binfmt_misc/
total 0
--w------- 1 root root 0 8月   3 18:06 register
-rw-r--r-- 1 root root 0 8月   3 18:06 status
```
on arm64:
```
root@entos-huawei-d05:~# ls -l /proc/sys/fs/binfmt_misc/
total 0
-rw-r--r-- 1 root root 0 Jul  6 12:52 llvm-3.5-runtime.binfmt
-rw-r--r-- 1 root root 0 Jul  6 12:52 python2.7
-rw-r--r-- 1 root root 0 Jul  6 12:52 python3.5
--w------- 1 root root 0 Jul  6 12:52 register
-rw-r--r-- 1 root root 0 Jul  6 12:52 status
```
Would you please have a look at this?

**Comment by arm64b** [comment]
Addition information, for LinuxKit running on x86 and arm64:
```
(ns: getty) linuxkit-ee5ac58f38ae:~# mount | grep binfmt
(ns: getty) linuxkit-ee5ac58f38ae:~# 
```
for Ubuntu 16.04 running on x86 and arm64:
```
root@dennis-ws:/# mount | grep binfmt
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=34,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=17162)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
```

**Comment by arm64b** [comment]
Rebase to the latest codes, so close this issue.
