### ISSUE TITLE
ZFS support

### ISSUE THREAD

**Issue by matjohn2** [linuxkit/linuxkit#2333]
Trying to build kernel modules for ZFS using the moby/LinuxKit image `linuxkit/kernel-compile`

Have tried using the default image `linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b` and also a modified version where the image has been upgraded to Alpine edge.

Having issues with alpines musl vs glibc libraries and unable to compile & run tests for building / testing the module.

Could you please provide the Dockerfile for the linuxkit/kernel-compile image? I cant find it anywhere and i'm hoping looking through it may allow me to build a linuxkit compatible module via another userspace env.

Thanks,
Matt

**Comment by justincormack** [comment]
We havent used the `kernel-compile` package for ages, you should be able to find the source in the repo history though.

The Alpine zfs patches are here https://git.alpinelinux.org/cgit/aports/tree/main/zfs?h=master which may help.

**Comment by rn** [comment]
what is the error? Looks like we need to update the docs (and the kmod test) but basically the `./kernel/Dockerfile` now installs the relevant tools from `linuxkit/alpine`

**Comment by matjohn2** [comment]
Thanks for the superfast response @justincormack !

Just to clarify, if `kernel-compile` hasn't been used for ages, is that now the wrong process for building modules?
(documented here: https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md#compiling-external-kernel-modules ) 

If so, any pointers to the correct process would be helpful and i'll PR the docs when i figure it out :)

**Comment by matjohn2** [comment]
*bump* looking for pointers to the "correct" tools/process to be using to build linuxkit compatible and packaged kernel modules?

Thanks.

**Comment by rn** [comment]
@matjohn2 The ZFS kernel modules compile perfectly fine with the exisiting kernel headers. The main issue was finding all the alpine packages required for `configure` to pass and create the `Makefile`. Here is the Dockerfile which I uses:
```
FROM linuxkit/kernel:4.9.46 AS ksrc
FROM linuxkit/alpine:21f2d52a0e20a78a0a81bbf5bebc652a3ec21b01 AS build
RUN apk add \
    attr-dev \
    autoconf \
    automake \
    build-base \
    git \
    libtirpc-dev \
    libtool \
    util-linux-dev \
    zlib-dev

COPY --from=ksrc /kernel-dev.tar /
RUN tar xf kernel-dev.tar

# Note: ZFS and SPL commit must match and we pick the current
# version of the ZFS tools in alpine.
ENV VERSION=0.6.5.9

ENV SPL_REPO=https://github.com/zfsonlinux/spl.git
ENV SPL_COMMIT=spl-${VERSION}
RUN git clone ${SPL_REPO} && \
    cd spl && \
    git checkout ${SPL_COMMIT}

ENV ZFS_REPO=https://github.com/zfsonlinux/zfs.git
ENV ZFS_COMMIT=zfs-${VERSION}
RUN git clone ${ZFS_REPO} && \
    cd zfs && \
    git checkout ${ZFS_COMMIT}

WORKDIR /spl
RUN ./autogen.sh && \
    ./configure && \
    cd module && \
    make && \
    make install

WORKDIR /zfs
RUN ./autogen.sh && \
    ./configure --with-spl=/spl && \
    cd module && \
    make && \
    make install

FROM scratch
ENTRYPOINT []
CMD []
WORKDIR /
COPY --from=build /lib/modules/ /lib/modules/
```

I'll prepare a PR which integrates this into the LinuxKit kernel build shortly.

**Comment by rn** [comment]
closing as this works.

**Comment by matjohn2** [comment]
Hey @rn 

Apologies if this re-opens, just wanted to add my thanks for looking into this.
It appears I was on the right path, as I had the following dockerfiles created below when I raised the issue;
```
FROM linuxkit/kernel:4.4.76 AS ksrc
# Extract headers and compile module
FROM linuxkit/kernel-compile:mj-custom AS build
COPY --from=ksrc /kernel-dev.tar /
RUN tar xf kernel-dev.tar

# copy module source code and compile
#COPY spl-0.6.5.11.tar.gz /
#COPY zfs-0.6.5.11.tar.gz /
#RUN tar -xzvf /spl-0.6.5.11.tar.gz
#RUN tar -xzvf /zfs-0.6.5.11.tar.gz

#RUN git clone -b spl-0.7.0-rc5 https://github.com/zfsonlinux/spl.git /spl
#RUN git clone -b zfs-0.7.0-rc5-mj-custom https://github.com/matjohn2/zfs.git /zfs
RUN git clone -b spl-0.7.1 https://github.com/zfsonlinux/spl.git /spl
RUN git clone -b zfs-0.7.1 https://github.com/zfsonlinux/zfs.git /zfs


RUN cd /spl ; ./autogen.sh
RUN cd /zfs ; ./autogen.sh

RUN cd /spl ; ./configure
RUN cd /spl ; make

RUN cd /zfs ; ./configure --with-spl=/spl
RUN cd /zfs ; make

CMD /bin/sh
```

As for alpine packages, I had broken those out into a custom `linuxkit/kernel-compile` build locally, hence the `:mj-custom` tag above, which got pretty to close to your package list, also attempted to update the apline image (hacky i know) to edge for some `gettext` compile errors I was seeing;

```
FROM linuxkit/kernel-compile:1b396c221af673757703258159ddc8539843b02b
RUN sed -i -e 's/v3\.5/edge/g' /etc/apk/repositories
RUN apk update
RUN apk upgrade --update-cache --available
RUN apk upgrade
RUN apk add autoconf
RUN apk add libtool
RUN apk add zlib-dev zlib
RUN apk add libuuid libattr attr-dev libblkid util-linux-dev util-linux
RUN apk add libtirpc libtirpc-dev
RUN apk add gettext-dev gettext-libs gettext gettext-lang
RUN apk add intltool libblkid
RUN apk add icu-dev libintl
```
Actually helped the ZFS team find one bug in the build process w/linuxkit, solve here:
https://github.com/zfsonlinux/zfs/issues/6357

And finally came to rest on this issue, which is when I raised the linuxkit Issue;
https://github.com/zfsonlinux/zfs/issues/6367

I see the main difference, as you've correctly pointed out to me, is that you're just building the KMOD's, which it looks like I had succeeded in doing, I was just failing on the tests and the userspace components (I basically wanted an overlay which would add kernel and matching versioned userspace tools to my linuxkit image and then insmod the kernel modules).

I was battling against it for so long I forgot to make the kernel/userspace seperation though, as you do with;

` cd module && \`

So thanks again, my issue was asking the wrong question!
As for your PR #2475 and userspace/kernel versions missmatch; I think the changes in the 7.x versions are significant, i'll ask the ZFS dev's and link to the PR :)

Kind Regards,
Matt

**Comment by rn** [comment]
@matjohn2 Thanks for the details. We still need to decide how we ship the kernel modules, but that's fairly trivial either way.

As for the userspace, ideally we pick up the standard Alpine packages but they are on a older version and have a whole host of patches (see https://git.alpinelinux.org/cgit/aports/tree/main/zfs?h=master).

I've renamed this issue to `ZFS support` and re-opened it for tracking

**Comment by justincormack** [comment]
Since https://github.com/linuxkit/linuxkit/pull/2475 it is possible to build and add easily yourself. In future we might ship builds, but I think this issue can be closed now.
