### ISSUE TITLE
linuxkit/node_exporter does not build

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2349]
With recent changes we pull with content trust enabled, and the prometheus image is not signed so it fails. It's disabled for now, but should get fixed and re-enabled.

**Comment by ijc** [comment]
Is this used anymore? Does this predate the addition of TRUST=0 support in the build? Or do we not want to disable that globally just to disable it for the FROM?

**Comment by rn** [comment]
probably pre-dates `TRUST=0` but we want to push the image with content trust, we just can't pull the base image with content trust.

Another option is to remove this package for now and add a replacement later which just builds it form source.

**Comment by ijc** [comment]
I was looking at it due to https://github.com/linuxkit/linuxkit/issues/2564. I think I'll add some sort of bodge rather than actually fix this package or add anything to the `linuxkit pkg build` I'm running (like I might just misname the yml file so the directory is skipped)
