### ISSUE TITLE
static mac address in qemu networking

### ISSUE THREAD

**Issue by w9n** [linuxkit/linuxkit#2351]
#the new qemu networking capabilities generate [new mac addresses](https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/run_qemu.go#L528) with every vm start which makes it hard to assign a static ip/hostname for the vm via dhcp.

Are there any future plans for this as the existing networking parameter or would an additional optional setting like -networking device,devicename[,xx:xx:xx:xx:xx:xx] be suitable?

**Comment by zacheryph** [comment]
I added "-I", "master" to the dhcpcd client. And add a dhcp-host option to dnsmasq. I'm still in the middle of my solution for this and couple other things. Just an FYI of another solution.

**Comment by zacheryph** [comment]
I understand projects are just that projects.  But exactly how far should/can these projects go within the parent repository?  Part of me thinks they are proofs of concept and maybe even a little for learning so they should be basic.  But another part of me thinks they are more than that.  Below is what I have been working on, which I could go both ways as far as trying to fit into projects or just leave as a separate thing. Ideas?

> https://github.com/zacheryph/linuxkit/blob/kube-static-master/projects/kubernetes/kube-master.yml
* kube-master.yml forcing hostname

> https://github.com/zacheryph/dotfiles/blob/master/bin/cluster#L59-L89 
* extravagant script for automating a cluster (still a heavy work in progress)
* Line 59-89 contain network setup and how I execute dnsmasq to force DNS for the master

**Comment by w9n** [comment]
looks very nice, i will extensively check it out in the next days. This is solved.
