### ISSUE TITLE
"linuxkit run" on aarch64/linux does not work

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2360]
Running `linuxkit run` on a aarch64/linux system with 4.10 kernel (with kvm and with the user in `kvm` group) and qemu version 2.5.0) results in an error:
```
 ./bin/linuxkit -v run linuxkit
DEBU[0000] [/usr/bin/qemu-system-aarch64 -device virtio-rng-pci -smp 1 -m 1024 -uuid 0ef7a972-0863-47e1-8b7f-a81a3fec4c9d -pidfile linuxkit-state/qemu.pid -cpu host -enable-kvm -machine virt -kernel linuxkit-kernel -initrd linuxkit-initrd.img -append console=tty0 console=ttyS0 console=ttyAMA0 -net nic,model=virtio,macaddr=ca:c0:fd:b3:4f:ea -net user -nographic]

Warning: hub port hub0port0 has no peer
Warning: vlan 0 with no nics
Warning: netdev hub0port0 has no peer
Warning: requested NIC (anonymous, model virtio) was not created (not supported by this machine?)
Failed to set device address: No such device
FATA[0000] signal: aborted
```
I get the same error when running as root.

Running `linuxkit run qemu -arch aarch64 linuxkit` on macOS (qemu version 2.9.0) works and results in the following command line:
```
/usr/local/bin/qemu-system-aarch64 -device virtio-rng-pci -smp 1 -m 1024 -uuid 60c2fbce-4e3e-4390-9241-ee425e1caefc -pidfile linuxkit-state/qemu.pid -cpu cortex-a57 -machine virt -kernel linuxkit-kernel -initrd linuxkit-initrd.img -append console=tty0 console=ttyS0 console=ttyAMA0 -net nic,model=virtio,macaddr=16:da:11:b4:44:c9 -net user -nographic
```

**Comment by ijc** [comment]
You might need to explicitly ask for PCI or to add a `-device virtio-mmio` for the `virtio` nic to attach itself to, the `-machince virt` model is super bare bones. .

Not quite sure how `-net nic,model=virtio` is translated internally into a `-device` option, but there you have `virtio-net-device` (uses `virtio-mmio` bus) and `virtio-net-pci` (uses the pci bus).

**Comment by rn** [comment]
```
/usr/bin/qemu-system-aarch64 -device virtio-rng-pci -smp 1 -m 1024 -uuid 0ef7a972-0863-47e1-8b7f-a81a3fec4c9d -pidfile linuxkit-state/qemu.pid -cpu host -enable-kvm -machine virt -kernel linuxkit-kernel -initrd linuxkit-initrd.img -append "console=tty0 console=ttyS0 console=ttyAMA0" -net nic,model=virtio,macaddr=ca:c0:fd:b3:4f:ea -net user -nographic -device virtio-mmio
Warning: hub port hub0port0 has no peer
Warning: vlan 0 with no nics
Warning: netdev hub0port0 has no peer
Warning: requested NIC (anonymous, model virtio) was not created (not supported by this machine?)
qemu-system-aarch64: Device virtio-mmio can not be dynamically instantiated
```

**Comment by rn** [comment]
@arm64b I gather you may have this running in qemu/kvm. Do you know what's missing?

**Comment by arm64b** [comment]
@rn 
My mainline build works on ARM64, the command line for the qemu is:
```
/usr/local/bin/qemu-system-aarch64 -device virtio-rng-pci -smp 1 -m 1024 -uuid 1383abd9-beae-4f5e-af33-ee3fbfbc7a9d -pidfile linuxkit-state/qemu.pid -cpu host -enable-kvm -machine virt -kernel linuxkit-kernel -initrd linuxkit-initrd.img -append console=ttyAMA0 -net nic,model=virtio,macaddr=32:a0:1a:43:90:5e -net user -nographic
```
I suspect the issue is related to the kernel config, I am using 4.9.x kernel version. You can try to copy the kernel/kernel_config-4.9.x-aarch64 into your/path/to/4.10/.config, then `make menuconfig` and exit directly with configuration saved, copy the new generated .config file into linuxkit/kernel/kernel-config-4.10.x-aarch64, rebuild that module and see if that can be help.

**Comment by arm64b** [comment]
I found that you have a additional '-device virtio-mmio' appended, where this comes from?

**Comment by rn** [comment]
I added that on suggestion from @ijc, but it didn't work either. 

I don't think it's a linuxkit kernel issue as the kernel boots fine on qemu on macOS.

@arm64b Which version of qemu are you using?

**Comment by arm64b** [comment]
qemu version:
```root@entos-huawei-d05:~# qemu-system-aarch64 --version
QEMU emulator version 2.9.50 (v2.9.0-1376-gcef8fd6-dirty)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

**Comment by rn** [comment]
It could be related to the qemu version on my arm64 server. It's based on Ubuntu 16.04 LTS and is qemu version 2.5.0. I couldn't find newer packages and couldn't compile qemu from source due to glib/gthread version requires for qemu 2.7, 2.8 and 2.9.

I'll try to spin up a arm server with a newer ubuntu and see if that works

**Comment by vielmetti** [comment]
@rn I'm looking for up-to-date build instructions for QEMU 2.9 on arm64 and not finding them at Linaro (which has a wiki with old instructions at https://wiki.linaro.org/Platform/DevPlatform/AArch64QEMU )

I did build the latest from source on arm64 and it didn't complain about glib/gthread versions - what specifically did you run into? I'm happy to chase down build bugs but I didn't see any obvious ones.

**Comment by vielmetti** [comment]
@rn I was just now able to get qemu latest from git to build and pass all of its tests, which put me at

```
QEMU emulator version 2.9.91 (v2.10.0-rc1-26-gb4174c4-dirty)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

**Comment by rn** [comment]
@vielmetti, doh, I had failed to install some deps to build it. Now I have 2.10-rc1

There are still some issue around linuxkit run and kvm so I'll leave this open for now

**Comment by rn** [comment]
I've hit this:
```
qemu-system-aarch64 -smp 1 -m 1024 -cpu host -enable-kvm -machine virt -kernel linuxkit-kernel -initrd linuxkit-initrd.img -append console=ttyAMA0 -net nic,model=virtio,macaddr=0e:48:f8:ad:b2:4b -net user -nographic
KVM_SET_DEVICE_ATTR failed: No such device
Aborted
```
but adding `-machine virt,gic_version=3` works.

See also comment: https://bugzilla.redhat.com/show_bug.cgi?id=1375571#c6

Looks like we need to figure out at run time what the platform is and then set accordingly

**Comment by arm64b** [comment]
@rn I totally agree! Sorry not see this before reply your email...

**Comment by vielmetti** [comment]
FYI - It looks like QEMU 2.9.1 just was released yesterday - release notes at 

https://wiki.qemu.org/index.php/ChangeLog/2.9#ARM

One curious statement from those release notes: "Support migration for the GICv3 when using KVM".

**Comment by ijc** [comment]
@vielmetti I think they just mean you can now live migrate (/save/restore) a VM which is using a GICv3.
