### ISSUE TITLE
bin/moby build linuxkit.yml failed

### ISSUE THREAD

**Issue by arm64b** [linuxkit/linuxkit#2370]
**Description**
```
root@entos-huawei-d05:/arm64/mainline# bin/moby build linuxkit.yml
Extract kernel image: m0807/kernel:4.9.40-m0807-arm64
FATA[0004] Failed to extract kernel image and tarball: Could not pull image m0807/kernel:4.9.40-m0807-arm64: Trusted pull for m0807/kernel:4.9.40-m0807-arm64 failed: you are not authorized to perform this operation: server returned 401. 
```

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by arm64b** [comment]
Need a quick workaround to address this issue.

**Comment by rn** [comment]
I should only do a trusted pull for images/orgs listed in the `trust` section. did you change that by any chance? Another option is to add `-disable-content-trust` to the `moby build` commandline.

**Comment by arm64b** [comment]
`-disable-content-trust` works. I use the traditional method build each individual component with `make ORG=m0807 NOTRUST=1`, then replace all from the linuxkit.yml. I never try to push an image :)

**Comment by riyazdf** [comment]
@arm64b: got it.  For content trust checks to work, you'll need to sign and push the image – for development, editing the `trust` section or  `-disable-content-trust` sounds good 👍
