### ISSUE TITLE
blacklist drivers for packet

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2379]
As discussed with  @TheOriginalAlex and `manny.packet` on the [packet.net community slack](https://packetcommunity.slack.com/archives/C4FEV702E/p1502139597080318) on the type 2 servers there are onboard ixgbe NICs which are not used and Mellanox cards which are used in a bonded config. When booting LinuxKit on on a Type 2 it seems that `mdev` will assign `eth0` to the non-connected, onboard  `ixgbe` NIC. One option is to blacklist the `ixgbe` driver.

Maybe the best option is to have a `packet-type-2` package in LinuxKit which can be added to the `init` section which adds the relevant rules.

**Comment by mmlb** [comment]
I have been summoned! Happy to answer any questions. So far it does seem like blacklisting is the best option, we've seen the mlx nics come up before onboard and so mlx were eth0/eth1 and ixgbe were eth2/eth3 and caused all sorts of fun.

I've got some changes landing hopefully this week making all new installs use predictable nic names [1][2] and making the situation better, linuxkit could do the same as a more longterm solution.

[1] As documented on https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
[2] Not to be confused with an earlier (failed) attempt that used biosdevname and gave names like p1p2

**Comment by TheOriginalAlex** [comment]
Can we have a udev container that we can add to the init section in yml file?  I had to make my own, but it would be nice if LinuxKit had an official udev init container.

**Comment by TheOriginalAlex** [comment]
Ah.  Just saw this: https://github.com/linuxkit/linuxkit/blob/46dfcd1574f8683a1061528194f03147736d01ef/reports/2017-05-08.md#issues.

**Comment by justincormack** [comment]
We need a custom packet container to set up the bonding anyway, as there is
really no way to autodetect that, so it can deal with renaming/ignoring the
other interfaces.

**Comment by rn** [comment]
Yes, we could have a onboot container which removes the I gene and sets up the bond before the dhcp container runs...or something along those lines

**Comment by justincormack** [comment]
Fixed in #2438 (tested on type 2) whch now sets up bonding correctly using the metadata.
