### ISSUE TITLE
No /tmp in docker service 

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2384]
Tried to start docker-compose inside of docker service. It failed because of missing /tmp in docker service rootfs. 

So /tmp should be added to docker service rootfs?

**Comment by justincormack** [comment]
What was the error exactly? There should be a `/tmp` in there I would think, as it is an ALpine base and that ought to have a `/tmp`.

**Comment by pwFoo** [comment]
I have a docker/compose based service with shared /var/run with the docker service which fails to start with:
````
INTERNAL ERROR: cannot create temporary directory
```

Change to docker service with ctr exec ...
Try to start a docker-compose container with cmd --help
```
docker run --rm -ti -v [...] docker/compose:1.15.0 --help
```

Output
```
[...]
docker: Error response from daemon: shim error: stat /tmp: no such file or directory
```

Check that.
```
ls -l /tmp
```

output
```
ls: /tmp: no such file or directory
```

Fix
```
mkdir /tmp
```

Test it again with docker-compose container cmd --help - output:
```
Define and run mulit-container applications with docker

Usage:
[...]
```

**Comment by justincormack** [comment]
I can't replicate this. Possibly there was an earlier bug in the `moby` tool, I did fix some that could have caused this. Closing, but let me know if it is still an issue for you with everything updated.
