### ISSUE TITLE
linuxkit run <foo> drops into a EFI shell of <foo> is a directory

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2385]
Here's a weird one:
```
$ moby build linuxkit.yml
$ mkdir linuxkit
$ linuxkit run linuxkit
[...]
UEFI Interactive Shell v2.1
EDK II
UEFI v2.40 (BHYVE, 0x00010000)
Error. No mapping found
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
Shell>
```
if I redirect to a file:
```
3h3h3h3h3h3h..PXE-E16: No offer received.
Boot Failed. EFI Network
^MUEFI Interactive Shell v2.1
EDK II
UEFI v2.40 (BHYVE, 0x00010000)
Mapping table
Error. No mapping found
Press ESC in 5 seconds to skip startup.nsh or any other key to continue.Press ESC in 4 seconds to skip startup.nsh or any other key to continue.Press ESC in 3 seconds to skip startup.nsh or any other key to continue.Press ESC in 2 seconds to skip startup.nsh or any other key to continue.Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
```

I suspect the recent changed to enable EFI boot hit some code path which cause the UEFI FW to be loaded instead of the kernel/initrd

```
% linuxkit version
linuxkit version 0.0
commit: bbf87410024706b4a5d20f92dad34d55ab0f4229
```

**Comment by justincormack** [comment]
It is presumably as the directory exists, so it thinks it is kernel boot but then the kernel is empty and hyperkit tries uefi... will check the filetype more carefully.

**Comment by rn** [comment]
AFAIK hyperkit does not have fallback on UEFI. This should be determined by `-f`. I suspect it might be some interaction between the recently changed go binding and how they are called by linuxkit. just a hunch

**Comment by rn** [comment]
moving the `UEFI.fd` out of the way:
```
% linuxkit run linuxkit
FATA[0000] Cannot run hyperkit: Bootrom /Applications/Docker.app/Contents/Resources/uefi/UEFI.fd does not exist
```
and with it back in place looking at `./linuxkit-state/hyperkit.json`:
```
  "cmdline": "/usr/local/bin/hyperkit -A -u -F linuxkit-state/hyperkit.pid -c 1 -m 1024M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-vpnkit,path=/Users/rn/Library/Containers/com.docker.docker/Data/s50 -U c1b066cc-19d1-4043-84d3-15ba112d85ed -s 2,virtio-sock,guest_cid=3,path=linuxkit-state -s 3,virtio-rnd -l com1,stdio -f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,,"
```
the hyperkit binary is actually invoked with the bootrom. so the issue is either in linuxkit or the go binding

**Comment by arm64b** [comment]
interesting, seems you haven't a valid EFI system partition in the bootable device which can be recognized by UEFI, so UEFI enter into the shell, else you will find something like fs0, fs1... which is a vfat type file system. I am not sure the iso-efi image will be used to boot the system on VM or a bare metal machine? IOW, what't purpose of the mkimage-iso-efi tool? usage case?

**Comment by deitch** [comment]
> seems you haven't a valid EFI system partition in the bootable device which can be recognized by UEFI

No, we don't, except within iso9660, which is a special case. If we converted it into a hybrid iso, then it would work. Actually was working on that yesterday evening. `mkimage-iso-efi` _does_ produce a valid EFI-bootable iso (i.e. cd/dvd), but _not_ bootable as a raw disk. Getting there, though...

**Comment by arm64b** [comment]
> No, we don't, except within iso9660, which is a special case. If we converted it into a hybrid iso, then it would work. Actually was working on that yesterday evening. mkimage-iso-efi does produce a valid EFI-bootable iso (i.e. cd/dvd), but not bootable as a raw disk. Getting there, though...

I am confused here, just take look at the script of the `mk-efi`, seems the initrd is totally dropped, so how can you make sure the kernel can boot up without a ramfs attached (we have some kernel modules need to be installed). Also seems the code try to mount a file system in the /dev/sr0, does that means /dev/sr0 will host a rootfs which will be mounted by the kernel? I just guess the mkimage-iso-efi is used to create a live USB stick to boot up the linuxkit image in it...

**Comment by rn** [comment]
The invocation says we want to boot with `kernel+initrd` but for some reason, because there is a directory, the code decides to do a UEFI boot and sets `-f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,,` which it only should set when doing UEFI boot from an ISO.

**Comment by arm64b** [comment]
OK, let me try to figure out the essential of the mkimage-iso-efi and the steps, correct me if I am wrong:
1. We'll get `linuxkit-initrd.img`, `linuxkit-cmd` and `linuxkit-kernel` after the `moby build linuxkit.yml`
2. put all those files(need to change file name order to adapt the script) into a `boot` folder, then `tar czf linuxkit-iso-efi.tar.gz boot/`, so we get a file `linuxkit-iso-efi.tar.gz`
3.  `cat linuxkit-iso-efi.tar.gz | docker run --rm -i m0809/mkimage-iso-efi:m0809-amd64 > linuxkit-efi.iso`
so we get a file `linuxkit-efi.iso`, then I try to run it with:
`linuxkit run linuxkit-efi.iso`
then nothing output from this command, from other terminal, I can see the entire command line for this is:
```
root@dennis-ws:/home/linuxkit# ps aux | grep linuxkit
root      2775  0.1  0.2  45284 35912 pts/9    Sl+  15:44   0:00 bin/linuxkit run linuxkit-efi.iso
root      2780 12.7  0.4 1665116 58292 pts/9   Sl+  15:44   0:03 /usr/local/bin/qemu-system-x86_64 -device virtio-rng-pci -smp 1 -m 1024 -uuid 86d0602e-57f4-4e90-a165-6a07325b61aa -pidfile linuxkit-efi-state/qemu.pid -machine q35 -cdrom linuxkit-efi.iso -boot d -net nic,model=virtio,macaddr=c2:a9:eb:9f:0a:9c -net user -nographic
root      2788  0.0  0.0  15968  1020 pts/10   S+   15:44   0:00 grep --color=auto linuxkit
```

any thoughts about this? or is this the result you guys expect?

**Comment by arm64b** [comment]
> The invocation says we want to boot with kernel+initrd but for some reason, because there is a directory, the code decides to do a UEFI boot and sets -f bootrom,/Applications/Docker.app/Contents/Resources/uefi/UEFI.fd,, which it only should set when doing UEFI boot from an ISO.

So you want to integrate the kernel and initrd into a bootable ISO file with help of UEFI?

**Comment by arm64b** [comment]
Ah, I tried to understand that you're using PXE to mount the initrd ramfs, but is it a requirement to boot a local ISO file (including kernel+initrd) without using PXE?

**Comment by deitch** [comment]
@justincormack did the change on the eft-iso, so I might get this wrong (go ahead and correct me).

The result of `moby build` is always a tar (internally). That is sent as stdout into the `make-eft` script which does the following:

1. Extract everything into `/tmp/efi`
2. Create a cmdline with `boot=/dev/sr0`  if it doesn't exist
3. Create a `.efi` from the kernel we just extracted plus the efi stub (from gummiboot) using `objcopy`
4. Remove the kernel and cmdline files
5. make a FAT filesystem in an image to use as the EFI system partition (ESP) 
6. Using the various `mtools`, create `/EFI/BOOT/BOOTX64.EFI` in the FAT image from the above EFI kernel
7. Using `xorriso` create an iso9660 `.iso` image

So when you system boots, it finds the `.iso` file, finds the ESP (assuming you boot UEFI), finds the standard default path of `/EFI/BOOT/BOOTX64.EFI` (yeah, should be back-slashes, but I cannot bring myself to type them here...) and boot the kernel from there.

The kernel in turn has `root=/dev/sr0` in it, so it just looks for root in `/dev/sr0` (and finds it).

Yeah, this ties it to `/dev/sr0`, which is less than ideal. Working on that.

This image currently is _not_ hybrid, it will not boot off of a USB, only off of optical media (or emulating it). Working on that too.

**Comment by arm64b** [comment]
> The result of moby build is always a tar (internally). That is sent as stdout into the make-eft script which does the following:
From the perspective of the end user, what's the exact way to do that? which command? I remember in earlier version, there is `output: --format efi-sio` in linuxkit.yml file, but now the moby build doesn't support the `output` section.

**Comment by deitch** [comment]
If you want the iso:

```
moby build -output efi-iso linuxkit.yml
```

If you want the raw tar image 

```
moby build -output tar linuxkit.yml
```

FYI, I just fully figured out this step last night. And when I say, "figured out", I mean, "@justincormack explained it to me." :-)

**Comment by arm64b** [comment]
Hmm, I don't know the `-output efi-iso`, this is very helpful 👍

**Comment by deitch** [comment]
```
$ moby build
Please specify a configuration file
USAGE: moby build [options] <file>[.yml] | -

Options:
  -dir string
        Directory for output files, default current directory
  -disable-content-trust
        Skip image trust verification specified in trust section of config (default false)
  -hyperkit
        Use hyperkit for LinuxKit based builds where possible (default true)
  -name string
        Name to use for output files
  -o string
        File to use for a single output, or '-' for stdout
  -output value
        Output types to create [ docker dynamic-vhd gcp iso-bios iso-efi kernel+initrd qcow2 raw tar vhd vmdk ]
  -pull
        Always pull images
  -size string
        Size for output image, if supported and fixed size (default "1024M")
```

Sorry, I got it backwards, it is `iso-efi`

**Comment by arm64b** [comment]
@deitch OK, typo is trivia. Now I get a linuxkit-efi.iso file with `moby build -output iso-efi linuxkit`, which way to use it? I try to use this command `bin/linuxkit run linuxkit-efi.iso` but can't get any output, the command is pending there. 
Or do I need to burn the linuxkit-efi.iso into a physical optical disk like DVD/CD?

**Comment by rn** [comment]
could we have the discussion on EFI boot somewhere else. This issue is completely unrelated.

**Comment by arm64b** [comment]
@rn sure, of course. raise a new issue ticket?

**Comment by rn** [comment]
yes, please
