### ISSUE TITLE
linuxkit push progressbar

### ISSUE THREAD

**Issue by asbjornenge** [linuxkit/linuxkit#2394]
Would be nice with a progressbar (and some contextual feedback) for `linuxkit push` 👍 🌈 🦄

**Comment by justincormack** [comment]
I think that will potentially be complicated to actually implement across all the providers, as they may not have suitable APIs, not sure.

**Comment by asbjornenge** [comment]
Some simple step progression would also help imho.

```
* Connecting
* Preparing bucket
* Pushing image to bucket
* Generating image
```

Or something 😛

**Comment by dave-tucker** [comment]
I think that is usually available with `linuxkit -v push`.
We can always promote some of the verbose logs to info level if it's helpful

**Comment by asbjornenge** [comment]
@dave-tucker alright, thanks! That helps a bunch 😁 👍  I'll just close the issue then.
