### ISSUE TITLE
Add thunder-nicvf/hns drivers to arm kernel

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2417]
Packet.net arm64 servers are Cavium Thunder-X and need the `thunder-nicvf` driver for ethernet.

**Comment by rn** [comment]
might as well add the HISILICON drivers at the same time. Not sure what the driver for the Qualcomm gear is...

**Comment by vielmetti** [comment]
If you can make sure that the `mlx5` driver is available, that will help @rn .

**Comment by rn** [comment]
@vielmetti on arm? I was going to do a pass of making the x86 and arm64 config file more a like and was thinking of having the same set of drivers for both so the mlx5 would be there

**Comment by vielmetti** [comment]
yup, `mlx5` on arm is going to be needed for several configurations, so it should be there.

**Comment by zlim** [comment]
@rn select these Kconfig:
THUNDER_NIC_PF
THUNDER_NIC_VF

**Comment by arm64b** [comment]
@rn Need to describe those NICs in the firmware via ACPI or DT, I think those ethernet devices should be PCI type, so the PCI RC must be in the ACPI  or DT since PCI is not native bus system support by arm family

**Comment by rn** [comment]
@arm64b I don't understand your comment. I would assume that the BIOS will do that and Linux just picks it up from there.

**Comment by arm64b** [comment]
@rn You're right, hmm my comment is just remind to make sure those devices have been detected successfully, meaning the FW of Packet.net is good, because AFAIK, some servers have broken FW to do that.
