### ISSUE TITLE
High Level "init" Library?

### ISSUE THREAD

**Issue by kevinschoon** [linuxkit/linuxkit#2431]
A lot of the Go code in Linuxkit is spread out across many packages: [init](https://github.com/linuxkit/linuxkit/blob/master/pkg/init/init.go), [metadata](https://github.com/linuxkit/linuxkit/blob/master/pkg/metadata/main.go), [runc](https://github.com/linuxkit/linuxkit/blob/master/pkg/runc/cmd/onboot/main.go), etc. Other important procedure reside in [shell scripts](https://github.com/linuxkit/linuxkit/blob/master/pkg/init/bin/rc.init) or are passed off to [busybox](https://git.busybox.net/busybox/tree/init/init.c).

Would it be beneficial to write a high(er) level library for handling some or all of these functions either as part of Linuxkit or from an entirely separate repo? Abstracting these functions into a separate library would make it easier for outsiders to build on top of and extend Linuxkit.

Found a few similar issues but not related to writing a new lib:
https://github.com/linuxkit/linuxkit/issues/1426
https://github.com/linuxkit/linuxkit/issues/2315

Thank you!

**Comment by justincormack** [comment]
This PR #2413 moves all the code out of `runc` and `containerd` back into `init` which is a bit better. And we are gradually cutting down the shell scripts and replacing them with Go code, I am planning to work on removing the init shell script soon.

But yes, the original plan was that there should be no code in this repo at all, just packaging, and the code could then live in another repo that we clone, and also be made available as libraries. We have a discussion in #2411 about moving the `linuxkit` tool code out (and also making it available as a library), but this is unrelated to the runtime code of course.

**Comment by justincormack** [comment]
As of https://github.com/linuxkit/linuxkit/pull/2500 there is even more Go, and less shell script.

**Comment by kevinschoon** [comment]
@justincormack Thank you for the response!

I opened this issue with the intent of discussing the possibility of creating a separate library that could be consumed by some other application that handled OS initialization. The changes in #2500 are definitely a step in the right direction, although not really usable outside of the specific startup process of Linuxkit, e.g. `/init --> /sbin/init --> runc ... --> containerd ...`. 

I don't mean to imply that this is wrong, just interested to know sort of what the "long term" vision for all the runtime Go code in Linuxkit will look like and if it will allow for more flexibility than the startup process described above. I recently started fleshing out a [new library](https://github.com/mesanine/ginit) for handling initialization for use in another project I am working on with Linuxkit.

**Comment by justincormack** [comment]
Yeah, I am not quite sure. There is a lot of boilerplate in Linux startup (eg all the mounts) but it is partly introspected from the kernel state (which cgroups does this kernel support etc), but much of it is just convention. I am totally happy to start pulling out any useful bits on an ad-hoc basis if thats useful, just not yet sure how useful it is...
