### ISSUE TITLE
promote projects/kubernetes to mainline & add projects/kubernetes-containterd

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2463]
Turning the discussion on #2400 into an issue with tickable steps.

We want to promote the existing (Docker engine based) `projects/kubernetes` to mainline and at the same time introduce a new incubation project using `containerd` directly via [cri-containerd](https://github.com/kubernetes-incubator/cri-containerd).

* Preparation:
  * [ ] Modify `linuxkitprojects/kubernetes` image to allow the image builder to pass additional options to `kubelet` (allowing them to pass `--container-runtime` etc).
* Promote `projects/kubernetes`:
  * [ ] Move `projects/kubernetes/kubernetes` to `pkg/kubernetes` and image to `linuxkit/kubernetes`
  * [ ] Move `projects/kubernetes/image-cache` to ~~`pkg/docker-image-cache`~~`pkg/kubernetes-docker-image-cache`. It is renamed as it goes to clarify the scope, likewise the image moves from `linuxkitprojects` org to `linuxkit` and is renamed. After thinking some more I decided my original proposal of naming `docker-image-cache` was not specific enough
  * [ ] Move remaining (relevant) bits of `projects/kubernetes` to `examples/kubernetes` and nuke what's left.
* Introduce `projects/kubernetes-containerd`:
  * [ ] Add new `projects/kubernetes-containerd` project containing the `cri-containerd` package (from #2400), yml files (derived from `examples/kubernetes`), README, scripts etc.
  * [ ] Add functionality to `linuxkit` and/or `moby` tools to allow prepopulation of the image store (replacing the `pkg/kubernetes-docker-image-cache` usecase in the Docker based system)

**Comment by ijc** [comment]
@justincormack one think I wasn't sure about was the "possibly an older certified one not the recent one we have?" from https://github.com/linuxkit/linuxkit/pull/2400#issuecomment-321867362 unless someone feels strongly I'll likely leave it as the more recent one through simple inertia.

**Comment by rn** [comment]
Thanks for this issue. clarifies the steps nicely. Instead of `examples/kubernetes` should this maybe got tp `blueprints`? It seems a bit more complete/complex than an example?

**Comment by ijc** [comment]
@rn if we agree that is appropriate then sure!

**Comment by ijc** [comment]
@riyazdf when adding a new repo under the `linuxkit` org is manual action needed to setup DCT or does it just work for all repos in the org?

**Comment by riyazdf** [comment]
@ijc: trust repositories are per-image repo, so yes I'll need to setup DCT for any new repo(s)

**Comment by ijc** [comment]
@riyazdf thanks! I think the `linuxkit/kubernetes` is pretty certain to be the desired name so if you could set that one up when yo get a moment that would be great (I have other things I need to do today so no urgency).

I've not had much feedback on the `linuxkit/kubernetes-docker-image-cache` name, but assuming adding it while you do the first one is low overhead you may as well do them both, I assume we can always rename or delete/create if people wantto pick a different name.

Thanks!

**Comment by riyazdf** [comment]
@ijc ok, I've set up both `linuxkit/kubernetes` and `linuxkit/kubernetes-docker-image-cache`!

**Comment by justincormack** [comment]
We would like to split out the Kube stuff into a seperate repo at linuxkit/kubernetes so that we can have all the different versions (cri-containerd etc), rather than having in blueprints etc.

**Comment by ijc** [comment]
What exactly are we proposing to move/not move and to where? e.g. the yml files (i..e just the "blueprints"), or the kubelet and image-cache packages too? the associated scripting and other stuff?

**Comment by deitch** [comment]
Wondering if these should be in a separate namespace? Keeping https://github.com/linuxkit/ for "core" and something like https://github.com/linuxkitprojects/ for extended projects? Or some other namespace?

**Comment by justincormack** [comment]
I would like to move everything, and keep this repo as just the core. That might mean suplicating some scripts, but that might encourage us to make them easier to maintain...

**Comment by ijc** [comment]
So you mean to move `projects/kubernetes/{kubernetes,image-cache}` (the packages) to this new repo instead of to `pkg/*` as proposed in the existing issue description? Are you also proposing to move other parts of `pkg/*`?

Won't this mean duplicating CI and perhaps the build test integration too? Perhaps into multiple different places or into some third aggregation location? Has that been scoped out?

I presume all this is about the git repos, but what about the hub orgas which @deitch is asking about?

I'd rather see a specific proposal for reworking the linuxkit repo in the way you envisage rather than trying to do it here piecemeal.

**Comment by justincormack** [comment]
Yes, moving those images, and the other scripts and stuff. The aim has always been that the core of LinuxKit is just system packages, not applications. There will need to be a new CI, but I want to put more realistic tests there, eg running the Kubernetes test suite, which we also don't really want in this repo.

Different hub orgs make sense too, but we can do this at a different time if necessary.

**Comment by ijc** [comment]
I covered a bunch of related stuff https://github.com/linuxkit/linuxkit/pull/2518 keeping things under projects.

It looks like there is a need for a different and more comprehensive plan for any graduation, so closing this here.
