### ISSUE TITLE
Please include CONFIG_ISCSI_TCP and CONFIG_DM_MULTIPATH in linuxkit/kernel builds

### ISSUE THREAD

**Issue by eyz** [linuxkit/linuxkit#2473]
**Description**
Please include `CONFIG_ISCSI_TCP` and `CONFIG_DM_MULTIPATH` in the linuxkit/kernel builds. 
- `iscsi_tcp` is required to start the Open-iSCSI daemon `iscsid`, which is commonly used to implement the control path of the iSCSI protocol.
- `dm_multipath` is required to support failover for iSCSI, and also is used for additional performance.

**Steps to reproduce the issue:**
The basic tutorial we use to prepare our hosts for use with the NetApp Docker Volume Plugin is posted at http://netappdvp.readthedocs.io/en/latest/install/host_config.html

**Describe the results you received:**
- Without `iscsi_tcp` included in the kernel package, `iscsid` cannot be started.
- Without `multipath_dm` included in the kernel package, multipath IO cannot be used.

**Describe the results you expected:**
- `iscsid` will start
- multipath is usable (I will work on a test case for this)

**Additional information you deem important:**
This relates to #2476, which was opened for the required user-land packages

**Comment by arm64b** [comment]
I think you can custom the linux kernel as your own image to construct the final tiny LinuxKit service, that's also one of the goals why the project is born.

**Comment by justincormack** [comment]
I think we would only want this compiled as a module, not built in.

@arm64b I think it probably makes sense to include in the default set of modules (not built in) as iscsi is fairly widely used.

**Comment by eyz** [comment]
Thanks, @justincormack. I opened this because I feel that iSCSI is a fairly core protocol to include in the included kernel -- especially for OSes which may not have directly-attached disks. We are using it on vSphere for high availability, but others on bare metal could benefit as well.

**Comment by arm64b** [comment]
@justincormack  The only reason we do that is the module is "faily widely used" while not end users need to take long time to build the kernel by themselves.
So apparently here raises a question, does only one pre-built kernel image built under the org "linuxkit" can meet the requirements for all the users? IOW, the question is about the granule of the "custom", in the YAML file level or the individual component level, from the logic of current codes, my conclusion is in the component level.

**Comment by eyz** [comment]
Yeah, there probably need to be guidelines about which classes of modules can/should be included in the kernel. This all said, I am compiling the kernel with these modules included in my local environment and will gladly continue if these modules don't end up being included.

**Comment by arm64b** [comment]
@eyz  I think probably we can't figure out the guidelines about the built-in modules or external module, because different users have different specific requirement. All we can do is try the best to work out which modules are "fairly widely used", but apparently this is a little bit subjective, that's also the reason we provides a pre-built kernel image in the hub.

**Comment by arm64b** [comment]
But I believe the user should config and build the kernel according to their own specific usage scenario in case the default pre-build image can't fit the usage case.
