### ISSUE TITLE
Ask a question: linuxkit implementation related unikernel technologies?

### ISSUE THREAD

**Issue by yaocaigen** [linuxkit/linuxkit#2484]
I have found some articles say that linuxkit is another unikernel technology. 
https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md But through this site,
I think linuxkit kernel is a simplified linux distribution. So, from the view of running an applicaton 
and an operation system environment, does linuxkit kernel look like a unikernel ?  I’m eager to know
whether linuxkit implementation is related a unikernel technology. 
Thinks.

**Comment by justincormack** [comment]
It is not, of course a unikernel. It does try to support minimalistic, immutable use cases, which have some similarities, and we do have some integration work in https://github.com/linuxkit/linuxkit/tree/master/projects/miragesdk but it is a distro toolkit at heart!

**Comment by coolljt0725** [comment]
@justincormack  From https://github.com/linuxkit/linuxkit/tree/master/projects/miragesdk which says
```
•	processes use KVM to supply extra hardware protection if available, via the Solo5 unikernel.
•	if KVM is not available, use seccomp-bpf to restrict the set of syscalls used
```
So, does it mean the same image of system containers can run both with kvm via Solo5 unikernel and linux containers?

**Comment by justincormack** [comment]
The miragesdk project plans to support that in future, yes.

**Comment by avsm** [comment]
Yes, it should be fairly straightforward to plumb through Solo5 into the minimal containerd in LinuxKit, as we use fd passing for most of the device setup. This is simpler than most other hypervisors and there is a satisfyingly minimal amount of attack surface for the Linux end of things, thanks to LinuxKit stripping down the rest of the distro.

**Comment by coolljt0725** [comment]
@justincormack  @avsm  That's very interesting :+1:

**Comment by coolljt0725** [comment]
@justincormack  @avsm  a further question , does these system container images requires some extra changes to enable they can run both on kvm and linux container?  In other word, does it mean a common image(for example busybox) pulled from dockerhub can run on kvm via Solo5 unikernel? If so, how can we do that? From what I understand,the unikernel is a single address space machine image and we need to link the application binary to the image before we run it, Is that possible to link a exist binary to a unikernel image without rebuild the binary source?
