### ISSUE TITLE
linuxkit run qemu uefi fails to find firmware on macOS

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#2510]
**Description**
`linuxkit run qemu --uefi` fails because it cannot find ovmf:

```
$ linuxkit run qemu --uefi lk.iso
FATA[0000] File [/usr/share/ovmf/bios.bin] does not exist, please ensure OVMF is installed
```

This can be fixed manually by downloading Tianocore explicitly and then passing it the path:

```
$ linuxkit run qemu --uefi --fw ./OVMF.fd lk.iso
```

The default path is set [here](https://github.com/linuxkit/linuxkit/blob/95a1c51d0da4f5774e1ca4c6ab6d3a4a7e49d430/src/cmd/linuxkit/run_qemu.go#L24) to `/usr/share/ovmf/bios.bin`.

While that might work on Linux, it does not work on macOS. You cannot install anything into `/usr/share` because it is a protected path.

We probably need some sane default, perhaps shipping it with `linuxkit`? That would be an issue as a separate binary.

**Steps to reproduce the issue:**
```
linuxkit run qemu --uefi someimg
```

**Describe the results you received:**
As above.

**Describe the results you expected:**
It should work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
I don't consider this a bug. The default path for the FW is for convenience. On macOS there is no default path for this so it fails

**Comment by deitch** [comment]
> The default path for the FW is for convenience. On macOS there is no default path for this so it fails

I think that is a valid point. If so, then it shouldn't fail the way it does. That means that `--fw <fw_path>` is a _required_ option when running on macOS (other platforms too?), and should fail with `required option --fw <fw_path> missing; you MUST provide a UEFI firmware to start in UEFI mode. See https://..... for more information`.

**Comment by deitch** [comment]
Also, as an alternative, could we not look to see if docker is installed and take the firmware from there as a secondary fallback? The error message might be:

```
You must either have docker > (some version) installed or provide a firmware via --fw ...
```

```
$ find /Applications/Docker.app/Contents/ -name '*fd'
/Applications/Docker.app/Contents//Resources/uefi/UEFI.fd
```

**Comment by justincormack** [comment]
You could change the default to `/Applications/Docker.app/Contents//Resources/uefi/UEFI.fd` on OSX, I think that would be ok.

**Comment by rn** [comment]
`linuxkit run qemu -fw /Applications/Docker.app/Contents//Resources/uefi/UEFI.fd -iso -uefi linuxkit-efi.iso` does not seem to work (blank screen for me). The EFI firmware we ship with Docker for Mac is from bhyve (and was build off a [fork](https://github.com/freebsd/uefi-edk2/tree/bhyve/UDK2014.SP1) of the standard UEFI code).

**Comment by arm64b** [comment]
I think current we don't need to support QEMU on Mac OS since it doesn't support `/dev/kvm` at all, since we have a very good hyper kit can run on Mac OS with very good networking feature integrated, I don't know why we need to run QEMU on Mac OS, is there special requirement for some usage case for that?

**Comment by rn** [comment]
we need to support qemu on macOS and it works, but there is not standard location for the OVMF firmware nor a standard way to get it. it just needs documenting, I think

**Comment by justincormack** [comment]
@arm64b we support qemu without kvm on OSX/Windows and Linux it can be useful for testing as it is uniform which can be useful. We use it in some of the build process where we don't need any platform specific features for example. It is a bit slower but ok for simple use cases.

**Comment by deitch** [comment]
> linuxkit run qemu -fw /Applications/Docker.app/Contents//Resources/uefi/UEFI.fd -iso -uefi linuxkit-efi.iso does not seem to work.... The EFI firmware we ship with Docker for Mac is from bhyve

Yeah. I tried some variants. I suspect that the firmware we have there has zero console or graphics output. Not sure what the change was - and probably not worth digging to find out - but looks like we cannot depend on the d4m one.

**Comment by deitch** [comment]
In that case, falling back to prior proposal:

if (virtualization == qemu && host os == mac && fw NOT specified) then (message as above "you must include firmware, downloadable from ...)

I'll open a PR if this is the agreed direction.

**Comment by rn** [comment]
that sounds like reasonable path to me, basically just improve the error message with qemu on macOS

**Comment by deitch** [comment]
> basically just improve the error message with qemu on macOS

Yep.
