### ISSUE TITLE
Update containerd to 1.0.0-beta.1

### ISSUE THREAD

**Issue by eyz** [linuxkit/linuxkit#2533]
**Description**
containerd 1.0.0-beta.1 has been released per https://github.com/containerd/containerd/releases/tag/v1.0.0-beta.1

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by ijc** [comment]
I'm on it.
