### ISSUE TITLE
Default build does not work: Could not pull image

### ISSUE THREAD

**Issue by davidcittadini** [linuxkit/linuxkit#2550]
Steps:

1. New macOS install.
2. Install Docker for Mac.
3. Install brew
4. brew install moby
5. brew install linuxkit.

Install failed as follows:

moby -v build  linuxkit.yml
DEBU[0000] Formats selected: [kernel+initrd]
DEBU[0000] validating output: [kernel+initrd]
INFO[0000] Extract kernel image: linuxkit/kernel:4.9.52
DEBU[0000] image tar: linuxkit/kernel:4.9.52
DEBU[0000] docker pull: linuxkit/kernel:4.9.52
DEBU[0000] pulling linuxkit/kernel:4.9.52 with content trust
DEBU[0000] entered ValidateRoot with dns: docker.io/linuxkit/kernel
DEBU[0000] found the following root keys: [885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a]
DEBU[0000] found 1 valid leaf certificates for docker.io/linuxkit/kernel: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for docker.io/linuxkit/kernel
DEBU[0000] checking root against trust_pinning config%!(EXTRA string=docker.io/linuxkit/kernel)
DEBU[0000] checking trust-pinning for cert: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000]  role has key IDs: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000] verifying signature for key ID: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000] root validation succeeded for docker.io/linuxkit/kernel
DEBU[0000] entered ValidateRoot with dns: docker.io/linuxkit/kernel
DEBU[0000] found the following root keys: [885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a]
DEBU[0000] found 1 valid leaf certificates for docker.io/linuxkit/kernel: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000] found 1 leaf certs, of which 1 are valid leaf certs for docker.io/linuxkit/kernel
DEBU[0000] checking root against trust_pinning config%!(EXTRA string=docker.io/linuxkit/kernel)
DEBU[0000] checking trust-pinning for cert: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000]  role has key IDs: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000] verifying signature for key ID: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0000] root validation succeeded for docker.io/linuxkit/kernel
DEBU[0000] updating TUF client
DEBU[0000] Loading timestamp...
DEBU[0001] 200 when retrieving metadata for timestamp
DEBU[0001] timestamp role has key IDs: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0001] verifying signature for key ID: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0001] timestamp role has key IDs: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0001] verifying signature for key ID: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0001] successfully verified downloaded timestamp
DEBU[0001] Loading snapshot...
DEBU[0001] snapshot role has key IDs: 5bfdcbf2e6e92b3c1ea96c07f3c16339704b325fb039b0dcadbafdb8e1d394a4
DEBU[0001] verifying signature for key ID: 5bfdcbf2e6e92b3c1ea96c07f3c16339704b325fb039b0dcadbafdb8e1d394a4
DEBU[0001] successfully verified cached snapshot
DEBU[0001] Loading targets...
DEBU[0001] targets role has key IDs: fae09d1ec6a5007f1e4bc708e44503e261ee476789f47bc0765bb10263283109
DEBU[0001] verifying signature for key ID: fae09d1ec6a5007f1e4bc708e44503e261ee476789f47bc0765bb10263283109
DEBU[0001] successfully verified cached targets
DEBU[0001] Loading targets/releases...
DEBU[0001] targets/releases role has key IDs: a85aab9d20a412c0eda2e134d38f2cc609bf67fdeab117e27005931d53604481,034370bcbd779e9aeb71f2deb87fe4dddb72d05d3c162c005a0e680dbe467567,74fc11c9c748aa1f51f578ac4ee1d85957b8763b12c4575d8b8f84870af2c657,54ec40e02fd0af41d8e38dc8142ce60b890fcaacf355af43c26beb49f95b7e6a,2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e,b6f9f8e1aab0676c4a7fd04eae5621a59fe15f97591eeb1a9ef7438ab6b0b0dc,82a66673242c9c12078ebea9cae303f3ac52610d9299477ed82de0454f4e285f,47caae5b3e61702d354c67706eccc40b90ec3e7c81f4c84522e2dee830e3df06
DEBU[0001] verifying signature for key ID: 2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e
DEBU[0001] successfully verified cached targets/releases
DEBU[0001] Loading targets/rolf...
DEBU[0001] targets/rolf role has key IDs: 2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e
DEBU[0001] verifying signature for key ID: 2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e
DEBU[0001] successfully verified cached targets/rolf
DEBU[0001] skipping targets/riyaz because there is no checksum for it
DEBU[0001] skipping targets/ci because there is no checksum for it
DEBU[0001] Loading targets/justin...
DEBU[0001] targets/justin role has key IDs: b6f9f8e1aab0676c4a7fd04eae5621a59fe15f97591eeb1a9ef7438ab6b0b0dc
DEBU[0001] verifying signature for key ID: b6f9f8e1aab0676c4a7fd04eae5621a59fe15f97591eeb1a9ef7438ab6b0b0dc
DEBU[0001] successfully verified cached targets/justin
DEBU[0001] skipping targets/ian because there is no checksum for it
DEBU[0001] skipping targets/avi because there is no checksum for it
DEBU[0001] successfully verified trusted reference docker.io/linuxkit/kernel:4.9.52@sha256:9af6cb9d77bf16cbf020b80b9e3b0f95e32348eacc5998a698e35a63473ab704 from notary
DEBU[0001] docker pull: trusted image docker.io/linuxkit/kernel:4.9.52@sha256:9af6cb9d77bf16cbf020b80b9e3b0f95e32348eacc5998a698e35a63473ab704 already cached...Done
DEBU[0001] could not tag trusted image docker.io/linuxkit/kernel:4.9.52@sha256:9af6cb9d77bf16cbf020b80b9e3b0f95e32348eacc5998a698e35a63473ab704 to linuxkit/kernel:4.9.52
DEBU[0001] docker create: linuxkit/kernel:4.9.52
DEBU[0001] docker pull: linuxkit/kernel:4.9.52
DEBU[0001] pulling linuxkit/kernel:4.9.52 with content trust
DEBU[0001] entered ValidateRoot with dns: docker.io/linuxkit/kernel
DEBU[0001] found the following root keys: [885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a]
DEBU[0001] found 1 valid leaf certificates for docker.io/linuxkit/kernel: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001] found 1 leaf certs, of which 1 are valid leaf certs for docker.io/linuxkit/kernel
DEBU[0001] checking root against trust_pinning config%!(EXTRA string=docker.io/linuxkit/kernel)
DEBU[0001] checking trust-pinning for cert: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001]  role has key IDs: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001] verifying signature for key ID: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001] root validation succeeded for docker.io/linuxkit/kernel
DEBU[0001] entered ValidateRoot with dns: docker.io/linuxkit/kernel
DEBU[0001] found the following root keys: [885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a]
DEBU[0001] found 1 valid leaf certificates for docker.io/linuxkit/kernel: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001] found 1 leaf certs, of which 1 are valid leaf certs for docker.io/linuxkit/kernel
DEBU[0001] checking root against trust_pinning config%!(EXTRA string=docker.io/linuxkit/kernel)
DEBU[0001] checking trust-pinning for cert: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001]  role has key IDs: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001] verifying signature for key ID: 885ce33cf9740773e5f9c37db1b38b67e2e9bd800efa3cb2c7d54ccc0afdcd1a
DEBU[0001] root validation succeeded for docker.io/linuxkit/kernel
DEBU[0001] updating TUF client
DEBU[0001] Loading timestamp...
DEBU[0002] 200 when retrieving metadata for timestamp
DEBU[0002] timestamp role has key IDs: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0002] verifying signature for key ID: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0002] timestamp role has key IDs: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0002] verifying signature for key ID: 2d250c48ae1a55ab33ab3ab5bbb1740c723ee05994bb6ba12067937368fe59b6
DEBU[0002] successfully verified downloaded timestamp
DEBU[0002] Loading snapshot...
DEBU[0002] snapshot role has key IDs: 5bfdcbf2e6e92b3c1ea96c07f3c16339704b325fb039b0dcadbafdb8e1d394a4
DEBU[0002] verifying signature for key ID: 5bfdcbf2e6e92b3c1ea96c07f3c16339704b325fb039b0dcadbafdb8e1d394a4
DEBU[0002] successfully verified cached snapshot
DEBU[0002] Loading targets...
DEBU[0002] targets role has key IDs: fae09d1ec6a5007f1e4bc708e44503e261ee476789f47bc0765bb10263283109
DEBU[0002] verifying signature for key ID: fae09d1ec6a5007f1e4bc708e44503e261ee476789f47bc0765bb10263283109
DEBU[0002] successfully verified cached targets
DEBU[0002] Loading targets/releases...
DEBU[0002] targets/releases role has key IDs: 54ec40e02fd0af41d8e38dc8142ce60b890fcaacf355af43c26beb49f95b7e6a,2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e,b6f9f8e1aab0676c4a7fd04eae5621a59fe15f97591eeb1a9ef7438ab6b0b0dc,82a66673242c9c12078ebea9cae303f3ac52610d9299477ed82de0454f4e285f,47caae5b3e61702d354c67706eccc40b90ec3e7c81f4c84522e2dee830e3df06,a85aab9d20a412c0eda2e134d38f2cc609bf67fdeab117e27005931d53604481,034370bcbd779e9aeb71f2deb87fe4dddb72d05d3c162c005a0e680dbe467567,74fc11c9c748aa1f51f578ac4ee1d85957b8763b12c4575d8b8f84870af2c657
DEBU[0002] verifying signature for key ID: 2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e
DEBU[0002] successfully verified cached targets/releases
DEBU[0002] Loading targets/rolf...
DEBU[0002] targets/rolf role has key IDs: 2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e
DEBU[0002] verifying signature for key ID: 2fb3dc88c28433196e859a31a6561226594b7d65e0bf021f589d6b81cdd14d6e
DEBU[0002] successfully verified cached targets/rolf
DEBU[0002] skipping targets/riyaz because there is no checksum for it
DEBU[0002] skipping targets/ci because there is no checksum for it
DEBU[0002] Loading targets/justin...
DEBU[0002] targets/justin role has key IDs: b6f9f8e1aab0676c4a7fd04eae5621a59fe15f97591eeb1a9ef7438ab6b0b0dc
DEBU[0002] verifying signature for key ID: b6f9f8e1aab0676c4a7fd04eae5621a59fe15f97591eeb1a9ef7438ab6b0b0dc
DEBU[0002] successfully verified cached targets/justin
DEBU[0002] skipping targets/ian because there is no checksum for it
DEBU[0002] skipping targets/avi because there is no checksum for it
DEBU[0002] successfully verified trusted reference docker.io/linuxkit/kernel:4.9.52@sha256:9af6cb9d77bf16cbf020b80b9e3b0f95e32348eacc5998a698e35a63473ab704 from notary
INFO[0002] Pull image: docker.io/linuxkit/kernel:4.9.52@sha256:9af6cb9d77bf16cbf020b80b9e3b0f95e32348eacc5998a698e35a63473ab704
DEBU[0017] could not tag trusted image docker.io/linuxkit/kernel:4.9.52@sha256:9af6cb9d77bf16cbf020b80b9e3b0f95e32348eacc5998a698e35a63473ab704 to linuxkit/kernel:4.9.52
FATA[0017] Failed to extract kernel image and tarball: Could not pull image linuxkit/kernel:4.9.52: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by justincormack** [comment]
Could you try just `DOCKER_CONTENT_TRUST=1 docker pull linuxkit/kernel:4.9.52` which is basically the same as what is failing here and see if there is a useful error message?

**Comment by davidcittadini** [comment]
I just attempted to do the same thing 12 hours later and now it worked.  Thanks :)
