### ISSUE TITLE
Create AMI target

### ISSUE THREAD

**Issue by deitch** [linuxkit/linuxkit#2562]
As discussed in #2558 , we should have a special "aws" target, like we have a "gcp" target, as distinct from "raw" (which is becoming "raw-bios"). 

`raw-bios` builds are MBR-partitioned disks with a bios boot sector. 

`aws` has special requirements. We need to verify and validate those requirements. As listed in #2558:

* "AWS requires a 1GB image." Is this correct? Is it minimum 1GB, or multiples of 1GB? Is it still true, or can it use a smaller image?
* "Docker4AWS images assume you can extend the ext4 filesystem if a larger block device is used. As discussed this will need to be changed to create a new partition instead and format it." What does it use it for? Does it need an extra partition at all, or could we just use additional EBS volumes?
* Does EC2 support GPT for the boot disk? To the best of my knowledge it does, but need to verify
* If EC2 supports GPT, does it support EFI boot, or does it still need a bios boot partition?

Once these are resolved, will create a `tools/mkimage-aws`, get it PRed in and then update `moby/tool`

cc @justincormack

**Comment by rn** [comment]
Since we now have a `aws` format target, can this be closed?

**Comment by deitch** [comment]
Yes. The original `raw` actually was "raw with MBR and BIOS with certain sizing requirements specialized for AWS." We probably should look at various other disk format options, and split aws `mkimage` from qcow2, but that doesn't change that we have this.

Closing.
