### ISSUE TITLE
Introduce "linuxkit pkg" sub-command for build and push

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2564]
Currently the LinuxKit package build/tag/push machinery is encapsulated in a `make` snippet (`pkg/package.mk`) which is included by each package's `Makefile` after overriding various configuration options.

There is also a helper script for signing/pushing in `scripts/push-manifest.sh` which is referenced by the packaging snippet.

This arrangement is one of the bigger blockers to having LinuxKit packages hosted in repositories other than this one. It's also a bit fragile.

I propose to replace this functionality with a new subcommand of the `linuxkit` binary. The existing per-package `Makefile`s would be replaced by a `linuxkit-build.yml` file encapsulating the various options/overrides available to the packages (as `Makefile` variables) today.

I propose to initially do a fairly straight conversion from the Makefile to go, e.g. using `os.exec` to call out to `docker build`, `git` etc as the `Makefile` does today, rather than attempt any sort of closer integration with the underlying tools. Initially I may do the same for the `push-manifest.sh` helper but I'd like to move its functionality into the tool sooner rather than later.

Command mapping:
* `make -C pkg/foo tag` » `linuxkit pkg build pkg/foo` ( or `cd pkg/foo ; make tag` » `linuxkit pkg build .`)
* `make -C pkg/foo forcetag` » `linuxkit pkg build --force pkg/foo`
* `make -C pkg/foo push` » `linuxkit pkg push pkg/foo`
* `make -C pkg/foo forcepush` » `linuxkit pkg push --force pkg/foo`
* `make --no-print-directory -C pkg/foo show-tag` » `linuxkit pkg show-tag pkg/foo`
* `make --no-print-directory -C pkg/foo show-tag HASH_COMMIT=DEADBEEF` » `linuxkit pkg show-tag --commit DEADBEEF pkg/foo`

Makefile variables to be supported by `linuxkit-build.yml` (with more yamly names):
* `ORG` (hub org to push to, default is linuxkit)
* `HASH` (hash to tag with, default is tree-sh)
* `ARCHES` (valid arches, default x86_64 + arm64)
* `REPO` (git repo this is in, default https://github.com/linuxkit/linuxkit)
* `NETWORK` (availability of network to build, default n)
* `TRUST` (enable content trust, default y)
* `CACHE` (some builds use `--no-cache` directly, need to decide if we should expose this)
* `DEPS` and `BASE_DEPS` will not be supported.

Future enhancements could include:
* Using `buildkit`
* More sanity checks on push (e.g. does the `org.opencontainers.image.revision` label match the current tree)
* Overriding of defaults (e.g. registry, org) on a per (git) repo basis.
* Pull the (unreadable) `org.mobyproject.config` label out of the `Dockerfile` and into the `linuxkit-build.yml`
* Support for HASH algorithms based on other schemes.
I'm sure other stuff, but I don't plan to address any of those here.

**Comment by justincormack** [comment]
SGTM.

**Comment by rn** [comment]
SGTM, you may want to keep the local override of options, like the equiv of `make ORG=foo NOTRUST=1` etc. I'm using this a lot during development and it would be tedious to loose even temporarily, Or are you suggesting to change the `linuxkit-build.yml` for that workflow?

**Comment by ijc** [comment]
I was intending to have the various commands take command line parameters to override anything which is in the yml, forgot to mention that.

**Comment by riyazdf** [comment]
SGTM!

**Comment by ijc** [comment]
I forgot about `DEPS` in the `Makefile`, those define a set of files to treat as dependencies of the `tag` targets etc.

AIUI all that does is evade a `uploading context to daemon` phase, since `docker builds` own caching will cause any actual work to be avoided if nothing has changed.

Unless someone has a counter argument I don't intend to reimplement the timestamp comparisons to avoid calling `docker build` in some cases, so `DEPS` will go away.

**Comment by justincormack** [comment]
docker build now has lazy context upload so I would ignore that

**Comment by ijc** [comment]
I intend to close this in favour of #2587  once #2578  is merged
