### ISSUE TITLE
Enable signing and content trust for more repositories.

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2580]
As part of #2578 I have discovered a handful of repositories which do not having signing/content trust enabled. We should fix this.

* [x] `test/pkg/ltp`  Ian keys missing
* [x] `tools/mkimage-dynamic-vhd` <-- this exists
* [x] `tools/mkimage-gcp` DNE
* [x] `tools/mkimage-iso-bios` Ian ARM key missing
* [x] `tools/mkimage-iso-efi` Ian ARM key missing
* [x] `tools/mkimage-rpi3` DNE, hopefully soon
* [x] `tools/mkimage-vhd` DNE
* [x] `tools/mkimage-vmdk` DNE
* [x] `pkg/ca-certificates` Ian keys missing
* [x] `pkg/extend` Ian ARM key missing
* [x] `pkg/acpid` Ian ARM key missing
* [x] `tools/qemu`  Ian ARM key missing

**Comment by justincormack** [comment]
cc @riyazdf can you set up signing for these?

**Comment by ijc** [comment]
I'll do the build side changes once @riyazdf is done.

**Comment by ijc** [comment]
@riyazdf I've added `pkg/ca-certificates` here but I think it has signing enabled but just not for my key, so I've tagged it as such. I'll add more as I come across them.

**Comment by riyazdf** [comment]
@ijc: I edited the description above - just added your keys to the relevant repos (sorry I missed these!) and initialized the new ones.  Let me know if you hit other snags?

**Comment by ijc** [comment]
@riyazdf Are you sure you added my key to the right place I see:
```
$ notary -s https://notary.docker.io delegation list docker.io/linuxkit/acpid

ROLE                PATHS             KEY IDS                                                             THRESHOLD
----                -----             -------                                                             ---------
targets/avi         "" <all paths>    9a8bbec6ba2af88a5fad6047d428d17e6d05dbdd03d15b4fc8a9a0e8049cd606    1
targets/ci          "" <all paths>    efe98d8d871c3e6e9f04857acfd50c32919c8301489fd6f9b7d8efb09699361e    1
targets/ian         "" <all paths>    6a11e4898a4014d400332ab0e096308c844584ff70943cdd1d6628d577f45fd8    1
targets/justin      "" <all paths>    433e245c656ae9733cdcc504bfa560f90950104442c4528c9616daa45824ccba    1
targets/magnus      "" <all paths>    333280b262d0783c013b1b935079e7afd3787f84ea6333200bcbd5b40d0fcc2f    1
targets/releases    "" <all paths>    9a8bbec6ba2af88a5fad6047d428d17e6d05dbdd03d15b4fc8a9a0e8049cd606    1
                                      efe98d8d871c3e6e9f04857acfd50c32919c8301489fd6f9b7d8efb09699361e    
                                      6a11e4898a4014d400332ab0e096308c844584ff70943cdd1d6628d577f45fd8    
                                      433e245c656ae9733cdcc504bfa560f90950104442c4528c9616daa45824ccba    
                                      a6c37cc2f99d3dd5c9f8515f0f442b2924493920779c8ff75e146f7bbf7511d2    
                                      54b40bbbc0e93f49090a37ae7388864814eeafe66c4c761b08ce3329522cb264    
                                      333280b262d0783c013b1b935079e7afd3787f84ea6333200bcbd5b40d0fcc2f    
targets/riyaz       "" <all paths>    a6c37cc2f99d3dd5c9f8515f0f442b2924493920779c8ff75e146f7bbf7511d2    1
targets/rolf        "" <all paths>    54b40bbbc0e93f49090a37ae7388864814eeafe66c4c761b08ce3329522cb264    1
```

Where as for e.g. `docker.io/linuxkit/init` it has:
```
targets/ian         "" <all paths>    6a11e4898a4014d400332ab0e096308c844584ff70943cdd1d6628d577f45fd8    1
                                      04dd031411ed671ae1e12f47ddc8646d98f135090b01e54c3561e843084484a3    
```

I checked `docker.io/linuxkit/qemu` and `docker.io/linuxkit/extend` too.

`6a11e4898a4014d400332ab0e096308c844584ff70943cdd1d6628d577f45fd8` is my x86 key and `04dd031411ed671ae1e12f47ddc8646d98f135090b01e54c3561e843084484a3` is my arm64 one.

What does `DNE` stand for? (`Do Not Erase` or `D(o)NE` perhaps?)

**Comment by ijc** [comment]
My eey seems to be missing from `docker.io/linuxkit/guestfs` too. I'm starting to wonder if maybe I need to refresh a cache somewhere or if I am using the wrong command line to query.

**Comment by rn** [comment]
@ijc I think something like: `notary reset -d ~/.docker/trust docker.io/linuxkit/guestfs --all` will remove local cashes. but on `guestfs` i only see one of your keys while on kernel two

**Comment by ijc** [comment]
Thanks. I tried it on a machine where I have never run notary or docker (and have a pretty much pristine `$HOME`, certainly no notary/docker stiff) and I see the same thing, so I think it isn't a cache.

**Comment by riyazdf** [comment]
@ijc: my mistake, I hadn't picked up your ARM key correctly.  It's fixed now.

> What does DNE stand for? (Do Not Erase or D(o)NE perhaps?)

"Does not exist," they exist now though :)  I made some tracking notes.
