### ISSUE TITLE
booting iso-efi bare metal mac

### ISSUE THREAD

**Issue by dprotaso** [linuxkit/linuxkit#2594]
**Description**

When building with the iso-efi format should it be bootable on a Mac bare metal?

**Steps to reproduce the issue:**

Build the getty example
```
moby build -format iso-efi getty.yml
```

Flash a USB with the iso using https://etcher.io/

When booting hold the Mac option key

**Describe the results you received:**

Holding the option key shows bootable devices and the USB flashed with the efi iso is not appearing

**Describe the results you expected:**

I would expect to see the bootable USB drive to appear and selecting would boot the iso and provide a tty

**Comment by deitch** [comment]
I don't know much about how https://etcher.io works (will try and read when I have a chance), but generally ISOs are considered removable media, with an iso9660 filesystem (with Rock Ridge extensions) and bootable that way by firmware (BIOS/EFI).

USBs, by contrast, are just considered hard drives. They need a proper partition table (GPT or MBR), boot sector (MBR) or ESP (EFI), etc.

There is an open (awaiting approval) PR to add building raw EFI file, so you can do `moby build -format raw-efi ...` . See https://github.com/linuxkit/linuxkit/pull/2540

**Comment by dprotaso** [comment]
Thanks for the info - this was a useful reference as well

http://wiki.osdev.org/El-Torito
