### ISSUE TITLE
should we be adding files under /var?

### ISSUE THREAD

**Issue by dprotaso** [linuxkit/linuxkit#2596]
**Description**

The [compose project](https://github.com/linuxkit/linuxkit/blob/77200864d0b298f8551ef6751056ce9c8c0336b5/projects/compose) example adds a files under /var

```
files:
  - path: var/html/a/index.html
    source: html-a.html
```

These files will appear in the image but not when the vm boots (tested via hyperkit)

**Steps to reproduce the issue:**

Build & run that specific project

**Describe the results you received:**

It fails to start the docker container because the /var/html bind is not present

**Describe the results you expected:**

If we expect `/var` to be a tmpfs mount point then the example should be updated. Then the vm and containers will start properly.

**Comment by justincormack** [comment]
Yes, this changed at one point and will no longer work. We could copy up files when we mount tmpfs, but it is probably better to put them somewhere else and bind mount them.

cc @deitch

**Comment by dprotaso** [comment]
> We could copy up files when we mount tmpfs, but it is probably better to put them somewhere else and bind mount them..

Putting it in a different place has a side effect of make those files & directories read only. Implicitly the bind mounts will be read-only as well.

The [compose.sh](https://github.com/linuxkit/linuxkit/blob/1d030172bf05bca151d3f14ec3516bb776b80748/projects/compose/image/load-images-and-compose.sh#L13) script assumes it can remove the images and fails.

I'm not particularly concerned about this specific example - just highlighting whether the readonly bind mounts would break some potential existing images. An obvious workaround would be to do move the files to a rw location or remount / as rw but it seems unnecessary.

**Comment by justincormack** [comment]
There is no need to remove the images if they are on a read only filesystem, as it will not actually free up space.

**Comment by justincormack** [comment]
The move to read only did break quite a few things, but they have all been fixed up now. It means you have to be explicit about what persists, which is generally a good thing.

**Comment by deitch** [comment]
Thanks for the @ mention, @justincormack . I will update the project with a PR.

**Comment by deitch** [comment]
See https://github.com/linuxkit/linuxkit/pull/2617
