### ISSUE TITLE
linuxkit pkg build has no "ignore git" option

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#2613]
If you try to use `linuxkit pkg build` outside a git repo, you get `fatal: Not a git repository (or any of the parent directories): .git`

I can't actually seem to be able to use it outside a git repo...

I think there should be a `--nogit` option that doesn't try to label it at all.

cc @ijc

**Comment by ijc** [comment]
Looks like it is currently doing two git things unconditionally
* checking if the tree is dirty
* figuring out if a release is tagged.

Seems like the check to use first is `git rev-parse --is-inside-work-tree`.

I added this to #2587 and will look at it at some point.
