### ISSUE TITLE
kubernetes-image-cache-common and control-plane missing on linuxkitprojects hub

### ISSUE THREAD

**Issue by w9n** [linuxkit/linuxkit#2638]
https://github.com/linuxkit/linuxkit/blob/master/projects/kubernetes/docker.yml#L26
https://github.com/linuxkit/linuxkit/blob/master/projects/kubernetes/docker-master.yml#L3

these are missing on linuxkitprojects hub from latest update, can be replaced with b06b6eb0b97026b2cbe8521509477c55471a7ca0 until push.

I also only get this when ``` make ``` in ``` kubernetes/image-cache ```
```
REPOSITORY                                               TAG                                                    IMAGE ID            CREATED             SIZE
linuxkitprojects/kubernetes-image-cache-common           b0fa7a0191616ed8bef9b7d4a5014dffc62c2082-amd64         cd5fecc3de07        42 minutes ago      249MB
<none>                                                   <none>                                                 1dc8758b02dc        42 minutes ago      517MB
```

**Comment by anonymuse** [comment]
I create a pull request #2651 to address.

**Comment by w9n** [comment]
```b06b6eb0b97026b2cbe8521509477c55471a7ca0``` is an older version. Most of the Maintainers are on holiday, but the new version will probably be pushed next week.

**Comment by anonymuse** [comment]
What's the working version now?

**Comment by w9n** [comment]
```b06b6eb0b97026b2cbe8521509477c55471a7ca0``` works, the newer version just has minor changes

**Comment by justincormack** [comment]
I pushed the correct ones, sorry about this, should be resolved now.
