### ISSUE TITLE
kubernetes: cri-containerd open tcp port

### ISSUE THREAD

**Issue by w9n** [linuxkit/linuxkit#2682]
cri-container listens on tcp port 10010 by default. This should be overwritten in a kubelet context.

**Comment by ijc** [comment]
It seems to be `"The port streaming server is listening on."`, not sure what that is.

Is it listening on actual IP or 0.0.0.0 or just localhost? The latter would be perhaps tolerable but the former two would be worth locking down by default for sure.

**Comment by w9n** [comment]
the cli says ```The ip address streaming server is listening on. The default host interface is used if not specified.```, so im not sure if it is 0.0.0.0 or the ip of eth0. I nmaped from a different machine on the network and it was visible.

**Comment by justincormack** [comment]
Sorry can you reopen this on https://github.com/linuxkit/kubernetes
