### ISSUE TITLE
kubernetes: nfs-utils dependencys for pvcs

### ISSUE THREAD

**Issue by w9n** [linuxkit/linuxkit#2683]
the kubelet container needs to implement fuse dependencies for pvc. RancherOS is building [theirs](https://github.com/rancher/kubernetes-package/blob/master/package/Dockerfile) on debian. There are at least problems with glusterfs in alpine gluster/glusterfs#268 . 
kubernetes-incubator/external-storage#432 Might be related but didnt throw an explicit error.

**Comment by justincormack** [comment]
Do you actually mean `fuse`? There don't seem to be fuse deps there unless they are dependencies of gluster or ceph (maybe they are)? What do you actually want to run?

**Comment by w9n** [comment]
Im not 100% sure about the terminology, but there are volume [provisioner](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#provisioner) in kubernetes and if I want to mount a nfs volume into a pod I have to mount the nfs filesystem in userspace.

I got this after provisioning a pod with a nfs volume claim
```
-11e7-8167-929c9436d3b0" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 10.106.239.49:/export/pvc-8734649f-c163-11e7-8167-929c9436d3b0 /var/lib/kubelet/pods/8740b7c9-c163-11e7-8167-929c9436d3b0/volumes/kubernetes.io~nfs/pvc-8734649f-c163-11e7-8167-929c9436d3b0
Output: mount: wrong fs type, bad option, bad superblock on 10.106.239.49:/export/pvc-8734649f-c163-11e7-8167-929c9436d3b0,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

```
after installing nfs-utils
```
 failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 10.106.239.49:/export/pvc-8734649f-c163-11e7-8167-929c9436d3b0 /var/lib/kubelet/pods/8740b7c9-c163-11e7-8167-929c9436d3b0/volumes/kubernetes.io~nfs/pvc-8734649f-c163-11e7-8167-929c9436d3b0
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.

```

**Comment by justincormack** [comment]
Ok, yes we may well want `nfs-utils` there. You should probably use `nfs4` as the type - this does not need split daemons for each function and is generally a more modern protocol (hopefully your server supports it).

**Comment by w9n** [comment]
ganesha from kubernetes-incubator/external-storage does, I will try to make it work nicely. I have no idea how ```AzureDisk``` or ```AWSElasticBlockStore``` work, they probably just use nfs aswell... cephfs and glusterfs would be nice too, but they are about 150mb each, so maybe they should be left out by default. All of them depend on python which is kind of weird.

**Comment by justincormack** [comment]
The block stores are not nfs based but AWS also has an nfs4 product (Elastic file system).

**Comment by w9n** [comment]
kubernetes basically does `mount -t nfs -o "vers=4.1" linuxkit-1111:/export_path /path/to/container` from the kubelet process. The 4.1 parameter must be defined in the storageclass. Would be better if pvc dependencys got deployed in containers but for now nfs-utils should be a good default.

**Comment by w9n** [comment]
e2e conformance testing does not set the version parameter and therefore has lots of missing rpc.statd errors
```
Mounting command: mount
Mounting arguments: -t nfs 10.38.0.3:/exports /var/lib/kubelet/pods/8e739971-cabe-11e7-8bc6-22275eb226e2/volumes/kubernetes.io~nfs/nfs-lppgd
Output: mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
```
There is actually the `experimental-mounter-path` flag that for e.g. takes this gci [mounter](https://github.com/kubernetes/kubernetes/tree/master/cluster/gce/gci/mounter) to chroot and prepare inside a specific path before mounting. This Path in kubelet context can be dynamically filled with a container root dir including the dependencies with a `HostPath` of a pod deployment.

Otherwise rpcbind has to run to pass testing.

**Comment by justincormack** [comment]
Sorry can you reopen this on https://github.com/linuxkit/kubernetes
