### ISSUE TITLE
Enable nested virt for CI

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2696]
GCP support nested virt and our test do a lot of `qemu` runs which likely will benefit from KVM acceleration via nested virt.

Details: https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances

**Comment by rn** [comment]
I temporarily enabled nested virt with something like: https://github.com/linuxkit/linuxkit-ci/pull/32
but a test CI run took as long as a non-nested on. When looking through the logs, I notice that the base OS we are using for CI is:
```
Linux linuxkit-ci-4 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
```
which seems ancient. Shouldn't matter for nested virt but a more up to date kernel/kvm might get us some improvements too...we should run it on LinuxKit anyway (cf https://github.com/linuxkit/linuxkit/issues/2099)

**Comment by ijc** [comment]
3.16 is Debian 8 (Jessie), which is currently old-stable.

If there was no difference in the time then that would suggest that KVM wasn't actually activated for some reason, perhaps the module didn't load or the perms on `/dev/kvm` were unhelpful?

Where are the relevant CI logs? I assume https://github.com/linuxkit/linuxkit-ci/pull/32 is not it?

**Comment by rn** [comment]
Ah, yes, managed to log into the GCP instance and there is no `/dev/kvm`. If I `modprobe kvm` it get's loaded (may have been loaded before but I forgot to check) but still no `/dev/kvm`

The cpu flags are:
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx hypervisor lahf_lm xsaveopt 
```
There is no `vmx` so i guess it's not enabled.

**Comment by ijc** [comment]
Agreed. I'm not actually sure https://github.com/linuxkit/linuxkit-ci/pull/32 gets deployed onto the running system, just having it in that PR can't be enough, can it?

**Comment by rn** [comment]
I manually changed the script in the container which deploys the system. Without access to the GCP account, I can't check the machine settings, but it might be that we get put on Sandy/Ivy Bridge where it wouldn't work

**Comment by rn** [comment]
Looks like we are on a Sandy Bridge system (thanks @talex5 for checking). Will try to force Haswell, which seems to be required for nested virt.

**Comment by ijc** [comment]
I guess you can be forgiven for thinking that asking for `vmx` would be enough to force a system where that was possible ;-)

**Comment by rn** [comment]
Added `'minCpuPlatform': 'Intel Haswell',` to the config and the CPU flags changed:
```
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm xsaveopt fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid
```
but still no `vmx` and unsurprisingly `modprobe kvm` does not create `/dev/kvm`. Maybe this is related to the CI using a custom machine type or the license part for enabling VMX is not working

**Comment by rn** [comment]
Ah, read the docs more carefully, the "License" to enable nested virt is actually a property of the image not the VM. So we need to update the image we use. Unfortunately, `gcloud compute images update` does not seem to allow changing the license (just the labels), but we can create a new image based on the existing one with the license set.

**Comment by justincormack** [comment]
Does that mean that `linuxkit push gcp` needs some flags if you want to run a nested virt image later?

**Comment by rn** [comment]
yes, adding that at the moment to play/test before messing more with the CI

**Comment by rn** [comment]
@talex5 created a new disk images with the nested virt:
```
gcloud compute images create linuxkit-ci-builder-6 --source-image=linuxkit-ci-builder-4  --licenses "https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"  --family linuxkit-ci-builder
```

This is for the disposable VMs used for PRs.

And certainly tests which start VMs are a lot faster, for example `linuxkit.kernel.config_4.9.x` takes 23.22s with nested virt and 48.29s without and `linuxkit.packages.containerd` takes 164.46s with nested virt while it is 602.87s without.

But the bottom line is that a full run takes around 51 minutes with nested virt vs 68 minutes without.

**Comment by rn** [comment]
Nested virt is now enabled for PR builds (see https://github.com/linuxkit/linuxkit-ci/pull/32). Closing
