### ISSUE TITLE
Minimal "Repo Info" on dockerhub?

### ISSUE THREAD

**Issue by mmariani** [linuxkit/linuxkit#2704]
**Description**

I was looking for the Dockerfile related to linuxkit/alpine (then found it under ./tools/alpine) and have noticed that the hub.docker.com descriptions for the linuxkit images are empty. Since the linuxkit package has a lot of Dockerfiles, a link to the right one would help newcomers to debug and contribute.

**Comment by rn** [comment]
I've added a short description as well as a link to the source to most packages/tools/test packages. Closing
