### ISSUE TITLE
linuxkit kernel fails to build_perf_4.13.x

### ISSUE THREAD

**Issue by zlim** [linuxkit/linuxkit#2707]
**Description**

Linuxkit kernel build is failing at build_perf_4.13.x.

**Steps to reproduce the issue:**

```
/linuxkit/kernel$ make build
```

**Describe the results you received:**

```
...
Step 32/32 : LABEL org.opencontainers.image.revision '581cbdd1e8bc34f21d6101b7c381297987bca240' org.opencontainers.image.source 'https://github.com/linuxkit/linuxkit'
 ---> Running in c0a23726c7d9
 ---> 2fef24da7559
Removing intermediate container c0a23726c7d9
Successfully built 2fef24da7559
Successfully tagged linuxkit/kernel:4.13.11-f475aca9d9ca1b9bef8fccf9a062dc760df16865-amd64
Tagging linuxkit/alpine@sha256:884f7502d90329b614c29a9a8226c30369d3c32dc2d3d329db12c78b512946bd as linuxkit/alpine:07f7d136e427dc68154cd5edbb2b9576f9ac5213
docker pull linuxkit/kernel-perf:4.13.11-f475aca9d9ca1b9bef8fccf9a062dc760df16865-amd64 || (docker pull linuxkit/kernel:4.13.11-f475aca9d9ca1b9bef8fccf9a062dc760df16865-amd64 && DOCKER_CONTENT_TRUST=0 docker build -f Dockerfile.perf --build-arg IMAGE=linuxkit/kernel:4.13.11-f475aca9d9ca1b9bef8fccf9a062dc760df16865-amd64 --no-cache --network=none  -t linuxkit/kernel-perf:4.13.11-f475aca9d9ca1b9bef8fccf9a062dc760df16865-amd64 .)
WARN[0001] certificate with CN Rolf Neugebauer is near expiry
WARN[0001] certificate with CN Rolf Neugebauer is near expiry
No trust data for 4.13.11-f475aca9d9ca1b9bef8fccf9a062dc760df16865-amd64
No trust data for 4.13.11-f475aca9d9ca1b9bef8fccf9a062dc760df16865-amd64
Makefile:175: recipe for target 'build_perf_4.13.x' failed
make: *** [build_perf_4.13.x] Error 1
/linuxkit/kernel$
```

**Describe the results you expected:**

Build completes without errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
/linuxkit/kernel$ git log -1
commit 581cbdd1e8bc34f21d6101b7c381297987bca240
Merge: 1e2dff6 4b9bf07
Author: Rolf Neugebauer <rn@users.noreply.github.com>
Date:   Fri Nov 10 13:29:02 2017 +0000

    Merge pull request #2701 from rn/vpnkit

    Add support for publish port on localhost to the hyperkit backend
/linuxkit/kernel$

```

**Comment by rn** [comment]
It's a little intricate. If you want to build your own kernel you should specify `make ORG=<org> NOTRUST=1 <target>` because otherwise the perf build will fail as you show above. It builds the kernel but then we do a `FROM <tag>` in `Dockerfile.perf` which, by default will be a pull with content trust. Overriding the ORG and disable content trust should work, at least that's how I build private kernels.

**Comment by zlim** [comment]
Thanks @rn.
The following works for me: `make ORG=<org> NOTRUST=1 push`.
For `push` to work, the following prereqs had to be installed: jq, manifest-tool.
Hope this helps anyone looking to rebuild linuxkit/kernel.

**Comment by rn** [comment]
@zlim this is also documented in https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md#building-and-using-custom-kernels

the requirements for building your own packages are documented here: https://github.com/linuxkit/linuxkit/blob/master/docs/packages.md#prerequisites

Please let us know if this documentation needs further improvements?
