### ISSUE TITLE
Alternative for including firmware blobs

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2714]
Linux 4.14.x has removed support for `make firmware_install` and, according to [this post](https://lkml.org/lkml/2017/9/15/343), the in tree firmware has not been updated since 2013. We need an alternative way of including firmware from [this repository](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git) instead.

**Comment by rn** [comment]
The AMD processor ucode updates are distributed via https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git since we have the Intel ucode in the 0.2 milestone moving this into the same milestone.

**Comment by rn** [comment]
We should have a `init` package containing a snapshot of the linux firmware repository. People building LinuxKit images for bare metal should include it. Need to see how big this will be and if we need to spent effort trying to prune it down to the drivers we support...

**Comment by rn** [comment]
a tar ball of the the current head of `linux-firmware` is 272MB. Clearly too much.

**Comment by eyz** [comment]
Might there be a way to filter the tarball for inclusion at the time the LinuxKit image is built, or similar?

**Comment by rn** [comment]
I'm not aware of such a mechanism. A large portion of the firmwares are for wifi cards, so I'll try to cut this down by deleting them them (and other unneeded large firmwares). Failing that, we only support a handful of NICs and storage drivers so it might be easier to manually only include those.

**Comment by w9n** [comment]
An image of the alpine linux-firmware is 205MB - still pretty big.

**Comment by eyz** [comment]
Like some sort of whitelist to limit inclusion in the YAML, or elseware? That would be assuming the bundle is pulled from some external URL, or part of the git checkout, but at least there is a chance that the LinuxKit ISO / image artifact would be slim..?

**Comment by eyz** [comment]
Perhaps I forget that others are only using the pre-built Docker Hub images, and not building from source very time, like I am

**Comment by w9n** [comment]
this could only work with something based on #2817 to dynamically produce pkgs

**Comment by eyz** [comment]
SGTM, offhand.

**Comment by ijc** [comment]
The kernel package is "magic" and is already post processed to extract only the relevant bits for the image (i.e. the kernel and optionally modules) which leaving the irrelevant (huge debug symbols for example) behind. If we keep the firmware in one or more tarballs in the kernel image we could support a mechanism for selecting which of those to extract into init, could have a base set (default) but include e.g. all the wifi ones in a separate tar within the package for optional selection etc.

An alternative would be to produce various `linuxkit/firmware-foo:HASH` packages which are all `FROM linuxkit-firmware-all:HASH` and just do a multistage copy of each `foo` set of firmware.

There should be no need for dynamic packages here.

**Comment by pwFoo** [comment]
firmware-all and also modules-all would be nice additional images. I moved to another kernel because of missing kernel modules.

**Comment by rn** [comment]
I am considering providing a `firmware` and `firmware-all` package with `firmware` only including the relevant subset. I'm not too keen to include them into the kernel package as this will bloat it a lot and will have to be pulled on every kernel update and in CI etc etc. even if they are not needed (like the majority of times)

At the moment there is no plan to provide a `modules-all` package. The management of the kernel configs is just too tedious for that. However, the documentation should be sufficient to allow user to roll their own kernel image.  For now the LinuxKit kernel focuses on running in VMs and modern server baremetal, which to me is a reasonable and significantly large subset of environments to support.
