### ISSUE TITLE
getty package should check for duplicate tty

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#2741]
if you end up with (perhaps for tooling issues) `console=ttyS1 console=ttyS1` on the kernel command line the console will be unusable for entering data, as the two `agetty` processes will complete. The script should try to de-dup.

**Comment by deitch** [comment]
I am confused. Are you saying that if the same `console=` appears twice, then it will start two getty processes, which will trounce each other?

**Comment by rn** [comment]
@deitch yes

**Comment by deitch** [comment]
Ok. Will take care of this.

**Comment by deitch** [comment]
See #2742
