### ISSUE TITLE
promote `projects/kubernetes` from incubation and split into separate repository

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2744]
This is a second attempt at #2463. I believe there are now no fundamental blockers to moving into a separate repository, also the `cri-containerd` stuff is already integrated.

`git filter-branch` will be used to extract `projects/kubernetes` into the root of a new repository:
* `projects/kubernetes/kubelet` → `pkg/kubelet`
* `projects/kubernetes/image-cache` → `pkg/image-cache`
* `projects/kubernetes/cri-containerd` → `pkg/cri-containerd`
* `projects/kubernetes/{README.md,Makefile}` → top level.
* `projects/kubernetes/*.yml` → top level.
* `projects/kubernetes/*.sh` → `scripts/*.sh`

In addition we will want to carry over `AUTHORS`, `LICENSE`, `NOTICE`, `MAINTAINERS`, `CONTRIBUTING.md`, `poule.yml`, `.mailmap` and `.github` from the current project (in some cases they will need tailoring for the new environment, see below).

Other tasks (brain dump, will edit as things occur to me, some of these are longer term than the initial transition):
* [x] Get `poule` enabled (does this cover dco check?).
* [x] Regenerate `AUTHORS` for the new repo.
* [x] Rewrite `README.md` (was `projects/kubernetes/README.md`) into suitable top-level README.
* [x] Update `Makefile` in the same way:
  * [ ] Grab `bin/linuxkit` and `bin/moby` from their respective CI
  * [ ] ...
* [x] Check the other imported files for updates.
* [ ] Switch to packages `linuxkit` hub org.
* [ ] Enable signing/content trust for the pkg repos.
* [ ] GH config
  * [ ] labels
* [ ] CI (I plan to use circleci, same as `linuxkit/linuxkit`, will use this as an opportunity to prototype things like sensible secrets handling for possible pushing of builds to hub etc)
  * [ ] Build `pkg/*` on each PR (need to investigate circle gating functionality for `/ok-to-test` type functionality.
  * [ ] Push `pkg/*` to hub from on master (only?).
  * [ ] Build and publish (as artefacts) a matrix of images covering `KUBE_RUNTIME={docker,cri-containerd}` × `KUBE_NETWORK={weave,bridge}` (EFI and BIOS images in both cases). Perhaps only for `master` branch or perhaps build for all but publish only for `master`.
  * [ ] Automation for bumping linuxkit components (`pkg/{init,runc,...}`). Perhaps a bot or nightly cron which maintains a single open PR at a time which tracks the latest versions?
  * [ ] Running kube e2e tests (nightly? may need a second stage of CI after circle to allow the use of virtualisation)
  * [ ] Other testing, pull in rtf and write some tests?
  * [ ] Ensure `kube.yml` matches latest `pkg/*` tags in every PR.

**Comment by ijc** [comment]
Discussed hub orgs IRL with @justincormack and agreed to move all four images (`kubelet`, `cri-containerd` and the two `kubernetes-docker-image-cache-*`) to the `linuxkit` org.

**Comment by errordeveloper** [comment]
@ijc please let me know which of these I could start working on, a lot of it involves CI, so I assume that may have to be Docker-hosted... happy to discuss on Slack etc.

**Comment by ijc** [comment]
@errordeveloper thanks! I think I need to do the basic repo setup first to unblock other contributions.

For CI right now I'm looking into circleci for most of it, the big unknown is actually booting and running things like the e2e tests since there is no nested virt on circle so we'd be emulating with qemu, which would not be ideal (although may turn out to be better than nothing).

**Comment by ijc** [comment]
https://github.com/linuxkit/kubernetes is now populated with a first cut. At this point I think we could still redo the extraction and force push so any comments with would necessitate that welcome ASAP (other comments also welcome of course.

Conversion was run while linuxkit `HEAD` was b27c196719f59a636146105519105720051ee161 using 
[kube-extract-rewrite-v0.1.tar.gz](https://github.com/linuxkit/linuxkit/files/1481974/kube-extract-rewrite-v0.1.tar.gz)

My next step will be to look at a basic circle ci setup.

**Comment by ijc** [comment]
@riyazdf please could you enable signing for:
* `linuxkit/kubelet`
* `linuxkit/cri-containerd`
* `linuxkit/kubernetes-docker-image-cache-common`
* `linuxkit/kubernetes-docker-image-cache-control-plane`
With all the usual maintainers' keys.

It's possible some of those already exist from #2463, but I know @rn did some cleanup of unused repos recently (at least at the hub level). Any others you setup for #2463 could be deleted too if you like.

**Comment by ijc** [comment]
@justincormack points me to:
```
$ ls pkg/*.yml
pkg/cri-containerd-master.yml  pkg/cri-containerd.yml
```
so there will be a rewrite in a moment!

**Comment by ijc** [comment]
Rewritten to fix that little snafu!
This time I ran:
```
$ linuxkit pkg build --dev pkg/kubelet/
$ linuxkit pkg build --dev pkg/cri-containerd
$ make
$ make clean 
$ make KUBE_RUNTIME=cri-containerd KUBE_NETWORK=bridge
```
All successfully.

**Comment by riyazdf** [comment]
@ijc: repos should be set!  the new `docker trust` commands coming in 17.11 make this simple, I can check in the script but it looks like:

```
if [[ -z  $DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE  ]]
then
    echo "must set DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE"
    exit 1
fi

if [[ -z  $DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE  ]]
then
    echo "must set DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE"
    exit 1
fi

docker trust signer add justin $1 --key justin.crt

docker trust signer add rolf $1 --key rolf.crt

docker trust signer add ian $1 --key ian.crt --key ian_arm.crt

docker trust signer add avi $1 --key avi.crt --key avi_arm.crt

docker trust signer add riyaz $1 --key riyaz.crt

echo "Successfully set up signing for $1"
```

**Comment by ijc** [comment]
Thanks @riyaz, https://github.com/linuxkit/kubernetes/pull/2 enables content trust for the images in this repo.
