### ISSUE TITLE
[RFC] Enable some security related kernel options

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2749]
This is a RFC to enable some additional kernel features
- Enable `HAVE_GCC_PLUGINS`. This then allows us to enable:
  - `GCC_PLUGIN_STRUCTLEAK`: Zero init structs which have __user attribute
  - `GCC_PLUGIN_STRUCTLEAK_BYREF_ALL`: Extension of the above
  - `GCC_PLUGIN_RANDSTRUCT`: Randomise the layout of structs
  - `GCC_PLUGIN_RANDSTRUCT_PERFORMANCE`: This is a slightly weaker version of the above but reduces the perf hit by cache aligning the structs.

- Enable `REFCOUNT_FULL`: This performs full refcount validation and has a slight perf hit, which may already been fixed for some arches.

@riyazdf @justincormack @ijc WDYT?

Sources:
- [4.14 security update](https://outflux.net/blog/archives/2017/11/14/security-things-in-linux-v4-14/)
- [4.13 security update](https://outflux.net/blog/archives/2017/09/05/security-things-in-linux-v4-13/)

**Comment by riyazdf** [comment]
seems like a good set of additions :+1:

**Comment by ijc** [comment]
Don't know the full details of them all but happy with whichever of them you feel are appropriate.

**Comment by justincormack** [comment]
SGTM. I also noticed "CONFIG_VMAP_STACK for arm64" in those notes, which we have on amd64, not sure if you added to arm64?

**Comment by rn** [comment]
yes, it's on for arm64 as well (and yes I noticed that in the notes and did check)

**Comment by tixxdz** [comment]
Hi,

* For `REFCOUNT_FULL` on arm64 it was updated to be default [1], on x86 it has to be enabled, however there is already kind of refcount protection that blocks overflows `ARCH_HAS_REFCOUNT` , maybe enable it unless there are some reports of performance degradation ?...
 
[1] https://www.spinics.net/lists/kernel/msg2606428.html

**Comment by tixxdz** [comment]
Also would it be possible to tweak the kernel config by: one commit per one config option that affects performance ?  just in case there are future performance reports it may make it easy to bisect.

Thank you!
