### ISSUE TITLE
Move LCOW to linuxkit/lcow

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2753]
Moving the LCOW related code to its own repository has the advantage that we can:
- make releases independent of LinuxKit
- provide binaries
- run LCOW specific CI
- have a  top-level readme for how to test LCOW (independent of blog posts etc)
- track LCOW specific issues

**Comment by justincormack** [comment]
SGTM

**Comment by rn** [comment]
`linuxkit/lcow` populated using the attached script (thanks to @ijc for the script).

[lcow-rewrite.tar.gz](https://github.com/linuxkit/linuxkit/files/1482429/lcow-rewrite.tar.gz)
