### ISSUE TITLE
supported kernels

### ISSUE THREAD

**Issue by zlim** [linuxkit/linuxkit#2763]
**Description**
[docs/kernels.md](https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md) references various kernel variants:

> linuxkit/kernel-mainline: Mainline kernel.org kernels from the Ubuntu Mainline PPA.
> linuxkit/kernel-ubuntu: Selected Ubuntu kernels.
> linuxkit/kernel-debian: Selected Debian kernels.
> linuxkit/kernel-centos: Selected CentOS kernels.
> linuxkit/kernel-fedora: Selected Fedora kernels.

 Are they still supported?

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
yeah, they are not really maintained as such. I'm tempted to remove that section from the documentation and tweak the scripts a bit so that you can roll your own if you need one

**Comment by zlim** [comment]
+1

Useful to have a script accept a git tree.
