### ISSUE TITLE
Proposal: add `prebuild` field to `build.yml`

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2766]
The [kubernetes `pkg/image-cache`](https://github.com/linuxkit/kubernetes/tree/master/pkg/image-cache) build wraps a `Makefile` around the usual `build.yml` machinery in order to run some commands prior to the build (downloading and exporting the Docker images). This means that unlike the majority of other packages (and all the other packages in the `linuxkit/kubernetes` repo) they cannot be built with a simple `linuxkit pkg build «path»`.

I propose adding a `prebuild` field to the `build.yml` format which would be a simple string to be passed to `/bin/sh -c «prebuild»` which could be used to do this preparatory work (I'd either embed a short script using the `|` yaml syntax or call out to a separate script).

Thoughts?

NB: with this in place I would also drop the `build.yml.in` stuff and the dynamic creation of the two package source trees and just duplicate the small amount of content into `pkg/kubernetes-docker-image-cache-@@CACHE@@` directly and get rid of the `Makefile` shenanigans entirely.

NB2: there are some other `Makefile` based builds in tree (at least `tools/guestfs`, `tools/alpine`, `kernel`) but these are using the old scheme and not wrapping `linuxkit build` and would not be helped by this change (at least not directly). Those are covered by issues linked from https://github.com/linuxkit/linuxkit/issues/2587

**Comment by rn** [comment]
having a `prebuild` section sounds reasonable to me

**Comment by ijc** [comment]
I've been thinking about this some more recently (by which I mean I have a prototype ;-)). My concern is that this functionality makes it rather easy (either deliberately or by mistake) to break determinism WRT the git hash, since the script can do basically anything. IOW it is actually _too_ flexible.

My actual use case is to replace a [`docker image pull` & `docker image save`](https://github.com/linuxkit/kubernetes/blob/master/pkg/image-cache/Makefile#L7...L8) which is part of producing the image cache packages. I'm considering something more tailored/specific e.g.:
```
depends:
  - images:
      target-dir: dl
      from-file: images.lst
```
Which would pull and save every image from `«pkgdir»/images.lst` (insisting on a sha56 being used, for reproducibility) as tarballs into «pkgdir»/dl` (`both `target-dir` and `from-file` are relative to the package directory). `from-file` is useful because `images.lst` can be more easily autogenerated (c.f. how [`versions.mk`](https://github.com/linuxkit/kubernetes/blob/master/pkg/image-cache/versions.mk) is produced by [`mkversions`](https://github.com/linuxkit/kubernetes/blob/master/pkg/image-cache/mkversions) today), could also support a mutually exclusive `images` field for use cases where it was desirable to inline the list.

Currently we go for one saved tarball per image (using the basename) but `docker image save` can output multiple images to the same tarball, which might be nicer. We could have `target` name a specific single tarfile and `target-dir` a directory if we wished to be flexible. To aid reproducibility and simplify the `Dockerfile` I would suggest that `target-dir` would _nuke_ the target directory and recreate it with exactly the request contents (so you can refer to `«tareget-dir»/*` without needing to reproduce a list in the `Dockerfile`).

In a first pass I would have this literally populate the directory, in the future we could consider building the build context ourselves and injecting tis stuff dynamically.

Eventually we could have other sections under `depends`, such as one for fetching URLs or whatever.

**Comment by justincormack** [comment]
second version seems fairly safe...

**Comment by rn** [comment]
sounds reasonable to me too
