### ISSUE TITLE
kernel:4.9.64 can not be pulled(?)

### ISSUE THREAD

**Issue by arm64b** [linuxkit/linuxkit#2771]
**Description**
`git pull` the latest codes, then `make` build a `bin/linuxkit`, with this tool:
```
# bin/linuxkit build -format iso-efi arm64.yml 
Extract kernel image: linuxkit/kernel:4.9.64
WARN[0004] certificate with CN Justin Cormack is near expiry 
WARN[0004] certificate with CN Justin Cormack is near expiry 
Pull image: docker.io/linuxkit/kernel:4.9.64@sha256:968d0deb4b3bc11674b83fa82ac040b6934b99d0bff3e86caef0dd074369493e
FATA[0010] Failed to extract kernel image and tarball: Failed to docker create image docker.io/linuxkit/kernel:4.9.64@sha256:968d0deb4b3bc11674b83fa82ac040b6934b99d0bff3e86caef0dd074369493e: Error: No such image: docker.io/linuxkit/kernel:4.9.64@sha256:968d0deb4b3bc11674b83fa82ac040b6934b99d0bff3e86caef0dd074369493e
```

**Steps to reproduce the issue:**
1. git pull the latest codes
2. make
3. #bin/linuxkit build -format iso-efi linuxkit.yml

**Describe the results you received:**
Failed to pull linuxkit/kernel:4.9.64 image

**Describe the results you expected:**
The linuxkit/kernel:4.9.64 should be pulled successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
look like it wasn't pushed on arm64:
```
manifest-tool inspect linuxkit/kernel:4.9.64
Name:   linuxkit/kernel:4.9.64 (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:968d0deb4b3bc11674b83fa82ac040b6934b99d0bff3e86caef0dd074369493e
 * Contains 1 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:f355bd4d704365431813c98a6653726729659ac95d98b597c46da8f6dfa19ffb
1  Mfst Length: 529
1     Platform:
1           -      OS: linux
1           - OS Vers:
1           - OS Feat: []
1           -    Arch: amd64
1           - Variant:
1           - Feature:
1     # Layers: 1
         layer 1: digest = sha256:b23a3222fe710a4f36c0c341e615ef8c45a7e3bab63c36b3324078c0e9dc1529
```

**Comment by arm64b** [comment]
So does that mean the linuxkit/kernel:4.9.64 in the hub is not multi-arch?

**Comment by rn** [comment]
yes. Looks like none of the kernels from this commit https://github.com/linuxkit/linuxkit/pull/2767/commits/6ede240737cadd7da40dd4abf7d90795f1d06cc7 got build and pushed. I kicked off a build, should be there in an hour or three

**Comment by rn** [comment]
ah, the arm64 kernel build failed on a kernel config change in 4.14.1

**Comment by rn** [comment]
the arm64 kernels should be pushed. still waiting for a other kernel updates to compile before creating the PR with the fix

**Comment by arm64b** [comment]
closed since the kernel can be pulled on AArch64 platform.
