### ISSUE TITLE
How to properly shutdown a linuxkit-started VM?

### ISSUE THREAD

**Issue by tstringer** [linuxkit/linuxkit#2805]
**Description**

When I build and run a VM through `linuxkit`, what is the appropriate way to shutdown the VM? I've tried running `shutdown` through the tty but the command isn't found on the machine. I see that I can pull the pid of the VM from the host and kill it from the host, but that doesn't seem like the "graceful" way to shut it down.

**Steps to reproduce the issue:**

A basic `build` and `run` brings up the VM. At that point I'm curious how to shut it down. I haven't seen any documentation on this, nor in the FAQ.

**Describe the results you received:**

I am forced to kill the VM from the host retrieved from the pid recorded in the VM state dir.

**Describe the results you expected:**

A clean and graceful way to shutdown the VM started through `linuxkit run`.

**Comment by deitch** [comment]
Does `halt` not work?

**Comment by ijc** [comment]
I habitually use `poweroff -f` so I know that works.

Depending on the hypervisor platform you might also need to include the `acpid` image in your build, else the OS may not be able signal that it has stopped to the hypervisor (so the latter won't actually exit).

**Comment by tstringer** [comment]
Thank you both for the reply! Both `halt` and `poweroff` work great! @ijc any reason to force poweroff? @deitch I guess since it's a VM it's relatively insignificant to use `halt` instead of `poweroff`, so it seems like either of those options would be appropriate.

**Comment by rn** [comment]
`halt`/`poweroff` shut down the system cleanly and, optionally, execute `onshutdown` containers. Most of my images I use for testing don't have any persistent state so `poweroff -f` is faster for shutdown. I can image @ijc doing the same

**Comment by tstringer** [comment]
@rn fair enough, thanks!

**Comment by eyz** [comment]
Just to strive for completeness I wanted to let you know that -- per Justin -- I am performing a guest VM shutdown via `kill -s SIGTERM 1`, to send a SIGTERM to the init process.

**Comment by ijc** [comment]
Yeah, I `-f` because I'm impatient.

**Comment by teeg82** [comment]
FYI in case someone else comes across this, `poweroff` doesn't send SIGTERM to runc containers. For example, I'm running docker-in-docker, so If I want to _gracefully_ shutdown everything, I need a SIGTERM sent to the dind container which in turn sends SIGTERMs to my docker containers. I'm not sure of the correct way to do that.

**Comment by eyz** [comment]
> FYI in case someone else comes across this, `poweroff` doesn't send SIGTERM to runc containers. For example, I'm running docker-in-docker, so If I want to _gracefully_ shutdown everything, I need a SIGTERM sent to the dind container which in turn sends SIGTERMs to my docker containers. I'm not sure of the correct way to do that.

Maybe try launching your processes within something like dumb-init, because as I understand if that process is terminated it ensures all of the trial processes launched through it are terminated as well; this one in particular has been very reliable for that class of situation for me over the last 5 years. See https://github.com/Yelp/dumb-init

**Comment by teeg82** [comment]
@eyz Thanks for the tip. But I'm not sure how that would work in the linuxkit context as the main processes (such as docker-in-docker for example) are executed by `runc`. It seems like none of the `containerd` processes are being sent a SIGTERM at all as I had hoped. Is this the type of situation solved by `onShutdown` containers, and I have to manually send the SIGTERM?

**Comment by eyz** [comment]
I would advise that you join the Linuxkit Slack community and ask the core engineering team, because it seems like this question could be answered by them. I'm pretty sure this solution would work for your case, or any case where you need to ensure sub-processes receive a signal through a parent process. This all said, I'm not actively working on the LinuxKit project at this time, but I sincerely hope you get traction on your answer.

**Comment by teeg82** [comment]
thanks @eyz I'll check that out
