### ISSUE TITLE
How customize /lib/modules and /lib/firmware

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2826]
I have a custom initrd build and a modules / firmware detection script. So it's possible to 
1) include all modules and firmware OR
2) detect current loaded modules with (compatible) firmware

So I can create a custom initrd (modules and firmware) for the current host.

Now I try to convert it to linuxkit and need to know how to modify firmware / modules included to initrd / rootfs (/lib/modules and /lib/firmware).

Firmware and modules shouldn't be added at boot time (container inside onboot section). So how could a add files detected by a custom script during the linuxkit build process?

rootfs should be build from images inside the init section, but is it possible to run a script which detect and copy the needed files?

**Comment by rn** [comment]
It depends on what you want to do, but it may work if you just create a docker image with `/lib/modules` and `/lib/firmware` and add it to the `init` section in the YAML.This simply adds them to the root fs. The downside is that `modprobe` won't work as `depmod` is not run to include the new modules, but `insmod` will.

If you want to include the modules properly (with `depmod` you can try and copy the build stuff for `zfs` in https://github.com/linuxkit/linuxkit/blob/master/kernel/Dockerfile.zfs and https://github.com/linuxkit/linuxkit/blob/master/kernel/Makefile#L185 ff. This creates a new LinuxKit package which include the original modules and the new ZFS modules and runs `depmod` over it.

**Comment by pwFoo** [comment]
ALL modules / firmware will be simple with a init image, yes. That will work fine.
Nice to boot with different notebooks and PCs.

2) But add detected modules / firmware looks more complicated... 
Maybe the easiest way would be to detect the needed modules and firmware and build a local image which to add to the yml file init section.
With my custom build (root isn't RO) it's possible to run depmod -a. So it should work, right?

**Comment by rn** [comment]
If you have a writable rootfs you can run `depmod` but it may slow down boot if run everytime. also it's not clear to me how it will interact with hot/cold plug. You'd probably have to run `depmod` before `mdev`

**Comment by rn** [comment]
does this work for you, ie can this issue be closed?

**Comment by pwFoo** [comment]
Hi @rn,

should work for me. Have to test it as soon as my module build (#2827 ) works.

Thanks
