### ISSUE TITLE
create metadata under /run not /var

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#2829]
If you mount a persistent drive on `/var` which is fairly common, you will overwrite metadata. I think `/run` is probably a better location for metadata as it does not persist over boot anyway.

**Comment by deitch** [comment]
I am opening a PR for this. It turned out to be surprisingly easy. I had one concern, though. Will raise it on the PR.

**Comment by deitch** [comment]
See https://github.com/linuxkit/linuxkit/pull/2860

**Comment by deitch** [comment]
Resolved via #2860
