### ISSUE TITLE
Need help to build kernel modules from kernel tree to extend /lib/modules

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2830]
I try to extend the 4.14.9-linuxkit /lib/modules/* to support more devices and also desktop builds.

I tried to compile the missing modules with that dockerfile against 4.14.9-linuxkit. Because I wouldn't enable each module in config I just used **allmodconfig**.
```
ARG     KERNEL_VERSION=4.14.9
ARG     KERNEL_IMAGE=dengleros/kernel:$KERNEL_VERSION
ARG     BASE_IMAGE=alpine:latest

FROM    $KERNEL_IMAGE AS kernel


FROM    $BASE_IMAGE AS ksrc

ARG     KERNEL_VERSION=4.14.9

RUN     apk --update --no-cache add wget ca-certificates

RUN     wget -O /tmp/linux-$KERNEL_VERSION.tar.gz https://www.kernel.org/pub/linux/kernel/v4.x/linux-$KERNEL_VERSION.tar.gz


FROM    $BASE_IMAGE AS modules

ARG     KERNEL_VERSION=4.14.9

ARG     WORKDIR=/mnt
WORKDIR $WORKDIR

RUN     apk --update --no-cache add \
        linux-vanilla-dev \
        build-base \
        ncurses-dev \
        binutils \
        libelf-dev \
        elfutils \
        openssl-dev \
        bc

COPY    --from=kernel   /kernel-dev.tar /tmp/
COPY    --from=kernel   /kernel-headers.tar /tmp/
COPY    --from=ksrc     /tmp/linux-$KERNEL_VERSION.tar.gz /tmp/

RUN     tar -xf /tmp/kernel-dev.tar -C /
RUN     tar -xf /tmp/kernel-headers.tar -C /
RUN     tar -xzf /tmp/linux-$KERNEL_VERSION.tar.gz -C $WORKDIR/

RUN     mkdir -p /dist

ENV     INSTALL_PATH=/dist
ENV     INSTALL_HDR_PATH=/dist
ENV     INSTALL_MOD_PATH=/dist

RUN     cp -a /usr/src/linux-headers-${KERNEL_VERSION}-linuxkit/.config $WORKDIR/linux-${KERNEL_VERSION}/.config

RUN     make -C $WORKDIR/linux-$KERNEL_VERSION allmodconfig

RUN     sed -i -e 's/CONFIG_MODULE_SIG=y/CONFIG_MODULE_SIG=n/g' $WORKDIR/linux-$KERNEL_VERSION/.config \
        && sed -i -e 's/CONFIG_MODULE_SIG_ALL=y/CONFIG_MODULE_SIG_ALL=n/g' $WORKDIR/linux-$KERNEL_VERSION/.config \
        && sed -i -e 's/CONFIG_MODULE_SIG_FORCE=y/CONFIG_MODULE_SIG_FORCE=n/g' $WORKDIR/linux-$KERNEL_VERSION/.config \
        && sed -i -e 's/CONFIG_DEBUG_INFO=y/CONFIG_DEBUG_INFO=n/g' $WORKDIR/linux-$KERNEL_VERSION/.config \
        && sed -i -e 's/CONFIG_MODVERSIONS=y/CONFIG_MODVERSIONS=n/g' $WORKDIR/linux-$KERNEL_VERSION/.config \
        && sed -i -e 's/CONFIG_MODULE_SRCVERSION_ALL=y/CONFIG_MODULE_SRCVERSION_ALL=n/g' $WORKDIR/linux-$KERNEL_VERSION/.config 


RUN     make -C $WORKDIR/linux-$KERNEL_VERSION --jobs=$(grep -c '^processor' /proc/cpuinfo) modules

RUN     make -C $WORKDIR/linux-$KERNEL_VERSION modules_install




FROM    scratch

COPY    --from=modules /dist/ /
```

Fixed a module sig problem by disabling some config options with SED. But after compiling again modules can't be loaded. Tested some modules (example ext4):
```
modprobe: ERROR: could not insert 'ext4': Exec format error
```

Could anyone help me to fix it? Or show me a way how to build additional modules for use with linuxkit kernel?

I'm new with make kernel / modules. Maybe I just do it wrong...?

**Comment by rn** [comment]
The easies way to do that is to modify `./kernels/config-4.14.x-x86_64` as described in the docs [here](https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md#modifying-the-kernel-config) (I suggest you use `make defconfig` followed by `make menuconfig` and then copy the `.config` to `/src/config-4.14.x-x86_64). The do a `make build_4.14.x` and you have should get a kernel image in your local docker store which you can use (as described [here](https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md#building-and-using-custom-kernels)).

**Comment by pwFoo** [comment]
So I can't use the linuxkit kernel with my additional modules and should re-compile the modules with a new kernel?

**Comment by rn** [comment]
in kernel tree modules are typically not compiled against existing headers.  The kernel headers are really there to compile external modules. It may be possibly with some Makefile hackery, but it is very uncommon to compile them this way. You may also be able to just do a `make defconfig && make oldconfig` to have a configured kernel and then just run `make modules` but I don't know if you can then load the modules in an existing kernel.

You are really better off just compiling the kernel as outlines about. Closing this issue

FWIW I don't recommend running LinuxKit on a desktop/laptop. It's really not meant for that use case (it really more for "appliance" type uses either as VMs or on modern server hardware). Getting the modules working is only a small and relatively simple task.
