### ISSUE TITLE
Error writing outputs: Error writing iso-efi output: docker pull failed: exit status 1 output:

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2838]
I tried to build an efi-iso after testing successful kernel+initrd.

My linuxkit binary is running inside of a container! Host is linux. Docker version 17.09.0-ce. 
Started by the following command to build kernel+initrd (default):
```
docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -v /usr/local/bin/docker:/usr/bin/docker -v $(pwd):$(pwd) --workdir $(pwd) linuxkit build test.yml 
```

Command to get a efi-iso fails:
```
docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock -v /usr/local/bin/docker:/usr/bin/docker -v $(pwd):$(pwd) --workdir $(pwd) linuxkit build -format iso-efi test.yml 
```
Also tried to build an iso-bios, but failed with the same error message.

Debugging output:
```
INFO[0002] Create outputs:                              
DEBU[0002] format: [iso-efi] test                  
DEBU[0002] validating output: [iso-efi]                 
DEBU[0002] output ISO: linuxkit/mkimage-iso-efi:43592c9b316b036338c4db9f90aada37b48415dc test-efi.iso 
INFO[0002]   test-efi.iso                          
DEBU[0002] docker run (input):                          
FATA[0003] Error writing outputs: Error writing iso-efi output: docker pull failed: exit status 1 output:
```

Because linuxkit build failed to pull it, I pulled it before I re-run the build
```
docker images | grep mkimage
linuxkit/mkimage-iso-efi   43592c9b316b036338c4db9f90aada37b48415dc   1aa149a150c3        8 weeks ago         531MB
```

But error is just the same.
```
DEBU[0003] docker run (input):                          
FATA[0003] Error writing outputs: Error writing iso-efi output: docker pull failed: exit status 1 output:
```

**Comment by pwFoo** [comment]
Cloned linuxkit from github, make binaries. Same yml file works fine to build a efi iso! 
So problem is the special setup inside of a docker container (alpine + linuxkt binary, docker+docker.sock mapped from host).

Any idea why it could fail to pull? Pull images from inside of the container works fine, but pull during linuxkit build fails. It isn't a linuxkit problem, because it works fine if I build it at the host...

Any idea about dependencies for linuxkit pull from inside of a container?

**Comment by deitch** [comment]
Hmm... it just outputs the entire tar as a stream to stdout piped to `docker run -i linuxkit/mkimage-iso-efi:<hash>`. The actual output func is called [here](https://github.com/moby/tool/blob/master/src/moby/output.go#L58) which in turn calls a [docker run](https://github.com/moby/tool/blob/master/src/moby/output.go#L303) whose source is [here](https://github.com/moby/tool/blob/master/src/moby/docker.go#L24)

The `docker pull` is nothing more than `docker pull linuxkit/mkimage-iso-efi:43592c9b316b036338c4db9f90aada37b48415dc` [here](https://github.com/moby/tool/blob/master/src/moby/docker.go#L39), so it must be something basic in the in-container setup you have.

I find it odd that there is no error message on the next line, as there should be one. Could it be a trust issue? Try going launching the `linuxkit` container (with appropriate volume mounts for the socket as you did) and doing

```
DOCKER_CONTENT_TRUST=1 docker pull linuxkit/mkimage-iso-efi:43592c9b316b036338c4db9f90aada37b48415dc
```

See if it is the trust issue?

**Comment by pwFoo** [comment]
Thank you, @deitch !

It was a problem with certificates. Missing ca-certificates! Verified by test:
```
DOCKER_CONTENT_TRUST=1 docker pull linuxkit/mkimage-iso-efi:43592c9b316b036338c4db9f90aada37b48415dc
```

Added `ca-certificates` to fix it.

**Comment by deitch** [comment]
Excellent! FWIW, I am working on replacing that entire "stream out to docker" build process, but it is a long slow painful process.
