### ISSUE TITLE
gcp builder fatal error

### ISSUE THREAD

**Issue by Gabology** [linuxkit/linuxkit#2854]
**Description**

Since upgrading to docker 17.12.0-CE the GCP builder for linuxkit will produce a fatal error.
**Steps to reproduce the issue:**
`linuxkit build -format gcp -name linuxkit linuxkit.yml`

**Describe the results you received:**
```
Create outputs:
  linuxkit.img.tar.gz
FATA[0056] Error writing outputs: Error writing gcp output: docker run failed: exit status 1 output:
```

**Describe the results you expected:**
I expected it to produce a working Linuxkit tarball for GCP.

**Comment by rn** [comment]
I can't reproduce this. I'm on docker 17.12.0-ce-rc3 (Docker for Mac) and:
```
% linuxkit version
linuxkit version 0.0
commit: 965c678f9c02dbd7e21262e89038682b9156ed29
```

Some formats require a fair bit of memory and when they run out of memory the error message is often not very helpful. My Docker for Mac was configured with 6G of memory but less should be fine.

Which platform are you running this on? If on Docker for Mac/Windows, does increasing the memory help?

**Comment by Gabology** [comment]
@rn 

You are right, increasing my memory from 2GB to 3GB seems to have fixed the issue. Strangely enough it worked with 2GB prior to 17.12.
