### ISSUE TITLE
Question: Use linuxkit parser to build service tar archives?

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#2859]
For some tests it would be great to have the services from yaml section as service.tar local instead of a builtin service inside of the initrd (/container/services/*).
Is it possible to reuse linuxkit features to get service as archive?

**Comment by pwFoo** [comment]
I know [riddler](https://github.com/jessfraz/riddler/) to parse container config. Is riddler used at linuxkit or another tool?

**Comment by justincormack** [comment]
You can get the output as a tarball with `linuxkit build -format tar`.

We don't use riddler any more, we used to a long time ago before the public release. You can use the code linuxkit uses as a library, see `ConfigToOCI` https://github.com/moby/tool/blob/master/src/moby/config.go#L373

**Comment by pwFoo** [comment]
Thanks! `linuxkit build -format tar` is what I'm searching for! 👍 

Is ConfigToOCI available as tool / binary (maybe with go get) or integrated in the moby tool as part? I'm It looks like a part of the tool for me, but I'm new with GO...

**Comment by justincormack** [comment]
It is not available as a vinary, only as a library at present.

**Comment by rn** [comment]
Closing as the question seem have been answered
