### ISSUE TITLE
Update hyperkit go bindings

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2868]
The upstream hyperkit go bindings have changed quite a bit. We should revendor and adjust the code here.

**Comment by rn** [comment]
IMHO, the go bindings itself in the hyperkit repo should just be a shim on top of the binaries. I'm not sure yet if we implement some form of defaults and/or OS detection in `linuxkit` to figure out which disk type to use

**Comment by dprotaso** [comment]
What’s your take on the fact that the go bindings currently create and
compact disks?

**Comment by justincormack** [comment]
I think we probably want to move all that stuff out eventually. We want a Go library in linuxkit for qcow2 anyway at some point in order to build disk images in userspace (cc @deitch who is working on some of this).
