### ISSUE TITLE
Include pigz in alpine package list

### ISSUE THREAD

**Issue by guillaumerose** [linuxkit/linuxkit#2879]
Since https://github.com/moby/moby/pull/35697, Moby can use `pgiz` instead of standard gzip golang library to decompress layers.

Using the latest `linuxkit/alpine` image to run Moby as a service, I can't add the `pigz` package. 

```
$ docker run -it linuxkit/alpine:d307c8a386fa3f32cddda9409b9687e191cdd6f1 apk add pigz
ERROR: unsatisfiable constraints:
  pigz (missing):
    required by: world[pigz]
```

I suppose pigz in missing from this list : https://github.com/linuxkit/linuxkit/blob/master/tools/alpine/packages

Should I continue using `linuxkit/alpine` or directly `library/alpine` ?

**Comment by justincormack** [comment]
We don't build a Docker package in this repo, so it is really up to you how you build yours; our examples here all use the `docker` official image. We can add the `pigz` package to the linuxkit/alpine package list.

**Comment by eyz** [comment]
@guillaumerose If it hasn't been done already, perhaps pigz should be added to the https://hub.docker.com/_/docker/ `dind` images, built from the https://github.com/docker-library/docker repo
