### ISSUE TITLE
Make it possible to key the package tags off of top level tree hash

### ISSUE THREAD

**Issue by rvs** [linuxkit/linuxkit#2887]
We are trying to use linuxkit pkg functionality on repositories containing one package per repo. This currently doesn't quite work because the [treeHash](https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/pkglib/git.go#L86)  always expects a package to reside in a subfolder so it can find the tree hash corresponding to it.

I don't think there's any reason to restrict it to just the subfolder since it can as easily use the top level tree hash (the one referenced in the commit).

If this sounds like a good idea in general, I can provide a pretty simple patch

**Comment by justincormack** [comment]
SGTM, I think its just not tested.

**Comment by rvs** [comment]
When you say "its just not tested" do you mean that it actually exists and I missed it somehow?

**Comment by deitch** [comment]
SGTM as well. Is it just the ability to do `lkt pkg . `?

**Comment by rvs** [comment]
@deitch pretty much: basically covering the use case when Dockerfile/build.yml are at the very top level of the git repo.

**Comment by deitch** [comment]
I’ve never tried it. Try it. If it works, it just needs tests and doc updates. If not, those plus the code change.

**Comment by justincormack** [comment]
@rvs no I meant it wasnt intentionally not working, I presume no one realised it needed special casing.

**Comment by rn** [comment]
I kinda knew this won't work (at least in the original version) as the tree hash needs a directory other than `.` (from hazy memory). So not sure the tree hash works on the root of a git repo. Might need some special cases and use the commit hash instead.

**Comment by rvs** [comment]
You don't need to use the commit hash -- you can simply use the tree hash that commit is pointing to (that'd be a root tree hash I was talking about).

Ok, since it seems that everybody's in agreement that it would be useful to have this working -- I'll propose a patch shortly.

**Comment by rvs** [comment]
Can someone please take a look at https://github.com/linuxkit/linuxkit/compare/master...rvs:master and let me know if this looks good enough for a pull request to be submitted?

**Comment by deitch** [comment]
@rvs go for a PR on that. There may be some comments on it, but it certainly is a good basis for a PR.
