### ISSUE TITLE
New binaries not executable

### ISSUE THREAD

**Issue by uberhacker** [linuxkit/linuxkit#2889]
I really appreciate the new tagged release!  I tried one of the new binary packages and noticed a few issues:
1. The binary was not executable
2. There was an extraneous `__MACOSX` directory in the zipfile
3. This is not a biggie but it would be nice if the binary was simply named `linuxkit` instead of `linuxkit-linux-amd64`

**Comment by rn** [comment]
Thanks for checking. This should now all be fixed. Binary is called `linuxkit` for linux and darwin and I removed the `__MACOSX` bit. at least from the amd64 linux binary.

Need to investigate on how to better distribute these via GH release.
