### ISSUE TITLE
Remove i8042 from x86_64 kernel config

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2893]
```
config SERIO_I8042
        tristate "i8042 PC Keyboard controller"
        default y
        depends on ARCH_MIGHT_HAVE_PC_SERIO
        help
          i8042 is the chip over which the standard AT keyboard and PS/2
          mouse are connected to the computer. If you use these devices,
          you'll need to say Y here.

          If unsure, say Y.

          To compile this driver as a module, choose M here: the
          module will be called i8042.
```

I would think we don't boot LinuxKit on computers requiring this. The reason to disable is that HyperKit does not emulate it and it takes a bit of time to realise this:
```
[    1.087047] Fusion MPT SPI Host driver 3.04.20
[    1.087368] i8042: PNP: No PS/2 controller found. Probing ports directly.
[    1.613909] i8042: Can't read CTR while initializing i8042
[    1.614347] i8042: probe of i8042 failed with error -5
[    1.614717] hv_vmbus: registering driver hyperv_keyboard
```

0.6s might not sound much, but the full kernel boot of the `minimal` example takes less than 2s

**Comment by justincormack** [comment]
I think that should be ok, as we use serial console everywhere.

**Comment by eyz** [comment]
Would this removal affect keyboard on VM consoles?

**Comment by justincormack** [comment]
On all the hypervisors we are using serial console by default. It is possible to boot with VGA console which may use ps2 emulation though, eg maybe in virtualbox.

@rn does it disable if you use boot command line parameters of `i8042_nokbd` etc as per https://github.com/torvalds/linux/blob/master/drivers/input/serio/i8042.c

**Comment by eyz** [comment]
I'll try it on vSphere if it's merged, as that's what we use.

**Comment by rn** [comment]
@eyz you can try with `rneugeba/kernel:4.14.15`. The one thing which does not work with it is `linuxkit run qemu -gui` as there is no keyboard.

However, while playing with it, I noticed that the 4.14. kernel does not have the delay:
```
[    0.920237] Fusion MPT SPI Host driver 3.04.20
[    0.922695] i8042: PNP: No PS/2 controller found.
[    0.923282] hv_vmbus: registering driver hyperv_keyboard
```

We could consider backporting whatever changes to 4.9 but it seems hardly worth the effort. Closing

**Comment by eyz** [comment]
Yeah, I can check it out. @rn Do you still want me to try even even though you closed this issue?

**Comment by rn** [comment]
no, don't worry. I think we'll switch to 4.14 soon anyway and it was only a small delay only on HyperKit anyway. so no big deal

**Comment by eyz** [comment]
OK, thanks.
