### ISSUE TITLE
Improve kernel patching

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2906]
When applying patches we should use the proper `patch` utility and use the following argument `-t -F0 -N -p1 -u` to error on any issue and disable fuzzing. The main kernel patches should all apply cleanly as they are derived from a branch which gets rebased for every release.

See https://github.com/linuxkit/linuxkit/pull/2897#discussion_r166590726

**Comment by tjfontaine** [comment]
What about using `git apply` instead of `patch` since currently any thing related to permissions that git has preserved is ignored by `patch`
