### ISSUE TITLE
Resolve `certificate with CN ABC DEF is near expiry` messages

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#2911]
https://github.com/linuxkit/kubernetes/issues/62 is the most recent instance of a user reporting the "certificate... is near expiry" messages:

```
WARN[0003] certificate with CN Justin Cormack is near expiry
WARN[0003] certificate with CN  is near expiry
WARN[0003] certificate with CN  is near expiry
WARN[0003] certificate with CN avi@atomicinc.com is near expiry
WARN[0003] certificate with CN Ian Campbell is near expiry
WARN[0004] certificate with CN  is near expiry
WARN[0004] certificate with CN  is near expiry
WARN[0004] certificate with CN avi@atomicinc.com is near expiry
WARN[0004] certificate with CN Ian Campbell is near expiry
WARN[0004] certificate with CN Justin Cormack is near expiry
WARN[0004] certificate with CN Justin Cormack is near expiry
```

Although these are benign (until the key actually expires) we should figure out what to do about them, either short or long term. For now this issue can serve as a place to point users who are concerned.

**Comment by justincormack** [comment]
The longer term solution is that apparently they will go away with Notary 0.6 which is out soon...

**Comment by ijc** [comment]
What is the behaviour of pulling an image which was signed with a now expired certificate going to be?

Is removing the message sufficient or do we also need to rotate our signatures?

**Comment by justincormack** [comment]
I believe the message is just referring to the timestamp signatures that are automatically rotated on hub, so we dont need to do anything.

**Comment by rn** [comment]
fixed via https://github.com/linuxkit/linuxkit/pull/2951

closing
