### ISSUE TITLE
switch to Alpine Edge again?

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#2922]
Containerd is probably going to switch to requiring Go 1.10 I think soon, due to some issues around tar handling that are now fixed. Next stable Alpine will be in May. There are no big changes scheduled for 3.8 so I don't think that being on the rolling Edge release will be an issue.

We don't need to do this until containerd requires 1.10 (and it is in Alpine Edge).

cc @ncopa

**Comment by justincormack** [comment]
ok this got merged in containerd https://github.com/containerd/containerd/pull/2162

@ncopa we discussed having Go 1.10 in Alpine stable too...

**Comment by rn** [comment]
closing as the original issue was fixed and we moved to alpine 3.8 as well
