### ISSUE TITLE
Running `linuxkit run vbox --networking bridged` does not start VM in bridged mode on Mac

### ISSUE THREAD

**Issue by obergner** [linuxkit/linuxkit#2929]
**Description**

On my Mac I tried running
```
linuxkit run vbox --networking bridged --iso lk-docker.iso
```
expecting it to start a virtualbox vm with a **bridged** network adapter. However, as confirmed by virtualbox' gui the vm was actually started in **default NAT mode**.

Further investigation revealed that this was due to the host's network adapter to attach the network bridge to not being specified. Doing the moral equivalent of
```
vboxmanage modifyvm --bridgeadapter1 en0
```
where `en0` is my Mac's primary network interface fixed the issue, i.e. the vm started from `lk-docker.iso` was started with bridged networking as confirmed by virtualbox' gui, and its `eth0` was assigned an IP via DHCP.

I have a very simple and obvious fix for this that adds command line option `--bridgeadapter en0` to the `linuxkit` binary.  If this bug report is accepted I would be more than willing to issue a PR.

**Steps to reproduce the issue:**

On Mac (probably on other OSes as well, but I didn't try) run
```
linuxkit run vbox --networking bridged --iso any-linuxkit-built.iso
```
and observe that the vm is **not** started in bridged mode.

**Describe the results you received:**

Virtualbox vm is started in NAT mode.

**Describe the results you expected:**

Virtualbox vm is started in bridged mode.

**Additional information you deem important (e.g. issue happens only occasionally):**

It is possible - although I did not check this - that virtualbox assumes a default network interface when starting in bridged mode, most likely `eth0`. So starting a virtualbox vm in bridged mode via `linuxkit` might actually have worked on some machines.

**Comment by justincormack** [comment]
The `vbox` code is not well tested with all the myriad of options, patches welcome.

**Comment by obergner** [comment]
Issued PR #2930 to fix this. Bare bones fix, no bells nor whistles. Simply adds `--bridgeadapter` as cli option.
