### ISSUE TITLE
finish initial s390x support

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#2949]
This is mostly a reminder to self, what is left for s390x integration
- Update `./tools` and `./pkg` to new alpine base
- build/push/sign packages
- test build

/cc @alicefr

**Comment by alicefr** [comment]
Cool! Let me know if you have any issues

**Comment by rn** [comment]
@alicefr am I right in assuming that currently s390x only boots via kernel+initrd? ie none of the `tools/mkimage-*` bits are needed?

**Comment by alicefr** [comment]
Yes, I tried only `kernel+initrd`. If we noticed that another format is needed, we can added later on I guess.

**Comment by ijc** [comment]
@alicefr the question is really which ones s390x as a platform supports. Can you boot from an ISO or a filesystem with a suitable bootloader embedded? Which bootloader would that be in each case (e.g. on x86 we use syslinux or isolinux or grub depending on the context, on arm64 it is grub for all the ones which are supported)

**Comment by rn** [comment]
My question was mostly about which of the tools we should enabled for s390x. I think for now I won't enable any.

**Comment by alicefr** [comment]
@rn. I'm not really a bootloader expert I guess there are 2 points to solve. First, which bootloader s390 support and how the kernel is booted on s390 KVM. I will ask my colleagues. I am afraid that it may be not the standard way as on x86. Second, which tools are already present in alpine for s390. As far as I know, there are not *syslinux* and *isolinux* on alpine for s390. It might be a subject for an extension.

**Comment by ijc** [comment]
`syslinux` and `isolinux` are very x86 specific and unlikely to be used on any other platform.

My expectation is that s390x will either use grub2 (if it is supported on s390x, I've no idea, but it supports a bunch of architectures) or some other custom/platform-specific bootloader (a bit of googling suggests that `qemu-system-s390x` is often used along with something called `zipl`).

**Comment by alicefr** [comment]
They are both but we principally use *zipl*

**Comment by alicefr** [comment]
We support only *zipl*. You may find also *grub2* from SUSE.
