### ISSUE TITLE
Building an image with with a private repository fails with `Error response from daemon: unknown: User UserId`

### ISSUE THREAD

**Issue by kojustin** [linuxkit/linuxkit#2954]
**Description**
When building a a LinuxKit image with a service that uses an image from a private registry, the build fails if the image is not available locally.

If the image IS available locally the build succeeds.

The local Docker daemon has already been logged in to the private repository and is able to pull with only a "docker pull".

**Steps to reproduce the issue:**
1. Create a new LinuxKit image.yml, add a new service with a image that comes from a private repository.
2. Make sure the image doesn't exist in the current list of images.
3. `linuxkit build`

**Describe the results you received:**
The build fails with...

```
linuxkit build myimage.yml
Extract kernel image: linuxkit/kernel:4.14.23
Add init containers:
Process init image: linuxkit/init:b212cfeb4bb6330e0a7547d8010fe2e8489b677a
Process init image: linuxkit/runc:7c39a68490a12cde830e1922f171c451fb08e731
Process init image: linuxkit/containerd:37e397ebfc6bd5d8e18695b121166ffd0cbfd9f0
Process init image: linuxkit/ca-certificates:v0.2
Add onboot containers:
  Create OCI config for linuxkit/sysctl:v0.2
  Create OCI config for linuxkit/sysfs:v0.2
  Create OCI config for linuxkit/format:v0.2
  Create OCI config for linuxkit/mount:v0.2
Add service containers:
  Create OCI config for linuxkit/getty:v0.2
  Create OCI config for linuxkit/rngd:v0.2
  Create OCI config for linuxkit/dhcpcd:v0.2
  Create OCI config for linuxkit/openntpd:v0.2
  Create OCI config for <PRIVATEIMAGE>
Pull image: <PRIVATEIMAGE>
FATA[0021] Failed to create OCI spec for <PRIVATEIMAGE>: Error response from daemon: unknown: User UserId(anon-dtvw3wn6dwbatyhyrgh) cannot ReadRegistryOrg on resource <SNIP>
```

**Describe the results you expected:**
The missing image should be pulled like any other missing image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
I think this is a dup of https://github.com/moby/tool/issues/202

**Comment by rn** [comment]
this should be fixed with https://github.com/linuxkit/linuxkit/pull/3125

please let us know if not.
