### ISSUE TITLE
Kernel panic error

### ISSUE THREAD

**Issue by vinoth-rajkumar-lebara** [linuxkit/linuxkit#2980]
When i tried to create customised image and boot the linuxkit with kernel version 4.14.x it gives me kernel panic error

Any ideas?

**Comment by deitch** [comment]
@vinoth-rajkumar-lebara can you please give more details that this? What linuxkit `.yml` did you use? How did you build it? How did you run it?

**Comment by rn** [comment]
and the output from the kernel panic would be useful too

**Comment by vinoth-rajkumar-lebara** [comment]
Guys, I managed to resolve the kernel panic error with below command

linuxkit run -mem=2014M linuxkit

**Comment by rn** [comment]
ah, this is a known issue (and a dup of https://github.com/linuxkit/linuxkit/issues/2713). If you run the image with `kernel+initrd` the root filesystem is run as a ramdisk. So if your `initrd` is quite large you may run out of ram. Unfortunately the kernel crashes with a somewhat obfuscated error messages (it would have helped if you had provided the log).

If you have a largish root filesystem you are better off building an iso and boot off that. With an ISO image we use the filesystem in the ISO directly, so no memory will be used for it.

**Comment by vinoth-rajkumar-lebara** [comment]
Thanks for the support. Really appreciate....
