### ISSUE TITLE
Switch user not found in postgres linuxkit

### ISSUE THREAD

**Issue by sandeep510** [linuxkit/linuxkit#2997]
Hello, Installed postgres 10.3 alpine image in linux kit. Build was successful and service is up  and running but i am unable to switch user and  result is.

(ns: getty) linuxkit-36bba5cbfa99:~# su postgres
su: unknown user postgres
(ns: getty) linuxkit-36bba5cbfa99:~#

Postgres yml file

``` 
kernel:
 image: linuxkit/kernel:4.9.89
 cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
 - linuxkit/init:7af4e32f31f04d6c63d457c502d2f69344db7d72
 - linuxkit/runc:e4b01b68b225d694a60f8b335258bd2144971239
 - linuxkit/containerd:d03b69c7d23fdae0fec1b6e62a72d362992135df
onboot:
 - name: dhcpcd
   image: linuxkit/dhcpcd:8b23f047ffa4d657a2c7dd465e69cc13721c4165
   command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
 - name: getty
   image: linuxkit/getty:9e2c184fdd708720d47e663f03ad137c074d4f21
   env:
    - INSECURE=true
 - name: postgres
   image: postgres:10.3-alpine
   capabilities:
    - CAP_NET_BIND_SERVICE
    - CAP_CHOWN
    - CAP_SETUID
    - CAP_SETGID
    - CAP_DAC_OVERRIDE
   net: host
trust:
 org:
   - linuxkit
   - library  ```
                             


(ns: getty) linuxkit-36bba5cbfa99:/var/lib# ls -l
total 0
drwxr-xr-x    2 root     root            40 Mar 23 21:50 apk
drwxr-xr-x    2 root     root            40 Mar 23 21:50 misc
drwxr-xr-x    2 root     root            40 Mar 23 21:50 udhcpd
(ns: getty) linuxkit-36bba5cbfa99:/var/lib#


(ns: getty) linuxkit-36bba5cbfa99:/# pstree
init---containerd-+-containerd-shim---tini---rungetty.sh-+-rungetty.sh---login-+
                  |                                      `-rungetty.sh---login-+
                  `-containerd-shim
(ns: getty) linuxkit-36bba5cbfa99:/#



Let me know if i am missing anything in yml file.Thanks

**Comment by ijc** [comment]
You are running `su` in the `getty` container not the `postgres` container (which is where I presume the user exists). You probably need to use `ctr` to get a shell in the `postgres` container.

Something like:
```
ctr -n services.linuxkit tasks exec --tty --exec-id ash postgres ash -l
```

**Comment by sandeep510** [comment]
Hello, tried as you mentioned getting below errors
(ns: getty) linuxkit-36bba5cbfa99:~# ctr -n services.linuxkit tasks exec --tty -
-exec-id ash postgres ash -l
**ctr: OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown**
(ns: getty) linuxkit-36bba5cbfa99:~# ctr -n services.linuxkit c ls
CONTAINER    IMAGE    RUNTIME
getty        -        io.containerd.runtime.v1.linux
postgres     -        io.containerd.runtime.v1.linux
(ns: getty) linuxkit-36bba5cbfa99:~#

**Comment by ijc** [comment]
The postgres container has stopped. You should check the logs to see why.

Please use triple backticks to quote logs and shell snippets etc, the above is close to unreadable. You can preview in the editor to see how it will look.

**Comment by ijc** [comment]
The container output is logged to `/var/log`, not to `/containers/...`.

**Comment by sandeep510** [comment]
i am i using correct yml file? if yes what is the solution to run postgres.?

**Comment by ijc** [comment]
I can't spot what is wrong in your yml file by eye and I'm not aware of any existing demo or examples  using postgres specifically, so I'm afraid you will need to debug this.

**Comment by sandeep510** [comment]
```(ns: getty) linuxkit-36bba5cbfa99:/var/log# ls -l
total 8
-rw-------    1 root     root             0 Apr 10 15:15 getty.err.log
-rw-------    1 root     root           425 Apr 10 15:15 getty.out.log
lrwxrwxrwx    1 root     root            15 Apr 10 15:15 onboot -> /run/log/onboot
-rw-------    1 root     root            57 Apr 10 15:15 postgres.err.log
-rw-------    1 root     root             0 Apr 10 15:15 postgres.out.log
(ns: getty) linuxkit-36bba5cbfa99:/var/log# cd onboot
(ns: getty) linuxkit-36bba5cbfa99:/run/log/onboot# ls -l
total 4
-rw-r--r--    1 root     root             0 Apr 10 15:15 onboot.000-dhcpcd.err.log
-rw-r--r--    1 root     root           418 Apr 10 15:15 onboot.000-dhcpcd.out.log
(ns: getty) linuxkit-36bba5cbfa99:/run/log/onboot#
```

**Comment by rn** [comment]
which container are you trying to access the file from. You should be able
to do so from the `getty` container

**Comment by sandeep510** [comment]
I am trying it access it from getty only
FYI
```(ns: getty) linuxkit-36bba5cbfa99:/var/log# cat postgres.err.log
 chmod: /var/lib/postgresql/data: Operation not permitted ```

**Comment by ijc** [comment]
`chmod: /var/lib/postgresql/data: Operation not permitted` is the _contents_ of `postgres.err.log`, it is not an error message from `cat`.

As @rn says you need to arrange for a writeable (and probably persistent) place for postgres to write its data.
