### ISSUE TITLE
kernel config: enable CONFIG_MPLS_ROUTING and CONFIG_MPLS_IPTUNNEL 

### ISSUE THREAD

**Issue by ajones-rvbd** [linuxkit/linuxkit#2998]
Feature request to enable MPLS_ROUTING and MPLS_IPTUNNEL in the linuxkit kernel config.

Linux kernel MPLS implementation has matured to the point where it can be used as an effective overlay for container networking.  Alpine linux enables these options, but, while linuxkit has CONFIG_MPLS=y and CONFIG_MPLS_GSO=y, CONFIG_MPLS_ROUTING and CONFIG_MPLS_IPTUNNEL are both still off.

Total cost is around 100k bytes:

/lib/modules/4.9.65-1-hardened/kernel/net/mpls # ls -lh
total 160
-rw-r--r--    1 root     root       40.5K Nov 27 15:59 mpls_gso.ko
-rw-r--r--    1 root     root       43.2K Nov 27 15:59 mpls_iptunnel.ko
-rw-r--r--    1 root     root       68.8K Nov 27 15:59 mpls_router.ko

**Comment by rn** [comment]
is it sufficient for your use case to have them as modules? I can roll that into the next kernel update

**Comment by ajones-rvbd** [comment]
Yes, modules work.  Thank you!
