### ISSUE TITLE
Failed to extract root filesystem in linuxkit/kernel:4.9.89 

### ISSUE THREAD

**Issue by micemuni** [linuxkit/linuxkit#3015]
Hi All,
By using jenkins job i am build linixkit image, When i tried to build images using linuxkit got error like 
I have installed Go and Linuxkit also. Even tried to increase the memory also but still got the same error. 

> 
Cmd used in job 
++ linuxkit build -format aws superset.yml
 >

**Jenkins output log:-**
FYI... 
++ linuxkit build -format aws superset.yml
Extract kernel image: linuxkit/kernel:4.9.89
Add init containers:
Process init image: linuxkit/init:7af4e32f31f04d6c63d457c502d2f69344db7d72
Process init image: linuxkit/runc:e4b01b68b225d694a60f8b335258bd2144971239
Process init image: linuxkit/containerd:d03b69c7d23fdae0fec1b6e62a72d362992135df
Add onboot containers:
  Create OCI config for linuxkit/dhcpcd:8b23f047ffa4d657a2c7dd465e69cc13721c4165
Add service containers:
  Create OCI config for linuxkit/getty:9e2c184fdd708720d47e663f03ad137c074d4f21
  Create OCI config for XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/add/ais-superset:0.23.a1
time="2018-04-24T14:24:54Z" level=fatal msg="Failed to extract root filesystem for XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/add/ais-superset:0.23.a1: archive/tar: cannot encode header: Format specifies USTAR; and USTAR cannot encode Name=\"containers/services/superset/lower/usr/lib/node_modules/npm/node_modules/libnpx/node_modules/yargs/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/node_modules/error-ex/node_modules/is-arrayish/.editorconfig\"" 

Any idea why this error coming. ??

**Comment by justincormack** [comment]
Hmm, it looks like a path length restriction in `tar` at some point...

**Comment by justincormack** [comment]
Ah it looks like the Go tar package defaults to USTAR unless you override https://golang.org/pkg/archive/tar/

**Comment by ragurakesh** [comment]
The golang version in the build system is go1.10 linux/amd64

**Comment by micemuni** [comment]
yes, golang version is go1.10 linux/amd64

**Comment by micemuni** [comment]
@justincormack Do you have any example on this, so that will help us. 
Linuxkit build -format aws superset.yml -> cmd i used. 

Used as you said:- 
linuxkit build -format aws superset.yml -import archive/tar
time="2018-04-24T14:57:27Z" level=fatal msg="Cannot open config file: open -import: no such file or directory"

**Comment by justincormack** [comment]
can you try using the `moby` tool from this PR (use `moby build` not `linuxkit build`) and see if it fixes it https://github.com/moby/tool/pull/216

**Comment by rn** [comment]
Is this still a problem or can this be closed?
