### ISSUE TITLE
Frankenkit and I don't understand why

### ISSUE THREAD

**Issue by orre** [linuxkit/linuxkit#3020]
**Description**
I'm considering to use Linuxkit for a project but I confess I don't understand why I cannot get the simplest example to work the way I expect. Maybe someone is willing to help me here.

I built linuxkit from GitHub and then did:

linuxkit build examples/docker.yml
linuxkit run qemu --kernel docker

The systems boots nicely it appears (no errors as far as I can see).
From the getty console I then do:
~# ctr t ls
TASK    PID    STATUS

Nothing!
Why no docker task? or getty for that matter?

Then I do:
~# runc list
ID           PID         STATUS      BUNDLE                          CREATED                          OWNER
000-sysctl   0           stopped     /containers/onboot/000-sysctl   2018-04-27T06:48:25.32311609Z    root
001-sysfs    0           stopped     /containers/onboot/001-sysfs    2018-04-27T06:48:26.784609605Z   root
002-format   0           stopped     /containers/onboot/002-format   2018-04-27T06:48:28.277591356Z   root
003-mount    0           stopped     /containers/onboot/003-mount    2018-04-27T06:48:29.672806581Z   root

All runc tasks stopped? Is this OK?

It all appears very strange to me. What am I missing here?

**Comment by orre** [comment]
Awsome! That was just what I was looking for.
Thanks a lot.

**Comment by deitch** [comment]
Most welcome.
