### ISSUE TITLE
404 on pushing image using GCS backend

### ISSUE THREAD

**Issue by Gabology** [linuxkit/linuxkit#3064]
**Description**

Pushing an image using the GCS backend now fails.

**Steps to reproduce the issue:**

```
linuxkit build -format gcp image.yml
linuxkit push gcp -bucket some-bucket -family some-family -img-name some-img-name image.tar.gz
```

**Describe the results you received:**
```
Uploading file image.img.tar.gz to Google Storage as some-img-name.img.tar.gz
Upload Complete!
gs://some-bucket/some-img-name.img.tar.gz
Creating image: some-img-name
FATA[0011] Error creating Google Compute Image: googleapi: got HTTP response code 404 with body: Not Found
```

**Describe the results you expected:**
The image to be created succesfully in GCE.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
> linuxkit version
linuxkit version v0.4+
commit: bd59dbf79355f6457ca47858d03365f81c6cfbac
```
It used to work for me, in v0.0. So I am guessing there has been some regression.

**Comment by justincormack** [comment]
Hmm, thats strange it is working fine for me. Does `linuxkit -v push ...` give any more information? Does the bucket exist?

**Comment by Gabology** [comment]
The bucket exists, the output I am getting is:

```
DEBU[0000] Connecting to GCP
DEBU[0000] Using Application Default crednetials
DEBU[0000] Generating SSH Keypair
INFO[0000] Uploading file some-image.img.tar.gz to Google Storage as some-image-v1-0-0.img.tar.gz
INFO[0026] Upload Complete!
gs://some-bucket/some-image.img.tar.gz
INFO[0026] Creating image: some-image-v1-0-0
FATA[0026] Error creating Google Compute Image: googleapi: got HTTP response code 404 with body: Not Found
```

**Comment by Gabology** [comment]
Ok seems like the issue was that I didn't pass the `-project` flag. I thought it would perhaps use the GCP configured default project.
