### ISSUE TITLE
Docker daemon log taking up too much disk space

### ISSUE THREAD

**Issue by kevinbrink** [linuxkit/linuxkit#3072]
**Description**

To start off with, I'd like to clarify that this concern is for the docker **_daemon_** logs, **not** for docker's container-level logs. The `log-driver` and `log-opts` docker daemon configurations seem to handle container-level logs just fine. 

With that out of the way, the issue I'm running into is that the `/var/log/docker.err.log` log file is growing too quickly and not being rotated on our production servers, making us nervous that it will eventually fill up enough disk space to cause issues on the server itself. Concretely, we've been running for 19 days, and, on one of the nodes, that log file has grown to `3.6GB`. As our VM's are expected to run for months on end, this is obviously a concerning trend. 

The `linuxkit` OS that we're using has very similar configuration to the [example docker configuration](https://github.com/linuxkit/linuxkit/blob/master/examples/docker.yml), with some additional configuration in the `/etc/docker/daemon.json` file, most notably that we set `debug` to `True`. That was clearly a mistake, as my tests show that, had we not used that option, our log files would substantially smaller.

However, even if we had left the log-level at it's default of `info`, it looks to me like the log file could still cause issues if the server is left running for too long. I did some rough calculations, and my guess is that the file could still grow to something like 10GB if the daemon is left running for 6 months or so. 

I have been trying to get a manual `logrotate` solution working to protect against this, but it seems like the docker daemon never reloads it's log file, which means that when `logrotate` does it's thing and creates a blank new `docker.err.log`, the docker daemon continues to write at whatever offset it left off at, and backfills the rest of the file with null bytes, taking up as much space as it was before. I've tried some solutions involving sending the `HUP` signal to the docker process without any success; it seems like the docker daemon doesn't handle that signal, or at least not in a way that reloads it's log file. 

All that to say, I have two things I'm wondering about:

1. Is there an accepted way to implement rotating of the docker daemon logs? It seems silly that I can't find any good information about this. Surely someone else has bumped into this issue before? Or is it just accepted that the `docker.err.log` file keeps on growing forever, and you'd better restart your server at some point? If that's the current answer, I'd love to have a linuxkit-based way of rotating that log file specifically. 
2. Do you have any suggestions on how to truncate the existing `docker.err.log` on a running server _without_ shutting down the server or docker daemon instance? We'd like to avoid having to update the OS image we're running just to prevent the docker daemon log from using up all our disk space. 

Thanks for your time!

**Steps to reproduce the issue:**

1. Create a linuxkit OS ISO with a docker daemon service with `debug: True` in it's configuration file
1. Using that ISO, run a docker swarm cluster in production for several days

**Describe the results you received:**

* `/var/log/docker.err.log` file grows rapidly, and is not rotated

**Describe the results you expected:**

* Log file is rotated automatically, conserving disk space
* Alternatively, the docker daemon responds to the `HUP` signal by reloading it's log file, and beginning to write from the beginning, so that we can use `logrotate` properly.

**Comment by kevinbrink** [comment]
@rn : Thanks for the response! Seems like a solid solution to me. 

I realize these things are hard to predict, but any idea when it would make it's way into a release? 

Also, out of curiosity, is there any particular reason that better logging handling hasn't been implemented before now? Naively, I would assume a lot of other projects would be bumping into these limits when using linuxkit in production, but I haven't found many other people complaining about this. Are we doing things in a particularly strange way? Or is this just a case of the natural progression of a project not having gotten to this stage yet?

**Comment by rn** [comment]
Currently @djs55 is actively working on an implementation. So I suspect this might be implemented soon (in fact I've seen a demo of it the other day :) )

As for when this will appear in a release, I tentatively think we'll cut a release once containerd 1.1.0 is out (there are on -rc2 at the moment so should be soon) and once we updated to alpine 3.8 (waiting for hub images to appear). So this should be within the next few weeks.

The reason it hasn't been implemented so far was that folks were simply too busy with other things. We have/had a nice prototype implementation under `projects/memlogd` for a while but people have been sidetracked and we hadn't had a chance promote it.

**Comment by kevinbrink** [comment]
@rn Awesome; thanks again for the reply, looking forward to playing around with it!

**Comment by ijc** [comment]
@kevinbrink you can already play around with it if you grab the code from #3085.

**Comment by djs55** [comment]
@kevinbrink I've got a branch which demonstrates log rotation here: https://github.com/djs55/linuxkit/tree/logging-logrotate This is based on the PR from #3085 with an extra patch on top which adds the log rotation program itself.

If you
```
git clone git://github.com/djs55/linuxkit
cd linuxkit
git checkout logging-logrotate
cd pkg
for i in init memlogd logwrite; do linuxkit pkg build $i; done
cd ../examples
linuxkit build -disable-content-trust logging.yml
linuxkit run logging
```
and then you can watch it with `watch ls -l /var/log`. It's set to rotate fairly quickly so after about 30s you should see:
```
Every 2s: ls -l /var/log                                    2018-07-06 09:38:55

total 32
-rw-r--r--    1 root     root           405 Jul  6 09:37 getty.out
-rw-r--r--    1 root     root            45 Jul  6 09:37 memlogd
lrwxrwxrwx    1 root     root            15 Jul  6 09:37 onboot -> /run/log/onboot
-rw-r--r--    1 root     root            88 Jul  6 09:37 onboot.001-dhcpcd.err
-rw-r--r--    1 root     root          1003 Jul  6 09:37 onboot.001-dhcpcd.out
-rw-r--r--    1 root     root          1001 Jul  6 09:38 write-to-the-logs.out
-rw-r--r--    1 root     root          1078 Jul  6 09:38 write-to-the-logs.out.0
-rw-r--r--    1 root     root          1078 Jul  6 09:38 write-to-the-logs.out.1
-rw-r--r--    1 root     root          1078 Jul  6 09:38 write-to-the-logs.out.2
```

**Comment by teeg82** [comment]
Hey folks, I'm one of @kevinbrink's coworkers who worked on getting our linuxkit version to use the aforementioned logging / rotating feature. Just in case anyone bumps into this, be sure to update your `init` container if you're still pointing to an older version, as the new one contains some new bits that make this feature possible. May seem pretty obvious but...it caught me.

**Comment by djs55** [comment]
@teeg82 good point -- it probably fails silently with the wrong `init` version. Is everything working as expected for you now?

**Comment by teeg82** [comment]
It did indeed fail silently, yeah. But now that its up and running, yes its working fantastically for us. The only thing I wish it had is the ability to compress the rotated files, similar to logrotate. We're in fact adding this to a forked version of the `logwrite` package. I could make a PR with that when its ready, if you think that's valuable @djs55.

**Comment by djs55** [comment]
Yes please, a PR would be welcome.
