### ISSUE TITLE
Update to alpine 3.8

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3081]
Alpine 3.8 was released: https://alpinelinux.org/posts/Alpine-3.8.0-released.html

We should update linuxkit to start using it.

**Comment by rn** [comment]
waiting for 3.8 images: https://github.com/docker-library/official-images/pull/4501

**Comment by justincormack** [comment]
The images are now available.

**Comment by rn** [comment]
I know...already started :) I hope to get the logging stuff in first, though to save some rebase hassle.
