### ISSUE TITLE
Additional packages requested for alpine base

### ISSUE THREAD

**Issue by kmjohansen** [linuxkit/linuxkit#3106]
During the review for #3101, @rn requested that I open an issue for the packages that are missing from `linuxkit/alpine` such that those could be used instead of an upstream alpine image.  The PR originally used the `alpine-3.7` base image, but it's preferable to use a `linuxkit/alpine` base instead.

After looking through the list of packages already in the `linuxkit/alpine` base image, it appears that the following are used in #3101 but not yet present in the linuxkit base:

- build-base
- clang
- clang-dev
- clang-static
- flex-dev
- fts-dev
- iperf
- libedit-dev
- llvm
- llvm-dev
- llvm-static
- luajit-dev
- python

**Comment by rn** [comment]
These look reasonable to me. I probably won't have time to add them tomorrow but try to do so before the end of the week

**Comment by rn** [comment]
@kmjohansen why is `iperf` needed?

**Comment by kmjohansen** [comment]
@rn `iperf` is a test tool, and it's not strictly required.  I think we could omit it if need be.  (https://github.com/iovisor/bcc/blob/master/tests/python/CMakeLists.txt)

As far as Python goes, I can try building with Python 3 to see if it works.  A quick look at the bcc repo shows that they're building RH based releases against Python2, and Debian based releases against both Python 2 and 3.  I had mostly defaulted to Python 2 because building that way had worked for me in the past.

**Comment by rn** [comment]
these were added as part of https://github.com/linuxkit/linuxkit/pull/3112
closing
