### ISSUE TITLE
lcow: Slower pull times with newer kernels

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3120]
This was reported by @jhowardmsft on slack. He noticed that with newer kernel, specifically 4.14.53, the first pull on fresh data root is a lot slower than on older kernels, specifically he tested 4.14.23. Apparently the `mkfs.ext4` seems to take a lot longer. One suspicion is the inclusion of `0020-scsi-storvsc-Allow-only-one-remove-lun-work-item-to-.patch` and `0021-scsi-storvsc-Avoid-excessive-host-scan-on-controller.patch`, which were introduced with 4.14.30 as part of some other debugging effort around LCOW and disk hotplug.

This is issue is to track the debug

**Comment by rn** [comment]
We use the `docker image load -i 10layers.tar` test as it has the least movable parts (times are from three runs):
```
4.14.23: 21.5s - 21.1s
...
4.14.30: 21.7s - 21.2s
...
4.14.34: 21.0s - 21.8s
4.14.35: 21.1s - 21.5s
4.14.36: 100.2s - 107.7s
...
4.14.38: 99.6s - 103.6s
...
4.14.54: 96.9s - 112.9s 
```

So the regression seems to have happened between `4.14.35-linuxkit` and `4.14.36-linuxkit`. We introduced the patches mentioned above with `4.14.30-linuxkit`, so they are unlikely the culprit. Just to make sure, I removed the patches and rebuild 4.14.54-linuxkit and still see the 100+s for the `docker image load`.

**Comment by rn** [comment]
As a quick check I looked at boot times of 4.14.35 and 4.14.36 kernels using a quick hack [`hcsvm` tool](https://github.com/rn/test-utils/tree/master/win-hcsvm). Boot times of both kernels are comparable with 4.14.46, actually slightly faster, 5.8s vs 6.2s (note these are quite slow as serial console output seems to slow things down a little).

**Comment by kmjohansen** [comment]
May be coincidental, but 4.14.36 contained some ext4 correctness fixes as well as a change to the locking in writeback.  I only mention this because I had to do some looking through that same changelog in order to figure out what was going on with random number generation: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v4.14.36

**Comment by rn** [comment]
yeah, I saw that too. Haven't gotten around bisecting this one yet.

**Comment by jhowardmsft** [comment]
Closing now it's bumped to 4.19.x. Doesn't seem to repro any more.

**Comment by jhowardmsft** [comment]
Oh I don't seem to have permission to close my own issue in this repro.... but @rn or @justincormack probably can.
