### ISSUE TITLE
AWS support on Win2016 server

### ISSUE THREAD

**Issue by pnik073** [linuxkit/linuxkit#3152]
**Description**

I face issues when I run linuxkit on **AWS Windows2016** AMIs. I follow the instructions from your github or the blog I refer below. Nothing works. After all docker still runs with windows containers. What could go wrong?

**Steps to reproduce the issue:**
First Hyper-V is enabled:

```
Install-WindowsFeature Hyper-V -IncludeManagementTools -Restart
Get-WindowsFeature Hyper-V|ft InstallState, PostConfigurationNeeded
```
Then I follow step-by-step the [blog](https://blog.docker.com/2017/09/preview-linux-containers-on-windows/#comment-437417) by Rolf. Note that, before I run `Invoke-WebRequest` I need to run `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`. The docker run or pull fail, see below.

**Describe the results you received:**

```
PS C:\Users\Administrator> docker -H "npipe:////./pipe//docker_lcow" run -ti busybox sh
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
C:\Program Files\Docker\docker.exe: no matching manifest for windows/amd64 in the manifest list entries.
See 'C:\Program Files\Docker\docker.exe run --help'.
PS C:\Users\Administrator> docker -H "npipe:////./pipe//docker_lcow" run ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
C:\Program Files\Docker\docker.exe: no matching manifest for windows/amd64 in the manifest list entries.
See 'C:\Program Files\Docker\docker.exe run --help'.
```

**Describe the results you expected:**

I expect to pull and run the linux containers

**Additional information you deem important (e.g. issue happens only occasionally):**

Some more diagnostics:

```
PS C:\Users\Administrator> docker -H "npipe:////./pipe/docker_lcow" version
Client:
 Version:      17.06.2-ee-15
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   64ddfa6
 Built:        Mon Jul  9 23:33:36 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-15
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   64ddfa6
  Built:        Mon Jul  9 23:45:29 2018
  OS/Arch:      windows/amd64
  Experimental: true
PS C:\Users\Administrator> docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 17.06.2-ee-15
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2312.amd64fre.rs1_release.180607-1919)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 32
Total Memory: 488GiB
Name: EC2AMAZ-SQRMUK8
ID: KIQC:6T4O:RVSD:4KDA:AQB3:I36Q:44HS:TKW4:CI2A:NQPA:DOUS:4IDO
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by rn** [comment]
You need a more recent version of docker. I suggest to use the nightly builds.

Also, LCOW requires Hyper-V to work and that would require nested virtualisation if you run a Windows VM. AFAIK AWS currently does not support nested virt

**Comment by rn** [comment]
Oh and you almost certainly need a newer windows build, like RS4+

**Comment by pnik073** [comment]
I could install the v18. However, if the nested virtualization is still a requirement, I guess there is 
**no chance** for docker to work, indeed AWS does not support that. Do you confirm my previous statement?

**Comment by rn** [comment]
If AWS does not support nest virt LCOW will not work

**Comment by pnik073** [comment]
Thank you for the nice tool anyhow. Too bad for aws :(

**Comment by rn** [comment]
i think this can be closed as the questions have been answered

**Comment by pnik073** [comment]
Yes, AWS is a no go. Instead it worked out of the box on Azure.
