### ISSUE TITLE
Fail to run examples/docker-for-mac

### ISSUE THREAD

**Issue by l0rd** [linuxkit/linuxkit#3165]
**Description**

I fail to run the `docker-for-mac` example. In particular:
- The VM doesn't seem to boot successfully (`VFS: Cannot open root device "(null)" or unknown-block(0,0): error -6`, [full linuxkit run logs](https://gist.github.com/l0rd/8a5cca0ab1018b90a27429fb5ad35bfe))
- `docker -H unix://docker-for-mac-state/guest.00000948 ps` doesn't log anything and never returns

**Steps to reproduce the issue:**

- Install and run docker for mac (I've tested both stable and edge streams)
- Install linuxkit:
```bash
brew tap linuxkit/linuxkit
brew install --HEAD linuxkit
```
- Follow the [instructions to run the docker-for-mac example](https://github.com/linuxkit/linuxkit/blob/master/examples/docker-for-mac.md):
```bash
git clone git@github.com:linuxkit/linuxkit.git
cd linuxkit
linuxkit build examples/docker-for-mac.yml
linuxkit run hyperkit -networking=vpnkit -vsock-ports=2376 -disk size=4096M docker-for-mac
```
- In a separate shell:
```bash
cd linuxkit
docker -H unix://docker-for-mac-state/guest.00000948 ps 
```

**Describe the results you received:**
`linuxkit run` log --> https://gist.github.com/l0rd/8a5cca0ab1018b90a27429fb5ad35bfe
`docker -H unix://docker-for-mac-state/guest.00000948 ps ` hangs and doesn't log anything

**Describe the results you expected:**
As described [here](https://github.com/linuxkit/linuxkit/blob/master/examples/docker-for-mac.md):
```bash
$ docker -H unix://docker-for-mac-state/guest.00000948 ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Additional information you deem important (e.g. issue happens only occasionally):**
The default `linukit.yml`as well as `examples/docker.yml` build and run fine.

**Comment by rn** [comment]
thanks for reporting this. It seems that the final image is now quite large which means that the initrd would require a lot of memory. I would suggest to build a `iso-efi` instead of the kernel+initrd (Docker for Mac is also doing this).

```
linuxkit build -format iso-efi docker-for-mac.yml
```

You can then boot this with `-iso -uefi` if you have docker for mac installed.

**Comment by l0rd** [comment]
Thank you @rn. I have been able to run the docker-for-mac example with your suggestions. I am closing this issue and I have opened PR #3166 to updated the documentation if you think `iso-efi` should be the standard format to build and run the example.
