### ISSUE TITLE
Linuxkit getty password login is not working 

### ISSUE THREAD

**Issue by micemuni** [linuxkit/linuxkit#3167]
Hi Team,
I have created Linuxkit AMI by using YML file. In that YML i have mentioned the services to run in Linuxkit. 
I have included the getty service and enabled password login method. I used Hash of root password in shadow file and bind mount the shadow file to /etc/shadow. 

Post which created AMI, launched server, Logged into that as root and while switching to getty shell service " nsenter -a -t pid-getty sh " but its not asking password. I don't know why. 

I have to enable getty password login. Please help me on this issue.

**Comment by deitch** [comment]
I don't understand. If you set it up for `getty` with password login, then when you "Logged into that as root", didn't you need to use the password? Of course, it is possible that AWS put in your public key as well.

Either way, the password for `getty` is not about restricting whether or not you can run `nsenter` by requiring a password (I do not believe that is possible, except perhaps by requiring `sudo` if you are not root when running `nsenter`); it is about requiring a password when logging in via console.

Does that answer?

**Comment by micemuni** [comment]
Fixed the issue as refereed https://github.com/linuxkit/linuxkit/blob/master/examples/getty.yml link
