### ISSUE TITLE
Unable to connect to nginx in linuxkit 

### ISSUE THREAD

**Issue by jayakumarn** [linuxkit/linuxkit#3195]
Team ,
I understand linuxkit is for  advanced users  who knows linux well, I am here because i started to use linux recently and I am interested on docker , 
I tried linuxkit basic example to run nginx server . I can able to see the linuxkit is running from my local machine  but unable to reach its Ip or nginx server,
Things which i tried are below
linuxkit build https://raw.githubusercontent.com/linuxkit/linuxkit/master/linuxkit.yml
linuxkit run linuxkit

after running this i can able to see linxukit is up and running with the ip 10.0.2.15 . But how to validate the nginx is working . I tried wget 10.0.2.15 from other machine its not working
Can some one help me

**Comment by rn** [comment]
you need to configure networking and this dependents on which hypervisor you are using. There should be documentation in `docs/platform-*.md` for your platform, e.g., if you are on a Mac, take a look at `docs/platform-hyperkit.md`

**Comment by jayakumarn** [comment]
Thank you its worked. I refereed to https://github.com/linuxkit/linuxkit/blob/master/docs/platform-qemu.md
