### ISSUE TITLE
Create a bpftrace package

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3201]
[bpftrace](https://github.com/iovisor/bpftrace) was recently released. It creates a single binary (and some sample scripts) for tracing similar to dtrace.

It would be nice to have a package containing the binary and sample so that it can be included, for example in the init section.

Need to investigate, though, if it requires matching kernel header for compilation or use.

**Comment by simar7** [comment]
@rn:  Is the idea of making bpftrace a core package under ```pkg/``` or something else?

(I'm fairly new to this project but looking to pick up some low hanging items to play with)

**Comment by rn** [comment]
yes, that would be the idea.

**Comment by simar7** [comment]
Cool! I've started to hack on this and here's the progress so far: https://github.com/linuxkit/linuxkit/pull/3230

**Comment by simar7** [comment]
This can be closed now as https://github.com/linuxkit/linuxkit/pull/3230 is merged.
