### ISSUE TITLE
why linuxkit VM machine is asking to init swarm after reboot

### ISSUE THREAD

**Issue by micemuni** [linuxkit/linuxkit#3204]
Hi Team,
I have created Linuxkit AMI and launched server using this AMI. Then i did docker swarm init. 
If i rebooted this linuxkit VM then swarm is stopped, then again i have to init swarm. 

i have applied some terraform code, if i do docker service ls then nothing running. 
Then i did swarm init, but still docker service are not running. but before reboot i was running.

Please let me know any idea why after reboot no docker service is running / swarm also stopped.?

**Comment by justincormack** [comment]
Have you added an external disk? If you don't everything will not persist, seems like that might be the issue? It is very hard to tell without seeing your config.
