### ISSUE TITLE
Cannot build LCOW image on Windows with nightly Docker installed

### ISSUE THREAD

**Issue by Iristyle** [linuxkit/linuxkit#3207]
## Description

The LinuxKit source hardcodes an API version to 1.23 which doesn't work with Docker nightly builds for Windows.

Given a Windows host with the following info:

#### `docker info` output

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: master-dockerproject-2018-10-17
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.345)
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: puppet-lcow-t2
ID: VTNK:TOA3:VOIT:VOPB:7NSJ:S4G5:MAL6:ODD2:6XSB:JLI3:HGGM:4AYF
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

#### `docker version` info

```
Client:
 Version:           master-dockerproject-2018-10-17
 API version:       1.39
 Go version:        go1.11.1
 Git commit:        445df70c
 Built:             Wed Oct 17 23:50:31 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          master-dockerproject-2018-10-17
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.11.1
  Git commit:       533e07af
  Built:            Wed Oct 17 23:59:08 2018
  OS/Arch:          windows/amd64
  Experimental:     true
```

## Steps to reproduce the issue:

- Build LinuxKit binaries on Windows with `go get -v -u github.com/linuxkit/linuxkit/src/cmd/linuxkit`
- Using the built binary, try to build the [LCOW image](https://github.com/linuxkit/lcow)
  * Essentially this means running `linuxkit build lcow.yml` against https://github.com/linuxkit/lcow/blob/master/lcow.yml

## Describe the results you received:

The build fails with

```
Extract kernel image: linuxkit/kernel:4.14.35
Pull image: docker.io/linuxkit/kernel:4.14.35@sha256:3bef6da5bdd9412954b1c971ef43e06bcb1445438e336daf73e681324c58343c
[31mFATA[0m[0001] Failed to extract kernel image and tarball: Could not pull image docker.io/linuxkit/kernel:4.14.35@sha256:3bef6da5bdd9412954b1c971ef43e06bcb1445438e336daf73e681324c58343c: Error response from daemon: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

## Describe the results you expected:

With a fixed linuxkit (see below), the correct output is:

```
linuxkit build lcow.yml
Extract kernel image: linuxkit/kernel:4.14.35
Pull image: docker.io/linuxkit/kernel:4.14.35@sha256:3bef6da5bdd9412954b1c971ef43e06bcb1445438e336daf73e681324c58343c
Add init containers:
Process init image: linuxkit/init-lcow:0b6d22dcead2548c4ba8761f0fccb728553ebd06
Pull image: docker.io/linuxkit/init-lcow:0b6d22dcead2548c4ba8761f0fccb728553ebd06@sha256:6756c19a2be2f68ee20f01bf5736c3e6f24ddb282345feb2d7ac5c3885972734
Process init image: linuxkit/runc:v0.5
Pull image: docker.io/linuxkit/runc:v0.5@sha256:9782c306200ad7d3dcbe52ac7b01f2594b9e970c46e002f6a5af407dc8c24165
Add files:
  etc/linuxkit.yml
Create outputs:
  lcow-kernel lcow-initrd.img lcow-cmdline
```

## Additional information you deem important:

I've forked the code here to my account. See https://github.com/Iristyle/linuxkit/commit/4daf9158491bb3effd0a258c2231c042921cc780 where I've changed the `1.23` value to `1.24` in the moby tool source to make builds proceed properly. The file in question lives at https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/moby/docker.go#L177 but previously lived at https://github.com/moby/tool/blob/master/src/moby/docker.go#L164 before it was vendored into linuxkit.

Normally I think that a user would be able to supply a `DOCKER_API_VERSION` environment variable to override this without patching linuxkit source, but since the code sets the environment variable without checking for one first, that won't work.

My code was just a spike to get things working - I'll leave it up to you folks to decide how to address this in a more robust way.

Thanks!

**Comment by justincormack** [comment]
Ah yes, I forgot Windows has different API versions. We only use the most basic API features so bumping to 1.24 is fine. Do you want to open a pull request?

**Comment by Iristyle** [comment]
This is fixed by https://github.com/linuxkit/linuxkit/pull/3317
