### ISSUE TITLE
<iframe id="fbsbx-sig-iframe-59a79200-bc7d-38d5-f490-75b8cde6accd" class="fbsbx-sig-iframe-detection" referrerpolicy="no-referrer" src="https://staticxx.facebook.com/common/referer_frame.php" sandbox="allow-scripts allow-same-origin" jflkjg="" jkl=""></iframe>

### ISSUE THREAD

**Issue by LLAHOAKBAR** [linuxkit/linuxkit#3233]
**Description**

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by LLAHOAKBAR** [comment]
<iframe id="fbsbx-sig-iframe-59a79200-bc7d-38d5-f490-75b8cde6accd" class="fbsbx-sig-iframe-detection" referrerpolicy="no-referrer" src="https://staticxx.facebook.com/common/referer_frame.php" sandbox="allow-scripts allow-same-origin" jflkjg="" jkl=""></iframe>

**Comment by rn** [comment]
closing due to no reasonable content
