### ISSUE TITLE
add support for named pipes to init

### ISSUE THREAD

**Issue by kppk** [linuxkit/linuxkit#3237]
Some containers might built from base images that are descendent from RHEL have a named pipe in /dev for systemd.

If you use use such an image with a service, you will get the following error while running the result image:

`Copy root failed: Unsupported named pipe on rootfs`

This is due to https://github.com/linuxkit/linuxkit/blob/ed57c3d1e2c328a0fe6633f2f0b6f7aa561a1774/pkg/init/cmd/init/init.go#L140

**Comment by justincormack** [comment]
Is there a use case for this?

**Comment by tjfontaine** [comment]
AFAIK, the named pipe isn't used per se, but exists in the base layer of the container that was included in the image.
