### ISSUE TITLE
Remove 4.4.x kernels?

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3250]
We currently have four LTS kernels (4.19.x, 4..14.x, 4.9.x, and 4.4.x).

I propose to remove support for 4.4.x.

Are there any objections? If not, I'll remove it early 2019.

**Comment by justincormack** [comment]
As 4.9 has longer term support than 4.4 this sounds good to me; also we largely used 4.4 before release of LinuxKit as open source.
