### ISSUE TITLE
Building Linuxkit image with criu installed to use with Docker for mac

### ISSUE THREAD

**Issue by arashd** [linuxkit/linuxkit#3263]
I've been trying to get the checkpoint/restore experimental feature of docker to work on a mac. 

After turning on the experimental feature, I see:

```
$ docker checkpoint create 53fc5dcc6fc9 checkpoint1
Error response from daemon: Cannot checkpoint container 53fc5dcc6fc9: runc did not terminate sucessfully: CRIU version check failed: exec: "criu": executable file not found in $PATH path= /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/53fc5dcc6fc9376f1cf067015750ce67cfbac1863a86b73593cc3dbab974223f/criu-dump.log: unknown
```

criu doesn't exist on the vm that docker for mac uses by default. I am pretty sure I need to install CRIU on the d4m linux vm. I attempted to use this approach (https://github.com/boucher/criu-for-mac), but realized it doesn’t work since docker for mac, in its newer versions, uses a `.iso` file built with Linuxkit for its vm, and the image has a read-only filesystem.

```
$ docker run --rm -it --privileged --pid=host boucher/criu-for-mac
sh: criu: not found
ERROR: Unable to lock database: Read-only file system
ERROR: Failed to open apk database: Read-only file system
```

The closest I could get was this [post](https://medium.com/@notsinge/making-your-own-linuxkit-with-docker-for-mac-5c1234170fb1), which attempts to pull out some of the missing pieces out of the existing docker for mac image: https://github.com/singe/linuxkit-for-mac.

Is there a better way of doing this that isn’t as brittle, and has someone made the above work?

Would appreciate any help.

**Comment by justincormack** [comment]
You can probably copy the criu binary into the `docker` container (which is writeable, as it has a tmpfs overlay).

**Comment by rn** [comment]
Try what Justin suggested. Otherwise, I'm closing this issue as this is not related to linuxkit itself. The Docker Desktop team uses Linuxkit to build their own images. If the Docker Desktop linuxkit image is missing some binaries, please file an issue in the appropriate tracker.

**Comment by arashd** [comment]
@rn agreed, I'm opening an [issue](https://github.com/docker/for-mac/issues/1059#issuecomment-454189645) there. But I'd still appreciate understanding how to use linuxkit for this. I'm not sure, after having read the docs, how to include a binary myself when building with linuxkit on my machine.

@justincormack appreciate the quick response. I'm a bit of a newbie to docker internals. I'm not sure I understand which docker container the binary should be copied into. Looking at `docker-for-mac.yml` in the examples directory of this repo, I see containers running as services in the vm. Should it be copied into the `docker-dfm` image there? How should it be copied into the vm itself when building with linuxkit?

**Comment by justincormack** [comment]
the `docker-for-mac.yml` no longer corresponds to how Docker Desktop is built. You can get into the docker container with `docker run -it --privileged --pid=host justincormack/nsenter1` and eg then curl a binary into the container.
