### ISSUE TITLE
Update to Alpine 3.9

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3282]
Alpine 3.9 was released earlier this week. Update the alpine base to it and then cut a new release

**Comment by masterzen** [comment]
Indeed, there hasn't been any release since last August (v0.6).
it would be helpful to me that some of the fixes I contributed end up published as a release :)

**Comment by rn** [comment]
split this issue into update to 3.9 (which is done, so closing this). A new release is now tracked in https://github.com/linuxkit/linuxkit/issues/3313
