### ISSUE TITLE
Mac + QEMU: no init or containerd output on the console

### ISSUE THREAD

**Issue by djs55** [linuxkit/linuxkit#3301]
**Description**

`linuxkit run qemu` prints the kernel console output but there is nothing from `init` or `containerd`, even after following the advice in the [FAQ](https://github.com/linuxkit/linuxkit/blob/master/docs/faq.md) and replacing the console with `ttyS0`

**Steps to reproduce the issue:**

in the `linuxkit/examples` directory I adjusted the `console` as recommended by the FAQ:

```
diff --git a/examples/getty.yml b/examples/getty.yml
index 0ee6f5965..a72de326a 100644
--- a/examples/getty.yml
+++ b/examples/getty.yml
@@ -1,6 +1,6 @@
 kernel:
   image: linuxkit/kernel:4.19.26
-  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
+  cmdline: "console=ttyS0"
 init:
   - linuxkit/init:005807f5c6a74e23f485a6d1657818bdccb70cd0
   - linuxkit/runc:606971451ea29b4238029804ca638f9f85caf5af
```

I then ran
- `linuxkit build -format iso-bios getty.yml`
- `linuxkit run qemu -iso ./getty.iso`

**Describe the results you received:**

The kernel output is present but there is nothing from userspace: no `init` or `containerd` output.

**Describe the results you expected:**

I expected `init` and `containerd` output and then a `getty`.

**Additional information you deem important (e.g. issue happens only occasionally):**

If I change the kernel command-line to have `console=tty0` then there is no kernel output either :) So I think `console=ttyS0` makes the kernel output work, but not the `init` or `containerd` output.

Adding the `-gui` parameter makes the kernel output appear in a GUI window but there is still no userspace output.

This is with
```
$ qemu-system-x86_64 --version
QEMU emulator version 3.1.0
Copyright (c) 2003-2018 Fabrice Bellard and the QEMU Project developers
```
and
```
$ ../bin/linuxkit version
linuxkit version v0.6+
commit: ff9a659213612c46428d0cf835e6c7be02ef9363
```

I switched back to the LinuxKit 0.6 binaries and images but it made no difference.

**Comment by djs55** [comment]
Actually the problem might be more fundamental -- the `emu-system-x86_64` process is using only 120MiB of RAM and is spinning on the CPU. I added a `qcow2` disk and the `format`, `mount`, `swap` `unboot` runes from `swap.yml` but the `qcow2` file appears empty. So the kernel might have crashed. For reference the last thing it said was:
```
[    1.180626] ACPI: Power Button [PWRF]
[    1.184450] ACPI: PCI Interrupt Link [GSIG] enabled at IRQ 22
[    1.195594] ACPI: PCI Interrupt Link [GSIH] enabled at IRQ 23
[    1.200637] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    1.240549] 00:04: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[    1.245038] Non-volatile memory driver v1.3
[    2.082718] tsc: Refined TSC clocksource calibration: 3099.741 MHz
[    2.087727] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x2cae5327ec5, max_idle_ns: 440795246643 ns
[    3.101915] clocksource: Switched to clocksource tsc
```
I took out the `-machine q35,accel=hvf:tcg` from the command-line to switch back to emulation but no difference. Maybe I'll try an older QEMU.

**Comment by justincormack** [comment]
I just built an run the top level `linuxkit.yml` and it works fine for me with `QEMU emulator version 3.1.0` (on up to date MacOS).

**Comment by djs55** [comment]
It's working fine for me at home with
```
$ qemu-system-x86_64 --version
QEMU emulator version 2.12.0
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
$ linuxkit version
linuxkit version v0.6+
commit: 4968390a927d00c997693064639a1c4a912a6aff
```
:/

**Comment by djs55** [comment]
I'm assuming there must be something wrong with the installation on my main laptop. I'll close this for now and re-open when I learn something new.
