### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3313]
With the update to Alpine 3.9 done, we should cut a new release.

for this to happen, it would be good to resolve https://github.com/linuxkit/linuxkit/issues/3295 first. Ideally we resolve https://github.com/linuxkit/linuxkit/issues/3296 as well, but I wouldn't block the release on it.

**Comment by deitch** [comment]
Agreed. #3295 is in process, actually close to done. Hold out a day or so and let's see if we can wrap it in.

**Comment by rn** [comment]
release v0.7 was cut. closing
