### ISSUE TITLE
FATAL: API 1.23 not compatible (Docker)

### ISSUE THREAD

**Issue by joaquinito01** [linuxkit/linuxkit#3316]
**Description**
Docker Build not working in LinuxKit.

**Steps to reproduce the issue:**
1. Install Docker Enterprise.
2. Build a Docker Image and i can see this error:
K:\Nueva carpeta (2)>linuxkit build -format vhd docker.yml
Add service containers:
  Create OCI config for docker
[31mFATA[0m[0000] Failed to create OCI spec for docker: Error response from daemon: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

**Describe the results you received:**
K:\Nueva carpeta (2)>linuxkit build -format vhd docker.yml
Add service containers:
  Create OCI config for docker
[31mFATA[0m[0000] Failed to create OCI spec for docker: Error response from daemon: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

**Describe the results you expected:**
K:\Nueva carpeta (2)>linuxkit build -format vhd docker.yml
Add service containers:
  Create OCI config for docker
[31mFATA[0m[0000] Failed to create OCI spec for docker: Error response from daemon: client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by justincormack** [comment]
Ok, will update.

**Comment by justincormack** [comment]
See #3317
