### ISSUE TITLE
Cross compilation for arm64

### ISSUE THREAD

**Issue by dapopescu** [linuxkit/linuxkit#3321]
I am trying to compile a Linux kernel for arm64 using the config-5.0.x-aarch64 using make build_5.0.x.
My current operating system is Ubuntu 18.04, so I had to replace the $(uname -m) manually in the Dockerfile with aarch64 to trigger the right commands in the Makefile. 
I also installed arm-linux-gnueabi-gcc and added to the make commands ARCH=arm64 CROSS_COMPILE=arm-linux-gnueabi- in the Dockerfile. 
However, I get the error  arm-linux-gnueabi-gcc: not found. 
My question is: what are the exact steps to achieve my goal?

**Comment by rn** [comment]
The tooling is not set up at all for cross-compilation. Even if it were, the resulting kernel package would be a x86 docker images and `linuxkit build` (for similar reasons) does not allow cross-build either. We compile all the arm64 kernels natively on arm64 machines on packet.net but other options (such as AWS A1 instances) should work too.

**Comment by dapopescu** [comment]
Thank you, I used AWS A1 instances.
