### ISSUE TITLE
Unclear documentation about booting on Raspberry Pi

### ISSUE THREAD

**Issue by dapopescu** [linuxkit/linuxkit#3324]
Hi,

I built an example minimal.tar for rpi3 as described in the documentation, but it is unclear to me what are the next steps. The documentation says extract the archive on a formatted SD card. I did so, but the image did not boot. Could you please elaborate on this part?

Thank you

**Comment by rn** [comment]
do you have the serial console setup? It is on the GPIO pins and there are adapters to USB, which I used

**Comment by dapopescu** [comment]
I have set it up today, I do not see any boot sequence, just two random
characters in the beginning.

How should the SD card be formatted? I currently have two partitions (boot
fat32 and a second ext4 one), and I copied the contents of the minimal.tar
archive on the first partition.

**Comment by rn** [comment]
I have the first partition as fat32 as well (IIRC) and just untarred the tar file on that partition. It has been a while since I did this (10+ months ago) so i'm not sure if this bit rotted. When I developed this i used both serial console and a monitor. Have you tested with a known working SD with a standard distro and checked that serial and monitor output works?

**Comment by dapopescu** [comment]
I tried on the same SD card Ubuntu 18.04 for Raspberry Pi and it worked
(monitor, keyboard, serial console), so this is not the issue.

**Comment by nakato** [comment]
What do your RPi LED's do?

I just tried on my RPi-3 B+ and saw the power LED turn on, go off, then ACT blink 8 times indicating that the firmware needs to be updated.

**Comment by dapopescu** [comment]
When I connect the monitor, I get the rainbow square, which I read means
that the kernel is not booting.

**Comment by dapopescu** [comment]
Yes, I also see the ACT blink 8 times. How do I update the firmware then?

**Comment by dapopescu** [comment]
So the LEDs do the following:
1. The power led (red) turns on, then goes off
2. The ACT led (green) blinks 8 times, four times slower, and then four
times quicker.

**Comment by nakato** [comment]
The firmware is available from https://github.com/raspberrypi/firmware

**Comment by dapopescu** [comment]
Thank you, it booted after I copied the contents of the firmware/boot folder.
