### ISSUE TITLE
RPi3 image eth0 does not exist

### ISSUE THREAD

**Issue by dapopescu** [linuxkit/linuxkit#3343]
Hi,

I added to the config file the lines for enabling networking with USB connected network interface from the RPi3 documentation (the ones for modprobe smsc95xx). I booted the image and ran lsmod, where I can see the module smsc95xx being already loaded. However, if I run ifconfig -a, I see only the loopback and two virtual interfaces.
I tried modprobe smsc95xx again, but I get the error: "can't change to /lib/modules: no such file or directory". I checked dmesg, where I saw the message "usbcore: registered new interface smsc95xx", but only this message is about the module.

Any idea what might be the cause of this behaviour and how can I get the ethx interface?

Thank you,
Diana

**Comment by rn** [comment]
hard to debug remotely, is there anything interesting in dmesg? How do you log in? everything is namespaced so you may not see the network interface. I use this YAML file https://github.com/rn/linuxkit-dnscrypt/blob/master/dnscrypt-proxy-aarch64.yml on my RPI3 and it works (with an older kernel, of course)

**Comment by dapopescu** [comment]
I don't have access now to the full dmesg log.
I just put getty in the services section, and I used the prompt I saw on
the screen (connected via HDMI) to run the commands that I mentioned in the
previous email.

Thank you for the link! I do not have the sysctl in the onboot section (and
I removed dhcpd since it was hanging, I want to set a static IP address
anyway for now). In the services section I just have getty. The usb storage
works (I plugged in a stick and could see the files and write a new file to
it).

**Comment by dapopescu** [comment]
I looked at the config you sent me and added sysctl, ntpd, sshd, but the usb_storage and net rules were the same (just different versions). I unfortunately still do not see the network interface.

I looked again at the dmesg log. What I noticed is that for the usb_storage module, I can see in the log something about /dev/sda after the device is registered (and I can find the device and it works), but for the smsc95xx I can't find anything (and from what I saw it should say something about eth0). 

Regarding namespaces, after the image boots, I get a message saying that "this namespace may not be root, try ctr -n services.linuxkit".

Also, I have to mention that the RPi is 3b+.

**Comment by dapopescu** [comment]
Hi,
I used the same config to build a x86 image which I ran in qemu. I noticed that the prompt says
(ns: getty) linuxkit-829d5cc94166 and I can see eth0 (although not the smsc95xx module)
while in the RPi image I had (ns:getty) (none). Is this related to the namespaces you mentioned and why I don't see the interface?

Thank you,
Diana

**Comment by dapopescu** [comment]
Thank you, using your patch I can see the interface now.
