### ISSUE TITLE
Different cmdline needed for baremetal and qemu

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#3354]
I need to build my linuxkit system with different cmdline values.

To boot into a shell with qemu I need:
```
console=ttyAMA0,115200 console=tty0 highres=off console=ttyS0
```

But to boot with baremetal notebook I need to build with a different cmdline:
```
cmdline: "console=tty0 console=ttyS0 console=ttyAMA0,115200"
```

Looks like `highres=off` isn't the problem... so order of multiple `console=` could be the problem? Or should multiple console values work fine?

Would be great to have just one cmdline in my YML file at build time. 
Optional would be great to build with baremetal needed cmdline and add / modify `linuxkit run qemu` "append" / cmdline to get it work with qemu too?

Tested with latest linuxkit build today

**Comment by justincormack** [comment]
Yeah, unfortunately in some use cases this seems to be a problem; mostly the multiple `console=` lines work ok. I don't know that we can fix this...

**Comment by pwFoo** [comment]
@justincormack 
Ok, thanks. I take a deeper look into my setup 👍
