### ISSUE TITLE
Custom kernel compilation fails because of missing openssl/bio.h

### ISSUE THREAD

**Issue by dapopescu** [linuxkit/linuxkit#3356]
Hi,
I modified the config for the kernel using menuconfig following the documentation from https://github.com/linuxkit/linuxkit/blob/master/docs/kernels.md and then managed to build the kernel successfully. 

I now require to enable more options, which I did in a similar way, but this time when I build the kernel (make build_4.19.x) I get the following error: 

HOSTCC  scripts/extract-cert
scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.host:90: scripts/extract-cert] Error 1
make[1]: *** Waiting for unfinished jobs....

for aarch64. From what I've seen, the libssl-dev is installed.

Any ideas what might cause the issue?

Thank you,
Diana

**Comment by rn** [comment]
maybe you need to add `openssl-dev` to the list of packages installed for the kernel compile

**Comment by dapopescu** [comment]
Thank you, yes, this was the problem, I first tried adding libssl-dev to the Dockerfile, but it seems I got the name of the library wrong.
