### ISSUE TITLE
Adding new package from the tool/alpin/packages list to image

### ISSUE THREAD

**Issue by dapopescu** [linuxkit/linuxkit#3364]
Hi,

I am trying to include in my image some tools that are listed in the tools/alpin/packages list. I could not find in the documentation how I should specify them in the YAML file. Or is there another way to add them to the image?

Thank you,
Diana

**Comment by rn** [comment]
you can't really specify them in the YAML you'd need to modify or create a package to add them to that package and then include it in your YAML

**Comment by dapopescu** [comment]
Thank you, I actually did this first, but I still can't see the utility. 
I am trying to add tcpdump. I modified the ip package with
RUN apk add --no-cache --initdb -p /out \
    alpine-baselayout \
    bash \
    busybox \
    iproute2 \
    iptables \
    ebtables \
    ipvsadm \
    bridge-utils \
    musl \
    tcpdump \
    wireguard-tools
and then I recompiled it, I see:
....
(21/26) Installing libpcap (1.9.0-r1)
(22/26) Installing tcpdump (4.9.2-r4)
....

and then I included the ip package in the YAML file (with the generated hash for this package). 
But tcpdump is not installed (I get command not found when I try it in the image).

**Comment by rn** [comment]
each service or onboot entry will run in it's own namespace/container and that includes it's root filesystem. So if you add tcpdump to the ip package then the utility is only present in the IP container. you likely have a getty or ssh container to which you login in and you'd need to add tcpdump to there, or if you added it to a service, you can also use `ctr` to exec into the running service
