### ISSUE TITLE
USB Access in Moby VM

### ISSUE THREAD

**Issue by rajasec** [linuxkit/linuxkit#3382]
**Description**
I have Windows 10, where I've installed DOcker Desktop where Moby VM using the Hyper V containers are started.

**Steps to reproduce the issue:**

**Describe the results you received:**
Inserted the drive in Laptop, not able to view the USB in Moby Linux VM

**Describe the results you expected:**
Able to access the USB in Moby Linux VM

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
I'm not sure if Hyper-V supports USB pass through, but in any case, this first would need to be supported in Docker Desktop for Windows and not LinuxKIt. Please open an issue on the Docker Desktop for Windows tracker. Closing here.
