### ISSUE TITLE
Update alpine base to alpine 3.11

### ISSUE THREAD

**Issue by guillaumerose** [linuxkit/linuxkit#3383]
Alpine 3.10 is now out. We can bump base images (and potentially do a release ?)

Thanks!

**Comment by rn** [comment]
This typically takes several days depending on how many changes there are and how many packages and other code needs adjusting. I'll do it once I have a spare few days but might take a while

**Comment by bjwschaap** [comment]
I would like to help submit a PR for this. But I'm not entirely sure on how to approach this, since it's a multi-stage thing; first a new linuxkit/alpine should be built and pushed, and then all references to this image should be updated using the new hash.

I have done this exercise on my local machine, and was able to build linuxkit and all pkgs with a 3.10 based linuxkit/alpine image. I was also able to build linuxkit-k8s using this new alpine version/image.

Could you please provide me with a suggested approach on how/what to submit in a PR?

**Comment by rn** [comment]
Thanks for the offer. The steps are more or less identical to the initial steps of a release (see https://github.com/linuxkit/linuxkit/blob/master/docs/releasing.md). The code changes themselves (PRs) is actually not the time consuming part. It's a lot of cut and past of command snippets at the moment. However, all packages and tools need to be rebuild and pushed for three different architectures and this is currently a manual and time consuming process.

**Comment by bjwschaap** [comment]
Ok, that's clear. Sorry I can't/couldn't be of more help...

**Comment by the-maldridge** [comment]
Alpine 3.10 will soon be the previous version as the merge window for 3.11 is/has closing/closed.  Assuming that the images provided by LinuxKit are no longer being actively updated (this project has the hallmarks of abandonware tbh), is it possible to just use the core tooling and use images I provide myself for all other functions?

**Comment by rn** [comment]
Updating the Alpine Linux base is at least a full day effort and maybe more if there are breaking changes. Simply didn't have the time to do this the past few month. Will try to update to 3.11 soon.

@the-maldridge the core tooling is pretty independent of the packages in the LinuxKit repository so you can use your own packages.

**Comment by the-maldridge** [comment]
@rn  Wow thanks for the reply and a Happy New Year to you!  I noticed the effort required to do the rebuild when trying it on my own.  I now have a 3.11 branch that builds, but doesn't actually appear to work.  I'm digging around now to try and find an IRC channel/users group somewhere.

**Comment by the-maldridge** [comment]
@rn this ticket is long obsolete, perhaps you can close it?

**Comment by rn** [comment]
yeah, thanks for the reminder
