### ISSUE TITLE
Nightly Links Broken

### ISSUE THREAD

**Issue by Silvenga** [linuxkit/linuxkit#3393]
**Description**

The README (https://github.com/linuxkit/lcow/blob/master/README.md) gives instructions on how to install nightly builds of Docker, however those links are no longer valid. 

```
404 https://master.dockerproject.org/windows/x86_64/dockerd.exe
404 https://master.dockerproject.org/windows/x86_64/docker.exe
```

Are there new locations for nightly builds? I haven't been able to find any via the Docker docs.

**Comment by Silvenga** [comment]
And as I post this I found a new link - https://master.dockerproject.com/windows/x86_64/docker.zip

I can make a pr if I can get a confirmation that this is the new location.

**Comment by justincormack** [comment]
Yes that looks correct it switched to a zip file once there was additional files included.

**Comment by Silvenga** [comment]
👍 I'll make that pr.
