### ISSUE TITLE
s390x kernel compile fails for 5.2.x

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3412]
Compiling the 5.2.x kernel on s390x I get.
```
  AR      drivers/virtio/built-in.a
  CC [M]  drivers/scsi/libiscsi.o
  CC [M]  drivers/scsi/libiscsi_tcp.o
  CC [M]  drivers/scsi/iscsi_tcp.o
  CC [M]  drivers/scsi/hpsa.o
  CC      drivers/scsi/scsi_sysfs.o
  AR      drivers/scsi/built-in.a
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.o
  MODINFO modules.builtin.modinfo
ld: kernel/kallsyms.o: `kallsyms_markers' non-PLT reloc for symbol defined in shared library and accessed from executable (rebuild file with -fPIC ?)
ld: final link failed: bad value
make: *** [Makefile:1054: vmlinux] Error 1
The command '/bin/sh -c make -j "$(getconf _NPROCESSORS_ONLN)" KCFLAGS="-fno-pie" &&     case $(uname -m) in     x86_64)         cp arch/x86_64/boot/bzImage /out/kernel;         ;;     aarch64)         cp arch/arm64/boot/Image.gz /out/kernel;         ;;     s390x)         cp arch/s390/b
oot/bzImage /out/kernel;         ;;     esac &&     cp System.map /out &&     ([ -n "${DEBUG}" ] && cp vmlinux /out || true)' returned a non-zero code: 2
Makefile:267: recipe for target 'build_5.2.x' failed
make: *** [build_5.2.x] Error 2
```

@alicefr any idea?

**Comment by alicefr** [comment]
@rn let me try to reproduce it.

**Comment by rn** [comment]
The PR with the 5.2 support is https://github.com/linuxkit/linuxkit/pull/3413

I disabled s390x support there for 5.2 for now

**Comment by alicefr** [comment]
@rn I'm able to reprodue the issue. If I use alpine container it's broken, but if I compile the kernel on my ubuntu host with the same config, the builds is successful. I'm not sure if this could be a problem with gcc from alpine.

**Comment by alicefr** [comment]
I need to correct my previous comment. It fails also on my ubuntu host system if I compiles with `KCFLAGS="-fno-pie"`

**Comment by alicefr** [comment]
@rn the breaking combination seems to be: `CONFIG_RELOCATABLE=y` together with `KCFLAGS="-fno-pie"`. If I turn the option off, it compiles without problems. I also managed to compile the kernel with that option adding additionally the option `-fPIC`.

**Comment by rn** [comment]
@alicefr thanks for the debug. I will try that on the next kernel update
