### ISSUE TITLE
targets/{justin|riyaz} metadata is nearing expiry, you should re-sign the role metadata

### ISSUE THREAD

**Issue by hyperized** [linuxkit/linuxkit#3447]
**Description**

When building linuxkit images I get:

```
WARN[0052] targets/justin metadata is nearing expiry, you should re-sign the role metadata
WARN[0052] targets/riyaz metadata is nearing expiry, you should re-sign the role metadata
```
For at least:

* linuxkit/sysfs:v0.7
* linuxkit/openntpd:v0.7
* linuxkit/node_exporter:v0.7

Since v0.7 is the latest major in most cases, it seems they might all soon trigger this warning.

**Steps to reproduce the issue:**
linuxkit build -format kernel+initrd build.yml

**Describe the results you received:**
WARN[0052] targets/{justin|riyaz} metadata is nearing expiry, you should re-sign the role metadata

**Describe the results you expected:**
No warnings.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by thaJeztah** [comment]
ping @rn @justincormack

**Comment by rn** [comment]
These messages are benign but will probably be fixed in any case once we do another release

**Comment by steeve** [comment]
Still happening, is there a release scheduled? Thanks!

**Comment by rn** [comment]
Not sure if if a release will fix this. We currently can't release as we lost access to s390x systems but are working on getting access back

@justincormack knows more about the the signing and we might have to update the keys...

**Comment by steeve** [comment]
Thank you for the quick update. Much appreciated!

**Comment by StefanScherer** [comment]
I thought about a self hosted runner, but unfortunately only X64, ARM, and ARM64 are supported https://help.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

**Comment by ChrisSalisbury** [comment]
In addition to a bunch of warnings, I am now also getting
```
ERRO[0273] Metadata for targets/riyaz expired
ERRO[0293] Metadata for targets/justin expired
```

**Comment by ChrisSalisbury** [comment]
Here's the workaround I'm using:
```
timedatectl set-ntp 0
timedatectl set-time 2020-05-25
linuxkit build my.yaml
timedatectl set-ntp 1
```
If anyone has something better, please let me know.

**Comment by hyperized** [comment]
@ChrisSalisbury To be fair, we decided to abandon our project based on linuxkit altogether based partially because it seems unmaintained (https://github.com/linuxkit/linuxkit/tree/master/reports). This issue being sort of a canary for us.

**Comment by steeve** [comment]
@hyperized last commit is 18 days ago

**Comment by hyperized** [comment]
@steeve thank you for that information, but this is not the _only_ factor here. Maybe more detail can be found at: https://github.com/linuxkit/linuxkit/issues/3437#issuecomment-549814242. Maybe I should not say unmaintained, should I say undermaintained?

**Comment by ChrisSalisbury** [comment]
@hyperized this issue does definitely seem to point to an undermaintained project -- what are you using instead?

**Comment by ChrisSalisbury** [comment]
@steeve, some alternatives I am currently considering: k3os, rancheros.
Some alternatives I have ruled out for now: photon, atomic, containeros, chromiumos.

I'd be interested to hear from others about what they are using if linuxkit isn't meeting their needs.

**Comment by rossgrady** [comment]
@rn: > Not sure if if a release will fix this. We currently can't release as we lost access to s390x systems but are working on getting access back
> 
> @justincormack knows more about the the signing and we might have to update the keys...

Are you still blocked by s390x access?

**Comment by razum2um** [comment]
Trick with setting time back into the past doesn't work anymore, because `2020-08-12` seems to be not enough, and later:

```
Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/70/....": 
x509: certificate has expired or is not yet valid: current time ... is before 2020-08-12T00
```

**Comment by attila123** [comment]
@justincormack could you please kindly help here

```
ERRO[0009] Metadata for targets/justin expired          
WARN[0009] Error getting targets/justin: targets/justin expired at Thu Jun 11 16:05:18 CEST 2020 
WARN[0010] Error getting targets/rolf: valid signatures did not meet threshold for targets/rolf 
```
Output is from 'DOCKER_CONTENT_TRUST=1 docker pull docker.io/linuxkit/kernel:5.4.39'.

I just wanted to do `linuxkit build -format raw-bios linuxkit.yml`. I am new to linuxkit.

I found this idea for `DOCKER_CONTENT_TRUST=1 docker pull ...` at https://github.com/linuxkit/linuxkit/issues/2838  
After that searched for `targets/justin` and got here.

**Comment by attila123** [comment]
Brute force workaround/hack for the Docker Content Trust issue by totally disabling DCT for linuxkit.  
Disclaimer: you must understand and accept the security implications and know what you are doing, otherwise do not do this ...  
This is just for entertainment purposes, do not use in production :)

So I edited src/cmd/linuxkit/moby/build.go deleted most of the code from enforceContentTrust() (probably comment out would be also fine) and just let it return false always:

```
func enforceContentTrust(fullImageName string, config *TrustConfig) bool {
	return false
}
```

Also just deleted src/cmd/linuxkit/moby/trust_test.go

With some help at https://github.com/linuxkit/linuxkit/issues/3599 I was able to build linuxkit.  
With the resulting linuxkit binary (in `bin` directory) I was finally able to execute `linuxkit build -format raw-bios linuxkit.yml` (took a few minutes).  
I tested the resulting image with VirtualBox: first converted the image to vdi: `VBoxManage convertfromraw linuxkit-bios.img linuxkit-bios.vdi`. Then it was quite straightforward to add this new image to VirtualBox and create a new VM using this image. It booted up fine.

**Comment by edvinerikson** [comment]
Seems there is an easy fix by removing the `trust:` section in `linuxkit.yml`. Perhaps not ideal though.

**Comment by rn** [comment]
we recently removed docker content trust from Linuxkit. so if you upgrade the `linuxkit` binary the warning should be gone

**Comment by edvinerikson** [comment]
You're right. I created a PR that updates `make install` to copy from the new bin directory. Seems I had an old binary on my PATH. #3659
