### ISSUE TITLE
Remove support for 4.9.x and 4.14.x kernels

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3449]
Proposing to remove support for 4.9.x and 4.14.x kernels.
- 4.9.x is ancient and has not had several security fixes back-ported.
- With 5.4.x the new LTS and 4.19.x as a mature LTS, we don't really need 4.14.x anymore.

**Comment by justincormack** [comment]
Hmm, 4.14 is the long long term support kernel, so maybe there is a case to keep it. Definitely can remove 4.9. I think we should get rid of 4.19 sooner maybe, although desktop currently uses it.
