### ISSUE TITLE
[Question] Additional info / files passed to service directory?

### ISSUE THREAD

**Issue by pwFoo** [linuxkit/linuxkit#3474]
Hi,

is it possible to add files to the bundle directory (for example `/containers/services/<NAME>`).
I play with custom init part and try to add a script outside of the service rootfs to handle by init and outside of the container rootfs.
Similar to runtime.json, but a custom file...

**Comment by justincormack** [comment]
I think we should add `files` in each container section. You can add them by adding to the `/containeres/name/...` path, or by using bind mounts in the runtime section now (which allows local paths), both of which are less convenient.

**Comment by pwFoo** [comment]
Ok. I replaced linuxkit init with a custom one (rustysd, crun, shell script...). So I think I can't parse / use the runtime.json file at the moment. I moved the overlayfs part to a simple shell init script to get it done.

**Comment by pwFoo** [comment]
At the moment add files to /container/*/* would be fine. Thanks!
