### ISSUE TITLE
perf package fails to build with alpine 3.11

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3498]
While updating `linuxkit/alpine` to 3.11, the `kernel-perf` package fails to builds. The primary reason seems to be that alpine 3.11 is missing `libz.a` and we try to build a statically linked `perf` binary.

we will temporarily disable the `perf` build. An alternative would be to compile our own `libz`

**Comment by thaJeztah** [comment]
From slack:

> we normally ship the static library in separate package. you can use `zlib-static`
> reason for splitting static is that alpine itself normally dont use it and sometimes the static lib can be very big
