### ISSUE TITLE
Incorrect location of provider_cdrom in the metadata package

### ISSUE THREAD

**Issue by giggsoff** [linuxkit/linuxkit#3501]
**Description**
The [metadata package with cdrom provider](https://github.com/linuxkit/linuxkit/blob/master/pkg/metadata/provider_cdrom.go) has different logic against [cloud-init package](https://cloud-init.io), which uses for cloud providers and 
represents a standard way of transferring data to a VM.

**Steps to reproduce:**
1. As described in [Cloud-Init NoCloud Source](https://github.com/canonical/cloud-init/blob/master/doc/rtd/topics/datasources/nocloud.rst) generate iso.
```
$ { echo instance-id: iid-local01; echo local-hostname: cloudimg; } > meta-data

$ printf "#cloud-config\npassword: passw0rd\nchpasswd: { expire: False }\nssh_pwauth: True\n" > user-data

## create a disk to attach with some user-data and meta-data
$ genisoimage  -output seed.iso -volid cidata -joliet -rock user-data meta-data
```
2. Mount iso and view files:
```
sudo mkdir -p /mnt/iso; sudo mount seed.iso /mnt/iso; sudo ls /mnt/iso; sudo umount /mnt/iso
```

**Received result:**
As defined in
https://github.com/linuxkit/linuxkit/blob/3716b312f6bf07cc0496b0ec051ae71336f47a59/pkg/metadata/provider_cdrom.go#L10-L14
metadata package try to get metadata from file "/config". And it is a constant value.

**Expected results:**
As described in [Cloud-Init NoCloud Source](https://github.com/canonical/cloud-init/blob/master/doc/rtd/topics/datasources/nocloud.rst) metadata should be located in /user-data and /meta-data of observed drives.

**Comment by deitch** [comment]
I looked into this when @giggsoff first mentioned it. Based on [this](https://github.com/linuxkit/linuxkit/blob/master/pkg/metadata/provider_cdrom.go#L12-L13) we look for cdrom at `/dev/sr[0-9]*` and for the file to be `/config`. 

The `NoCloud` source from the official cloud-init docs is [here](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) and says:

```
These user-data and meta-data files are expected to be in the following format.

/user-data
/meta-data
```

We should support reading them from the standard location. The question is how not to break backwards compatibility. My current inclination is to include `/user-data` and `/meta-data` in the scanning, as well as `/config` (in that order - standard first).

Thoughts?

**Comment by rn** [comment]
@djs55 might know if Docker Desktop is using this an in what way. Otherwise the proposal for looking for standard first and then for `/config` seems ok to me

**Comment by deitch** [comment]
Sure. @djs55 do you know if having us check in cdrom for the cloud-init standard `/user-data` and `/meta-data` and after falling back to `/config` is ok in terms of docker desktop?

**Comment by djs55** [comment]
@deitch @rn looking first in the standard cloud-init locations and then falling back to `/config` sounds sensible to me. When Docker Desktop next updates the linuxkit package we'll move our files from `/config` into the standard locations. Thanks for the heads-up!

**Comment by deitch** [comment]
Ok. I’ll get a PR in soon.

**Comment by deitch** [comment]
I am going to do this in 2 stages. In the first, we will support retrieving user-data from `/user-data`, falling back to `/config`. In the second, we will parse the `/meta-data` as we do with AWS, GCP, etc.

I want to get the metadata done as well, but that requires knowing what to parse and look for. The work to add that intelligence will slow down getting this fix in.
