### ISSUE TITLE
Feature request: add vmware/cloud-init as a metadata provider

### ISSUE THREAD

**Issue by dxlr8r** [linuxkit/linuxkit#3507]
Support being able to read and store cloud-init metadata from VMWare's VMX https://github.com/vmware/cloud-init-vmware-guestinfo

**Comment by Jonatan-McE** [comment]
Is there any update on this. It would be great to have this feature for K3os deployments that are based on 
linuxkit.

I'm unfortunately not a developer and dont think i have the experience to help out with a pull request. And it seems the current pull request for this has stalled as there has not been any action on if for a number of months. Is there anything i can do to help out besides coding?

Thanks a lot! This would be very appreciated!

**Comment by tuxpeople** [comment]
A bit more than two years after the last comment, I'd like to ask again for an update on this :-) thanks!
