### ISSUE TITLE
Failed to extract kernel image and tarball

### ISSUE THREAD

**Issue by rajasec** [linuxkit/linuxkit#3535]
**Description**

**Steps to reproduce the issue:**
linuxkit build linuxkit.yml

**Describe the results you received:**
Failed to extract kernel image and tarball: Could not pull image docker.io/linuxkit/kernel:5.4.39: Trusted pull for docker.io/linuxkit/kernel:5.4.39 failed: client is offline

**Describe the results you expected:**
Kernel src is extract for building the image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by rn** [comment]
is it possible that the hub or the notary server are temporarily unreachable?

I can happily do a:
```
DOCKER_CONTENT_TRUST=1 docker pull linuxkit/kernel:5.4.39
```

**Comment by rajasec** [comment]
@rn 
Looks like network bandwidth issue. I have tried to pull via faster bandwidth where I could pull the image for kernel src.
Thanks for the support.
I'm closing this issue.
