### ISSUE TITLE
Request: allow FS_USERNS_MOUNT for overlayfs

### ISSUE THREAD

**Issue by AkihiroSuda** [linuxkit/linuxkit#3536]
Ubuntu has a kernel patch for allowing mounting overlayfs inside a user namespace: https://kernel.ubuntu.com/git/ubuntu/ubuntu-bionic.git/commit/fs/overlayfs?id=3b7da90f28fe1ed4b79ef2d994c81efbc58f1144

This patch would be useful for running [Rootless BuildKit](https://github.com/moby/buildkit/blob/master/docs/rootless.md). cc @tonistiigi

**Comment by thaJeztah** [comment]
@rn @justincormack ptal

**Comment by justincormack** [comment]
Have they submitted this upstream?

**Comment by rn** [comment]
I don't see it upstream and google can't find it outside ubuntu/debian

**Comment by AkihiroSuda** [comment]
This was upstreamed in kernel 5.11

**Comment by thaJeztah** [comment]
@AkihiroSuda does this need further changes beyond https://github.com/linuxkit/linuxkit/pull/3654 ? (I see that updated the default kernel to 5.10, not 5.11 (or above) yet

**Comment by AkihiroSuda** [comment]
Upgrading to 5.11 or later would be appreciated 🙏
