### ISSUE TITLE
Missing initrd/kernel/boot config when consumed as a library.

### ISSUE THREAD

**Issue by the-maldridge** [linuxkit/linuxkit#3566]
I am continuing a terraform-provider that allows the config for a linuxkit image to be composed using terraform resources.  I have gotten to a point in updating libraries where images build (mostly) but they don't boot.

An example terraform file that mirrors the sshd example: https://github.com/resinstack/terraform-provider-linuxkit/tree/master/examples/sshd

To run the above example you'll need to compile the terraform provider from the linked repo and place it in `~/.local/share/terraform/plugins/terraform.resinstack.io/resinstack/linuxkit/1.0.0/linux_amd64/`; the file must be named `terraform-provider-linuxkit`.

After building the plugin, initializing the terraform repo and building the config will look similar to below:

```
  $ terraform initInitializing the backend...Initializing provider plugins...
- Using previously-installed terraform.resinstack.io/resinstack/linuxkit v1.0.0Terraform has been successfully initialized!You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.$ terraform apply
data.linuxkit_trust.default: Refreshing state...
data.linuxkit_kernel.kernel: Refreshing state...
data.linuxkit_image.rngd1: Refreshing state...
data.linuxkit_image.dhcpcd: Refreshing state...
data.linuxkit_image.sysctl: Refreshing state...
data.linuxkit_image.getty: Refreshing state...
data.linuxkit_init.init: Refreshing state...
data.linuxkit_image.rngd: Refreshing state...
data.linuxkit_image.sshd: Refreshing state...
data.linuxkit_config.sshd: Refreshing state...An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + createTerraform will perform the following actions:  # linuxkit_build.sshd will be created
  + resource "linuxkit_build" "sshd" {
      + config_yaml = <<~EOT
            kernel:
              image: linuxkit/kernel:5.6.11
              cmdline: console=tty0 console=ttyS0 console=ttyAMA0
            init:
            - linuxkit/init:v0.8
            - linuxkit/runc:v0.8
            - linuxkit/containerd:v0.8
            - linuxkit/ca-certificates:v0.8
            onboot:
            - name: sysctl
              image: linuxkit/sysctl:v0.8
            - name: rngd1
              image: linuxkit/rngd:v0.8
              command:
              - /sbin/rngd
              - "-1"
            onshutdown: []
            services:
            - name: getty
              image: linuxkit/getty:v0.8
              env:
              - INSECURE=true
            - name: rngd
              image: linuxkit/rngd:v0.8
            - name: dhcpcd
              image: linuxkit/dhcpcd:v0.8
            - name: sshd
              image: linuxkit/sshd:v0.8
            trust:
              org:
              - linuxkit
            files: []
        EOT
      + destination = "./sshd.tar"
      + id          = (known after apply)
      + type        = "tar"
    }  # linuxkit_image_qcow2_bios.sshd will be created
  + resource "linuxkit_image_qcow2_bios" "sshd" {
      + build       = "./sshd.tar"
      + destination = "./sshd.raw"
      + id          = (known after apply)
      + size        = 1
    }Plan: 2 to add, 0 to change, 0 to destroy.Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.  Enter a value: yeslinuxkit_build.sshd: Creating...
linuxkit_build.sshd: Still creating... [10s elapsed]
linuxkit_build.sshd: Still creating... [20s elapsed]
linuxkit_build.sshd: Still creating... [30s elapsed]
linuxkit_build.sshd: Creation complete after 34s [id=08b6ad40aa4d1919a7f53fc1440badde]
linuxkit_image_qcow2_bios.sshd: Creating...
linuxkit_image_qcow2_bios.sshd: Still creating... [10s elapsed]
linuxkit_image_qcow2_bios.sshd: Still creating... [20s elapsed]
linuxkit_image_qcow2_bios.sshd: Still creating... [30s elapsed]
linuxkit_image_qcow2_bios.sshd: Still creating... [40s elapsed]
linuxkit_image_qcow2_bios.sshd: Still creating... [50s elapsed]
linuxkit_image_qcow2_bios.sshd: Creation complete after 51s [id=82ea625698206113c9323910a6c1bb00]Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

So far I believe that something is not being done correctly in setting up the kernel/initrd.  The base filesystem is built in https://github.com/resinstack/terraform-provider-linuxkit/blob/master/linuxkit/resource_build.go#L103 and is assembled into an image in https://github.com/resinstack/terraform-provider-linuxkit/blob/master/linuxkit/resource_image_raw_bios.go#L62

The output from qemu when trying to boot an image as built with this process is as follows:

```
SeaBIOS (version rel-1.13.0-48-gd9c812dda519-prebuilt.qemu.org)
Machine UUID bae8ea02-2ba9-4c7d-812c-5f957e0591ac


iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+3FF8EFA0+3FEEEFA0 CA00
                                                                               


Booting from Hard Disk...
Missing operating system.
```

Any thoughts?

**Comment by deitch** [comment]
Can you extract the actual linuxkit build command?

**Comment by the-maldridge** [comment]
Since I'm consuming linuxkit as a library I'm not sure what build command you're seeking, so I'll try and read the tea leaves.

The build is triggered by a call to:

```
err = moby.Build(config, outputFile, false, typ, false)
```

The config is known good, I can spit it out to a file and it works just fine.  The outputFile is a file that is created in a known writeable place.  The type argument is set to 'tar'.

Once the tarball is built, another pass converts it to a raw disk image with a call to:

```
err = moby.Formats(filepath.Join(dir, "base"), build, []string{"raw-bios"}, 0, false)
```

The closest I can come up to an equivalent linuxkit CLI command would be:

```
$ linuxkit build -format raw-bios -size 2G config.yml
```

The resulting image seems to be missing a kernel/initrd/boot config, but walking through how the actual build CLI command works, I don't see anywhere special that it creates those, so I would have expected them to be created during the `Formats()` call.

**Comment by deitch** [comment]
Oh, I see. How big is the tarball? Can you run it and spit out the tarball somewhere that we can examine? Let's tease this apart step by step.

**Comment by the-maldridge** [comment]
The file is 58M compressed.  What's the best way for me to put that somewhere that you can pull from?

**Comment by deitch** [comment]
USB key and UPS? 😂

**Comment by deitch** [comment]
The yaml looks fairly standard, no unique images. Can you replicate it with a simple gist that has a golang file and yaml that could reproduce the exact steps? Might be easiest.

**Comment by the-maldridge** [comment]
Given the significant number of dependencies that are necessary to run linuxkit this won't be a simple gist, but I'll see what I can come up with.

**Comment by the-maldridge** [comment]
Infuriatingly this works: https://gist.github.com/the-maldridge/d9d76ca330e19d4a18de87317cf8b8a2

**Comment by the-maldridge** [comment]
So far the best answer I have is that this is plausibly a race condition in terraform.  Since terraform is actively hostile to debugging, I have made no further progress at this time.

**Comment by the-maldridge** [comment]
So for raw-bios I have it working now, though the problem has moved.  Now I have qcow2-bios is missing its kernel/initrd.

**Comment by the-maldridge** [comment]
here's a qcow2 file that's way too small, I'm not sure what would have caused it to be missing almost all of its content.
[sshd.qcow2.zip](https://github.com/linuxkit/linuxkit/files/5769674/sshd.qcow2.zip)

**Comment by the-maldridge** [comment]
I'm not entirely sure when or how I fixed this at my end, but it has been long fixed.
