### ISSUE TITLE
Question: what’s the best eay to persistent files during reboot

### ISSUE THREAD

**Issue by jeffwubj** [linuxkit/linuxkit#3569]
Hi expects,
new to linuxkit... wonder what will be the best way to persistent files during vm reboot with vmware backend (run vmware on desktop)?

would like to run some containers that could reload the data while vm rebooted? However, looks like files stored in var folder got lost while vm rebooted, from doc, seems -disk will be the way to have a persistent disk, does this apply to vmware backend as well? run vmware with -disk keeps giving me create disk error on my mac with fusion. appreciate if any suggestions!

**Comment by deitch** [comment]
I was going to ask if you have seen the [external disk documentation](https://github.com/linuxkit/linuxkit/blob/master/docs/external-disk.md)? 

If you are getting specific errors with vmware and `-disk`, post here your linuxkit.yml and how you are running it, so someone can try to recreate it?

**Comment by jeffwubj** [comment]
thanks for the information, after appending one more vmdk, it works well with format and mount operations!
