### ISSUE TITLE
'make' fails with lookup proxy.golang.org network problem

### ISSUE THREAD

**Issue by attila123** [linuxkit/linuxkit#3599]
**Description**

make fails with some docker related network error

**Steps to reproduce the issue:**
Host OS: Arch Linux on bare metal (a laptop)  
cloned the linuxkit git repo, on branch master, at last commit 4cdf6bc56dd43227d5601218eaccf53479c765b9  
then tried to build it (execute make according the readme, here added basic make debugging to better see what is happening):  
  
```
$ make --debug=b
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'default' does not exist.
   File 'bin/linuxkit' does not exist.
     File 'tmp_linuxkit_bin.tar' does not exist.
    Must remake target 'tmp_linuxkit_bin.tar'.
tar cf - -C src/cmd/linuxkit . | docker run --rm --net=none --log-driver=none -i  linuxkit/go-compile:b1446b2ba407225011f97ae1dba0f512ae7f9b84 --package github.com/linuxkit/linuxkit/src/cmd/linuxkit --ldflags "-X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.GitCommit=4cdf6bc56dd43227d5601218eaccf53479c765b9 -X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.Version="v0.8+"" -o bin/linuxkit > tmp_linuxkit_bin.tar
gofmt...
govet...
go: cloud.google.com/go@v0.57.0: Get https://proxy.golang.org/cloud.google.com/go/@v/v0.57.0.mod: dial tcp: lookup proxy.golang.org on 192.168.0.1:53: dial udp 192.168.0.1:53: connect: network is unreachable
sh: cloud.google.com/go@v0.57.0:: unknown operand
make: *** [Makefile:60: tmp_linuxkit_bin.tar] Error 2
make: *** Deleting file 'tmp_linuxkit_bin.tar'
```

I also tried to build with removing the '--net none' from the appropriate 'docker run' command in the Makefile. Then it downloaded some go stuffs and finally failed with 'sh: downloading: unknown operand'. See attached build_log_without_net_none.txt.
[build_log_without_net_none.txt](https://github.com/linuxkit/linuxkit/files/5937060/build_log_without_net_none.txt)

**Describe the results you received:**

As above. Strange that the docker run is supposed to work with '--net=none' yet it wants to get something from the network.

**Describe the results you expected:**

Build should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

I am on Arch Linux.  
docker works fine in my system, e.g. I can build, run docker images without problems
If any other information is needed about my system, let me know.  

```
$ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:46:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:52:55 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by rn** [comment]
@deitch looks like your recent changes might have broken things badly. 

running `make` builds with `--net=none` and fails as above. Removing `--net=none` as per above fails as well (after pulling in a log of packages which are already in `vendor`. `make local` also fails with not being able to find packages which are in `vendor`.

I suspect the `vendor` directory is not picked up...

**Comment by rn** [comment]
`make local` also fails with `golang:latest` and `golang:1.13`:
```
docker run --rm -it -v $(pwd):/lk golang:1.13
cd /lk
make local
```

**Comment by deitch** [comment]
Hmm, did you try 1.15?

**Comment by deitch** [comment]
I just run `make local` on my own laptop, no issues. I am running 

```
$ go version
go version go1.15.4 darwin/amd64
```

I would think maybe the go-compile image is an issue, but then your `make local` should work.

**Comment by rn** [comment]
```
docker run --rm -it -v $(pwd):/lk golang:1.15
# cd /lk
gofmt...
govet...
src/cmd/linuxkit/azure.go:13:2: cannot find package "github.com/Azure/azure-sdk-for-go/profiles/2017-03-09/storage/mgmt/storage" in any of:
        /usr/local/go/src/github.com/Azure/azure-sdk-for-go/profiles/2017-03-09/storage/mgmt/storage (from $GOROOT)
        /go/src/github.com/Azure/azure-sdk-for-go/profiles/2017-03-09/storage/mgmt/storage (from $GOPATH)
[...]
```
but:

```
docker run --rm -it -v $(pwd):/go/src/github.com/linuxkit/linuxkit golang:1.15
# cd /go/src/github.com/linuxkit/linuxkit
root@c72e7feb40d2:/go/src/github.com/linuxkit/linuxkit# make local
gofmt...
govet...
# github.com/linuxkit/linuxkit/src/cmd/linuxkit/vendor/golang.org/x/crypto/curve25519
src/cmd/linuxkit/vendor/golang.org/x/crypto/curve25519/doc.go:10:5: basePoint redeclared in this block
        previous declaration at src/cmd/linuxkit/vendor/golang.org/x/crypto/curve25519/curve25519.go:43:5
src/cmd/linuxkit/vendor/golang.org/x/crypto/curve25519/doc.go:14:6: ScalarMult redeclared in this block
        previous declaration at src/cmd/linuxkit/vendor/golang.org/x/crypto/curve25519/curve25519.go:20:41
[...]
src/cmd/linuxkit/vendor/golang.org/x/text/unicode/norm/tables12.0.0.go:37:2: too many errors
make: *** [Makefile:78: local-check] Error 2
```

**Comment by deitch** [comment]
Several distinct things here then:

> So go does not pick up the vendoring if compiled outside GOPATH. This seems like a regression.

It does, and that is quite strange. I always have it in my GOPATH, which is why it worked locally for me. What happens if you explicitly set `-mod=vendor`?

> we also have an issue with compiling with go-compile, possibly a go version issue

Almost definitely. go-compile is using go 1.13, which is pretty ancient, but it is built on our linuxkit/alpine, so one needs to cut a whole new version of linuxkit/alpine, then update tools/go-compile.

**Comment by deitch** [comment]
Also, try explicitly setting `GO111MODULE=on`. I have seen some strange behaviour, as it is supposed to be on when outside of GOPATH, but who knows?

**Comment by rn** [comment]
It's actually the `govet` process which fails. if I run `golang:1.15` with `--net-none` `govet` actually works:
```
docker run --net=none --rm -it -v $(pwd):/go/src/github.com/linuxkit/linuxkit  golang:1.15
root@f63a4c71af6f:/go# cd /go/src/github.com/linuxkit/linuxkit
root@f63a4c71af6f:/go/src/github.com/linuxkit/linuxkit# make local
gofmt...
govet...
mkdir -p bin
CGO_ENABLED=0 go build -o bin/linuxkit --ldflags "-X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.GitCommit=4cdf6bc56dd43227d5601218eaccf53479c765b9 -X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.Version="v0.8+"" github.com/linuxkit/linuxkit/src/cmd/linuxkit
go test github.com/linuxkit/linuxkit/src/cmd/linuxkit github.com/linuxkit/linuxkit/src/cmd/linuxkit/cache github.com/linuxkit/linuxkit/src/cmd/linuxkit/docker github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4 github.com/linuxkit/linuxkit/src/cmd/linuxkit/pkglib github.com/linuxkit/linuxkit/src/cmd/linuxkit/util github.com/linuxkit/linuxkit/src/cmd/linuxkit/version
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit   [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/cache     [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/docker    [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd    [no test files]
ok      github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby      0.049s
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4      [no test files]
ok      github.com/linuxkit/linuxkit/src/cmd/linuxkit/pkglib    12.686s
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/util      [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/version   [no test files]
```
Note, I also remove `golint` and `ineffassign` from the `Makefile` since they are not in the standard container.

It also works with `golang:1.13`, which is not too surprising since the CI is using that:
```
docker run --net=none --rm -it -v $(pwd):/go/src/github.com/linuxkit/linuxkit  golang:1.13
root@243bfe18814a:/go# cd /go/src/github.com/linuxkit/linuxkit
root@243bfe18814a:/go/src/github.com/linuxkit/linuxkit# make local
gofmt...
govet...
mkdir -p bin
CGO_ENABLED=0 go build -o bin/linuxkit --ldflags "-X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.GitCommit=4cdf6bc56dd43227d5601218eaccf53479c765b9 -X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.Version="v0.8+"" github.com/linuxkit/linuxkit/src/cmd/linuxkit
go test github.com/linuxkit/linuxkit/src/cmd/linuxkit github.com/linuxkit/linuxkit/src/cmd/linuxkit/cache github.com/linuxkit/linuxkit/src/cmd/linuxkit/docker github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4 github.com/linuxkit/linuxkit/src/cmd/linuxkit/pkglib github.com/linuxkit/linuxkit/src/cmd/linuxkit/util github.com/linuxkit/linuxkit/src/cmd/linuxkit/version
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit   [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/cache     [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/docker    [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/initrd    [no test files]
ok      github.com/linuxkit/linuxkit/src/cmd/linuxkit/moby      0.027s
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/pad4      [no test files]
ok      github.com/linuxkit/linuxkit/src/cmd/linuxkit/pkglib    12.785s
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/util      [no test files]
?       github.com/linuxkit/linuxkit/src/cmd/linuxkit/version   [no test files]
```

**Comment by deitch** [comment]
Now I am confused. This works or fails?

**Comment by rn** [comment]
it works if I run with `--net=none`. If the container has network access, the `govet` fails

**Comment by deitch** [comment]
I still am trying to recreate this. And I love it when `go build` just completely hangs a container, to the point where I cannot kill it and must restart d4m.

It appears that explicitly adding `-mod=vendor` makes this all go away.

Some experiments:

* go 1.15 directly with `--net=none` works:

```
$ docker run --entrypoint=sh --rm  --net=none -it -v $(pwd):/lk  golang:1.15.7-alpine3.13
/go # cd /lk
/lk # cd src/cmd/linuxkit/
/lk/src/cmd/linuxkit # GO111MODULE=on go build -mod=vendor .
```

* go 1.15 directly with network enabled works:

```
$ docker run --entrypoint=sh --rm  -it -v $(pwd):/lk  golang:1.15.7-alpine3.13
/go # cd /lk
/lk # cd src/cmd/linuxkit/
/lk/src/cmd/linuxkit # go build -mod=vendor .
```

So, at least with go 1.15, if you explicitly give it `-mod=vendor`, it works with or without network.

* go-compile (which uses go 1.13) directly with `--net=none` works:

```
$ docker run --entrypoint=sh --rm --net=none --log-driver=none -it -v $(pwd):/lk linuxkit/go-compile:b1446b2ba407225011f97ae1dba0f512ae7f9b84
/ # cd /lk
/lk # cd ./src/cmd/linuxkit/
/lk/src/cmd/linuxkit # go build .
go: cloud.google.com/go@v0.57.0: Get https://proxy.golang.org/cloud.google.com/go/@v/v0.57.0.mod: dial tcp: lookup proxy.golang.org on 192.168.65.1:53: dial udp 192.168.65.1:53: connect: network is unreachable
/lk/src/cmd/linuxkit # go build -mod=vendor .
```

Assuming I read the above correctly, we have two things to be done:

1. Add `-mod=vendor` to our builds, which makes sense.
2. Bump alpine to a later version, so we get go 1.15.x, then bump go-compile. 

Thoughts?

**Comment by deitch** [comment]
FYI, yes, I tried `go vet` with all of the above, same thing.

**Comment by rn** [comment]
`go` is weird/broken....

```
docker run --net=none --rm -it --entrypoint=/bin/sh -v $(pwd):/go/src/github.com/linuxkit/linuxkit linuxkit/go-compile:b1446b2ba407225011f97ae1dba0f512ae7f9b84
/ # cd /go/src/github.com/linuxkit/linuxkit
/go/src/github.com/linuxkit/linuxkit # go vet -printf=false ./src/cmd/linuxkit/...
/go/src/github.com/linuxkit/linuxkit #
/go/src/github.com/linuxkit/linuxkit # cd ./src/cmd/linuxkit/
/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit # go vet -printf=false .
go: github.com/Azure/azure-sdk-for-go@v50.1.0+incompatible: Get https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/@v/v50.1.0+incompatible.mod: dial tcp: lookup proxy.golang.org on 192.168.65.1:53: dial udp 192.168.65.1:53: connect: network is unreachable
/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit # cd ../../../
/go/src/github.com/linuxkit/linuxkit # go build github.com/linuxkit/linuxkit/src/cmd/linuxkit
/go/src/github.com/linuxkit/linuxkit #
cd ./src/cmd/linuxkit/
/go/src/github.com/linuxkit/linuxkit/src/cmd/linuxkit # go build                                                                               │local-dynamic: $(LINUXKIT_DEPS) | bin
go: github.com/Azure/azure-sdk-for-go@v50.1.0+incompatible: Get https://proxy.golang.org/github.com/%21azure/azure-sdk-for-go/@v/v50.1.0+incomp│        go build -o $(LOCAL_TARGET) --ldflags "$(LOCAL_LDFLAGS)" github.com/linuxkit/linuxkit/src/cmd/linuxkit
atible.mod: dial tcp: lookup proxy.golang.org on 192.168.65.1:53: dial udp 192.168.65.1:53: connect: network is unreachable
```

So `go-compile.sh` changes directory to `src/cmd/linuxkit` and then runs `go vet` and `gp build` in the local directory. The `Makefile` and, by extension, the CI, runs `go vet` and `go build` from the repository root and that works

**Comment by rn** [comment]
so we have three options:
1. Add -mod=vendor to our builds, which makes sense.
2. Change the `go-compile.sh` to use the subdirs. This is a bit ugly and may break other builds which use `go-compile.sh`
3. Bump alpine to a later version, so we get go 1.15.x, then bump go-compile.

I think 1. is the easiest/quickest short term fix. 3. is quite an under taking as ideally we'd bump all packages to the new alpine base

**Comment by deitch** [comment]
Agreed. We definitely should do 1, as it is easy. We should do 3, as it will work well, but is just a pain, as you pointed out. Hopefully those can help us avoid 2.

**Comment by attila123** [comment]
Thanks for quick response, gentlemen.  
I was able to build linuxkit in golang:1.15 with 'make local' as per https://github.com/linuxkit/linuxkit/issues/3599#issuecomment-774665643  
As mentioned in the above comment, I needed to comment out the golint and ineffassing commands in the Makefile (target 'local-check').

**Comment by attila123** [comment]
Hi @deitch @rn may I help out with 3. Bump alpine to a later version, so we get go 1.15.x, then bump go-compile.

I would then fork and prepare the changes.

**Comment by rn** [comment]
Thanks for the offer but updating alpine base is best done by a maintainer as things need to be signed. Because it is the base of all other packages, I tend to also update all the other packages to make sure it doesn't break anything. it's a multi-day effort
