### ISSUE TITLE
Microcode not included in output formats other than kernel+initrd

### ISSUE THREAD

**Issue by sprat** [linuxkit/linuxkit#3739]
**Description**

The microcode is only included when the output format is kernel+initrd, not in the other cases (.img and .iso targets especially)

**Steps to reproduce the issue:**

Run `linuxkit build -format raw-bios file.yml`.

Content of file.yml:
```
kernel:
  image: linuxkit/kernel:5.10.76
  cmdline: console=tty0
  ucode: intel-ucode.cpio
```

**Describe the results you received:**

The microcode is not included and loaded when the kernel starts, which leads to the following warning message:
```
[    0.006359] SRBDS: Vulnerable: No microcode
```

**Describe the results you expected:**

The following line should appear at the start of the `dmesg` log:
```
[    0.000000] microcode: microcode updated early to revision 0x2f, date = 2019-11-12
```

**Additional information you deem important (e.g. issue happens only occasionally):**

There's a TODO in the code ;)

**Comment by rn** [comment]
https://www.kernel.org/doc/html/latest/x86/microcode.html describes three ways of loading the microcode. LinuxKit currently only supports the first (prepending it to the initrd). For some output formats LinuxKit doesn't use a initrd so this method does not work. One could use the late ucode load, but IIRC this might not work for all ucode fixes. The other option is to compile the ucode into the kernel image using `CONFIG_EXTRA_FIRMWARE` but we'd have to include all ucodes for all processors, but ucode is only needed on metal platforms so this would bloat the kernel for non-metal.

**Comment by sprat** [comment]
Oh, I understand it may not apply to all output formats, but I expected that it applied to .img or .iso format at least, which expose the same initrd.img file internally and which could also be prepended with the microcode, like the kernel+initrd output format. Or did I miss something? Note that there's a TODO in the code, so someone probably thought that it could be added in other output formats too ;)
