### ISSUE TITLE
Release a binary for darwin/arm64

### ISSUE THREAD

**Issue by dgageot** [linuxkit/linuxkit#3833]
I believe the release process should include releasing a binary for darwin/arm64.

I would like to help make that happen but I'm unsure which steps to follow.

**Comment by deitch** [comment]
I just hunted through all of our workflows, and was surprised that there is nothing for cutting releases based on tags and sharing artifacts. I didn't do the last releases, but @rn did, so perhaps he knows?

I think we should standardize this. Do you want to create a workflows file `release.yaml` for releases? Sees a tag, generates a release, loads up release artifacts.

**Comment by rn** [comment]
we didn't really had the auto-push for any of the previous releases. so it was all done manually.

**Comment by dgageot** [comment]
I'll try to take a look at it tomorrow or next week

**Comment by dgageot** [comment]
This is fixed now
