### ISSUE TITLE
Release a 0.9.0

### ISSUE THREAD

**Issue by dgageot** [linuxkit/linuxkit#3852]
I can't wait to see a new release of linuxkit. The last one was more than two years ago!

@deitch wdyt?

**Comment by djs55** [comment]
I'm keen to see a release! I'm happy to go with 1.0 🎉

**Comment by justincormack** [comment]
SGTM, yeah 1.0 is good, the structure has matured.

**Comment by deitch** [comment]
Just pushed v1.0.0!

**Comment by dgageot** [comment]
@deitch did the release go well? Can you make it non-draft?

**Comment by dgageot** [comment]
@deitch In fact I don't even see the git tag

**Comment by dgageot** [comment]
I think you pushed it to your fork

**Comment by deitch** [comment]
Oops, yeah, I did. Tried again now.
