### ISSUE TITLE
update github.com/Code-Hex/vz to v3

### ISSUE THREAD

**Issue by Code-Hex** [linuxkit/linuxkit#3864]
**Description**

Hi 👋 

I'm the author of https://github.com/Code-Hex/vz which is Go binding with Apple Virtualization.framework.

Just a few moments ago I released v3 of this package. This enables the following functions to be used.

- Boot Extensible Firmware Interface (EFI) ROM
- Clipboard sharing through the SPICE agent
- Running Intel Binaries in Linux VMs with Rosetta (arm64 only)

v1, v2 deprecated. So I've created this issue. Thanks.

By the way, I have also started compiling the Linux information needed to use each of the features provided by the Virtualisation.framework here. Anyone is free to edit it.

https://github.com/Code-Hex/vz/wiki

**Comment by deitch** [comment]
Thanks @Code-Hex ; updated.
