### ISSUE TITLE
Create a 1.0.1 release

### ISSUE THREAD

**Issue by dgageot** [linuxkit/linuxkit#3867]
Hey @deitch! With https://github.com/linuxkit/linuxkit/pull/3855 being merged, it would make sense for us (Docker Desktop team) to release a 1.0.1 of linuxkit that has this fix. Could you create the tag?

**Comment by deitch** [comment]
Yeah, that is fair enough. There were a few other merges since then, and some pending, but no reason to delay a patch version.

**Comment by dgageot** [comment]
@deitch Don't forget to push the tag on upstream, not on your fork :-)

**Comment by deitch** [comment]
Minor details....

**Comment by dgageot** [comment]
@deitch awesome! The release build is over. All we need is the release to be moved from draft to release. thanks!

**Comment by deitch** [comment]
Done
