### ISSUE TITLE
Unable to build with 1.0.1

### ISSUE THREAD

**Issue by devisbal** [linuxkit/linuxkit#3885]
tar cf - -C . . | docker run --rm --net=none --log-driver=none -i -e GOARCH= linuxkit/go-compile:7b1f5a37d2a93cd4a9aa2a87db264d8145944006 --package github.com/linuxkit/linuxkit/src/cmd/linuxkit --ldflags "-X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.GitCommit= -X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.Version="v0.8+"" -o linuxkit > tmp_linuxkit_bin.tar
gofmt...
vendor/github.com/Code-Hex/vz/v3/internal/objc/finalizer_118.go:8:18: expected '(', found '['
vendor/github.com/moby/buildkit/frontend/attest/sbom.go:75:13: expected '(', found '['
vendor/github.com/moby/buildkit/frontend/frontend.go:15:28: expected ';', found '['
vendor/github.com/moby/buildkit/frontend/gateway/client/client.go:17:28: expected ';', found '['
vendor/github.com/moby/buildkit/solver/result/result.go:16:15: expected ']', found any
vendor/github.com/moby/buildkit/solver/result/result.go:26:2: expected declaration, found 'if'
vendor/github.com/moby/buildkit/solver/result/result.go:68:3: expected declaration, found 'return'
vendor/github.com/moby/buildkit/solver/result/result.go:91:2: expected declaration, found 'if'

**Comment by deitch** [comment]
Local build works fine:

```
$ git checkout v1.0.1
Note: switching to 'v1.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 860163a9c Merge pull request #3863 from deitch/rationalize-build-pull
$ make -C ./src/cmd/linuxkit local-build
CGO_ENABLED=1 go build -o /Users/adeitcher/Documents/Development/go/src/github.com/linuxkit/linuxkit/bin/linuxkit  --ldflags "-X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.GitCommit=860163a9c7dd3125c51a65667cf457e1201aac90 -X github.com/linuxkit/linuxkit/src/cmd/linuxkit/version.Version="v0.8+""
codesign --entitlements linuxkit.entitlements --force -s - /Users/adeitcher/Documents/Development/go/src/github.com/linuxkit/linuxkit/bin/linuxkit
```

Checking the containerized build:

```
$ docker run -it --rm --entrypoint=go linuxkit/go-compile:7b1f5a37d2a93cd4a9aa2a87db264d8145944006 version
go version go1.16.3 linux/arm64
```

Well, that might have something to do with it. The go install in `tools/go-compile` is [inherited from alpine](https://github.com/linuxkit/linuxkit/blob/master/tools/go-compile/Dockerfile#L1-L9):

```dockerfile
FROM linuxkit/alpine:33063834cf72d563cd8703467836aaa2f2b5a300 AS mirror

RUN mkdir -p /out/etc/apk && cp -r /etc/apk/* /out/etc/apk/
RUN apk add --no-cache --initdb -p /out \
    alpine-baselayout \
    busybox \
    git \
    go \
    musl-dev
```

Which is set in `linuxkit/alpine`, based [here](https://github.com/linuxkit/linuxkit/blob/master/tools/alpine/Dockerfile#L1):

```dockerfile
FROM alpine:3.14 AS mirror
```

3.14 is a might old, and installs go v1.16. We need to move to alpine:3.16 (go 1.18) or alpine:3.17 (go 1.19) for it to work.

**Comment by deitch** [comment]
The `linuxkit/alpine` base image was updated recently, as was `go-compile`. We can update this and it should fix it.
