### ISSUE TITLE
getty cannot start with image build by docker build

### ISSUE THREAD

**Issue by sheepcat** [linuxkit/linuxkit#3910]
1. build getty image:
cd linuxkit/pkg/getty
docker build -t xxx:xx  . 

2. linuxkit build mygetty.yml 

content is :
kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:14df799bb3b9e0eb0491da9fda7f32a108a2e2a5
  - linuxkit/runc:436357ce16dd663e24f595bcec26d5ae476c998e
  - linuxkit/containerd:eeb3aaf497c0b3f6c67f3a245d61ea5a568ca718
  - linuxkit/ca-certificates:4de36e93dc87f7ccebd20db616ed10d381911d32
onboot:
  - name: sysctl
    image: linuxkit/sysctl:e5959517fab7b44692ad63941eecf37486e73799
  - name: dhcpcd
    image: linuxkit/dhcpcd:2a8ed08fea442909ba10f950d458191ed3647115
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: registry.company.com/getty:githubmaster
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:331294919ba6d953d261a2694019b659a98535a4

4.linuxkit run mygetty
blocked

![image](https://user-images.githubusercontent.com/8611901/218401821-f943990e-87c8-4708-86d5-dad4bddee8e0.png)

5. if i use the getty image from docker hub, it works file.   such as  image: linuxkit/getty:06f34bce0facea79161566d67345c3ea49965437

**Comment by sheepcat** [comment]
fixed  
should build image use linuxkit  rather than  docker build 

but what is the difference between  ‘linuxkit build’  and  ‘docker build ’

**Comment by deitch** [comment]
Yeah, that is it. There are certain permissions.

* `linuxkit build` just builds a runnable OS image that you can then boot up via `linuxkit run` or an AWS or VMware or bare metal, etc.
* `docker build` builds the image, as you saw
* `linuxkit pkg build` pretty much runs a `docker build`, but it does so in an opinionated fashion. It sets certain parameters including required runtime permissions on the image (saved in the image's config), that `linuxkit build` knows to look for as defaults.

Essentially, `linuxkit pkg build` is "run a `docker build` using a bunch of settings from a config file `build.yaml`". You can see the additional information in [getty's `build.yml`](https://github.com/linuxkit/linuxkit/blob/master/pkg/getty/build.yml). Look at all of the stuff in the `config` key of that yaml file.

You can override any of those, or you can set them explicitly in the linuxkit yaml file, see [the package specification in this doc](https://github.com/linuxkit/linuxkit/blob/master/docs/yaml.md#image-specification).
