### ISSUE TITLE
Missing updated versions of poweroff package

### ISSUE THREAD

**Issue by MatheusAfinovicz** [linuxkit/linuxkit#3943]
**Description**

Building an image with `aws` format fails due to missing `linuxkit/poweroff` image in the required version.
The command `linuxkit build -f aws` requires `linuxkit/poweroff:992d9c7531166fe071d945e8b2728d8b61eb8d5a`, when searching for this version in https://hub.docker.com/r/linuxkit/poweroff/tags?page=1, we can check that the image doesnt exist.

**Steps to reproduce the issue:**

Using `linuxkit version: 03c97c3584175812d2144bf699ddd26d19f4c37c`, run `linuxkit build -f aws --name output your.config.yml`

**Describe the results you received:**

```
Error: Error parsing formats: Failed to set up format type aws: Could not pull image linuxkit/poweroff:992d9c7531166fe071d945e8b2728d8b61eb8d5a: error getting manifest for trusted image docker.io/linuxkit/poweroff:992d9c7531166fe071d945e8b2728d8b61eb8d5a: Get "https://index.docker.io/v2/": context deadline exceeded
2023/07/24 13:26:09 error during command execution: Error parsing formats: Failed to set up format type aws: Could not pull image linuxkit/poweroff:992d9c7531166fe071d945e8b2728d8b61eb8d5a: error getting manifest for trusted image docker.io/linuxkit/poweroff:992d9c7531166fe071d945e8b2728d8b61eb8d5a: Get "https://index.docker.io/v2/": context deadline exceeded
make: *** [Makefile:16: testnet.raw] Error 1
```

**Describe the results you expected:**

Image builds without errors

**Additional information you deem important (e.g. issue happens only occasionally):**

linuxkit version: `03c97c3584175812d2144bf699ddd26d19f4c37c`

**Comment by deitch** [comment]
#3942 should fix this. As it moved out of `test/` and into the regular `pkg/`, it should be picked up by the package distribution pipeline.
