### ISSUE TITLE
No tagged images on dockerhub since v0.8

### ISSUE THREAD

**Issue by devtools-teamcity** [linuxkit/linuxkit#3946]
Is there a reason `v1.0.x` does not have any tagged releases on dockerhub?

I see the github actions workflow publishes new images, but the tagged releases did not have any jobs associated with it.

**Comment by rbuckland** [comment]
DO we have a follow up for this ? 

v1.0.1 is showing as the latest release. But the docker images are all v0.8 (version tagged)

**Comment by deitch** [comment]
We have been more careful about tagged releases on the tool itself; packages tend to update more frequently.

But that is no reason to avoid tags on the packages themselves. Let's cut some releases there as well.

**Comment by deitch** [comment]
Done. Now the repository supports tags `pkg-v<semver>` which will tag the packages. v1.0.0 of packages is being tagged as we write here.

**Comment by rbuckland** [comment]
Very nice. Thanks
