### ISSUE TITLE
kernel-perf for 6.6.x has no bins?

### ISSUE THREAD

**Issue by richarddd** [linuxkit/linuxkit#4022]
**Description**

Inspecting `linuxkit/kernel-perf` recent tags seems to the perf binaries or am i missing something?
**6.6.13**
```Dockerfile
COPY /out/* / # buildkit 200.21 MB
```

**5.4.172**
```Dockerfile
COPY /out/perf /usr/bin/perf # buildkit 1.84 MB
```

**Steps to reproduce the issue:**
Use the latest perf image and try to copy /usr/bin/perf
```
FROM ubuntu
COPY --from=linuxkit/kernel-perf:6.6.13 /usr/bin/perf /usr/bin/perf
```

**Describe the results you received:**
"/usr/bin/perf": not found

**Describe the results you expected:**
Perf added to my layer

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by deitch** [comment]
This is confusing. I pulled down the latest image and inspected its contents.

```bash
$ docker create linuxkit/kernel-perf:6.6.13 sh
ff32f250a6dc052915b4521873cb20a88a408eddfa9c7166b9f40b8e0b684c40
$ docker export ff32f250a6dc052915b4521873cb20a88a408eddfa9c7166b9f40b8e0b684c40 > /tmp/kernel.tar
$ tar tvf /tmp/kernel.tar
-rwxr-xr-x 0/0               0 2024-04-16 07:43 .dockerenv
-rw-r--r-- 0/0         8535352 2024-03-06 08:51 System.map
drwxr-xr-x 0/0               0 2024-04-16 07:43 dev/
-rwxr-xr-x 0/0               0 2024-04-16 07:43 dev/console
drwxr-xr-x 0/0               0 2024-04-16 07:43 dev/pts/
drwxr-xr-x 0/0               0 2024-04-16 07:43 dev/shm/
drwxr-xr-x 0/0               0 2024-04-16 07:43 etc/
-rwxr-xr-x 0/0               0 2024-04-16 07:43 etc/hostname
-rwxr-xr-x 0/0               0 2024-04-16 07:43 etc/hosts
lrwxrwxrwx 0/0               0 2024-04-16 07:43 etc/mtab -> /proc/mounts
-rwxr-xr-x 0/0               0 2024-04-16 07:43 etc/resolv.conf
-rw-r--r-- 0/0            1677 2024-03-06 08:46 intel-ucode-license.txt
-rw-r--r-- 0/0         4738048 2024-03-06 08:46 intel-ucode.cpio
-rw-r--r-- 0/0        11444992 2024-03-06 08:51 kernel
-rw-r--r-- 0/0              56 2024-03-06 08:52 kernel-builder
-rw-r--r-- 0/0        91514880 2024-03-06 08:52 kernel-dev.tar
-rw-r--r-- 0/0         7137280 2024-03-06 08:52 kernel-headers.tar
-rw-r--r-- 0/0              79 2024-03-06 08:46 kernel-source-info
-rw-r--r-- 0/0       123228160 2024-03-06 08:51 kernel.tar
-rw-r--r-- 0/0       144125632 2024-03-06 08:47 linux.tar.xz
drwxr-xr-x 0/0               0 2024-04-16 07:43 proc/
drwxr-xr-x 0/0               0 2024-04-16 07:43 sys/
```

All of that is what should be inside _kernel_:6.6.13, not _kernel-perf_. I wonder if the build process got confused somewhere down the line.

Looking at GitHub Actions - whatever is available after a month - [job #179](https://github.com/linuxkit/linuxkit/actions/runs/8169572904/job/22333914758#step:10:38) finds `linuxkit/kernel-perf:6.6.13-ad4d0da9e582d714cf61c8d99468cc7c1109bce5` on the registry and does not push, but [job #180](https://github.com/linuxkit/linuxkit/actions/runs/8170524413/job/22336815599#step:10:38) finds the most recent `linuxkit/kernel-perf:6.6.13-e274bc71d6552570c922d2fca6c6481d1f9f045a` on the registry. Which means it got pushed out somewhere in between, perhaps not by the pipeline.

The latest tag is `e274bc71d6552570c922d2fca6c6481d1f9f045a`, which you can see via `make show-tags` in the `kernel/` directory.

So where did that build get messed up? Not sure, but we can manually override.

**Comment by deitch** [comment]
Ah shoot, I see it. Messed up build.yml is rebuilding the kernel each time. Should be fixable.

**Comment by deitch** [comment]
Should be all good now.
