### ISSUE TITLE
Fortify finding : Insecure Transport in run_packet.go

### ISSUE THREAD

**Issue by neelpandya** [linuxkit/linuxkit#4037]
We have configured fortify scanning for our go modules and it pointed out a vulnerability in run_packet.go file. 

Insecure Transport

go func() {
			log.Debugf("Listening on http://%s\n", *serveFlag)
			if err := httpServer.ListenAndServe(); err != nil {
				log.Infof("http server exited with: %v", err)
			}

Basically, the code is expected to use TLS in the http server. But my question is 
Is this code only used while building the image ? If yes, the purpose of the server so created ends when the image is built and the image itself will not carry this server config. Fundamentally , I need to justify this fortify finding  to be a false positive and bears no security risk to the posture of the OS as well as to the workloads running on these instances.

Kindly help me out.

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by deitch** [comment]
Can you link to the actual file and lines?

**Comment by neelpandya** [comment]
Sure, here is link from the current master - 

https://github.com/linuxkit/linuxkit/blob/master/src/cmd/linuxkit/run_packet.go#L128

**Comment by deitch** [comment]
The commit that added it is [here](https://github.com/linuxkit/linuxkit/commit/fced67dab82eea1628f24217188a966e3fc48bca), with the comment:

> The -serve command starts a local HTTP server which serves
the kernel and initrd files.  The server can then easily be
made available via ngrok or other means.

The reason for it is that Packet (now Equinix Metal) does custom operating systems via iPXE, so you need something to act as the iPXE server. You can use something hosted, or, for testing, you can use this, run a local http server that is listening on localhost, and then use some remote-to-Internet service, like ngrok or inlets, to expose it to the Internet.

Either way, it is intended for testing, e.g. `linuxkit run packet someos`, which is not part of building an OS or the built OS itself, only part of "here is how I can run it easily via command-line for testing purposes".

**Comment by neelpandya** [comment]
Thanks a lot for clarifying .
