### ISSUE TITLE
Packet is Equinix Metal now [since 2020]

### ISSUE THREAD

**Issue by SamuelMarks** [linuxkit/linuxkit#4051]
Ref https://www.equinix.com/newsroom/press-releases/2020/03/equinix-completes-acquisition-of-bare-metal-leader-packet
https://www.datacenters.com/news/packet-com-is-now-equinix-metal-colocation-provider-goes-all-in-on-colo-cloud-an

You might want to update your docs, like:
- https://github.com/linuxkit/linuxkit/blob/master/docs/platform-packet.md

And rename files like:
- `docs/platform-packet.md`
- `docs/platform-packet.md`
- `examples/platform-packet.arm64.yml`
- `examples/platform-packet.yml`
- `pkg/metadata/provider_packet.go`
- `src/cmd/linuxkit/push_packet.go`
- `src/cmd/linuxkit/run_packet.go`

**Comment by deitch** [comment]
Yeah, we really should. Thought about it not long after the acquisition, but wasn't worth the effort, and we figured it would take time to go through. Maybe I will try to do it now.
