### ISSUE TITLE
Can't get an efi build to run with kernel 6.6.13

### ISSUE THREAD

**Issue by ErikSJan** [linuxkit/linuxkit#4068]
Hello Everyone,

**Description**
Since the 6.6.13 kernel is mentionned in the yaml sample files, no build for efi can work anymore.

**Steps to reproduce the issue:**
1 - clone last repo
2 - linuxkit build -f iso-efi-initrd linuxkit/examples/sshd.yml
3 - linuxkit run sshd-iso-initrd.iso or copy the iso to an USB key an place it in a computer

**Results in:**
error: kernel doesn't support EFI handover.
error: you need to load the kernel first.

**Additional information:**
The 'EFI handover' method got deprecated. 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cc3fdda2876e58a7e83e558ab51853cf106afb6a

**Comment by deitch** [comment]
Strange, because I don't think it actually does that. There is a grub.cfg on the iso image, and a `BOOTX64.EFI` (or `BOOTAA64.EFI` if on arm64) inside the catalog.

Did you get this from running `lkt run ssh-iso-initrd.iso`? On what platform? What else can you share?

**Comment by ErikSJan** [comment]
Hello Avi,

Whether I build the image on an Ubuntu 22.04 in a VM in Hyper-V or directly in powershell using the windows version of linuxkit the produced image gives the same result:
- in the Ubuntu VM, qemu doesn't recognize the image as a bootable one so nothing can be tested
- on the Windows PC directly, linuxkit calls Hyper-V to generate a VM that displays the message
- on an i5 PC booting on an usb drive with the image the message is the same as on the Hyper-V launch

**Comment by deitch** [comment]
👋 @ErikSJan 

On qemu, you get UEFI prompt? That sounds like misconfigured commands to qemu call from `linuxkit run`. I saw that as well, rather than the "EFI handover" error. Can you open a fresh issue on that, so it can be tracked separately, and have its own fix? I also think that once that is fixed, we are likely to see the same issue as you find on PC/Hyper-V, so it can help get this one moving. A lot faster to iterate on a cloud instance running qemu that local PC boot.

**Comment by ErikSJan** [comment]
@deitch 
I have just opened the following: #4071

**Comment by deitch** [comment]
I responded there. We can focus on this issue here. You actually can recreate it if:

```sh
$ sudo apt install -y ovmf
$ cp /usr/share/ovmf/OVMF.fd .
$ lkt run qemu --fw ./OVMF.fd --uefi linuxkit-efi-initrd.iso
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0)
Welcome to GRUB!
  Booting `LinuxKit ISO Image'

error: kernel doesn't support EFI handover.
error: you need to load the kernel first.
```

Now we can focus on fixing that. Well, we can try.
