### ISSUE TITLE
Missing kernel parameters for socket max buffer sizes

### ISSUE THREAD

**Issue by georgeyanev** [linuxkit/linuxkit#4088]
I'm using Docker Desktop for Mac with 6.10.14-linuxkit  SMP aarch64 GNU/Linux

When I do `sysctl -a` I don't see the kernel parameters regarding socket max buffer sizes:
`net.core.wmem_max` and `net.core.rmem_max`.

Also the parameters for SCTP socket buffer sizes are missing:
`net.sctp.sctp_mem`, `net.sctp.sctp_rmem`, `net.sctp.sctp_wmem`

These are crucial if you need larger SCTP messages.

How these parameters can be enabled?

**Comment by deitch** [comment]
I am afraid I cannot answer. While linuxkit is the _basis_ for Docker Desktop's VM, it has its own build and its own parameters. I recommend asking on Docker Desktop forums or issues.
