### ISSUE TITLE
logging enhancements

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#459]
- [ ] Add syslog logging to `dockerd` (https://github.com/docker/docker/issues/936) and `containerd`, or redirect via `logger`. Need a config to output eg `local0` for `docker.log`. This will allow log rotation, would also allow logging via a socket instead of filesystem if we want.
- [ ] Mount the docker logs on osx on a different path, so that only docker log is redirected to the Mac. Currently all the other logs are being hidden by the bind mount. Probably put all the docker related logs here.
- [ ] Clean up the other logs, several programs may not be logged correctly.

**Comment by rn** [comment]
closing, refers to a predecessor of LinuxKit
