### ISSUE TITLE
windows build support

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#495]
Self hosted build should be ok for running on Windows, but `moby-initrd:build` is not pushed anywhere. Clean up the mkinitrd process too, to avoid the copy, maybe can be done more cleanly.

Currently `docker run -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/moby -w /moby moby-initrd:build make` works as a self hosted build.

**Comment by rn** [comment]
`moby build` and `linuxkit run` work on windows closing
