### ISSUE TITLE
upstream Alpine missing chrony config dir in dhcpcd ntp hook

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#561]
See https://github.com/docker/moby/pull/560/files#diff-30a9660d1a10c4e7f4c17cacc6d7f401R20

needs adding `/etc/chrony` as a directory as Alpine uses that as the config file dir (it is not the default, which appears to be `/etc/chrony.conf`).

**Comment by rn** [comment]
switched to openntp, so closing
