### ISSUE TITLE
resolve redis startup errors

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#588]
- [X] #586 allow overcommit
- [ ] THP says "echo never > /sys/kernel/mm/transparent_hugepage/enable" even though we have "madvise" which should be ok
- [ ] "The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128" needs per container default sysctl support.

**Comment by rn** [comment]
closing. redis works on LinuxKit
