### ISSUE TITLE
Support btrfs

### ISSUE THREAD

**Issue by dsheets** [linuxkit/linuxkit#597]
Users in docker/for-mac#388 are agitating for `btrfs` support because Concourse CI workers apparently demand it (or fall back to sloooow `tmpfs`). The users don't know why this fail chain is setup the way it is and no one has looked into what the application is doing that requires either `btrfs` or `tmpfs` but not another graph driver.

Either we need to enable `btrfs` or liaise with Concourse about fixing their graph driver preferences and fall back paths. Comments about open source are beginning to appear so we should take some kind of action to prevent "y u no like BeTterFS?!?!?! Docker doesn't understand open source!" etc activity.

**Comment by rneugeba** [comment]
closed via #1707 which added BTRFS to the LinuxKit kernel
