### ISSUE TITLE
phase out plan for aufs

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#620]
Assuming we don't find more critical issues with `overlay2` it would be good to phase out `aufs` to avoid kernel patching.

First step is to measure the number of users with each filesystem.
Second step is to measure issues around overlay, to see if there are people who cannot switch.

We may need a migration plan if all goes well, or at some point stop upgrades if people have not reset.

Probably on 1.14 timetable, as before 1.13 we are unlikely to have enough experience.

**Comment by AkihiroSuda** [comment]
AUFS seems already removed.
Is there plan to revive it?
Or is it permanently removed?

**Comment by rneugeba** [comment]
It has been removed here, but not yet from some of the editions we ship.

We don't have a plan to revive it as overlay2 works well and it's tedious to maintain the AUFS patches. We already added BTRFS as containerd also supports that.

**Comment by rn** [comment]
closing. the AUFS removal for Docker for Mac/Windows is tracked elsewhere.
