### ISSUE TITLE
Moby logs do not reach host in Docker for Mac

### ISSUE THREAD

**Issue by dsheets** [linuxkit/linuxkit#709]
It used to be the case that syslog entries appeared in the Docker app asl/syslog/os_log output. This not longer occurs.

Further, it used to be the case that `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/` contained system logs from Moby's boot sequence. This no longer occurs.

Finally, the `diagnostics` package in Moby attempts to collect the last 20000 lines of `/var/log/messages` which is now no longer present.

We have almost no Moby logs in Docker for Mac diagnostic bundles and this severely impairs our ability to triage and diagnose issues. I'm not sure when this broke.

**Comment by rn** [comment]
closing
