### ISSUE TITLE
Try harder than `fsck -p` with corrupted filesystems

### ISSUE THREAD

**Issue by ijc** [linuxkit/linuxkit#736]
In https://github.com/docker/for-mac/issues/949 we reformatted a filesystem due to:
```
boot2docker-data contains a file system with errors, check forced.
boot2docker-data: Inodes that were part of a corrupted orphan linked list found.  

boot2docker-data: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
    (i.e., without -a or -p options)
Initializing partitions on /dev/vda...
Creating file systems...
```

Reading the manpages I'm unsure if `e2fsck -y` might try harder than the `e2fsck -p` which we use today to recover the filesystem. Losing some containers to `/lost+found` might be a bit better than losing all of them?

**Comment by rn** [comment]
closing. seems old
