### ISSUE TITLE
diagnostics-server sometimes fails without hope of recovery

### ISSUE THREAD

**Issue by nathanleclaire** [linuxkit/linuxkit#872]
I'm not 100% sure why (maybe panic in the run?) Last thing I'm seeing on one host is

```
Error writing:  Put https://editionsdiagnostics.s3.amazonaws.com/1481570985-JN6c4Xb4znUnrV70KWDSp672zM0u3xeF-swarm-worker000000.tar: write tcp 10.0.0.4:50162->54.231.235.1:443: write: connection timed out
```

We don't have any process supervision for restarts so it means the diagnostic server on that host is hosed forever, which can be problematic since it's naturally the thing that's meant to be around to debug problems.

@justincormack what do you think.  should we try and attempt restarts?  It might be a good start to maybe use `start-stop-daemon` instead of just `	/usr/bin/diagnostics-server ${DIAGNOSTICS_SERVER_FLAGS} &` so that we could send the output of the process to syslog, right now I'm assuming panic is the problem but not really sure how to debug it as I'm missing the panic trace.

**Comment by rn** [comment]
closing as per previous comment
