### ISSUE TITLE
trim after significant block deletions

### ISSUE THREAD

**Issue by justincormack** [linuxkit/linuxkit#950]
Can probably use eBPF to see if a lot of stuff has been deleted (eg via purge) and then run the fstrim to free up the space.

**Comment by gcstang** [comment]
Prior to Docker for Mac Version 17.10.0-ce-mac36 build 19824 I had been using a trim script to clean up my Docker.qcow2 but it no longer works now with this release.  It seems this release release notes include built on LinuxKit and crond is no longer available.

Is there a way to still do this with the newer version(s)?

Release Notes
`### 2017-10-24 17.10.0-ce-mac36 "17.10.0-ce-mac36"

* Upgrades
  - [Docker 17.10.0-ce](https://github.com/docker/docker-ce/releases/tag/v17.10.0-ce)
  - [Docker Machine 0.13.0](https://github.com/docker/machine/releases/tag/v0.13.0)
  - [Docker compose 1.17.0-rc1](https://github.com/docker/compose/releases/tag/1.17.0-rc1)

* New
  - VM entirely built with Linuxkit`

**Comment by justincormack** [comment]
Please can you open Docker for Mac specific issues on https://github.com/docker/for-mac/issues

Also you really need to give more detail on what you are doing and what you are trying to achieve,
